### ISSUE TITLE
Unified view

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#100]
Now that we are trying for changes in frontend and backend, it makes sense to have a unified view also.

The user can choose the dictionaries in which he wants to search and also the order of dicts for display. We populate results from those dicts and show in a single window.

E.g.

**Comment by gasyoun** [comment]
> can choose the dictionaries in which he wants to search 

And a mode to search in all at once, @juhnowski

**Comment by drdhaval2785** [comment]
Rather than ALL, I would love to be able to select any number. So two,
three, .... thirty six any combination should be possible. And to make it
less obtrusive, we can keep this in preference section. These choices are
relatively stable. So once a user chooses some preferences, all future
requests will be processed accordingly.

**Comment by gasyoun** [comment]
> So once a user chooses some preferences, all future
requests will be processed accordingly.

Agree.

**Comment by juhnowski** [comment]
At the left there is a circles with dictionary abbreviations. This is a favorite dictionary.
It has a two state:
 black color font with shadow - available
 gray color font without shadow circle - disable
 
Available mean that the search will be carried out on this dictionary.
Disable - dictionary will be exclude from searching list of dictionaries.

The main purpose of the field "Favorites" group dictionaries for user categories.
User categories may be stored and shown in menu list.

In search screen menu also contain:
All Favorites - select at first and unselect at second dictionaries in favorites.
All Available - hide all circles and only one "All" presented. It means search will be carried out on all available dictionary

My Choice 1
My Choice 2 - are examples of User presets. When one of them selected favorites should be changed according saved settings.

User favorites settings (aggregate of dictionaries and states) may be saved by clicking "Save As" option, and after naming it should be shown immediately in the menu list.

Near with menu circle I place "Correction" button with pencil icon.


I try to illustrate it: http://5cw75p.axshare.com (updated)

**Comment by juhnowski** [comment]
About @drdhaval2785 "also the order of dicts for display"
favorites area should be like an ordered list and user may change position like in basic order list, dragging and dropping items (circles).

Please let me know if I have misunderstood or missed something...

**Comment by juhnowski** [comment]
My vision of behaviour of first page.
At first start application it will shown some interactive tutorial and the next it will be open in that state, when the app has been closed.

**Comment by funderburkjim** [comment]
Is it just a UI at present?

If so, you might try to use the 'getword' api, as illustrated in index.html for basic04a display - see [this comment](https://github.com/sanskrit-lexicon/MWS/issues/37#issuecomment-282904182) for reference details.

**Comment by drdhaval2785** [comment]
simple search has this facility now. Closing.
