### ISSUE TITLE
MD requirements

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#103]
All Sanskrit words in explanation within `<s>...</s>` tag or some other tag (in case exigencies mandate so) and in SLP1 please.

This will help me experiment for babylon and stardict files.
@funderburkjim I have not evaluated pros and cons. You may discuss them if any of this approach.

**Comment by funderburkjim** [comment]
@drdhaval2785   
Here are the first few records of md.xml
```
<H1><h><key1>a</key1><key2>a</key2><hom>1</hom></h><body><s>a</s>^1  a, <i>pn.</i> <i>root used in the inflexion of</i> idam <lb/><i>and in some particles</i>: a-tra, a-tha.</body><tail><L>1</L><pc>001-1</pc></tail></H1>
<H1><h><key1>a</key1><key2>a°</key2><hom>2</hom></h><body><s>a°</s>^2  a-, <s>an°</s> an- <i>before vowels</i>, <i>neg. px.</i> = un-.</body><tail><L>2</L><pc>001-1</pc></tail></H1>
<H1><h><key1>aMSa</key1><key2>aMSa</key2></h><body><s>aMSa</s>  a4<i>ms</i>a, <i>m.</i> part, share; <i>N. of a god</i>: <i>in.</i> <lb/>partly.</body><tail><L>3</L><pc>001-1</pc></tail></H1>
<H1><h><key1>aMSakalpanA</key1><key2>aMSakalpanA</key2></h><body><s>aMSakalpanA</s>  a<i>ms</i>a-kalpana1, <i>f.</i> arrangement <lb/>of shares.</body><tail><L>4</L><pc>001-1</pc></tail></H1>
<H1><h><key1>aMSaprakalpanA</key1><key2>aMSaprakalpanA</key2></h><body><s>aMSaprakalpanA</s>  a<i>ms</i>a-kalpana1, <i>f. id.</i>.</body><tail><L>5</L><pc>001-1</pc></tail></H1>
<H1><h><key1>aMSapradAna</key1><key2>aMSapradAna</key2></h><body><s>aMSapradAna</s>  a<i>ms</i>a-prada1na, <i>n.</i> distribution of <lb/>shares.</body><tail><L>6</L><pc>001-1</pc></tail></H1>
<H1><h><key1>aMSaBAgin</key1><key2>aMSaBAgin</key2></h><body><s>aMSaBAgin</s>  a<i>ms</i>a-bha1gin, <i>a.</i> having a share.</body><tail><L>7</L><pc>001-1</pc></tail></H1>
```
Here is scan:
![image](https://cloud.githubusercontent.com/assets/6393033/24059371/3ff96732-0b25-11e7-8634-bd6a197baa6c.png)


The xml looks like a good place for you to start, with one exception.  
That exception is with the AS coding  (like a4 (for a-accent), a1 for a-macron).

So, what I need to do first is to convert that AS coding to IAST unicode.  

Agree?

**Comment by gasyoun** [comment]
> Agree?

Agree. It's the number one issue.

**Comment by funderburkjim** [comment]
For reference, here is the information from md-meta.txt regarding occurrences of AS codings:
```
A1  1364 := Â  (\u00c2)  LATIN CAPITAL LETTER A WITH CIRCUMFLEX
a1 24672 := â  (\u00e2)  LATIN SMALL LETTER A WITH CIRCUMFLEX
a11  1042 := â'   (\u00e2\u0301)  LATIN SMALL LETTER A WITH CIRCUMFLEX and ACUTE
a12     9 := â* (\u00e2\u0306) LATIN SMALL LETTER A WITH CIRCUMFLEX and BREVE
a14    11 := â'   (\u00e2\u0301)  LATIN SMALL LETTER A WITH CIRCUMFLEX and ACUTE
a15     9 := â~ (\u00e2\u0303) LATIN SMALL LETTER A WITH CIRCUMFLEX and TILDE
a3     1 := a3  (in Greek only)
a4  5583 := á (\u00e1) LATIN SMALL LETTER A with ACUTE
a5   162 := â'   (\u00e2\u0301)  LATIN SMALL LETTER A WITH CIRCUMFLEX and ACUTE
a8    29 := ă (\u0103) LATIN SMALL LETTER A WITH BREVE
e1     3 := ê  (\u00ea)  LATIN SMALL LETTER E WITH CIRCUMFLEX
e11     2 := ê'  (\u00ea\u0301)  LATIN SMALL LETTER E WITH CIRCUMFLEX and ACUTE
e4   292 := é  (\u00e9)  LATIN SMALL LETTER E WITH ACUTE
H1 20748 := H1 in <H1> tag
h4     2 := h4  (twice in Greek text)
i1  6826 := î  (\u00ee)  LATIN SMALL LETTER I WITH CIRCUMFLEX
I1    70 := Î  (\u00ce)  LATIN CAPITAL LETTER I WITH CIRCUMFLEX
i11   337 := î'  (\u00ee\u0301)  LATIN SMALL LETTER I WITH CIRCUMFLEX and ACUTE
i12     3 := î*  (\u00ee\u0306) LATIN SMALL LETTER I WITH CIRCUMFLEX and BREVE
i14     3 := î'  (\u00ee\u0301)  LATIN SMALL LETTER I WITH CIRCUMFLEX and ACUTE
i4   924 := í (\u00ed) LATIN SMALL LETTER I and ACUTE
i5    29 := î'  (\u00ee\u0301)  LATIN SMALL LETTER I WITH CIRCUMFLEX and ACUTE
i8    17 := ĭ (\u012d) LATIN SMALL LETTER I WITH BREVE
i9     5 := ĭ (\u012d) LATIN SMALL LETTER I WITH BREVE
m2     1 := m%  (\u006d\u0310)  LATIN SMALL LETTER M WITH CHANDRABINDU
N3    12 := Ṅ  (\u1e44)  LATIN CAPITAL LETTER N WITH DOT ABOVE
n3  1076 := ṅ  (\u1e45)  LATIN SMALL LETTER N WITH DOT ABOVE
N5    31 := Ñ  (\u00d1)  LATIN CAPITAL LETTER N WITH TILDE
n5   959 := ñ  (\u00f1)  LATIN SMALL LETTER N WITH TILDE
o11     1 := ô'  (\u00f4\u0301)  LATIN SMALL LETTER O WITH CIRCUMFLEX and ACUTE
o4   223 := ó  (\u00f3) LATIN SMALL LETTER O and ACUTE
U1    53 := Û  (\u00db)  LATIN CAPITAL LETTER U WITH CIRCUMFLEX
u1  2601 := û  (\u00fb)  LATIN SMALL LETTER U WITH CIRCUMFLEX
u11   164 := û'  (\u00fb\u0301)  LATIN SMALL LETTER U WITH CIRCUMFLEX and ACUTE
u12     1 := û (\u00fb\u0306) LATIN SMALL LETTER A WITH CIRCUMFLEX and BREVE
u14     7 := û' (\u00fb\u0301)  LATIN SMALL LETTER U WITH CIRCUMFLEX and ACUTE
u4   681 := ú (\u00fa) LATIN SMALL LETTER U and ACUTE
u5    15 := û' (\u00fb\u0301)  LATIN SMALL LETTER U WITH CIRCUMFLEX and ACUTE
u7     2 := ü  (\u00fc)  LATIN SMALL LETTER U WITH DIAERESIS
u8    11 := ŭ (\u016d) LATIN SMALL LETTER U WITH BREVE
u9     2 := ŭ (\u016d) LATIN SMALL LETTER U WITH BREVE
w11     1 := w11 once, in Greek
```

**Comment by funderburkjim** [comment]
For the most part, the conversions indicated above will be those that I'll use to replace the AS codings in md.txt.

However, there will be a few differences, in deference to modern conventions.

The main difference will be that  vowel-circumflex  will be changed to vowel-macron.

So, instead of `A1  ->  Â`, the conversion will be `A1  -> Ā `

**Comment by gasyoun** [comment]
> The main difference will be that vowel-circumflex will be changed to vowel-macron.

Yes, yes, yes!

**Comment by funderburkjim** [comment]
Here is another thing that should be changed, but that I just noticed - it is not mentioned in md-meta.txt.

This was seen under 'kram' : {%k%}an3kramate   
![image](https://cloud.githubusercontent.com/assets/6393033/24061388/a5028fe8-0b2d-11e7-9b0b-55f6ea8f6d5b.png)

So MD is using an initial italicized 'k'  instead of 'c', in those reduplicated verb forms.

In fact there are 16,000+ instances of a single italicized letter in md.txt.  Most of these seem to be
representing a Sanskrit letter (Muller's convention?)
 So we should change these to their modern IAST forms also.

**Comment by gasyoun** [comment]
> So MD is using an initial italicized 'k' instead of 'c', in those reduplicated verb forms.

Yes, it's prehistorical and inspired by Max Mueller, it's a hell.

> So we should change these to their modern IAST forms also.

Yes, yes and again yes!

**Comment by funderburkjim** [comment]
Here is another peculiarity of the digitization of MD.  
```
<H1>{#akarman#}¦~a-karman, {%n.%} inaction; {%a.%} (-ma4n) 
<>doing nothing, idling; wicked.
<H1>{#akarmaprApti#}¦~a-karma-pra1pti, {%f.%} non-intervention
<>12[] of fate.   <<<
<H1>{#akarmaSIla#}¦~a-karma-{%s%}i1la, {%a.%} inactive, idle.
<H1>{#akarmaSrAnta#}¦~a-karma-{%s%}ra1nta, {%pp.%} untiring in 
<>[]ritual.  <<<
<H1>{#akalaNka#}¦~a-kalan3ka, {%a.%} spotless.
<H1>{#akali#}¦~a-kali, {%a.%} not quarrelling, concordant.
<H1>{#akalita#}¦~a-kalita, {%pp.%} unknown; undefinable.
<H1>{#akaliprasara#}¦~akali-prasara, {%a.%} where no quarrelling
<>4 occurs.  <<<
<H1>{#akalkakalila#}¦~a-kalka-kalila, {%a.%} free from 
<>[]baseness.  <<<
<H1>{#akalkatA#}¦~a-kalka-ta1, {%f.%} honesty.
```
There is this description from Thomas:
```
<> with number following = line break at character of preceding word (including marks)
```
![image](https://cloud.githubusercontent.com/assets/6393033/24067939/87133e3e-0b59-11e7-970b-5228d0650c92.png)

It's hard to know what to do with such cleverness.  For now, at least I can do nothing but stand back
in wonder.

**Comment by funderburkjim** [comment]
md.txt uses a bold-italic markup for root headwords:
```
<H1>{@{#akz#}@}¦~AKSH, reach: {%pp.%} {@ash{%t%}a. nis,@} unman.

```
There are only 5 cases where this bold-Sanskrit markup is used in a different way:
```
  13528:<H1>{@{#inv#}@}¦~INV, I.P. {@i4nva-ti,@} {%or%} {@{#in#}@} IN, VIII. 
  20095:<H1>{@{#kuc#}@}¦~KU{%K%}, VI.P. {@ku{%k%}a@}, {@{#kuYc#}@} KU{%N5K,%} 
  22253:<H1>{#kruYc#}¦~kru4{%n5k%} ({%nm.%} {@krun3@}), {@{#kruYca#}@} kru4{%n5k%}a, {%m.%} curlew.
  96487:<H1>[{@{#sI#}@}¦~SI1, draw a straight line.]
```

Just noting this feature. No action seems required at the moment.

**Comment by gasyoun** [comment]
> No action seems required at the moment.

Let's add a root markup.

**Comment by drdhaval2785** [comment]
@funderburkjim let me know when this is over.

**Comment by funderburkjim** [comment]
### This conversion to IAST is done.   

The [md-meta2](http://www.sanskrit-lexicon.uni-koeln.de/scans/MDScan/2014/pywork/md-meta2.txt) file describes the current particulars of the md.txt digitization file.

The [md.dtd](http://www.sanskrit-lexicon.uni-koeln.de/scans/MDScan/2014/pywork/md.dtd) describes the structure of md.xml.  The only change here was the addition of an 'lbinfo' tag, which puts the odd line break information described [above](https://github.com/sanskrit-lexicon/Cologne/issues/103#issuecomment-287507422) into the value of the 'n' attribute of 'lbinfo'.

### methodological details
The conversion of the AS and italics  to IAST is conceptually fairly simple;  The [astable.txt](http://www.sanskrit-lexicon.uni-koeln.de/scans/MDScan/2014/pywork/20170324/astable.txt) file gives the idea.   The last column shows how the print edition represents the Sanskrit alphabet.  The digitization representation is an amalgam of the italic parts of the last column ({%ri%}, for instance) and the AS parts of the next-to-last column (e.g. a1 = आ).   The third to last column shows modern IAST.
So the conversion task is to change the forms shown in the AS/italics columns to the form shown in the modern IAST column.

Both of these conversions could be done via the general transcoding process, guided by special purpose transcoding definition files.

For the AS  conversion (letter-number to modern IAST), the process is governed by the [mdas_roman.xml](http://www.sanskrit-lexicon.uni-koeln.de/scans/MDScan/2014/pywork/20170324/mdas_roman.xml) transcoding definitions.
This part is quite easy.

For the conversion of italicized sections to modern IAST, the [mditalic_roman.xml](http://www.sanskrit-lexicon.uni-koeln.de/scans/MDScan/2014/pywork/20170324/mditalic_roman.xml) governs most of the cases.  Note that in addition to the expected conversions of single letters, such as {%ri%} to ṛ,  there are hundreds of more complex conversions.   Detecting these additional cases is what made this task so odiously complicated.

One other detail is that the retroflex sibilant is represented in the text, and coded in the digitization as a non-italicized 'sh'.   A blanket conversion of 'sh' to  'ṣ' would erroneously convert many English words spelled with 'sh'  (ship, ship, etc.);  and there are some words or word-fragments that could be either English or Sanskrit (.e.g., rush), so the context had to be examined.
was an odious task, with hundreds of special cases.  The main way to handle these was to compile a list of all  words with 'sh' in the text of MD, and to (a) weed out those that are English, and (b) to provide adequate context for the small number of ambiguous cases.   The [mdsh_roman.xml](http://www.sanskrit-lexicon.uni-koeln.de/scans/MDScan/2014/pywork/20170324/mdsh_roman.xml) transoding definitions essentially handles (a).  A few context additions (like `-rush` which was determined to only occur when the Sanskrit root was intended) were made to handle the (b) cases.

### completeness (almost)
Although a valiant effort was made to ensure the completeness of the conversion to modern IAST, it is almost certain that some cases slipped past.  When noticed, these can be corrected as normal corrections.

### accents and IAST
MD uses accents profusely, and the digitization represents these.   I have taken the [Wikipedia article on IAST](https://en.wikipedia.org/wiki/International_Alphabet_of_Sanskrit_Transliteration) as gospel for modern IAST.    But this article is silent on Sanskrit accents.   As the table in  [md-meta2](http://www.sanskrit-lexicon.uni-koeln.de/scans/MDScan/2014/pywork/md-meta2.txt) shows the choices made.,   

Basically, there are two ways to add an acute accent to a Latin letter in Unicode.
*  With a preformed letter, such 'a+acute' = `á` is unicode code point \u00e1 LATIN SMALL LETTER A WITH ACUTE.
*  With a combining accent, unicode code point \u0301 COMBINING ACUTE ACCENT.  This is necessary for a few cases where there is no preformed unicode code point. For instance, the Sanskrit vocalic `r` is represented as unicode code point  ṛ LATIN SMALL LETTER R WITH DOT BELOW, but there is no preformed letter that has both the r with dot below and acute accent.  So, the use of the combining acute accent is required to be appended.  

Another choice would have been to always use the combining accent.  This would have the advantage of uniformity of identification of accented letters.  This would have the disadvantage of spotty display implementation (for instance, in Emacs, I often cannot see the accent with    ṛ;  and even in constructing this GitHub comment, I could not readily copy-paste  to construct ṛ with an accent. )  
On balance, I thought it was better to use the preconstructed accented letters when these were available.

**Comment by funderburkjim** [comment]
@drdhaval2785 md.xml should be ready for you to convert to stardict form.

The md.dtd should let you know how to convert.  Text Devanagari is represented in SLP1; this only occurs in key1, key2, and the few additional cases of the 's' tag.  You will also want to probably remove the 'g' and 'lbinfo' tags, at least, maybe a few others.

Let us know when you have a stardict form you can load into colordict on Android.

**Comment by funderburkjim** [comment]
Here is what the first few lines of md.xml look like now:
```
<H1><h><key1>a</key1><key2>a</key2><hom>1</hom></h><body><s>a</s>^1  a, <i>pn.</i> <i>root used in the inflexion of</i> idam <lb/><i>and in some particles</i>: a-tra, a-tha.</body><tail><L>1</L><pc>001-1</pc></tail></H1>
<H1><h><key1>a</key1><key2>a°</key2><hom>2</hom></h><body><s>a°</s>^2  a-, <s>an°</s> an- <i>before vowels</i>, <i>neg. px.</i> = un-.</body><tail><L>2</L><pc>001-1</pc></tail></H1>
<H1><h><key1>aMSa</key1><key2>aMSa</key2></h><body><s>aMSa</s>  áṁśa, <i>m.</i> part, share; <i>N. of a god</i>: <i>in.</i> <lb/>partly.</body><tail><L>3</L><pc>001-1</pc></tail></H1>
<H1><h><key1>aMSakalpanA</key1><key2>aMSakalpanA</key2></h><body><s>aMSakalpanA</s>  aṁśa-kalpanā, <i>f.</i> arrangement  <lbinfo n="[]"/> <lb/>of shares.</body><tail><L>4</L><pc>001-1</pc></tail></H1>
<H1><h><key1>aMSaprakalpanA</key1><key2>aMSaprakalpanA</key2></h><body><s>aMSaprakalpanA</s>  aṁśa-kalpanā, <i>f. id.</i>.</body><tail><L>5</L><pc>001-1</pc></tail></H1>
<H1><h><key1>aMSapradAna</key1><key2>aMSapradAna</key2></h><body><s>aMSapradAna</s>  aṁśa-pradāna, <i>n.</i> distribution of  <lbinfo n="[]"/> <lb/>shares.</body><tail><L>6</L><pc>001-1</pc></tail></H1>
<H1><h><key1>aMSaBAgin</key1><key2>aMSaBAgin</key2></h><body><s>aMSaBAgin</s>  aṁśa-bhāgin, <i>a.</i> having a share.</body><tail><L>7</L><pc>001-1</pc></tail></H1>
```

This can be compared to the 'before IAST' form shown in [comment above](https://github.com/sanskrit-lexicon/Cologne/issues/103#issuecomment-287448526)

**Comment by funderburkjim** [comment]
###  identifying roots

In md.txt, the Sanskrit root entries can be identified by the regular expression:
```
¦~[A-ZĀĪŪÑŚḌṄṆṚṢṬ]
```
There are 992 found.  [Here](https://gist.github.com/funderburkjim/f0a040920c2316f1fa950b75718738c5) are the lines of md.txt so chosen.

It would be reasonable to add an empty markup  (maybe `<vlex type="root"/>`  (as in mw.xml) to these;
but I haven't yet done so.

**Comment by gasyoun** [comment]
> It would be reasonable to add an empty markup

You name it.

> but I haven't yet done so.

It's up to you and not Dhaval anyway. So we, the root lovers out there, can only hope for the `<vlex type="root"/>` markup. Afte that manual fine tuning can be done. In:

```
<H1>{@{#aYj#}@}¦~AÑJ, VII. {@anákti, aṅkté,@} anoint, 
<H1>{@{#aw#}@}^1¦~AṬ, I.P. roam about, wander 
```

We have a meaning, that's best possible way.

```
<H1>{#aYc#}^1¦~AÑC, {%v.%} {#ac#} ¤1.¤ aC.
<H1>{@{#as#}@}^1¦~AS, II.P. {@ás-ti@} (¤2¤ {%sg.%} Ā. {@se,@} {%in V. %}
<H1>{@{#As#}@}^4¦~ĀS, II.Ā. {@ā́s-te@} ({%E.%}+ I.Ā. Āsa, II. 
<H1>{@{#kft#}@}^1¦~KṚT, VI.P. {@kṛnatá@} ({%E. also%} Ā. {%and%} 
```

No meaning. For that I do not see no regex way other than manual tuning, because not all root entries are similar. Markup dirt left (a case for RegEx):

```
<H1>{@{#ujJ#}@}¦~UJJH [ud + hā], VI.P. {@ujjha@}, abaudon, <lbinfo n="4"/>
<H1>{#kf#}^2¦~KṚ, {%pt.%} {@cakrát@}, {%intv.%} {@car-kṛ@}, remember, <lbinfo n="2"/>
<H1>{@{#kzad#}@}¦~KSHAD, I.Ā. {@kṣáda,@} carve; slaughter. <lbinfo n="6"/>
<H1>{@{#kzap#}@}¦~KSHAP, I. {@kṣapa,@} practise abstinence <lbinfo n="5"/>
```

Root allomorphs:
```
<H1>{#und#}¦~UND, {%v.%} {#ud#} UD.
<H1>{#uh#}¦~UH, {%v.%} {#Uh#} ŪH.
<H1>{#kalp#}¦~KALP, {%v.%} {#klip#} KḶP.
<H1>{#[kuq#}¦~KUḌ, {#kuRq#} KUṆḌ, encircle.].
<H1>{#gA#}^2¦~GĀ, {%v.%} {#gE#} GAI.
<H1>{#gf#}¦~GṚ, {%v.%} {#jAgf#} JĀGṚ.
```

Two or more classes:
```
<H1>{@{#fD#}@}¦~ṚDH, IV.P. {@ṛdhya@}; V.P. {@ṛdh-nó-@}
<H1>{@{#gam#}@}¦~GAM, I. {@gáma@} {%and%} II. {@gán-ti@} ({%V.%}); 
```

With upasargas:
```
<H1>{@{#kf#}@}^1¦~KṚ (skṛ after upa, pari, sam), VIII. 
<H1>{@{#Gaww#}@}¦~GHAṬṬ, I.Ā. (only with vi {%and%} sam) 
```

In `<H1>{@{#jakz#}@}^1¦~JA-KSH [{%redupl. of%} ghas]. II.P. ` the `-` between `A-K` makes no sense.

**Comment by drdhaval2785** [comment]
I regenrerated stardict. My requirement over. Gasyoun and Jim may discuss finer nuances of verbs.

**Comment by drdhaval2785** [comment]
Regarding verbs identification, https://github.com/sanskrit-lexicon/MD/issues/1 is a much detailed work. Closing.
