### ISSUE TITLE
Novice Non-friendly, Lack of Metadata

### ISSUE THREAD

**Issue by Shalu411** [sanskrit-lexicon/COLOGNE#11]
Namaste
The display on page is too "new user non-friendly". New users should also be given fair chance to explore. When one sees the page (without seeing home page- if directly enters the search page) it doesn't say anything in the title that it is a dictionary. What input language, what output, nothing. One who is familiar alone can know how and what to do on the page. So some background is presumed. This is all it says-
Grosses Petersburger Wörterbuch
bearbeitet von Otto Böhtlingk und Rudolph Roth
7 Theile, St. Petersburg 1855 
One has to click on "about" to get an idea, where one has landed. Even that is one sentence. (Advanced search is better though. In help we get good information.) This is exactly what happened to me in 2005-06 when I was a novice in the field. It was too late when I realized how worthy a resource I was away from all these years..!
1. A small description about how to use that page right at the top or bottom will surely help.  
2. Some things like - drop-down menu information (like at Find Word - Example with a HK alphabet- (Better - Harvard-Kyoto :) not HK)) will help. Or something like- a small display when mouse is placed on it.
3. "Input", "out put", "Dbg On, Off", in Basic Display; and "exact", "sub string" etc. in Advanced Display need some hints, suggestions and information of help with.
   Thankyou

**Comment by drdhaval2785** [comment]
There is another reason why people end up on deprecated links - Google.
The first search for 'monier williams' on google is http://www.sanskrit-lexicon.uni-koeln.de/monier/
which is 2008 version.
If I get a message that this is deprecated version - and I should go to XXXXXXX site, it would be great.

**Comment by gasyoun** [comment]
Exactly, because of Google's index.

**Comment by funderburkjim** [comment]
Should   XXXX site be the cologne sanskrit lexicon [home page](http://www.sanskrit-lexicon.uni-koeln.de/)
or the current [MW basic display](http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/webtc/indexcaller.php) ?

**Comment by gasyoun** [comment]
Current MW would do a better job.

**Comment by funderburkjim** [comment]
Added links to the 2008 display.

**Comment by gasyoun** [comment]
Just links might not be noticed. @Shalu411 would it do?

**Comment by drdhaval2785** [comment]
@funderburkjim 
I guess it is now time to kill the deprecated links.
Make them redirect to the latest link for the given dictionary.

And block google search for deprecated ones by using readme at https://support.google.com/webmasters/answer/1663419?hl=en.

**Comment by funderburkjim** [comment]
History shows that killing the deprecated links would lead to unhappy users.

So, we should leave the deprecated links.

However, I like the idea of blocking google search for the deprecated ones.

Since you've understood the google link,  can you tell me what I need to do to block google search on the deprecated ones?

**Comment by gasyoun** [comment]
> Since you've understood the google link, can you tell me what I need to do to block google search on the deprecated ones?

http://blog.hubspot.com/marketing/how-to-unindex-pages-from-search-engines

> History shows that killing the deprecated links would lead to unhappy users.

Better unhappy, than still using a 2008 edition. I know about 20 people using the 2008 edition, who are not even aware of anything newer. Because it's #1 in search.

**Comment by funderburkjim** [comment]
The above hubspot link points to a [robots.txt tutorial](https://support.google.com/webmasters/answer/6062608?hl=en&topic=1724262&ctx=topic&visit_id=1-636124245626650348-1004931910&rd=1), which in turn says that

>You should not use robots.txt as a means to hide your web pages from Google Search results

But instead suggests use of [noindex](https://developers.google.com/webmasters/control-crawl-index/docs/robots_meta_tag).

This article in turn says that this meta element in `<head>` of html page:
```
<meta name="robots" content="noindex" />
```
>instructs all search engines not to show the page in search results. 

So, That `<meta>` element looks to be the thing to add to the pages mentioned in the ['Deprecated Editions'
section](http://www.sanskrit-lexicon.uni-koeln.de/#deprecated) of Cologne home page.

@gasyoun You know about SEO.  Does adding the meta tag to those links look to be the right
thing to do, so the deprecated pages don't show up in web searches?

**Comment by gasyoun** [comment]
> meta tag to those links look to be the right
thing to do

Yes. Robots.txt + meta tag noindex should do the thing.

**Comment by funderburkjim** [comment]
Added the above 'meta' element to the following web pages, which appear in the 'Deprecated'
section of the Sanskrit-lexicon home page:
```
/scans/MWScan/2012/web/index.php Monier-Williams Sanskrit-English Dictionary, 2012/2013 displays
/monier/indexcaller.php  Monier-Williams Sanskrit-English Dictionary, 2008
/mwquery/index.html  Monier-Williams Advanced Search, 2008
/scans/MWScan/tamil/index.html   Sanskrit and Tamil  Dictionaries, 2005
/scans/WILScan/web/index.php Wilson Sanskrit-English Dictionary, semi-digitized edition, 2008
/aequery/index.html  Apte English-Sanskrit Dictionary, 2007
/scans/PWGScan/disp2/index.php  Boehtlingk & Roth Sanskrit-German Dictionary, 2011
/scans/PWScan/disp2/index.php  Boehtlingk + Schmidt Sanskrit-German Dictionary, 2012
```

Can someone think of (and do) a **before/after** kind of test with Search engines to see if this
meta tag has any effect?

**Comment by gasyoun** [comment]
> before/after kind of test with Search engines to see if this
meta tag has the desired effect?

Not now, after 45 days we will test. For now all we can do is ping Google.

**Comment by drdhaval2785** [comment]
@gasyoun at least use your SEO skills. Let us know the status.

**Comment by gasyoun** [comment]
> The first search for 'monier williams' on google is http://www.sanskrit-lexicon.uni-koeln.de/monier/
which is 2008 version.

Remains the same.

![mws](https://user-images.githubusercontent.com/80761/64357814-0b58cf80-d00e-11e9-85df-b2159b471aa8.PNG)

**Comment by drdhaval2785** [comment]
![Screenshot_20201217-181532_Chrome](https://user-images.githubusercontent.com/5755132/102489738-e87fec80-4093-11eb-8f0a-91c955b1718c.jpg)
Now Google has 2020 version. Not bad. Closing this issue.
