### ISSUE TITLE
Benfey IAST

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#112]
### long-short vowel coding

There are numerous (200+) instances where Benfey uses a combined diacritic over a vowel to indicate
that the vowel is either short or long.

![image](https://cloud.githubusercontent.com/assets/6393033/24784826/471907c6-1b23-11e7-838b-5af95412a277.png)

In converting to IAST, we will change the circumflex to a macron.  

But how to represent the short-vowel sign also?

In the digitization, the `¤` (CURRENCY SIGN) is used.  So, we could represent  the above as `ī¤`.

aṅgulī¤

Another way would be to use the unicode Combining-Breve  `ī\u0306`  (I can't paste this 
combining breve in).

An alternate would be to introduce a separate xml-type markup, maybe something like
```
<longshort n="aṅguli">aṅgulī</longshort>
```
In MW, this is handled by putting an empty `<shortlong/>` tag after the vowel, as in
```
<H1><h><hc3>501</hc3><key1>aBiDI</key1><hc1>1</hc1><key2>aBi-<root>DI</root></key2>
</h><body> <p><ab>perf.</ab> <c>1.</c>~ <ab>sg.</ab>~<s>-dIDayA<shortlong/>
</s>~;~<ab>p.</ab>~ <vlex>A1.</vlex>~<s>-dI/DyAna</s>~<ls>RV._iv_,_33_,_9</ls></p>
 <c><to/>to_reflect_upon_,_consider</c> <ls>RV._iii_,_38_,_1_and_x_,_32_,_4.</ls> </body>
<tail><mul/> <MW>008408</MW> <pc>63,2</pc> <L>11550</L></tail></H1>
```
![image](https://cloud.githubusercontent.com/assets/6393033/24785163/9c8ee200-1b25-11e7-9db3-ecd2bd225d32.png)

With the MW notation: `aṅgulī<shortlong/>`.  The drawback
is that this leaves open the final resolution of the two forms of the vowel (although a short computation could look at the preceding vowel and deduce the two forms), and how to display
the two forms.  Also, I am unsure in MW whether the vowel preceding `<shortlong/>` is always
the long vowel, as in the above example, and whether the length of the preceding vowel matters.

Although more verbose, one of the xml forms might be the best.
 
For consistency, maybe we should go with the MW markup scheme.

Any suggestions?

**Comment by gasyoun** [comment]
> In converting to IAST, we will change the circumflex to a macron.

Agree.

> Another way would be to use the unicode Combining-Breve ī\u0306 (I can't paste this
combining breve in).

That would be the Unicode way. As there is no such sign in Unicode in my Charter font it's a private character.

![breve](https://cloud.githubusercontent.com/assets/80761/24793698/afa681ac-1b8b-11e7-96b3-faf464866f6c.PNG)

> An alternate would be to introduce a separate xml-type markup, maybe something like <longshort n="aṅguli">aṅgulī</longshort>

It would be better to update MW this way, than just `aṅgulī<shortlong/>`, because without the computation nobody knows what is behind it. And in this case, we should get a new alternative headword as well. So it's important to know that it is and not to calculate it each time.

**Comment by funderburkjim** [comment]
@gasyoun   So you favor the combining breve:   ī̆   ?

I think combining breve is widely available.  I couldn't copy it from [fileformat](http://www.fileformat.info/info/unicode/char/0306/index.htm) page for some reason.

**Comment by funderburkjim** [comment]
This combining-breve approach is  reasonable when Latin letters with diacritics are used to represent Sanskrit.

It would not be appropriate in situations where the coding of Sanskrit uses SLP1, such as in MW.

I wonder if there is some Devanagari way to represent the short-long vowel situation.

**Comment by gasyoun** [comment]
> favor the combining breve: ī̆ ?

For typographical purposes - sure.

> I couldn't copy it from fileformat page for some reason.

Neither do I.

> I wonder if there is some Devanagari way to represent the short-long vowel situation.

No and that's where IAST is above Devanagari.

> It would not be appropriate in situations where the coding of Sanskrit uses SLP1, such as in MW.

Let's ask Peter what tag to invent. It would be stupid not to have it and use always IAST instead of SLP1 where it makes sense. If Peter will not give one, we'll take it ourselves.

**Comment by drdhaval2785** [comment]
Let's ask Peter what tag to invent. It would be stupid not to have it and
use always IAST instead of SLP1 where it makes sense. If Peter will not
give one, we'll take it ourselves.


There are SLP2, 3, 4.
There may be some item in them to represent this phenomenon. Peter always
replies this.

**Comment by gasyoun** [comment]
> There are SLP2, 3, 4.

I'm aware.

> There may be some item in them to represent this phenomenon

Jim, should I ask or you can?

**Comment by funderburkjim** [comment]
As I recall, the 'shortlong' tag was Peter's idea in the first place.  But this may have been before his
LIES book, which describes the other SLP's.

Dhaval -  How do Sanskrit Grammarians refer to such situations  like (aNguli, aNgulI) ?  Is this a topic
in traditional Sanskrit Grammar, or an invention of European grammarians of Sanskrit?

**Comment by drdhaval2785** [comment]
Dhaval - How do Sanskrit Grammarians refer to such situations like (aNguli,
aNgulI) ? Is this a topic
in traditional Sanskrit Grammar, or an invention of European grammarians of
Sanskrit?


There is no such case in Sanskrit. Purely European intervention. आवली आवलि
etc are written separately everywhere in koSas. To be frank, I cant even
understand properly what Benfey is trying to say here? Is it read as
alternatives aNguli/aNgulI in single reading?

**Comment by gasyoun** [comment]
> alternatives aNguli/aNgulI in single reading?

Yes.

**Comment by funderburkjim** [comment]
> Purely European intervention

Thanks for confirming my suspicion.

Yes, I think Benfey is saying there are two alternate spellings.

**Comment by funderburkjim** [comment]
Benfey conversion to IAST now completed.

new ben.xml file available.

I ended up using the combining breve form:  ī̆

**Comment by funderburkjim** [comment]
For future reference, the details are in pywork/20170407 folder.

This is part of the 'pywork' download for Benfey.

**Comment by gasyoun** [comment]
> I ended up using the combining breve form: ī̆

Good to know.
