### ISSUE TITLE
Word Weight vs. Alphabetical Order in Search Results

### ISSUE THREAD

**Issue by Shalu411** [sanskrit-lexicon/COLOGNE#12]
Namaste
In the Advanced display parameters- "Maximum" 20, 50, 100, 200 etc. is for output options. Right? 
(Please suggest that with "Maximum Words/results in output"- that's a different issue)

Here my point is the exact word searched for (that particular spelling-ed word) should be given first preference of appearance. Others should follow, only later. So if I am searching for a very popular word and it has 1000s of appearances, then I will have to keep on increasing my Maximum output - until I find it. This happened recently to me, when I was trying to explain how to use this page to my friend.

So this thing could be rectified by 1. giving exact word first and 2. Arranging the entries not by alphabet order, but by maximum number of occurence of the word in the text of that particular suggested word.
Thankyou.

**Comment by drdhaval2785** [comment]
@funderburkjim Point 2 and 3 are worth doing.

**Comment by gasyoun** [comment]
@drdhaval2785 let us start using Projects. See bellow:

![projects](https://user-images.githubusercontent.com/80761/102532644-52f55480-40b5-11eb-885b-b30cf3d9fdc3.JPG)
