### ISSUE TITLE
google analytics on Cologne

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#120]
I am not sure whether we have any analytics installed or not. If not, worthwhile to do so. Give us viewibg rights.

**Comment by gasyoun** [comment]
I've spoken about it a year ago, Jim said there is none and will be none. We had Piwik for some time, @funderburkjim removed it as well.

**Comment by drdhaval2785** [comment]
Closing. Analytics is not much required for a low traffic site as ours.
