### ISSUE TITLE
user query statistics

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#121]
Just to give us moral boost that our labour is not going down the drain, would it be possible to keep some 10-15 different query statistics, so that we can check whether our popularity increased, decreased etc.

**Comment by gasyoun** [comment]
> 10-15 different query statistics, so that we can check whether our popularity increased, decreased etc.

We can ask to look at server logs at least, I guess. @funderburkjim what's your take?

**Comment by gasyoun** [comment]
@funderburkjim tried Piwik before, but there are several Cologne limitations. We can't have Google Analytics if I get it right, @drdhaval2785

**Comment by drdhaval2785** [comment]
Not worth the trouble. Closing this.
