### ISSUE TITLE
cologne scripts in this repository

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#128]
IMPORTANT

This issue is an offshoot of Jim's exclamation and sigh at being the only assignee.

# Review of present scenario

1. Cologne server has following folders txt, xml, pywork.
2. Jim does some changes based on need in his local machine and uploads on cologne server / changes server file directly and closes an issue. He usually gives very detailed theoretic explanation for his handling.
3. We don't have a clue what he did in his code. Every coder has uniques style just as every author has. If I dont get what Jim did to fix an issue, I can't fix it myself in future.

# Proposal

1. There are only few data files which are necessary input e.g. pw.txt, updatebyline.txt etc.
The rest pw.xml, hw0.txt etc are generated files.
2. There are scripts to convert input into output.
3. If we can identify necessary input files and upload them to this directory, and add scripts in this directory, it will be easy to track changes which Jim makes.
4. I can git pull and run redo.sh to generate the derived files in my local machine. This will keep github repository relatively clean. There is no point tracking changes in pw.xml if I am tracking pw.txt and scripts properly. I can regenerate any time.
5. Enumerate the derived files in .gitignore so that they dont get uploaded even by error.

What do @funderburkjim and @gasyoun think?

**Comment by drdhaval2785** [comment]
If we are concerned with world looking at our scripts, we can buy a private organization or repo at github and restrict access to allowed ones.

**Comment by gasyoun** [comment]
> We don't have a clue what he did in his code

Exactly. And you are the only one around smart enough to try to follow him at least.

> There is no point tracking changes in pw.xml if I am tracking pw.txt and scripts properly. I can regenerate any time.

Right. This is what I and Jim agree on as well. We see the results, but not the process. Without the processes even the simplest change on Cologne will be impossible if Jim finds a more attractive hobby like gardening, for example.

**Comment by drdhaval2785** [comment]
# make cologne server sync with github

If we come to an agreement to the above proposal, I request making a script which will take the latest github changes and copy to Cogne server e.g. `git pull` on Cologne server.
This way guthub and Cologne server may keep in sync. This will also obviate the need for password etc for accessing Cologne server from collaborators like me. I can push to github. Cologne server can take it from github. As only authorised collaborators can push to guthub repositpry, safety or stability should not be much of an issue.

**Comment by gasyoun** [comment]
> Cologne server can take it from github

Without Jim launching it manually, the redo file?

**Comment by drdhaval2785** [comment]
A cronjob every hour?

**Comment by gasyoun** [comment]
> A cronjob every hour?

Hmm, sounds ok, should not kill the server. But at the same time you can't make a change - remember how MW went wrong, when a backup was made at the same time?

**Comment by drdhaval2785** [comment]
See the brighter side Marcis. Even if ine git pull goes off track and some
file was being uploaded to github, it will autocorrect with next cycle
within an hour. In current scenario we even dont know if a particular page
had problem, before anybody reports it.

Self correcting system does seem better.

**Comment by drdhaval2785** [comment]
And if there is no difference in github repo, git pull will return empty.
Not much load on server.

**Comment by drdhaval2785** [comment]
And every hour is just to mention possibility. Otherwise, every day is also
fine for me. We dont run google inc. One day lag is also justifiable.

**Comment by gasyoun** [comment]
> In current scenario we even dont know if a particular page
had problem, before anybody reports it.

Right.

> One day lag is also justifiable.

Ok, at what time should it be done?

**Comment by drdhaval2785** [comment]
Ok, at what time should it be done?


See https://github.com/sanskrit-lexicon/CORRECTIONS/graphs/punch-card.

So 12.30 pm IST i.e. 07.00 GMT i.e. 03:00 US time seems ideal time. Jim
usually completes his corrections by 08.30 am IST (23.00 US time) and I go
office around 10.30 am IST.

So 12.30 IST doesnt have active members presnt.

**Comment by gasyoun** [comment]
> 12.30 IST

Great.

**Comment by drdhaval2785** [comment]
In absence of Jim, we have decided the methodology in detail. Only whether
to apply or not remains to be decided by Jim. ;-)

**Comment by funderburkjim** [comment]
I see your point in wanting to be able to follow the process, as well as the results.

The details of how to accomplish this goal are not clear enough for me to implement right now.

However, I'll keep the above suggestions in mind as I proceed with IAST and other projects.

Dhaval, how does this relate to the idea of a shadow Cologne server that we've discussed recently via email?

**Comment by drdhaval2785** [comment]
The details of how to accomplish this goal are not clear enough for me to
implement right now.


1. Make your local computer folder a git repository which hold acc, ap90,
ap .... etc subfolders. Before you commit these, ensure that they are the
same as in Cologne server.
2. gi commit and git push them to sanskrit-lexicon/cologne repository.
3. git clone this repository to cologne server.
4. Make a cronjob on cologne server which does git pull origin master every
one or two hours.
5. Remove the non technical persons from collaborators in this particular
repository, otherwise a wrong move from them will destabilise cologne
servers.

I think this is it. Whenever I or you push some change to github
repository, within one or two hours Cologne will absorb that change.

Dhaval, how does this relate to the idea of a shadow Cologne server that
we've discussed recently via email?


They may be treated as alternatives.

**Comment by funderburkjim** [comment]
I am leary to push to Cologne, as Cologne is the active version.  I would rather treat Cologne as
the 'master'. 

I would rather pull from Cologne.   
To repeat a question asked in some other issue a few hours ago:

What git command would be
needed to pull a git repository on Cologne  to my local computer?

**Comment by drdhaval2785** [comment]
First you need to do

git clone repositoryaddress

Thenvfor any change later on

git pull origin master

**Comment by drdhaval2785** [comment]
I am leary to push to Cologne, as Cologne is the active version. I would
rather treat Cologne as
the 'master'.

I would rather pull from Cologne.


Usually for development, we do test the code on localhost and then if it
works as desired, we upload from local machine to server. At least it is
the way I do.

If I do some modification to the script, how is it going to be absorbed in
Cologne server if it is not pulling from github?

My proposal is

0. At one particular point of time our local machine is brought to sync
with Cologne server.
1. We do test and develop code in local machine.
2. We push to Github repository (and not directly to Cologne server) from
local machine.
3. Cologne does git pull from Github to grab latest changes in code.


This will help us track changes made in Cologne scripts via version control
of github. Currently the changes in code are not tracked via git.

**Comment by gasyoun** [comment]
> This will help us track changes made in Cologne scripts via version control
of github. Currently the changes in code are not tracked via git.

Makes sense.

**Comment by funderburkjim** [comment]
In my experience, there are sometimes little differences between the cologne server and local that are tricky to eliminate.

For instance,  I recently wrote a bash script on local machine when doing one of the IAST conversions.  But, when I uploaded to Cologne, the script failed.  Why?  It turned out that the difference was due to line endings.  I created the script X.sh using local text editor, and it followed the Windows convention of \r\n line endings.   When run under the  Linux of Cologne,  the '\r' was treated as a character , rather than as part of the line ending.   

Now it might be that using the Git approach would solve this problem  (since Git is aware of such problems). 

So that's an example of the kind of situation that causes pause.

However, I'm game to try to get more comfy and cozy with Git.  As the approach you are suggesting is more modern than my file-copying approach.

**Comment by gasyoun** [comment]
> Now it might be that using the Git approach would solve this problem

Let Jim try.

**Comment by drdhaval2785** [comment]
> However, I'm game to try to get more comfy and cozy with Git. As the approach you are suggesting is more modern than my file-copying approach.

OK. Let us do this for one of the least used dictionary in our collection - BOP.
Let us set it up in this repository and then git pull it in Cologne servers.
We will do some small change in this repository and test whether the desired effect is achieved on Cologne server or not.
@funderburkjim what is your take ?
It will let us experiment without unhappy users.

**Comment by drdhaval2785** [comment]
Most is in open domain now. I also can venture to say that I understand a bit of what is expected bt each repo. csl-pywork repo has most scripts. Closing.
