### ISSUE TITLE
More than two broken bars in single line - ACC

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/Cologne#134]
Total 587 such cases.
This is idiosyncratic at the best.

See the following section from ACC.
```
<HI>{#aRumaDvavijaya#}¦ or {#aprameyanavamAlikA#} life of Ānandatīrtha.
<>Burnell 109^a.
<HI1><symbol n="C.">C.</symbol> Gūḍhārthaprakāśikā by Veṅkaṭabhaṭṭa. Burnell
<>109^a.
<HI>{#aRuratnamaRqana#}¦ or shorter {#ratnamaRqana,#}¦ pupil of Ratnaśe-
<>khara (died 1461):
<HI1>Jalpakalpalatā alaṃk. W. 1722.
<HI>{#aRuvAyustuti#}¦ or {#laGuvAyustuti,#} praise of Ānandatīrtha,
```

Here `{#aprameyanavamAlikA#}` and `{#laGuvAyustuti,#}` doesn't have broken bar after them, but `{#ratnamaRqana,#}` has.
Is there some significance to it @funderburkjim ?

**Comment by funderburkjim** [comment]
Good find. I had not noticed this phenomenon.

These all appear to be candidates for alternate headwords.   The presence of a second broken bar 
in some cases but not others is an inconsistency within the coding.   Once we've got the meta-form
of acc ironed out, we can go back and generate corrections to remove the 2nd broken bar.  
Then, as a separate enhancement, we can do a filter to get the alternate headword cases, and add those
to alternate headwords for ACC.

I don't think we need to do any of this before the meta-line structure adjustment is established.

**Comment by drdhaval2785** [comment]
I don't think we need to do any of this before the meta-line structure
adjustment is established.


Yes. I absolutely agree. Just noting the odd behaviour as I encounter it,
lest is be forgotten.

**Comment by gasyoun** [comment]
> as a separate enhancement, we can do a filter to get the alternate headword cases, and add those
to alternate headwords for ACC.

A dream come true. As a byproduct - what a life!

**Comment by funderburkjim** [comment]
I think this issue is now resolved - we have 1500+ alternate headwords on ACC.
