### ISSUE TITLE
ACC - removal of two trailing spaces

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/Cologne#137]
`<>yājin. Ulwar 51. Extr. 8. `
`<>bhaṭṭa. AS p. 241. `

Just for documentation.
Inversion gave these two issues.
No information loss.

These two are aberrant in that they have trailing spaces.

**Comment by funderburkjim** [comment]
Although not a big deal, obviously, there is a way to avoid such inversion differences.

Somewhere in the code (probably in meta_hw),  there is a 'line.strip()' or similar code.   

Usu. when I read the lines of a file, I do:
```
with codecs.open('filename','r','utf-8') as f:
 for line in f:
   line = line.rstrip('\r\n')
   # rest of code 
```
rstrip('\r\n') removes end of lines characters only.

By contrast, string.strip()  removes all the default whitespace characters from both ends of string.
```
string.whitespace
A string containing all characters that are considered whitespace. On most systems this includes the characters space, tab, linefeed, return, formfeed, and vertical tab.
```

So probably a string.strip()  is being used somewhere.

**Comment by drdhaval2785** [comment]
Thanks for rstrip('\r\n') tip. 
Problem resolved.
