### ISSUE TITLE
Update sanhw1.txt and sanhw2.txt for alternate headwords

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/Cologne#144]
https://github.com/sanskrit-lexicon/CORRECTIONS/issues/352#issuecomment-303934092
Mentioned the need to update sanhw1.txt and sanhw2.txt to depict the alternate headwords too.
Now L-nums have stabilized. Should not be a difficult job for @funderburkjim .

**Comment by funderburkjim** [comment]
Thanks for reminder.  sanhw1/2 regenerated

**Comment by gasyoun** [comment]
@drdhaval2785 I thought he'll never forget that and was eagerly waiting :+1:

**Comment by drdhaval2785** [comment]
@funderburkjim 
Should it not be part of regular update process to regenerate these two files?

And also I am ecstatic to see only 1555 changes in sanhw2.txt.
In older regime, I would have been killed by 200,000+ changes in sanhw2.txt.
![capture](https://cloud.githubusercontent.com/assets/5755132/26522679/3ed64c72-4323-11e7-9d46-dcbfa65fe6eb.png)

**Comment by funderburkjim** [comment]
>  Regarding lesser number of changes in sanhw1/2

I had thought this would be the case, but am delighted to see that git confirms that the system worked as
hoped.

> sanhw1/2 always part of update procedure.

It is  part of the regular steps at Cologne.  but I just overlooked it with ACC.

**Comment by gasyoun** [comment]
> It is part of the regular steps at Cologne. but I just overlooked it with ACC.

No Kaa for these pythons?
