### ISSUE TITLE
Missed out tagging - line breaks

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/Cologne#145]
See
```
<L>12<pc>1-001,1<k1>akzapAda<k2>akzapAda
{#akzapAda#}¦ or {#akzacaraRa,#} a name of Gautama, the philo-
<>sopher, Hall p. 20.
```
Ideally this should have the tagging `<ab type="pers">philosopher</ab>`.
But because of typical line breaks of acc.txt, this is missed out.

A separate exercise is needed to identify such cross line references.

**Comment by gasyoun** [comment]
> A separate exercise is needed to identify such cross line references.

Guess plenty of them.

**Comment by drdhaval2785** [comment]
Yes.
I am not sure how we want to go about it.
Maybe @funderburkjim will be the best judge.
In some dictionary (forgot which), Jim did some exercise to remove hyphens from line breaks and added `<lbinfo>` tag.
Maybe similar exercise can be taken up for all dictionaries, particularly ACC.

In current scenario, multiline correction is not available. So better to have words on single line, so that tagging, matching or any other manipulation can happen effectively.

**Comment by funderburkjim** [comment]
md is the dictionary with 'lbinfo'.   This adapted markup that Thomas invented.  

Here's an example of how to interpret the 'lbinfo' field in md.txt.

```
<L>9446<pc>122-2<k1>durlalita<k2>durlalita
{#durlalita#}¦~dur-lalita, {%a.%} spoiled, wayward; unmannerly; <lbinfo n="2"/>
<> weary of (-°); {%n.%} ill habit: {@-ka,@} 
<>{%a.%} wayward; {@-lasita,@} {%pp. id.%}; {@-lipi,@} {%f.%} fatal 
<>writing ({%inscribed by fate on the forehead%}); 
<>{@-lekha,@} {%m. id.%}; {@-lekhya,@} {%n.%} incorrectly written 
<>document.
<LEND>
```
![image](https://cloud.githubusercontent.com/assets/6393033/26524157/2fd4c15c-42f8-11e7-9062-efec70e50da8.png)

The n="2" parameter indicates that there is a line-break after `2` characters in the preceding word.

Thus, one could, if desired, reconstruct the line-break from this lbinfo data.

**Comment by gasyoun** [comment]
> md is the dictionary with 'lbinfo'. This adapted markup that Thomas invented.

Oh, thanks for the reminder.

> Thus, one could, if desired, reconstruct the line-break from this lbinfo data.

Yeah, that's the dream, the everything can be rebuilt.

**Comment by drdhaval2785** [comment]
Till we find out a way to do lbinfo type of thing for ACC, I have done some analysis and found out the cases of subject tagging which got missed out because of this phenomenon.
```
;12:philosopher
;903:vedānta
;1913:vedānta
;1914:disciple
;10627:lexicographer
;11154:brother
;19197:lexicographer
;19953:disciple
;22143:astronomer
;27820:jy
;33225:prahasana
;43649:grammarian
```

**Comment by drdhaval2785** [comment]
pywork/correctionwork/issue-cologne-142/analyze_acc4.py does the identification of missed cases for @funderburkjim's knowledge.

**Comment by gasyoun** [comment]
> pywork/correctionwork/issue-cologne-142/analyze_acc4.py does the identification of missed cases for @funderburkjim's knowledge.

There is a script, for every script, that launches a script and a script to test them all. It's like the good Old India.

**Comment by drdhaval2785** [comment]
Missed cases manually added for acc4.txt and acc5.txt.
Closing this issue.
