### ISSUE TITLE
Stage of Sanskrit Dictionary Digitalisation (1/5)

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/Cologne#15]
We are now at the first step now in 2014. In the middle of second step for MW, which is there for 18 years around as a file and full of junk text or false markup. It seems to me that we are still 20-70 years away to have a few clean Sanskrit dictionary files. And about 100 years away to get a new printed Sanskrit dictionary. Poona dictionary will be finished in 700 years, so anyway it will happen hopefully before it get's printed.
The stages are as following:
1) Draft of digital file of printed book
2) Clean errors in file, error origin - digital
3) Clean errors in file, error origin - book
4) Implement "Nachträge und Verbesserungen", now as separate articles
5) Implement "Additions" from additional sources (like Schmidt), now as separate articles.
Right now the text is faithful to the book as much as possible. But each book has hundreds of errors. To make a list of them - is a task for 5-10 years as it's done now. Jim can't do it on his own, nor can Peter or Thomas. It's time for crowd-sourcing. But for that we need to make the platform collaboration friendly and announce it. What I propose is that the real work of many involved people will start in 2015. We have 11 months to make the platform easy to understand for Indian scholars, who right now are not even aware that they can contribute. In 2015 I'm ready to tell the scholarly world what they can do to make the word a better place to live.

**Comment by drdhaval2785** [comment]
All dictionaries digitized and innumerable corrections made. Time to close.
