### ISSUE TITLE
Yates - IAST and meta-line conversions done

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#154]
This is just a notification that for the Yates dictionary, 
* AS -> IAST conversion is done.
* The structure of yat.txt now has the meta-line structure of ACC, MD.

**Comment by gasyoun** [comment]
> AS -> IAST conversion is done.

Let's make a table or list who is left? I remember a list. I guess I need lists of lists to remember where they are.

**Comment by funderburkjim** [comment]
> Table or list who is left

It is in #110

**Comment by gasyoun** [comment]
> It is in #110

Thanks, I miss dates in the table, otherwise right, a dream come true.

**Comment by drdhaval2785** [comment]
@funderburkjim 
The details of #110 are now placed as a table for better viewing in https://github.com/sanskrit-lexicon/Cologne/issues/177.
Kindly update the table there now onwards.
