### ISSUE TITLE
updateByLine enhancement for insertions and deletions

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#155]
In the course of doing the meta-line conversion of Yates dictionary, it was noticed that there was a missing headword.  This was due to a coding error.

In order to reinstate this headword,  it was necessary to insert a 'meta' line and its closing ending line into
the yat.txt file.

The updateByLine.py program in pywork directory for yat was modified to permit insertions and deletions.  SInce this same enhancement will likely be useful for other dictionaries,  a copy of the program is put into this Cologne repository in the [enhancements/code](https://github.com/sanskrit-lexicon/Cologne/tree/master/enhancements/code) directory.  Maybe some other general purpose programs can also be put in the same place.

The readme.md program displayed at the link just shown aims to provide details about program usage.

In the next comment is shown the change file transactions that accomplished the addition of the missing headword.

**Comment by funderburkjim** [comment]
### Example of chgfile for inserting a headword

This is from pywork/manualByLine03.txt for yates dictionary; the change is being made to yat2.txt, which
is the digitization with the new meta-line forms for entries.

COMMENT
```
; 05/30/2017.  Headword wrongly marked
; BEFORE
;78394 <L>22176<pc>437-a<k1>nrasTimAlin<k2>nrasTimAlin
;78395 {#nrasTimAlin#}¦ {#(lI)#} 5. {%m. Shiva.%} So
;78396 <>{#nrasTi.BUzaRaH,#} &c.
;78397 <H>{#pa#}
;78398 <H>{#pa#}¦ {%pa%} The 19th consonant, and first
;78399 <>letter of the labial class.
;78400 <LEND>
; AFTER
;78394 <L>22176<pc>437-a<k1>nrasTimAlin<k2>nrasTimAlin
;78395 {#nrasTimAlin#}¦ {#(lI)#} 5. {%m. Shiva.%} So
;78396 <>{#nrasTi.BUzaRaH,#} &c.
;78397 <LEND>   <<< insertion
;78398 <H>{#pa#}
;78399 <L>22176.1<pc>437-a<k1>pa<k2>pa   <<< insertion. Note new L number
;78400 {#pa#}¦ {%pa%} The 19th consonant, and first    <<< change
;78401 <>letter of the labial class.
;78402 <LEND>
```
THE ACTUAL CHANGE TRANSACTIONS
```
78396 old <>{#nrasTi-BUzaRaH,#} &c.
78396 ins <LEND>
78397 old <H>{#pa#}
78397 ins <L>22176.1<pc>437-a<k1>pa<k2>pa
78398 old <H>{#pa#}¦ {%pa%} The 19th consonant, and first
78398 new {#pa#}¦ {%pa%} The 19th consonant, and first
```

**Comment by drdhaval2785** [comment]
Closing. Served purpose.
