### ISSUE TITLE
AP90 - reference to another headword

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#157]
Placeholder for https://github.com/sanskrit-lexicon/cologne-stardict/issues/2
Because touches on a more theoretical part of structure of XMLs.

**Comment by funderburkjim** [comment]
The line from ap90.txt is
```
<P>.{#upekzaRaM = upekzA#}.¦
```
In this case, there is a headword upekzA (in fact the next headword):
```
<P>.{#upekzA#}¦ {@1@} Overlooking, disregard.
```
So it is appropriate to think of `= {#upekzA#}` as the content (the body) of this entry, which is just
a reference to the upekzA entry.
Thus,
I think this should be considered a coding error, and changed to
```
<P>.{#upekzaRaM#}  ¦ = {#upekzA#}.
```
A side effect is that the = would not be part of key2, and the body wouldn't be empty in the record
for upekzaRaM in ap90.xml.  

I've entered this as a correction.

In the ap90hw0.txt file, we find 28 other cases where the current coding of the raw (key2) headword contains an '='.   

Probably these require similar recoding.  To be continued in next comment.

**Comment by funderburkjim** [comment]
Corrections have been made to these 29 cases.

[Details](http://sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-cologne-157/filterdetails.txt)  from ap90.txt are shown, for both the entry with the '=' in key2 field (like upekzaRaM), and
the corresponding entry (like upekzA).

And the corresponding [change transactions](http://sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/pywork/correctionwork/issue-cologne-157/filterchange_edit.txt).

17 cases were 'just like' the upexzaRaM/upekzA example, and need no further comment.

12 cases are slightly different, in that the word after the '=' is not the spelling of another headword in 
ap90.  Of these 12, ten are like  `urIkAra = urarIkAra`, in that the headword entry is the usual
masculine form of ap90, with an extra visarga.  In this case, the change also reflects the actual
spelling of the referenced headword:
```
58526 old <P>.{#urIkAra = urarIkAra#}¦ q. v.
58526 new <P>.{#urIkAra#}¦ = {#urarIkAraH#} q. v.
```

Two cases were slightly different, and reflect print errors, as I see it.
```
66574 old <P>.{#kazA = kraSA#}¦ q. v.
66574 new <P>.{#kazA#}¦ = {#kaSA#} q. v.

84352 old <P>.{#curiH = rI#}¦ {%f.%} A small well.
84352 new <P>.{#curiH#}¦ = {#cUrI#} {%f.%} A small well.
```

In two cases, the referenced headword is not the primary headword, but is one of various spellings:
```
70207 old <P>.{#kurubaka = kurabaka#}¦ q. v.
70207 new <P>.{#kurubaka#}¦ = {#kuravaH#} q. v.

103589 old <P>.{#nAqikelaH = nArikela#}¦ q. v.
103589 new <P>.{#nAqikelaH#}¦ = {#nArikeraH#} q. v.

```

Examination of the details file (and conference with MW in kaSA case) provide support for the
change transactions.

One other point, re `70146 old <P>.{#kuraMgakaH, kuraMgamaH = kuraMga#}¦ q. v.`
kuraMgamaH  should be added as an alternate headword to kuraMgakaH.  This change has also been made.

**Comment by funderburkjim** [comment]
In all these cases, the headword (e.g. upekzaRaM) is functionally an alternate headword to the headword after the '=' sign (e.g. upekzA).   However, since Apte mentions these alternates in separate entries, we do not mention them in our list of alternate headwords.

**Comment by funderburkjim** [comment]
@drdhaval2785  -- Do these changes get rid of the stardict problem?

**Comment by drdhaval2785** [comment]
Will try and revert back late tonight.

**Comment by drdhaval2785** [comment]
The issue was resolved. Closing.
