### ISSUE TITLE
ap90 meta-line conversion

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#158]
We have (mostly) done the IAST conversion for AP90 dictionary.  (I'll explain the 'mostly' caveat later).

Now beginning the meta-line conversion.

It is complicated by the fact that there are homonyms, as well as some other quirks.

**Comment by funderburkjim** [comment]
### A tricky python point

In the program that generates the meta-line form, there is a place where we need to check for one of
various types of headword forms.  The current code lists these forms as a dictionary, with keys '1', '2', and '3':
```
  d = {'1':u'^<P>[.]{#(.*?)#}¦',  # no homonym
           '2':u'^<P>[.]{#(.*?)#}[\^]([1-9])' + u'¦', # homonym - tricky
           '3':u'^<P>[.]{#(.*?)#}(.*?)¦' # something else
          }

```
Then to find which pattern a given headword line follows we loop over the (keys) of the dictionary:
```
for pattern in d:  
  # so pattern is 1,2 or 3
  regex = d[pattern]  # this is the regex for the pattern
  if re.search(regex, line):
    # do something
```
Now in this example, the 3rd regex is a generalization of the 2nd regex --- we want to try
the 2nd regex (the more specific one) before we try the 3rd regex.

### the patterns are not ordered as expected
But the loop `for pattern in d:` actually generates the patterns in the order 1,3,2 .

This is a well-known aspect of Python dictionaries -- the keys are traversed in some order that
might differ from the order in which they are entered into the dictionary.  E.g. we entered the
pattern keys in order 1,2,3  but iteration of the keys occurs in the order 1,3,2 -  which is not what we
want.

Once the problem is understood, a solution is easy:
We recast 'd' as a list of 2-tuples

```
  d = ('1',u'^<P>[.]{#(.*?)#}¦'),  # no homonym
           ('2',u'^<P>[.]{#(.*?)#}[\^]([1-9])' + u'¦'), # homonym - tricky
           ('3',u'^<P>[.]{#(.*?)#}(.*?)¦') # something else
          ],
```
And we traverse the list with
```
for (pattern,regex) in d:
  # do whatever
```
now we get the patterns in the desired order.

**Comment by funderburkjim** [comment]
### nyAya aphorisms -- headwords?
Look at `nyAyaH` in the [list display](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/list-0.2.php?dict=ap90&input=slp1&output=roman&key=nyAyaH).

You'll see several words, starting with aṁdhacaṭakanyāyaḥ being listed as headwords.
According to the text, these are 'popular maxims' of Nyāya philosophy.

Question: Should we keep these as headwords of ap90?
Or not?

**Comment by drdhaval2785** [comment]
nyAya aphorisms should stay as headwords.

**Comment by gasyoun** [comment]
> nyAya aphorisms should stay as headwords.

Because...?

So we can have sentences as headwords, right? Not only in Apte or only in Apte, @drdhaval2785 ?

**Comment by drdhaval2785** [comment]
No.
Because they are headwords. 
aMDacawakanyAyaH is a headword by all means.
It is not sentence.

**Comment by gasyoun** [comment]
> It is not sentence.

It's a phrase :1234:

**Comment by funderburkjim** [comment]
These are probably not *normal* headwords, but rather subsections within the nyAya entry.

However, I'll keep them marked up as headwords because:
* it's technically easier to remove them as headwords in the meta-line form of the digitization that
   is under construction than it is to later add them as headwords in the meta-line form.
* And the 'more the merrier' principle of headwords.  We could later reclassify these as 'subheadwords'

**Comment by funderburkjim** [comment]
After beginning the work on meta-line conversion, I encountered significant incompleteness in the
previous IAST conversion work.  Work to improve this situation is described in #159

**Comment by gasyoun** [comment]
> We could later reclassify these as 'subheadwords'

Can we now?

**Comment by funderburkjim** [comment]
Why the rush?

**Comment by funderburkjim** [comment]
I've finished a first pass at the meta-line conversion.

Not sure whether to spend time now with some potential extra headwords
* authors from [appendix II](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=AP90&page=1191)
* places from [appendix III](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=AP90&page=1193)

These appendices are part of the ap90.txt digitization, but thus far have not contributed to the
headwords and are not part of ap90.xml.

The first appendix, on [Sanskrit Prosody](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=AP90&page=1179) , is also coded. But identification of headwords would be much harder, if possible at all.

Also, not sure whether to tackle adding 'division' markup now.

**Comment by funderburkjim** [comment]
#### headword additions
* from authors appendix  (31), example kAlidAsa (SLP1)
* from places appendix  (76) example kurukzetra (SLP1)
* from previously missed headwords (11) due to miscoding.  
  * about 20 alternate headwords identified from these

#### display markup
The ap90.txt digitization is a line-by-line digitization.
But there are conventions within the existing markup of ap90.txt that can be used to infer divisions
that make the displays easier to read, by exposing some of the structure of complex entries.

At the moment, these conventions have not been embedded as xml-markup within ap90.xml, but I
have tried to use the information in the disp.php program that governs the display.  To see the effect
of this, take a look at some complex entry (such as that for headword guru), using a display such as
the [list display](http://www.sanskrit-lexicon.uni-koeln.de/scans/AP90Scan/2014/web/webtc1/index.php).

You can contrast this to the previous line-by-line display by using the [list-0.2 display](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/list-0.2.html), which is in the line-by-line format.

#### a next step
A logical next step would be to embed some kind of `<div>` markup into ap90.xml, and to adjust
disp.php to use this div markup.  This adjustment to ap90.xml could be done 
using principles similar to those used in the experimental display. Those principles are simple:
* `<b>--X</b>`   usu. X is 
  * a number , indicating a sequence of 'senses' for a particular form.  Often, when X=1, the '--' is
    absent.
     * sometimes the bold markup is absent, e.g., there is '--2', '--3', etc.
  * a fixed word like 'Comp.'  used at  the beginning of (abbreviated) words which form
    compounds with the parent headword.
* `<s>--X</s>`   This seems to be the way the abbreviated words of compounds may be identified.
  * it seems that ap90 has prefixed verbs as separate entries

**Comment by gasyoun** [comment]
> The first appendix, on Sanskrit Prosody , is also coded. But identification of headwords would be much harder, if possible at all.

http://sanskrit.sai.uni-heidelberg.de/Chanda/HTML/ is based on it. I have scraped it, @vvasuki has  a google doc based on it.

**Comment by vvasuki** [comment]
>‌ http://sanskrit.sai.uni-heidelberg.de/Chanda/HTML/ is based on it. 

Really? http://sanskrit.sai.uni-heidelberg.de/Chanda/HTML/ had 1k + metrical definitions, Apte appendix has only a few. 

> I have scraped it, @vvasuki has  a google doc based on it.

Also as a dict - https://github.com/sanskrit-coders/stardict-sanskrit/tree/master/sa-kAvya/Chandas
