### ISSUE TITLE
Devanagari Input Issues

### ISSUE THREAD

**Issue by Shalu411** [sanskrit-lexicon/COLOGNE#16]
Namaste
http://www.sanskrit-lexicon.uni-koeln.de/scans/SKDScan/2013/web/webtc1/index.php

In this SKD page there is one option- Preferences- which gives me an option to input querry in Devanagari. But -
1. both the options i.e. Devanagari Inscript, Devanagari Qwerty have same input scheme. I tried setting my Language Toolbar with Sanskrit as well as English- (it does however have least effect, once I select the Preferences) It says Inscript but only gives Phonetic letters.
2. Once I give the input, (say- "sev" (-a dhAtu)) then before the word appears- two messages come - "Error! Request status is 0- OK" And then - "Error! Request status is 0- Prevent this page from creating additional dialogues- OK"
After I click OK, the word entry is given -but only a part of it- in the right side box. It is "se" (part of sev) and in the left there is a list- where सेरु सेल सेंलु सेव सेव etc. appear and first "सेव" is highlighted. When I select it, then whole thing comes properly. It takes extra time and effort.. though fruit that comes later is worth that.
I prefer "Preferences" search because I can input in Devanagari and it will save me strain of reading Sanskrit in Roman script.
3. When result for "सेव" ultimately shows up, the search word I entered in the box disappears. When I want to search a new word (say - div (- a dhAtu again)), I start typing in the box- but what I see is it is something like this-  "सेव्दिव्" - 
It means the previous word is coming in way of the new word being searched, from nowhere. Then I have to erase it and enter the word back.
Then- same thing, the three steps in order, happens. It is the schedule everytime I search for a word.
Now-
Que-1. I use Mozilla Firefox mostly. Is it problem because of that? I don't find chrome  good with Unicode Devanagari.
Que-2. If at all it does not recognize the queried word, how does it give that particular entry in the preferences list with highlight - in left box? (Though it helps better in the first instance, in the right box :)) 
Que-3. Why does the word previously entered not appear in the search box first and then appear suddenly when I type a new word? Its problematic because It mixes with the next one. I don't need it sticked to the new query; It comes in way. it should not. 
It is either there- then appear all the time; or not there- then should not appear along with new querry. 

Can you follow my problem? If not, let me know. I will try to explain better.

**Comment by funderburkjim** [comment]
I'm wanting to find the best way to type in Devanagari.  

The approach I'm looking at now is to use the 'Sanskrit Devanagari Inscript Keyboard' that is available in the Windows (10) OS.  

This seems to be aimed to those wanting to type Hindi in Devanagari.

There seems to be a limitation with typing Sanskrit.  Namely, there seems to be no way to
type the long vocalic r , and the long/short vocalic 'l'  (slp1 codes F,x,X).

Is this a weakness of the Inscript method, or am I just missing how to type these letters?

**Comment by gasyoun** [comment]
> Is this a weakness of the Inscript method, or am I just missing how to type these letters?

No idea.

If we could input in a pseudo-HK with ignoring the capitalness of letters - that's what we lack, not the nagari part. As per my students at least for sure.

**Comment by drdhaval2785** [comment]
On windows - I prefer PramukhIME
On linux - ibus

**Comment by gasyoun** [comment]
> On linux - ibus

We might want to document as a possible solution on the site?

**Comment by funderburkjim** [comment]
How can a user conveniently input IAST?

Also agree there should be some site-wide documentation  on such questions.   Maybe a link on home page?

**Comment by drdhaval2785** [comment]
1. https://itsfoss.com/type-indian-languages-ubuntu/ (there are similar packages for almost all linux distros) 
2. select sanskrit-IAST as language. 

Works fine for me.

**Comment by funderburkjim** [comment]
Does this work on Windows 10 computer?  Looks like a linux solution (ubuntu).

**Comment by gasyoun** [comment]
> Looks like a linux solution (ubuntu).

It is. For Windows I used KeySwap tray tool and can document it as well in English 
https://vk.com/sanskritskype?w=wall-89658969_3060, adore it's ease really much.

**Comment by funderburkjim** [comment]
Thanks for link --  Will give it a try on Windows 10 as IAST input assistant.

**Comment by funderburkjim** [comment]
> Don't see how to download sanskritskype from vk.com

**Comment by gasyoun** [comment]
@funderburkjim see https://www.yesvedanta.com/keyswap-sanskrit-diacritics-transliteration-typing-tool/

**Comment by funderburkjim** [comment]
Am able to use this.  Hope it is safe.

Note that the site dictionary is beautifully done.  Wish they would fill in the 'credit'  to acknowledge usage of
 Cologne digitizations.

**Comment by gasyoun** [comment]
> Am able to use this. Hope it is safe.

Perfect, so am I. And I have the source code if we want to change something.

> Wish they would fill in the 'credit' to acknowledge usage of Cologne digitizations.

Oh, that I can ask for.

**Comment by funderburkjim** [comment]
>   I have the source code

Maybe they should open source the keymap program, such as on GitHub.

**Comment by gasyoun** [comment]
> Maybe they should open source the keymap program, such as on GitHub.

Hmm, not sure. It has some minor bugs, but I adore it.

**Comment by Andhrabharati** [comment]
> Am able to use this. Hope it is safe.
> 
> Note that the site dictionary is beautifully done. Wish they would fill in the 'credit' to acknowledge usage of
> Cologne digitizations.

It is not the site's dictionary, but it is their favourite dictionary-- its our (AB)  dictionary page.

We have quite many favourite users!!
