### ISSUE TITLE
meta-line conversion of MD

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#161]
In March 2017, the first part of the meta-line conversion of MD was completed, shortly after the IAST conversion.

The rest of the meta-line conversion has now been completed.   The work was done on the dev server,
and has also been installed at Cologne.

The additional steps taken include these changes:
*  removal of `<e>` element needed for checking invertibility of meta-line form of md.txt
*  reposition of `<LEND>` so that `<H>` and `[Pagexxx]` elements at end of entry not included in entry
*  correction of some italic-within-bold markup awkwardnesses (about 200 of these)
*  change IAST anusvara from former  ṁ to ṃ   (the dot-below is the standard IAST Sanskrit symbol).
*  Change the few Greek text elements from adhoc Latin letter coding to Unicode.
* Change markup from `<g>X</g>` to `<lang n="greek">X</lang>`

and these xml choices:
* Change from double dagger ‡ to underscore _ for vowels that are shown in pre-sandhi form
  such as vi_ava   as a verb prefix (when final sandhi form will be vyava).  
* Removal of ¤  (Currency sign) -- this is used around some numbers - but the usage seems to be
   non-useful.  
* preserve line-breaks of md.txt in md.xml as `<lb/>`.  As mentioned in #160, we should revisit this
  choice when time and inclination permit a more thorough examination of 'div' markup in md.

We may want to push the first two changes down to md.txt at some time.

Otherwise, the xml conversion is vanilla.

**Comment by gasyoun** [comment]
> xml conversion is vanilla

Wah, so much trouble. Hope because it's the first of it's kind, hurray!
