### ISSUE TITLE
meta-line conversion of AP

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#162]
The meta-line conversion of AP now completed.
Will make a few observations tomorrow.

**Comment by funderburkjim** [comment]
#### correction to standard IAST anusvara

For some unknown reason, in the previous work to convert to standard IAST, the anusvara was represented as m-over-dot, rather than the standard m-under-dot.   Now m-under-dot is used.

#### false homonyms removed
The ap.txt digitization split  the entries of some words into multiple parts.  Only a few words are involved:  eka, nir, mahA, and su.  In these, the 'false' headwords (and associated false homonym markup) were removed.   Thanks to the meta-line conversion, this removal of false headwords causes no change to the L-numbers of other headwords.   A explanation of the case of 'eka' will clarify this change.
'eka' has many 'sub-headwords'.   Here is relevant printed text 👍 
![image](https://user-images.githubusercontent.com/6393033/28138302-4c288e84-671e-11e7-87c1-730ba5f28d93.png)
The corresponding part of digitization prior to the correction:
```
<LEND>
<L>10632<pc>0493-c1<k1>eka<k2>eka<h>a
{#eka#}a¦ {%pron. a.%} [{#i-kan#}]
.....  [many lines omitted]
.{@{#-codana#}@} {%a.%} Resting upon one rule. ({@{#-nam#}@}) referring
 to in the singular number.
.{@{#-cCatra#}@} {%a.%} Ruled by one king solely.

<L>10633<pc>0495-2<k1>eka<k2>eka<h>b
{#eka#}b¦
.{@{#-cCAyASrita#}@} {%a.%} Involved in similarity (of debt) with one debtor
 (said of a surety); Y. 2. 56.
.{@{#-ja#}@} {%a.%}
[MANY MORE LINES]
```
After correction  (the L=10633 headword removal is the main point):
```
<L>10632<pc>0493-c1<k1>eka<k2>eka
{#eka#}¦ {%pron. a.%} [{#i-kan#}]
.....
.{@{#-codana#}@} {%a.%} Resting upon one rule. ({@{#-nam#}@}) referring
 to in the singular number.
.{@{#-cCatra#}@} {%a.%} Ruled by one king solely.
.{@{#-cCAyASrita#}@} {%a.%} Involved in similarity (of debt) with one debtor
 (said of a surety); Y. 2. 56.
.{@{#-ja#}@} {%a.%}
```

**Comment by funderburkjim** [comment]
### current div markup in ap.txt 
Thomas' digitization of ap.txt separates entries into sections.  These are identified in the meta-line form
of the digitization as lines beginning with a period.
* `.²1`  number section
* `.³({%a%})`  letter section.  This typically occurs 'within' a number section
*  `.{@{#-ja#}@}`  sub-headword section.

The markup of ap.xml converts these into analogous xml 'div' elements
*  `<div n="1" name="[number]">...</div>`
*  `<div n="2" name="[letter]">...</div>`
*  `<div n="?">...</div>`  A 'question-mark' is used since the structure of ap.txt after the initial period
    (e.g. `{@{#-ja#}@}`) has not been examined further.

One other isolated instance is converted to a `<div>`, the section marked in ap.txt as `<Poem>` under headword akzOhiRI:
```
<L>183<pc>0011-1<k1>akzOhiRI<k2>akzOhiRI
{#akzOhiRI#}¦ [{#UhaH samUhaH saMvikalpajYAnaM vA so'syAmasti ini, akzARAM#}
 {#raTAnAM sarvezAmindriyARAM vA UhinI; RatvaM vfdDiSca#} P. VI 1. 89 Vārt.]
 A large army consisting of 21870 chariots, as many elephants, 65610 horse,
 and 109350 foot. {#akzOhiRI = 10 anIkinyaH#}.{# anIkrinI = 3 camvaH#}.
 {#camUH = 3 pftanAH#}.{# pftanA = 3 vAhinyaH#}.{# vAhinI = 3 gaRAH#}.{# #}
{#gaRa = 3 gulmAH#}.{# gulmaH = 3 senAmuKAni#}.{# senAmuKam = 3 pattayaH#}.
 {#pattiH = 1 raTaH + 1 hastI + 3 aSvAH + 5 padAtayaH#}.
<Poem>cf. {#ekeBEkaraTA tryaSvA pattiH paYcapadAtikA . pattyaNgEstriguREH#}
 {#sarvEH kramAdAKyA yaTottaram .. senAmuKaM gulmagaRO vAhinI pftanA camUH#}
 {#. anIkinI daSAnIkinyakzOhiRI #}......{# ..#}</Poem>
<LEND>
```
This is changed to `<div n="Poem"> ... </div>`.

**Comment by funderburkjim** [comment]
#### further work on `<div>`
The division markup just described is probably a good start to a more complete markup for ap.xml.
There are some places where additional markup is needed in order to more adequately reflect the semantic structure of some entries.
* Under headword 'a':
   ```
   {#a#}¦ The first letter of the alphabet; {#akzarARAmakAro'smi#}  Bg. 10. 33.
   .{@{#-aH#}@} [{#avati, atati sAtatyena tizWatIti vA; av--at vA, qa#} Tv.]
   .²1 N. of Viṣṇu, the first of the three sounds constituting the sacred
    ...
    .²2 N. of Śiva, Brahmā, Vāyu, or Vaiśvānara. 
     ...
     efficacious mantra, reins, the horse of a chariot, a wheel, the head of
    a cock, the disc of the moon]; {%ind.%}    <<<<need break here. 
   .²1 A prefix corresponding to Latin {%in,%} Eng. {%in%} or {%un,%} Gr. 
   ```
   There needs to be a break for the indeclinable forms
* Under many root headwords, there need to be breaks for Causal, Desiderative, and other secondary
  verb forms.  Look at the display for 'gam', and notice that the last 8 numbered forms pertain to
  the causal forms gamayati, -te.

**Comment by funderburkjim** [comment]
### special character ‡ DOUBLE DAGGER
This character is used within ap.txt within Devanagari text to indicate a line-break of the printed text. 
This usage occurs 7000+ times.
For example, under headword aMSin
```
{#aMSin#}¦ {%m.%} [{#aMSa-ini#}]
.²1 A sharer, co-parcener; ({#punarviBAga‡karaRe#}) {#sarve vA syuH samAMSinaH#}
 Y. 2. 114 (entitled to the same share.)
```
![image](https://user-images.githubusercontent.com/6393033/28140073-cca5384a-6724-11e7-8563-101c3598476d.png)

In ap.xml, we are currently changing this to the simple '-'.  However, in almost all examples (such as the one just shown),  the digital display probably should just omit the '-'.

Note the usage of this character is different in md.txt, where it indicates a pre-sandhi form of touching vowels in IAST representation of Sanskrit, e.g. `{#aMSukAnta#}¦aṃśuka‡anta`.

**Comment by funderburkjim** [comment]
### special character € EURO SIGN
This character is used in roots before the class-pada information.  It occurs 3000+ times.
```
{#aMS#}¦ €10U. {#aMSayati-te#} also {#aMSApayati#} To divide, distribute, share among.
```
![image](https://user-images.githubusercontent.com/6393033/28140797-cbdaddfe-6727-11e7-9791-d50e324bc381.png)

In ap.xml, we currently convert this symbol into an empty `<root/>` tag:
```
<H1><h><key1>aMS</key1><key2>aMS</key2></h><body>
  <s>aMS</s>  <root/>10U. <s>aMSayati-te</s> also <s>aMSApayati</s> To divide, distribute, share
 among.</body><tail><L>3</L><pc>0001-2</pc></tail></H1>
```
The display ignores this tag.

**Comment by funderburkjim** [comment]
Perhaps these observations will be of use for further markup work on this dictionary.

**Comment by gasyoun** [comment]
> entries of some words into multiple parts. Only a few words are involved: eka, nir, mahA, and su

They have in common that they are HUGE.
