### ISSUE TITLE
BUR IAST, corrections

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#164]
In processing a user correction to Burnouf, I discovered at least one systematic error in the IAST conversion described in #105 .

### Error with `ś` in French words instead of `ç`
Under headword nAman, we see `reśoivent` instead of the correct `reçoivent`
```
<P>{%nāmarūpa%} n. Bd. le nom et la forme [des objets sensibles]; la
forme en raison de laquelle <lbinfo n="6"/> ils <<<reśoivent>>> un nom; la forme idéale; 
```
A check shows 52 matches for `reś`, almost all of which are part of French words which should be
spelled `reç`.
This mistake should be correctable fairly readily.

### Error: use of circumflex instead of macron for long vowels.
This is quite confusing to disentagle, since circumflex is used in French words (example relâche).
But in Sanskrit words, the modern IAST convention of macron should be employed: Brahmâ should be, in modern IAST, Brahmā .  Note that BUR printed text uses the circumflex in Sanskrit words as well as French.
There are 2600+ instances of â  in the digitization, so moving to modern IAST convention for Sanskrit words will be challenging.  Probably worth doing, nonetheless.

**Comment by gasyoun** [comment]
> systematic error in the IAST conversion 

Yeah, that's where converting becomes fun, know it sooo well.

> There are 2600+ instances of â in the digitization, so moving to modern IAST convention for Sanskrit words will be challenging. Probably worth doing, nonetheless.

Let the French do that. There are people who submit corrections to the French part, right? You are not alone. Propose and see what they will answer. If they do not want to, why should you? Too many such details for too many dictionaries, Jim.

**Comment by funderburkjim** [comment]
####  ś in French words instead of ç, corrected
About 170 such corrected.  The approach used was to identify definitely French words, where  `ś` would
be an error, and to change these to the correct French spelling with `ç`.

These chiefly occur in the informal (non-italic) IAST of BUrnouf.   In some cases of non-italic Sanskrit
the spelling of the text uses ç. For instance, under headword (slp1) `aSvatTa`, we see  in the print
the spelling `açwattha` in both italicized and non-italicized text.  The spelling is changed to `aśvattha` in both the italicized and non-italicized instances.

####  ń -> ṃ  corrections
While examining the above, noted that in italicized IAST there were many n-acute characters.  This is
not a standard IAST coding.  It is used by Burnouf, and the prior AS-IAST conversion work did not 
properly convert.   There are 750+ such instances, and all but a handful (25+) ń instances precede a
sibilant `ś , ṣ, s` or `h`;  all these cases changed to IAST anusvara `ṃ`.

The other handful were mostly preceding palatal consonants, and  were changed to the palatal nasal `ñ`.

#### w -> v  in some informal IAST
In non-italic text, Burnouf presents informal IAST spellings of Sanskrit words, chiefly proper names.
I noticed several cases of 'w' in place of 'v'.   *Some* of these non-italic spellings of Sanskrit words were changed.   However, somewhere along the way I noticed the functional difference between italicized Sanskrit, which is systematic and was changed to modern IAST,  and non-italic Sanskrit, which is less systematic.  And decided not to pursue a thorough *modernization* of the non-italic Sanskrit.   
For instance , under headword ASvayuja, one still sees the spelling `le mois âświna, septembre-octobre.`

**Comment by gasyoun** [comment]
> And decided not to pursue a thorough modernization of the non-italic Sanskrit.

Agree.
