### ISSUE TITLE
Kyoto-Harvard -> Harvard-Kyoto

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/Cologne#165]
Did I mention it before? There is no Kyoto-Harvard, @funderburkjim, but only Harvard-Kyoto :v: 

![kh](https://user-images.githubusercontent.com/80761/28241184-34222e4a-6998-11e7-8114-c12ae8627ea6.PNG)

**Comment by funderburkjim** [comment]
The Kyoto-Harvard terminology was introduced in the Cologne displays due to Peter's strong preference for this term (over Harvard-Kyoto).

**Comment by gasyoun** [comment]
> due to Peter's strong preference for this term (over Harvard-Kyoto).

I have a strong preference for disagreeing, but I'm not ready to start a long discussion with Peter.
In his `Linguistic Issues in Encoding Sanskrit` there are no arguments for a change (and not even an Harvard-Kyoto entry in Index). Either he changes https://en.wikipedia.org/wiki/Harvard-Kyoto to https://en.wikipedia.org/wiki/Kyoto-Harvard or we change it on Cologne. 
Both Peter and Wiki refers to Wujastyk (http://indology.info/email/members/wujastyk/#x1-120005.2 - one of the grandfathers on Indology on the net), but he can't have two opinions and I could ask his on this matter. I adore Peter's huge knowledge, passion and without his efforts, we would lack so many dictionaries at Cologne. But inventing a new term, without even documenting and argumenting, I'm against. @drdhaval2785 what's your take? And the issue is not me - I can call it Hanuman. It's that people, who do not know how to use Cologne and come for the first time, they have enough to learn, but no need to know for them that Kyoto stands above Harvard in Peter's understanding of historical importance. It indeed does, but it's easier to pronounce and it's a tradition: Harvard-Kyoto.

**Comment by gasyoun** [comment]
![kh](https://user-images.githubusercontent.com/80761/37789575-55a4f236-2e15-11e8-8215-83674d530142.PNG)

@funderburkjim let us have 1, not 2 at once http://sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/simple-search/v1.0/list-0.2s.html

**Comment by funderburkjim** [comment]
> let us have 1, not 2 at once

Both now show 'HK'.  OK?

**Comment by drdhaval2785** [comment]
Time to celebrate

**Comment by gasyoun** [comment]
> OK?

Can we have simple chosen by default?

**Comment by funderburkjim** [comment]
'simple' is already the default.
```
  <option value='simple' selected='selected'>simple</option>
```
So no change required.

Cookies are used to remember previous choice. So if you use HK for a session, then the next session
will start with HK.   Or if you use 'simple' for a session, then the next session will also be 'simple'.
