### ISSUE TITLE
BUR meta-line conversion

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#166]
Now that IAST conversion for BUR (Burnouf Sanskrit-French Dictionary) is mostly done, it is time to
convert the format of the bur.txt digitization to the more standardized format which we have been calling  'meta line'.    This issue devoted to this conversion.

**Comment by gasyoun** [comment]
Jim, is it worth? If so, so be it, but it's weeks of converting and it might need to change in a year or so when we realize we missed something important.

**Comment by funderburkjim** [comment]
@gasyoun   It's my judgment that it is worth it.   The AS coding used in original digitization is an obstacle
to anyone who wishes to do further work with the dictionaries.   It needs to be replaced by unicode.
Similarly, the irregularities of the digitizations involved in headword identification and L-number stability need to be smoothed out, so we don't have to keep relearning separate systems over and over again -- that's the reason for the meta-line conversion.

If I don't do this,  it likely would never get done;  and this would make the future handover of the project
to Dhaval or whoever more difficult on that person than it needs to be.

I'm continuing to do work on tasks with more immediate payback -- like the simple search -- as you've seen.  And value your inputs on what should be included as priorities in these tasks.

**Comment by gasyoun** [comment]
> If I don't do this, it likely would never get done; and this would make the future handover of the project
to Dhaval or whoever more difficult on that person than it needs to be.

Yes, agree. But finish all of these months and months will be required.

> I'm continuing to do work on tasks with more immediate payback -- like the simple search -- as you've seen. And value your inputs on what should be included as priorities in these tasks.

Yes, I see it. Being mostly selfish, I'm dreaming about issues like https://github.com/sanskrit-lexicon/alternateheadwords/issues/20 - all the possible ways to increase the number of headwords. And the last missing brick is the sopasarga dhatus that are still deep inside the articles. Rereading https://github.com/sanskrit-lexicon/CORRECTIONS/issues/181#issuecomment-299332371

**Comment by funderburkjim** [comment]
### Meta-line conversion of BUR completed.

Observations for later work
#### sub-headwords are easily identifiable in BUR. 
```
<L>11<pc>005,2<k1>akara<k2>akara
{#akara#}¦ {%akara%} a. {%(kara)%} sans main, manchot. <lbinfo n="5"/> || Inactif
{%(kṛ).%}

<P>{%akaraṇi%} m. état de manchot, t. d'imprécation. <lbinfo n="7"/>
<LEND>
```
The subheadword here is `akaraṇi`, in IAST.  Only need to convert to SLP1.  Note no need to
complete abbreviated words, as the subheadword is spelled out in full.

#### Use of '||'  and `—` (mdash) to indicate different senses
   The xml version has changed these to `<div>`.   
   The mdash separates grammatical variants  (adjective, masculine-feminine-neuter).

####  Greek
There are about 700 instances of Greek text.  These are uncoded. Identifiable by
`<lang n="greek"></lang>`  markup in bur.txt.

#### Three levels of spelling of Sanskrit
Headwords are spelled with Devanagari.   Within entries,  Sanskrit words appear in two spellings.
*  Italics - IAST    This is now standardized to modern IAST
* non-italics -- Informal spelling, presumably for the purpose of pronunciation by French language speakers.   No attempt has been made to alter or in any way *standardize* these spellings.  Mostly this informal spelling occurs with proper names.
Some examples:
   * `<P>{%indrāvaraja%} m. {%(avaraja)%} ép. de Vishnu.`
   * `{#uccadeva#}¦ {%uccadeva%} m. surnom de Krishna.`
   * `{#kuSIvaSa#}¦ {%kuśīvaśa%} m. surnom de Vâlmîki`
   * `<P>{%kaiṭabhajit%} m. {%(ji)%} Vishnu, vainqueur de Kaetabha.`

**Comment by gasyoun** [comment]
> The subheadword here is akaraṇi, in IAST. Only need to convert to SLP1. Note no need to
complete abbreviated words, as the subheadword is spelled out in full.

Good news.

> There are about 700 instances of Greek text. These are uncoded. Identifiable by
lang n="greek" markup in bur.txt.

Let's grab 'em out?

> IAST This is now standardized to modern IAST

Changes documented? I mean list of correspondences.

**Comment by funderburkjim** [comment]
> Changes documented? I mean list of correspondences.

Probably not as well documented as you might hope.  Primary reasons:
* The starting point is AS (letter-number) coding of letters with diacritics.
* Typically, an AS code (say n4) represents some Burnouf letter-with-diacritic (e.g. `ń`).
* But ń is not modern IAST, but usually represents modern anusvara (`ṃ`).
* In Burnouf, there are also diacritics in non-Sanskrit text (e.g. French `ô`, etc.). 
* The conversion from AS to IAST in Burnouf has been done in more than one step, in 
   version bur03.txt of 2015, and the current 2017 work.

So the 'list of correspondences' is difficult to even define.  

Probably the best way to get at the correspondece is to compare two listings of the
Sanskrit alphabet:
*  Burnouf's [Tableau de Transcription](http://www.sanskrit-lexicon.uni-koeln.de/scans/csldoc/dictionaries/prefaces/burpref/burpref06.html)
* Wikipedia's  [IAST Sanskrit](https://en.wikipedia.org/wiki/International_Alphabet_of_Sanskrit_Transliteration)

We start with an AS coding of Burnouf's Tableau.  We end with a Unicode coding of IAST Sanskrit.

**Comment by funderburkjim** [comment]
### A comparison of digitizations
Here is the first (original) form of one entry in Burnouf:   HK + AS
```
.{#chagala#}¦ {%c13agala%} m. {%(c13aga)%} bouc. -- F. {%c13a|gala10%}
et {%c13agali10%} che11vre. ;; Esp. de convolvu|lus. -- N. e4toffe ou
ve10tement bleu.
```
Here is the current form of that entry (SLP1 and modern IAST):
```
{#Cagala#}¦ {%chagala%} m. {%(chaga)%} bouc. -- F. {%chagalā%} <lbinfo n="6"/>
et {%chagalī%} chèvre. || Esp. de convolvulus. <lbinfo n="4"/> -- N. étoffe ou
vêtement bleu.
```

**Comment by gasyoun** [comment]
> Probably not as well documented as you might hope.

I'm not a maniac. All I mean is a table of a summary. 
Was ń, became ṃ. So I can add such valuable info as to what people will actually see in the scan, so they do not submit it as a mistake at least.

**Comment by funderburkjim** [comment]
> add such valuable info as to what people will actually see in the scan,

Using the two documents  mentioned above (Burnouf Tableau and Wikipedia IAST table),  one could 
make a useful html document showing the correspondence between Burnouf's IAST system and the
modern IAST.   This could be done by copy-pasting small snips of images.   

If you decide to do this, we can link to the resulting html (combined burnouf-modern IAST table)  from some point within the Burnouf web pages.

**Comment by gasyoun** [comment]
> If you decide to do this, we can link to the resulting html (combined burnouf-modern IAST table) from some point within the Burnouf web pages.

Ok.
