### ISSUE TITLE
PDF scan pages problem in Android Chrome

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#168]
This problem has been noticed by several users.  I'm hoping that by posting it here, in a stripped down form, that someone may come up with a clue towards solution.

### Statement of problem
[This link](http://funderburkjim.github.io/servepdf/01/index.html) works properly in a desktop Chrome browser:  The browser renders a pdf page.

However, when this same link is accessed in the Chrome browser under Android, we get 'This plugin is not supported'.    Incidentally, I don't find a 'Developer Tools' option in the Android Chrome, so I can see no way to determine exactly what plugin *This plugin*  is referring to.

**Comment by funderburkjim** [comment]
### The code for index.html above
Here is the index.html file of the above link:
```
<html>
<head>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=utf-8">
<title> MW Cologne Scan</title>
<link rel='stylesheet' type='text/css' href=serveimg.css' />
</head>
<object id='servepdf' type='application/pdf' data='sample.pdf' style='width: 98%; height:98%'></object>
<!--
<div id='pagenav'>
<a href="prev.pdf" 
   class='nppage'><span class='nppage1'>&lt;</span>&nbsp;</a>
<a href="next.pdf" 
   class='nppage'><span class='nppage1'>&gt;</span>&nbsp;</a>
</div>
-->
</body>
</html>
```
Actually, the stylesheet is not needed either, and I've commented out the `< and >` controls used at
cologne.

So the question may boil down to whether there is a modern replacement for the `object` tag, that will
work in both Android and Desktop Chrome.

**Comment by funderburkjim** [comment]
### use of 'a href="sample.pdf"`

There is some progress when the `object` tag above is replaced by an anchor `a` tag:
```
<a id='servepdf' href='sample.pdf' style='width: 98%; height:98%'>sample.pdf</a>
```
See [indexaref.html](http://funderburkjim.github.io/servepdf/01/indexaref.html).

When the link is clicked in Android browser, then
* the pdf file is downloaded
* it is autoloaded into some viewer.

This is partial progress toward the goal.

**Comment by funderburkjim** [comment]
### A possible solution

The [Development version for MW](http://198.199.88.166/cologne/mw/web/webtc/indexcaller.php) implements one solution for viewing the pdfs of the scan pages in Android.
I've found it to be acceptable using Chrome browser on android.

The (simple) technique is described in this [stackoverflow article](https://stackoverflow.com/questions/18564774/how-to-support-pdf-viewing-for-all-mobile-browser?rq=1) ;  first solution.  The idea is to put a normal  link within the object tag
`<object ...><a href="PDF">click to load pdf</a></object>` 

Incidentally, the code change does not interfere with the desktop browser experience; it seems that
a desktop browser, which knows how to handle the `<object>` tag, simply ignores the `<a>` tag.

#### Comments requested
Will other android users give this a try, and share their opinion on whether this seems satisfactory?

If so, various apps on Cologne can be migrated to use this code.

**Comment by gasyoun** [comment]
> Will other android users give this a try, and share their opinion on whether this seems satisfactory?

Let me ask my students, well done.

**Comment by funderburkjim** [comment]
@gasyoun   Did you get any feedback on this ?

**Comment by gasyoun** [comment]
Yes, asked two - they do not see the bug.

**Comment by funderburkjim** [comment]
servepdf now rewritten, and the above code for android devices included. See https://github.com/sanskrit-lexicon/csl-websanlexicon/issues/6.

**Comment by funderburkjim** [comment]
##  Also Linux MInt/Firefox solution

A user had reported several months ago a similar problem of not seeing pdf scanned images on 
his Linux laptop.
He recently reported that the problem is solved and makes use of the 'click to load pdf' link put.

## User's comment

I see there's a new "load PDF" link, and that fetches the scanned page just fine.  Thanks!
Just clicking on the page number in the dictionary entry display still brings up an almost blank screen:
![image](https://user-images.githubusercontent.com/6393033/65711586-3362ae00-e063-11e9-95f4-399bb386428c.png)

I'm using Linux Mint Cinnamon 19.2, and Firefox 69 with almost no add-ons (a Facebook container).

## Elementary Linux with Chrome
I have this on one laptop.  It behaves like Windows 10 desktop with Chrome, in that the pdf is rendered by the browser directly, with no intermediate 'Click to load pdf' link.
