### ISSUE TITLE
Dictionary selection in list-0.2.html

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#169]
### Previous version non-intuitive
This pertains to the [list-0.2.html display](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/list-0.2.html) . 

User E.H. describes confusion on how to change dictionaries:
```
The ‘dictionary’ input box has no drop down icon, unlike the other three menu items.
 
I have discovered by chance, that a user has to ‘edit’ that default ‘MW’ text  to bring up 
that dropdown with its big listings.
e.g. clear the ‘MW’, move the cursor hard left.
 
This is necessary, to obtain a utf-8 entry for ādhi in VCP from the initial display.
 
And again, no info. given about having to right click a mouse button to access the
 copy pop up list.
 ```

In response, I modified this JQUERY UI autocomplete widget to be like in [list-0.2s.html](http://sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/simple-search/v1.0/list-0.2s.html) used in the simple display currently under development.

Based on his response, I think this helped. But EH brought up some other interesting suggestions, also:
```
  Thanks Jim.
 
    You move the goal posts without telling us!
 
How about a pop-up message when there is a mouse-over those menu items, or a message 
to the status bar as happens when the pointer moves over Koeln icon.
 
The autocomplete feature seems to search the extended dictionary names rather than just the 
abbreviated name. 
If I start typing di...  the list finds everything listing with the word dictionary in it.
 
 
And here’s another one for you, from the list-0.2.html: 
 
I enter aadhi into the citation box when using the MW dictionary, with IAST as the input mode
and get Internal error in basicDisplay for MW, aaDi?? in response.
 
Anyway, should I be using the GitHub forum for these things?
 ```

I'll discuss these other suggestions in further comments (And have invited EH to join the discussion here at GitHub).

**Comment by funderburkjim** [comment]
> How about a pop-up message when there is a mouse-over those menu items ?

When mouse hovers above word 'Dictionary' (or the dictionary input field below that word), what
should a tool-tip say?  
Example: `Select new dictionary, or enter dictionary code`  ?

**Comment by funderburkjim** [comment]
@gasyoun   You mentioned writing a 'faq' or 'help' or 'intro' for list-0.2s.html.  Still going to do this?

**Comment by funderburkjim** [comment]
### aadhi error
The problem is that this is not an IAST spelling of any headword in the dictionary. 

Proposed solution: Change the error message to a less ominous form:

`Could not find headword aadhi in dictionary MW`

**Comment by funderburkjim** [comment]
### the 'di' problem with dictionary autocomplete 

Currently the autocomplete does a simple character match within each of the suggestion fields.  
So with 'di', any entry with the characters 'di' is kept -- only those fields with no 'di' are excluded.

It *might* be better if the matching was done *only on the dictionary codes* that are embedded in each field.   
* Would this be better, more intuitive behavior?  What do others think?

If this would be better, the technical question remains of 
it is possible to do this within JQuery UI autocomplete widget .

**Comment by Taff-Rivers** [comment]
Jim,

Re. aadhi error

"That's what is done. OK?"*

No Jim, 
The 'aadhi' was a mistake on behalf as the a user (myself) , therefore words the effect  **the 'aa' is not part of the IAST character set - have you checked your spelling.** with its emphasis on spelling, rather than the  emphasis on absence (of 'ādhi)' in the dictionary.

Best,
Taff,

------------------

*The problem is that this is not an IAST spelling of any headword in the dictionary.
Proposed solution: Change the error message to a less ominous form:

Could not find headword aadhi in dictionary MW

That's what is done. OK?

**Comment by Taff-Rivers** [comment]
Jim,

Re. the 'di' problem with dictionary autocomplete*

The list of dictionaries is quite a short one. Personally, I think the wizard should be confined to the citation field, where it is ideally suited. And a drop down icon in dictionary Menu box.

best,
  Taff

----------

*Currently the autocomplete does a simple character match within each of the suggestion fields.
So with 'di', any entry with the characters 'di' is kept -- only those fields with no 'di' are excluded.

It might be better if the matching was done only on the dictionary codes that are embedded in each field.

    Would this be better, more intuitive behavior? What do others think?

**Comment by funderburkjim** [comment]
Taff -  Are you aware that the dictionary field can function like standard drop-down menu?   You don't
have to type anything.  You can just use arrow keys or mouse to scroll through the list, and then do
a mouse click when the highlighted dictionary is at the place you want.

On the other hand, if you know the dictionary abbreviations, you can just type in the abbreviation.

**Comment by funderburkjim** [comment]
> the 'aa' is not part of the IAST character set - have you checked your spelling

That's an interesting idea. Currently the program does not do any validity check between 
* the characters that the user types in the citation 
* and the character set that is implied by the choice of 'input'.

In fact, this would be a difficult comparison.   In the 'aadhi' example, each character, by itself
(namely, 'a', 'a', 'd', 'h', 'i') is a legitimate character in the [IAST Sanskrit](ref: https://en.wikipedia.org/wiki/International_Alphabet_of_Sanskrit_Transliteration) character set.

The problem is that the 2-gram 'aa'  is probably never seen in an IAST spelling of a Sanskrit word.

You might like to try the 'simple' input option of the [list-0.2s.html](http://sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/simple-search/v1.0/list-0.2s.html) display we've been experimenting with.
And try 'aadhi' there.

**Comment by gasyoun** [comment]
> Could not find headword aadhi in dictionary MW

make

> Could not find headword aadhi in dictionary MW in IAST encoding.

**Comment by Taff-Rivers** [comment]
**You might like to try the 'simple' input option of the list-0.2s.html display we've been experimenting with.
And try 'aadhi' there.**

Jim,  sounds interesting. But what is this mysterious experimental option. How do we access it.

Taff,

   Think that if there was a user manual you would have the luxury to tell us to RTFM (-:)

**Comment by gasyoun** [comment]
> Think that if there was a user manual

Write it. Because I know too much - spoiled. One needs to be clean. @Shalu411 wanted, but failed. See https://docs.google.com/document/d/1FJgJkv6ltjT7OC1m0Fk0xvxZZ0nVxXBEPx_-TTXRYYM/edit#heading=h.uao9dywp6gla

**Comment by funderburkjim** [comment]
> But what is this mysterious experimental option. How do we access it?

If you click on the link above for list-0.2s.html,  you'll get access.

When we feel it is ready for general usage, we'll put a link on the Cologne home page.

Documentation is always a struggle.   A lot of attention is given to making the displays more or less
self-explanatory.  If you think some written 'manual' is needed, maybe you can do some work along
those lines -- perhaps many people would find it helpful.

**Comment by gasyoun** [comment]
> When we feel it is ready for general usage, we'll put a link on the Cologne home page.

I feel it's about time.

> If you think some written 'manual' is needed, maybe you can do some work along
those lines -- perhaps many people would find it helpful.

Exactly, @Taff-Rivers

**Comment by Taff-Rivers** [comment]
**If you click on the link above for list-0.2s.html, you'll get access.**

There is no 'list-0.2s.html'!

Taff Rivers,

I love the smell of bytes in the morning.

**Comment by Taff-Rivers** [comment]
Я тебя не понимаю!

**The problem is that the 2-gram 'aa' is probably never seen in an IAST spelling of a Sanskrit word.**

**Write it. Because I know too much - spoiled. One needs to be clean. @Shalu411 wanted but failed.**

Please, this 'English' is very bad, Я тебя не понимаю/Ich verstehen sie nicht.

And why are you signing off with my Name? Viz:  '@Taff-Rivers'

Taff Rivers

**Comment by gasyoun** [comment]
> And why are you signing off with my Name?

So you see a notification.

> Please, this 'English' is very bad, Я тебя не понимаю/Ich verstehen sie nicht.

I wanted to say - write it yourself. We will publish it. Ready to do so?

**Comment by drdhaval2785** [comment]
Dictionaries are there in the dropdown at 
https://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/list-0.2.html
