### ISSUE TITLE
Split Output on Large Search Queries

### ISSUE THREAD

**Issue by Shalu411** [sanskrit-lexicon/COLOGNE#17]
Namaste
http://www.sanskrit-lexicon.uni-koeln.de/scans/PWGScan/2013/web/webtc2/index.php
I see that there is an option of maximum output entries from 5 to 1000 and then - all - Which means it could be more than 1000 as well.
Now a very common word searched will certainly give numerous entries in output. And meanwhile- "preparing data display..." message appears.
Longer the list, longer the time it takes to display. 
So why not set the options (esp. when maximum number of output entries is big) such that- you want to see that particular querry in a particular entry (in the left box), then click on it- for display. One will see that it is not there, then move to the next entry word in the list. Even if the machine (depending on speed of one's computer) manages to give the huge list in minutes, the searched querry word will however is not highlighted. (Browser Find option a good idea though- but issue here is Time factor). I do not know if it pleases all searchers, this is my opinion.

**Comment by drdhaval2785** [comment]
@Shalu411 

Are there any functionalities you still need?

**Comment by drdhaval2785** [comment]
I rarely cross 1000 entries in the search. Highlight functionality is tracked elsewhere.
