### ISSUE TITLE
SHS: IAST conversion

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#170]
This issue devoted to the conversion of IAST coding in digitization of Sabda Sagara dictionary (SHS) to modern IAST.

There are two aspects to this conversion:
* Use of AS (Anglicized Sanskrit, letter-number) coding for diacritics in Cologne digitization shs.txt
* Use of non-modern conventions by the printed text for representing Sanskrit words with Latin alphabet
   and diacritics.
   * One source of the author's conventions is in [this page](http://www.sanskrit-lexicon.uni-koeln.de/scans/csldoc/dictionaries/prefaces/skdpref/skdpref30.html) from the printed prefatory material.
     Although this rather poor-quality image is somewhat hard to see,  some details can be discerned.
     For instance the most prevalent diacritic is the 'acute-accent':  this is used to lengthen vowels and to
     modify the interpretation of various consonants.
   * However, this preface does not accurately describe what one sees in the printed text, at least in
      some details.  For instance, the preface says that the vocalic r  (slp1 'f', HK 'R') is represented by
      `r-underdot + i-acute-accent`.  But the text appears to use 'r + i-acute-accent'  (no dot under 'r'):
![image](https://user-images.githubusercontent.com/6393033/28985739-f7b1e76c-7931-11e7-86b2-241bc9c06912.png)
   * Compare this to Ga'yatri'  , where the same printed form ('r + i-acute-accent) represents 'consonant r plus long i':
    
![image](https://user-images.githubusercontent.com/6393033/28985877-a056469c-7932-11e7-96d9-f035ef2a1f39.png)

In the Cologne digitization, both of these are represented as 'ri4', hence indistinguishable.

Due to such interpretation difficulties,  the conversion to modern IAST will be problematic.  My approach here is to do this in a relatively expedient way, but without an attempt to develop a modern spelling for all cases.   In other words, I will probably convert `Sri4ngi` of the first example to `Sṛngi`  but may well
not go the further step to `Śṛṅgi` (where the S and n both have diacritics, as well as r).

**Comment by gasyoun** [comment]
> without an attempt to develop a modern spelling for all cases

Sure, Jim.

**Comment by funderburkjim** [comment]
#### Some digitizations use `X'` instead of `X4`

This is understandable: see the Ga'yatri'  scan image above.   In the IAST conversion, these also have to
be handled.

**Comment by funderburkjim** [comment]
### IAST conversion completed.

All of the AS to IAST conversions have been completed.  All in all, there are about 2400 words with changed spellings, and these changes occur in 7000+ lines.

[as_iast_summary.txt](https://gist.github.com/funderburkjim/ad2a449cc1730159e1a0cb969c90c31d) shows the changes made.

#### comment on completeness of conversion to modern IAST
This conversion aims to correctly change the AS and Apostrophe coding of diacritics to modern IAST diacritics.   Some attempt is made to correct errors.  For `BUDD'HA` and several variants are changed to 
 `BUDDHA`  since the `D'` in this case does NOT represent a retroflex 'D'.

#### comment on incompleteness of conversion
There are several ways that the above conversions are incomplete.   For instance the text uniformly uses 'SH' for the retroflex sibilant, instead of the modern IAST S-underdot `Ṣ`.  Also 'W' is often used for 'V', as in `VIŚHWADEVA`;  This example also shows that often the palatal sibilant is represented with a following 'H', so a fully modern IAST spelling would be `VIŚVADEVA`.

The second column of the as_iast_summary file would be a good starting point for further modernization of spellings in the shs digitization.

**Comment by gasyoun** [comment]
> and Apostrophe

Hurray!

> 'W' is often used for 'V'

As long as our search engine has v=t that's not an issue.
