### ISSUE TITLE
SHS meta-line conversion

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#172]
This issue relates to the conversion of the shs (Sabda Sagara) digitization to the 'meta-line' form.

**Comment by funderburkjim** [comment]
### two missing entries added

Due to minor deatils of the original digitization coding, two entries were, up to now, not identified as
such.
*  First entry with headword 'a': 
   * `The first letter of the alphabet, and inherent short vowel. [L=0.9]`
* Entry `mriyamARa`  formerly merged in prior entry `mradIyas`:
   ```
   mriyamāṇa¦ 
   mfn. (-ṇaḥ-ṇā-ṇaṁ) Dying.
   E. mṛ to die, śānac aff. [L=32294.1]
   ```

Note L-numbers adjusted so no change to rest of headword L-numbers.

**Comment by funderburkjim** [comment]
### Adding of `<div>` formatting 
Several regularities were noticed in the digitization of shs.txt  relating to the hierarchical structure within 
an entry.   In shs.xml these regularities have been coded as different kinds of `<div n="X">` sections.
The disp.php program has been adjusted to enter some line-break and indentation formatting on the
basis of the divs.  The text is regular enough that the resulting display is generally improved.
* ` E.`  Etymology section.  This appears at the end of most non-verb entries.
* ` [mfn][.] ` Begins the senses appropriate to certain genders for nouns/adjectives.
* ` [1-9][.] `  Begins a particular sense, for nouns and verbs.
*  ` r[.] [1-9]` For roots, begins a section for a particular conjugation class of the root headword
*  ` [Ww]ith <s>.*?</s>`  For roots, begins a section for a particular prefix used with the root headword
*  `<Poem>...</Poem>`  Occurs 9 times in shs.txt.

**Comment by funderburkjim** [comment]
#### Sample display for `guru`

![image](https://user-images.githubusercontent.com/6393033/29097787-b0571456-7c69-11e7-97c9-0f8ec06d0a79.png)

**Comment by funderburkjim** [comment]
#### Sample display for root `gama`
![image](https://user-images.githubusercontent.com/6393033/29097808-d68514c0-7c69-11e7-8d63-cbd726a1e31b.png)

**Comment by gasyoun** [comment]
> This appears at the end of most non-verb entries.

So it's Wilson-style, interesting.

**Comment by funderburkjim** [comment]
Sabda Sagara Dictionary is based on Wilson, and is very close.
For instance, compare headword `afRin` in Cologne digitizations
```
wil.txt
{#afRin#}¦ mfn. ({#-RI-RiRI-Ri#}) Free from debt or obligation; also
{#anfRin.#}
.E. {#a#} neg. {#fRin#} a debtor.

shs.txt
{#afRin#}¦ mfn. ({#-RI-RiRI-Ri#}) Free from debt or obligation; also
<>{#afRin#} E. {#a#} neg. {#fRin#} a debtor.
```

It would be interesting to try some detailed comparisons --  this might provide an indirect way of looking for corrections in both shs and wil.


Yates Dictionary is also based on Wilson, but the relation is not so close as that between shs and wil;
for instance 'afRin' is not a headword in Yates, and Yates doesn't show Etymologies like wil, shs.
Maybe he was aiming at a simplification of Wilson (see [Yates Preface](http://www.sanskrit-lexicon.uni-koeln.de/scans/csldoc/dictionaries/prefaces/yatpref/yatpref02.html)).

**Comment by gasyoun** [comment]
> is based on Wilson

That I knew, did not knew HOW close.
