### ISSUE TITLE
vcp meta-line conversion

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#173]
Beginning the work to convert the Cologne digitiization of Vachaspatyam to the newer 'meta-line' format.

Since there is no IAST in this vcp.txt (the text is all Devanagari), there is no requirement for IAST modernization to do first. Hurray!

**Comment by funderburkjim** [comment]
### section on vowels and consonants -- 

There is an interesting part of vcp after the headword Ozmya  (last headword beginning with a vowel) and before the headword 'ka'  (first headword beginning with a consonant).
*  a table, occurring on two pages, with a row for each letter of the alphabet. I'm not sure what the
    other columns of the table are about
*  a section on vowels:  svaravarRaviBAgAdi
   * within this section, the current Cologne markup has separate headwords for vowels
*  a section on consonants

I think this markup of headwords is suspect, and that perhaps the whole section should be considered
as outside the sequence of headword entries that comprise the bulk of the dictionary.  It appears more
like an appendix that happens to occur in the middle of the dictionary.

However, I'm not making any changes to the headword list at this time.  We need a more informed opinion than mine to consider this point.

**Comment by funderburkjim** [comment]
### Siddhanta font needed
Noticed that the 'standard' displays (basic, list, advanced, mobile-friendly) do not use the siddhanta font for
Devanagari.  Noticed this with vcp,  it is probably true for most of the other dictionaries as well.  By contrast the apidev displays (list-0.2.html, etc) do use the siddhanta font.

**Comment by gasyoun** [comment]
> it is probably true for most of the other dictionaries as well

Exactly.

**Comment by funderburkjim** [comment]
#### meta-line conversion done

The meta-line conversion has been done.  

xml markup made more consistent with other dictionaries, by liberal use of the `<div>` tag.  However,
the display is largely unchanged.

**Comment by funderburkjim** [comment]
Reopening as reminder to drop 'nukta' coding in VCP.

### SKD nukta
In course of meta-line conversion of skd  #176 ,  found information on nukta in SKD.

In the original version  (skd_orig_utf8_slp1.txt) of the digitization, nuktas for SLP1 `q` and 'Q` were
coded with a following digit '2'  (`q2`, `Q2`).  15000+ instances of these.   

These 2-nukta codings were nuked (excuse the bad pun) in the skd_v0.txt version.
