### ISSUE TITLE
Ordering issues in MW Advanced search

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/Cologne#174]
http://sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/webtc2/index.php

त after द
![capture](https://user-images.githubusercontent.com/5755132/29493166-d1b71c9c-85ae-11e7-8317-89d11c1d9cf1.png)

**Comment by funderburkjim** [comment]
Ordering shown agrees with [printed text](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=MW&page=136)

**Comment by gasyoun** [comment]
Maybe it's tta and no ta ordering issue?

**Comment by SergeA** [comment]
It is not an issue, but MW's logic. The participle ātta "given" goes under the verb ādā "to give".

**Comment by drdhaval2785** [comment]
So I take that the ordering in list is as per the printed text and not as per alphabetical order.
I am curious to see what happens when the dictionaries have three volumes e.g. ACC.

Does the list follow alphabetic order or printed order?

**Comment by funderburkjim** [comment]
> the ordering in list is as per the printed text

Yes, this is the way the ordering is done in Advanced Search Display, no matter which dictionary.
Technically, it is by 'L' (cologne record id).

**Comment by drdhaval2785** [comment]
OK. Then this is not a bug. Thanks.
