### ISSUE TITLE
SKD meta-line conversion

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#176]
This issue for details regarding the change in Cologne digitization of Sabdakalpadruma dictionary (skd.txt) to the newer format which we are calling 'meta-line'.

**Comment by funderburkjim** [comment]
### Markup changes
I understand very little of the structure of entries of this dictionary.   There is a relatively small amount of markup that Thomas introduced, and I've made only minor changes to this.  

### The only `<div>` tag is for 5 footnotes.
Coded as `<div n="F">...</div>`
Html rendering is clear, but ugly (example under hw `grahaH`):

![image](https://user-images.githubusercontent.com/6393033/29642049-8a450454-8834-11e7-9ef2-35fe4d04d497.png)


### `<Cn>` column breaks
Used to code columns in Tabular data of the dictionary.  The example above shows current
rendering.  Here is corresponding print:

![image](https://user-images.githubusercontent.com/6393033/29641901-d44fcf30-8833-11e7-98c2-c4c8bb1ea166.png)


### `<mark n="H"/>`
This tag indicates some header information.  To improve the rendering, we would need to examine
the scope tag, which the current digitization does not indicate.  The above example includes one `<H>`.

### `<mark n="P"/>` tag
Generalizing from a couple of examples, this tag is used when there is some indentation of the
first line of a paragraph.  Current rendering just ignores.

Note that the `<mark/>` tag is *Empty*.  It just indicates some kind of break in the text.

That's about all the markup there is in SKD.

**Comment by funderburkjim** [comment]
### `<mark n="Picture"/> tag
There are 5 of these.
For instance, under headword [mantraH](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=SKD&page=3-618)

**Comment by funderburkjim** [comment]
### meta-line conversion completed.

Also, the 350+ extra headwords also converted to meta-line form.

**Comment by gasyoun** [comment]
> I understand very little of the structure of entries of this dictionary.

So do I. But I hope in 20 years it will change.
