### ISSUE TITLE
Full List of Abbreviations

### ISSUE THREAD

**Issue by Shalu411** [sanskrit-lexicon/COLOGNE#18]
Namaste
The main problem I face while searching dictionaries (digital or real) is findng full forms the abbreviations.  Examples are cited from different works. Very popular ones are OK, understood. But problem arises with 1. identical-named works cited (like- mahābhāṣya, mahābhārata MBH. or MBh.) 2. user-unknown works. (GORR. 2, 7, 23.) 
Since we are dealing with a digital dictionary, please let there be a page of abbreviations (like a help page,) at one click display- either typed or scanned from original book- pages as they are.

Please see this page for example- http://dsal.uchicago.edu/dictionaries/apte/ 
They give abbreviations in "Front Matter" page. 
DSAL people also give an explanation of how to use their pages. 
I do understand that their pages and approach are different from yours. 
But nevertheless, you can add some instructions below each page of your dictionary- because they are all the same structure and working. Done for one page- done for all. :)

**Comment by drdhaval2785** [comment]
Lists of abbreviations have been cleaned up a lot in the meanwhile and are tracked separately. Closing this.
