### ISSUE TITLE
Side question on React and Ajax

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#186]
### Side question re React.js

Since @gasyoun recently made a comment that @juhnowski is still interested in what we're doing here,
this is a technical question for @juhnowski .  

I've spent a fair amount of time reading about React.js, and a smaller amount 
with Polymer and with vue.js; even an oldie-but-goodie like Backbone.js.

In my reading with React, one puzzling question to me is how to do Ajax calls.   

For instance, suppose I want
an html page with (a) an input field and (b) a `<div id="display">`.
  When somebody types a request X in the input field
(and hits return key), I want to make an ajax call to some external server program  such as `test.php?input=X`, and use the value returned by the server to display something in the `<div id="display">`.

In a non-react setting, this would be easy by putting a jQuery ajax function as the callback to an 
onChange event handler for the input field.  But how do we do this with React components?

Can you cook up a simple example that shows how to do this?

**Comment by gasyoun** [comment]
@funderburkjim somehow I missed all the fun, seems that github UI has changed and it's no good for me. Let me ping @juhnowski.

**Comment by juhnowski** [comment]
Hello, Jim.

Following I try to explain my view on React.
React is a View in MVC pattern, others (Model and View) you may implement as you wish. A jQuery ajax function is not bad, but now developers prefer to use fetch, some one (https://daveceddia.com/ajax-requests-in-react/) prefer js libraries. «The thing is, it doesn’t really matter. There’s no “best.”»
Usually React is used with http://redux.js.org/, but in our case, I see, that redux excessively functional.

Now I'm thinking about how to write a simple example.

**Comment by gasyoun** [comment]
> Following I try to explain my view on React.

Does it help, Jim?

**Comment by funderburkjim** [comment]
Hi, Ilya.   I'll take a look at the ajax-requests-in-react link.

One aspect that is confusing is the way data flows in react.  For instance,  Suppose one component
is a 'citation' input field.  When the user enters and hits return, that event should trigger an ajax call to
server.  But when the data returns from server, that data needs to be displayed in some other component.   How to get the data over to that other component ? That's where I am stuck.

A simple example sounds good.

**Comment by juhnowski** [comment]
Hello, Jim.
I want to confess you, that I can’t write simple and easy example on react with redux. 

I have been actively involved in the development of a large project for a reactive native for more than a year. In recent days, I analyzed the history of the project and came to disappointing conclusions.
Two-year usage history has revealed a number of negative aspects. They are: 
code confusion with increasing functionality, 
performance degradation with code growth,
 dubious universality - code diverges for Android, iOS and browser - hence the complexity of support. 
difficult implementation of simple things, like:
	— Asynchronous data exchange with the server
	—Transferring data to components
	— unclear implementation of the nesting of components and as a result a lot of side effects when displaying, transmitting events

Now I'm looking at a number of technologies, writing tests, and maybe I'll offer something by the end of the week. To use technology for which it is impossible to write a simple visual functional example is unreasonable.

P.S. data is transmitted through the state

**Comment by funderburkjim** [comment]
Hi, Ilya.  Thank you for the interesting comments regarding downside of serious work with React.

Will decrease my interest in React.

Am currently reading a course in Bootstrap, as I think it might help us develop web apps that will work
nicely on both mobile and desktop devices.  And Bootstrap will not get in the way of simple Jquery principles.

Again, thanks for thinking about this.  It's useful to have input from someone with serious web app experience.

**Comment by gasyoun** [comment]
> Again, thanks for thinking about this. It's useful to have input from someone with serious web app experience.

Exactly.

**Comment by drdhaval2785** [comment]
No work in react for three years. Closing.
