### ISSUE TITLE
Cut off verbal endings

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/COLOGNE#189]
Sometimes people do not know what they search for.
If they search a verb, but enter a verb form instead, we can try to cut off the ending.
Bellow is a list of all verbal endings as per Bucknell. @funderburkjim what do you think of it? @drdhaval2785 does it makes sense?

```
-
-a
-aH
-at
-ata
-ataH
-atam
-atAm
-ati
-atu
-atuH
-ate
-aTa
-aTaH
-aTuH
-aDvam
-aDve
-an
-anta
-antAm
-anti
-antu
-ante
-am
-avam
-avAni
-avAma
-avAmahE
-avAva
-avAvahE
-avIH
-avIt
-avIti
-avItu
-avImi
-avIsi
-avuH
-avE
-aval
-asi
-ase
-asva
-AH
-ARi
-At
-Ata
-AtaH
-Atam
-AtAm
-Ati
-Atu
-Ate
-ATa
-ATaH
-ATAm
-ATe
-An
-Ana
-Ani
-Anti
-Antu
-Am
-Ama
-AmaH
-Amahi
-Amahe
-AmahE
-Ami
-AyAH
-AyAt
-AyAta
-AyAtam
-AyAtAm
-AyAm
-AyAma
-AyAva
-AyuH
-Ava
-AvaH
-Avam
-Avahi
-Avahe
-AvahE
-Asi
-Ahi
-i
-iQvam
-ita
-itaH
-itam
-itAm
-iti
-itu
-iTa
-iTAH
-iDve
-ima
-imaH
-irnahe
-imahe
-imi
-ire
-iva
-ivaH
-ivahe
-izata
-izam
-izAtAm
-izATAm
-izi
-izuH
-ize
-izwa
-izwam
-izwAm
-izWAH
-izma
-izmahi
-izva
-izvahi
-ihi
-IH
-It
-Ita
-ItaH
-Itam
-ItAm
-Ite
-ITa
-ITaH
-ITAH
-IDvam
-IDve
-Ima
-ImaH
-Imahi
-Imahe
-Iya
-IyAH
-IyAt
-IyAta
-IyAtAm
-IyAm
-IyAma
-IyAva
-IyuH
-Iran
-Iran
-Iva
-IvaH
-Ivahi
-Ivahe
-Ize
-Izva
-Ihi
-u
-uH
-uta
-utaH
-utam
-utAm
-ute
-uTa
-uTaH
-uDi
-uDvam
-uDve
-unoH
-uma
-umaH
-umahi
-umahe
-uyAH
-uyAt
-uyAta
-uyAtam
-uyAm
-uyAma
-uyAva
-uyuH
-uva
-uvaH
-uvata
-uvAtAm
-uvAte
-uvan
-uvanti
-uvantu
-uvahi
-uvahe
-uvATAm
-uvATe
-uvi
-uvIta
-uvITAH
-uvIDvam
-uvImahi
-uvIya
-uvIyAtAm
-uvIyATAm
-uvIran
-uvIvahi
-uve
-uze
-uzva
-uhi
-e
-eH
-et
-eta
-etam
-etAm
-ete
-eTam
-eTAH
-eTAm
-eTe
-eDvam
-ema
-emahi
-eya
-eyam
-eyatAm
-eyaTAm
-eyuH
-eran
-eva
-evahi
-E
-oH
-ot
-oti
-otu
-omi
-ozi
-O
-OH
-Ot
-Oti
-Otu
-Omi
-Osi
-wa
-waH
-wam
-tam
-wAm
-wi
-wu
-we
-Wa
-WaH
-WAH
-Qi
-Qvam
-Qve
-ta
-taH
-tAm
-ti
-tu
-te
-Ta
-TaH
-TAH
-Da
-DaH
-Dam
-DAH
-DAm
-Di
-Du
-De
-Dvam
-Dve
-ma
-maH
-mahi
-mahe
-mi
-yAH
-yAt
-yAta
-yAtam
-yAtAm
-yAm
-yArna
-yAma
-yAva
-yava
-yuH
-va
-vaH
-vata
-vatAm
-vati
-vatu
-vate
-van
-vanti
-vantu
-vahi
-vahe
-vAtAm
-vAte
-vATAm
-vATe
-vi
-vIta
-vITAH
-vIDvAm
-vimahi
-vImahi
-vIya
-vIyaTAm
-vIran
-vIvahi
-ve
-zaH
-zat
-zata
-zatam
-zatAm
-zaTAH
-zaDvam
-zan
-zanta
-zam
-zAta
-zAtam
-zATAm
-zAma
-zAmahi
-zAva
-zAvahi
-zi
-zIH
-zit
-zuH
-ze
-zwa
-ztam
-stAm
-sTAH
-sma
-smahi
-zva
-zvahi
-sata
-sam
-sAtAm
-sATAm
-si
-sIH
-sIt
-suH
-se
-sva
-svahi
```

**Comment by funderburkjim** [comment]
I like the fact that you've gathered all the verb endings from Bucknell. 

#### reverse engineering inflected forms of verbs
Even with this table of verb endings in hand, there remains (at least) one obstacle to making use of these endings: the stem formation.

For instance, suppose someone enters 'bhavati'.   We find the ending 'ati' in Bucknell table, and
remove it, resulting in 'bhav'.   We want to direct the reader to root 'bhU' , so we need another
table that takes us from 'bhav' to 'bhU'.  

Given the fact that most roots are class 1. and that it is not too hard to derive the stem used for
present tense, imperfect tense, imperative (mood) and optative (mood) ,  its conceivable to 
consider adding logic to do so in the simple search.   

While incomplete, this approach might be a practical way to add many common inflected verb forms as
end points in the simple-search.


#### Another approach: precompute all inflected forms.
This was the approach taken in the 'MW inflected forms'  database 
[first display](http://www.sanskrit-lexicon.uni-koeln.de/work/fflexphp/web/index.php).

In this  first attempt at 'full-form lexicon', the user enters an inflected form (verb form or noun form), and gets all the possible underlying MW dictionary words.

**Comment by gasyoun** [comment]
> I like the fact that you've gathered all the verb endings from Bucknell.

12 years ago.

> We want to direct the reader to root 'bhU' , so we need another
table that takes us from 'bhav' to 'bhU'.

Agree.

> Given the fact that most roots are class 1. and that it is not too hard to derive the stem used for
present tense, imperfect tense, imperative (mood) and optative (mood) , its conceivable to
consider adding logic to do so in the simple search.

Exactly!

> While incomplete, this approach might be a practical way to add many common inflected verb forms as
end points in the simple-search.

Yes.

> In this first attempt at 'full-form lexicon', the user enters an inflected form (verb form or noun form), and gets all the possible underlying MW dictionary words.

Can we reuse it here? Where is `pre-1a` described?

`004 verb: gam , model: pre-1a`


![gacchat](https://user-images.githubusercontent.com/80761/31918062-5a90deae-b863-11e7-94c8-d6d5059e0f24.PNG)

**Comment by funderburkjim** [comment]
pre-1a notation was inspired by the scheme Peter Scharf used in his rAmopAKyAna book (detailed in
an appendix).

pre = present tense, 1 = verb class number (1 to 10), a = active voice = parasmaipada.

**Comment by gasyoun** [comment]
> Peter Scharf used in his rAmopAKyAna

Thanks, so here it is:

![pages from scharf_p_ramopakhyana_the_story_of_rama_in_the_mahabharata_page_1](https://user-images.githubusercontent.com/80761/31931988-a745231e-b8ad-11e7-8713-9b66ab0b8151.jpg)

![pages from scharf_p_ramopakhyana_the_story_of_rama_in_the_mahabharata_page_2](https://user-images.githubusercontent.com/80761/31932003-b1a3eb24-b8ad-11e7-8415-c530ff919395.jpg)

**Comment by drdhaval2785** [comment]
I have a precomputed verb form list.
https://github.com/sanskrit-coders/stardict-sanskrit/blob/master/sa-vyAkaraNa/dhaval-tiNanta/dhaval-tiNanta.babylon_final

This is it if it helps.

**Comment by gasyoun** [comment]
> precomputed verb form list.

In what order are the forms? Where one can read the prehistory of the file and how clean/verified it is?

**Comment by drdhaval2785** [comment]
There is no order of forms.

The file is generated by our SanskritVerb code. The file is cross checked with Uni of Hyderabad database and INRIA database. Necessary corrections are already incorporated. 

Corrections to UoHyd and INRIA database based on this file was sent to Amba and Gerard respectively. Many of those may have been corrected in their databases too.

So it is as clean as it can be at this stage of Sanskrit computation.

**Comment by gasyoun** [comment]
> Necessary corrections are already incorporated.

And listed where?

> sent to Amba and Gerard respectively. 

Can you upload a copy to github as well, please, for reference?

> Many of those may have been corrected in their databases too.

Good to know.

> So it is as clean as it can be at this stage of Sanskrit computation.

So it's dirty :100:

**Comment by drdhaval2785** [comment]
After csl-inflect repository came to horizon, this would be closable.
