### ISSUE TITLE
Scanned Page Navigation by Page Number

### ISSUE THREAD

**Issue by Shalu411** [sanskrit-lexicon/COLOGNE#19]
Namaste
Is page navigation on Scan page possible? "<>" marks are give for previous and next pages. But can we be provided a chance to enter page number directly and jump to the desired page? 
http://www.sanskrit-lexicon.uni-koeln.de/scans/VCPScan/2013/web/webtc/servepdf.php?page=0025
Am I asking for too much?
I see one solution to this- as changing the number in the end of the link in the address bar. It will help but if provided directly as option, then good..

**Comment by drdhaval2785** [comment]
@funderburkjim Can you provide the latest link to servepdf functionality, so that I can close this issue?

**Comment by funderburkjim** [comment]
https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=MW72&key=aSva

Note 'key' is SLP1 spelling.

https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=MW72&page=101

These are the two forms that csl-apidev/servepdf.php  accepts.

So requirements are
* `dict` parameter  with value one of the dictionary codes
* Either `page` parameter or `key` parameter.

Currently, the Basic, Advanced, and other displays also use this same
csl-apidev/servepdf.php for serving up images.
