### ISSUE TITLE
PWG IAST conversion

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#195]
This issue will document the IAST conversion recently implemented for the PWG dictionary.

IAST here refers to the use of Latin alphabet *with diacritics* to represent Sanskrit words.

There are two flavors of IAST involved here.
* That used by the PWG print 
* Modern IAST, as described in this [iast article](https://en.wikipedia.org/wiki/International_Alphabet_of_Sanskrit_Transliteration).

**Comment by funderburkjim** [comment]
### as_roman1 transcoding

Thomas's original digitization aimed to provide a coding faithful to the print IAST.  It used a version of his 'AS' (Anglicized Sanskrit) coding scheme, which uses letter-number combinations to represent letters with diacritics.   Thus, in the original coding, the AS coding 'k4' represents `ḱ`  (k with acute accent) which corresponds to modern IAST 'c'.   

The general transocoding system  was used to implement this conversion from PWGIAST-AS to IAST; specifically, the Python version [transcoding.py](https://github.com/funderburkjim/sanskrit-transcoding/blob/master/transcoder.py) was used.

A particular transcoding is governed by a simple xml file. In our case,
The relevant transcoding parameters are in [as_roman1.xml](https://github.com/sanskrit-lexicon/PWG/blob/master/pwg_ls1/as_roman1.xml).

I don't think that PWG specifically documents his IAST system.
The details of this transcoding were determined basically by comparing the spellings of known words.
I seem to recall seeing some documentation either in PW or PWG print on B's transliteration system, but can't find that now, if indeed it is documented at all.

**Comment by funderburkjim** [comment]
### Transcoding changes within `<ls>`

The transcoding from AS to modern IAST within the scope of `<ls>` tags was done in such a way that a
summary of the changes was also constructed.

This summary is [manualByLine_iast_ls_log.txt](https://github.com/sanskrit-lexicon/PWG/blob/master/pwg_ls1/manualByLine_iast_ls_log.txt).

Each `<ls>X</ls>`  (with X in AS coding) was transcoded to `<ls>Y</ls>` (with Y in modern IAST coding).

To make the summary,  each X was separated into tokens X1, X2, ...   by splitting on spaces.
SImilary, the corresponding Y was separated into tokens Y1,Y2,...    Then corresponding tokens
were compared and when token Xi differed from corresponding token Yi, a counter for (Xi,Yi) was updated.
Each line of the summary represents the totals for these counters.
There are about 1850 entries, one for each different (Xi,Yi).

The first field in an entry represents the frequency of occurence of some (Xi,Yi) change,
and the change itself is shown as Xi -> Yi.


### Conversion problems
I used this summary as an aid to spotting conversion problems.  There are no doubt still a few
conversion problems that still need correction.  For instance, x or X within an 'ls' is problematic.
'x; is used by PWG to represent `kṣ` as in Nax. -> Nakṣ. (Nakṣatra).  But of course it also has 
use in non-Sanskrit words and in Roman numerals.  In preparing these comments I noticed that
`Appendix -> Appendikṣ` appears an an obviously wrong conversion which needs to be adjusted.

### Mis-spelled sources
This list can also be examined for errors due to mis-spellings.  For instance, the example 
`MR2KK4H -> MṚKCH`  needs to be corrected to `MṚCCH`.

### How to correct
When we find such errors in this log file,  the current digitization pwg.txt needs to be examined to
find the instance or instances that need correction, and the correction should be made there.

Examination of this file is a fairly self-contained task, for someone familiar with distinguishing 
Sanskrit from non-Sanskrit, and having a feel for correct spelling in IAST Sanskrit.   For the most
part, the AS spelling can be ignored, as it plays no direct role in the current digitization.

**Comment by funderburkjim** [comment]
### Transcoding within `<is>` tags.

The `<is>` tag represents printed text whose form is distinguished by (a) being composed of Latin letters with diacritics and (b) wide letter spacing. This was discussed in [this comment](https://github.com/sanskrit-lexicon/Cologne/issues/190#issuecomment-345383225) of #190.

The current work assumed that all such words are Sanskrit, and changed the spelling of such 'is'  words by applying the transcoding from AS to modern iast  (as_roman1.xml transcoder file mentioned above).

There is a summary file of the changes: [manualByLine_iast_is_log.txt](https://github.com/sanskrit-lexicon/PWG/blob/master/pwg_ls1/manualByLine_iast_is_log.txt).

There are more cases here, currently 5250.  Format is similar  to the *iast_ls_log* file mentioned above.

#### Sources of error
The sources of error are generally similar
* misapplication of transcoding
* mis-spelling.  For instance, I notice `Krṣṇa`   (should be `Kṛṣṇa`).
* Possible mis-classification of word as 'wide' (i.e. should not be marked with `<is>`).
* Y = X 
 A fourth potential source of error involves `<is>` codes that do NOT appear in this list.   This list was 
 constructed to consider only `<is>X</is>` cases where transcoding X resulted in a Y *different from X*.
It is likely that for some X, transcoding made no change to X (i.e. Y == X), but that it should have made a change.   These cases of Y=X could be examined separately

**Comment by funderburkjim** [comment]
### Other AS transcoding

There are other words within the text with original coding of diacritics using AS scheme.  For instance, diacritics in French words were so coded, e.g. `apre4s` for `aprés`.  Most of these were handled in preliminary work determining the details of the as_roman1.xml transcoding file.

However, after all the transcoding described above was finished, a check was made for other likely AS (letter-number) codings.  214 cases were identified, and reside in a 'change' file: [manualByLine_isprob.txt](https://github.com/sanskrit-lexicon/PWG/blob/master/pwg_ls1/manualByLine_isprob.txt).

**Comment by funderburkjim** [comment]
This concludes this review of the AS-IAST transcoding of PWG.

Three files are mentioned as starting points for further examination for generating corrections to pwg.txt digitization:
* manualByLine_iast_ls_log.txt   IAST occurring with scope of `<ls>` tag
* manualByLine_iast_is_log.txt   IAST occurring within the `<is>`  tag
* manualByLine_isprob.txt  remaining untranscoded AS (letter-number) text.

These all need to be examined by willing helpers.  For anyone committing to adopt one of these as a project, I'll help as needed to prepare auxiliary materials.

**Comment by drdhaval2785** [comment]
Conversion to IAST is complete. Closable @funderburkjim? If any errors are found by someone, it will be treated as a new correction submission.

**Comment by funderburkjim** [comment]
Yes. Looks closeable.
