### ISSUE TITLE
BHS meta-line/iast conversion

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#201]
This issue is for notes relating to changes in the digitization bhs.txt (Edgerton Buddhist Hybrid Sanskrit Dictionary).

**Comment by funderburkjim** [comment]
### Additional headwords

During the course of the conversion, 29 new headwords were uncovered.  These were missed by the
previous headword detection logic due to the fact that the raw form (key2) of the headwords spanned
two lines.
For instance, 
anantaparikarasāgarameghavyūhatejomaṇḍalachattrākārarāja  , n. of a nāga king: Megh 292.8 ff.

**Comment by funderburkjim** [comment]
### Error in 'documentation' corrected.
In preparing these comments, I noticed that the first two pages of the Front Matter (Title and Contents) of the documentation were wrong;  these now corrected

**Comment by funderburkjim** [comment]
#### IAST conversion

The form of diacritics used to represent Sanskrit  words in bhs  is consistent with modern conventions.  The work was originally published in 1953.  We can infer that what we call 'modern' IAST was stabilized sometime before 1953.

In general, Sanskrit words are not distinguishable by any typographic feature from words in other languages (including English, Pali, French, German).  This will provide some challenges to anyone wanting to classify the words, such as for the purpose of searching.

**Comment by funderburkjim** [comment]
### Reclassify as a Specialized Dictionary

In the [Preface](http://www.sanskrit-lexicon.uni-koeln.de/scans/csldoc/dictionaries/prefaces/bhspref/bhspref03.html), the author states

> I have deliberately excluded words and forms occurring (with the same meanings) in standard Sanskrit.

Thus, it seems sensible to change the position of the dictionary on the Sanskrit-Lexicon [Home Page](http://www.sanskrit-lexicon.uni-koeln.de/) from the *Sanskrit-English Dictionaries* section to the *Specialized Dictionaries* section, and this has been done.

**Comment by funderburkjim** [comment]
### Enhancement suggestion: abbreviations

There is a nicely presented 6-page section of the Preface which presents abbreviations of works and general abbreviations used in the Dictionary.
This could be used to add useful markup  (`<ls>X</ls>` and `<ab>X</ab>`) to the digitization and tooltips to the displays.

This preface material has not been digitized.

**Comment by funderburkjim** [comment]
### Enhancement suggestion: alternate headwords

About 1000 of the 17000 headwords have non-trivial key2 information; many of these could be interpreted to provide alternate headword forms.

Verbal headwords are presented in inflected form rather than root form, e.g. `gacCati` (3rd singular present form) instead of root form `gam`.   Adding the root as alternate headword would facilitate programmatic cross referencing of such entries with entries in standard Sanskrit dictionaries.

**Comment by funderburkjim** [comment]
Enhancement suggestion: lbinfo

In current converted form of the dictionary, line break information is present in the form `<div n="lb">`.
There are many lines ending in a hyphen `-`; in most of these cases the digitized text would be more useful without the '-'  (i.e., reconstituting the unhyphenated word). This could be done in the same way as was done in Burnouf digitization and others, namely by using a tag `<lbinfo n="N"/>` after the
unhyphenated word to indicate the offset N from the end of the original printed '-'.

Programs already exist that could do a good first approximation of this.  Since there are some cases where the '-' should be retained, a more perfect handling would require additionaly attention.

**Comment by funderburkjim** [comment]
###  Conversion installed
The conversion has now been completed 
* meta-line form, 
*  replacement by Unicode text of AS (letter-number) representation of letters with diacritics

**Comment by gasyoun** [comment]
Guess the Preface digitalisation task is a whole big task I would want to undertake.
