### ISSUE TITLE
BOP meta-line/iast conversion

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#202]
This issue devoted to the conversion of bop.txt, the Cologne digitization of Bopp's Glossarium Sanscritum, a Sanskrit-Latin dictionary.

**Comment by funderburkjim** [comment]
The conversions have now been completed.

**Comment by funderburkjim** [comment]
### Additional headwords

6 missed headwords were discovered, and properly recoded with deimal L-numbers.

**Comment by funderburkjim** [comment]
### IAST conversion

Generally Sanskrit words are presented in Devanagari within the text; this includes headwords.

However, some words appearing in Latin alphabet have letters with diacritics.  
Some of these words are related to Sanskrit words  such as `Vêdorum`.
![image](https://user-images.githubusercontent.com/6393033/35755770-9a34815a-0836-11e8-9320-37a3d54ebbd5.png)
No attempt has been made to impose a 'modern IAST' spelling to such words as Vêdorum -- eg., we
leave the circumflex diacritic as printed.

There are also numerous words in other languages in what appear to be etymological comments.
For instance, there are 135 instances of 'russ.' indicating presumably related or cognate Russian words.
![image](https://user-images.githubusercontent.com/6393033/35755928-3b163564-0837-11e8-9b35-4a3c5b9c8c4b.png)

The spelling of these words also has been coded with unicode characters which aim to approximate the
diacritics of the text.

**Comment by funderburkjim** [comment]
### Markup

The digitization recognizes the line breaks of the text.  New lines of text are generally marked as
`<div n="lb">`.   

The original digitization also identifed the prefixes occurring within roots, and these lines have been
marked as `<div n="pfx">`.  For example under root `gam`:

![image](https://user-images.githubusercontent.com/6393033/35756411-37ffbc86-0839-11e8-8806-9697ed370fa9.png)

There are about 1400 instances of Greek text;  the Greek is uncoded and is marked as `<lang n="greek"></lang>`.

There are about 50 footnotes in the entries.  The original digitization has been rearranged using the same strategy as used for footnotes in [krm](https://github.com/sanskrit-lexicon/Cologne/issues/200#issuecomment-361131579).
Here is the display for the footnote under headword `akza`:
![image](https://user-images.githubusercontent.com/6393033/35756587-eca0b212-0839-11e8-8fb3-a3b33b238f93.png)

**Comment by funderburkjim** [comment]
### Enhancement suggestion: line breaks

As with other dictionaries coded line-by-line, the resulting digitization might be more useful if the
hyphenated words were presented in unhyphenated form.  This could be done without information loss by using the `<lbinfo n="N"/>` markup idea used in Burnouf and other dictionaries.

**Comment by funderburkjim** [comment]
### Enhancement suggestion: abbreviations

The printed text preface contains two pages of [abbreviations](http://www.sanskrit-lexicon.uni-koeln.de/scans/csldoc/dictionaries/prefaces/boppref/boppref04.html). These pages are also part of
the bop.txt digitization.  This list could be used as a guide to applying the `<ls>X</ls>` and `<ab>X</ab>` markup (for literary sources and general abbreviations) .

**Comment by funderburkjim** [comment]
### Enhancement suggestion: prefixed forms headwords

Additional headwords could be generated for the prefixes associated with root entries.  The regularity of the coding following the already present  `<div n="pfx">` markup would solve the primary problem of identification.  Of course the problem of sandhi between the prefix and root needs to be solved also.

**Comment by funderburkjim** [comment]
### Enhancement suggestion: corrections and additions

There are six pages of [ADDENDA ET EMENDANDA](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=BOP&page=407) .

The bop.txt digitization also contains these additions and corrections.
They could be applied to the digitization entries.   We have not thus far developed a satisfactory markup scheme for such a task; the approach used in a similar task for MW should be examined as a guide line whenever this task for BOP is undertaken.

**Comment by funderburkjim** [comment]
These are all the comments that come to mind regarding the BOP conversion.

**Comment by gasyoun** [comment]
Give Greek to the Greeks between us, Jim!
