### ISSUE TITLE
PD meta/iast conversion

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#203]
This is placeholder for comments on the conversion of PD to the meta-line format, and includes the conversion of AS-coding of text with diacritics to Unicode.

**Comment by funderburkjim** [comment]
#### metrical characters
These are used in only one place, headword akzi (hom3).  
The metrical breve is the short, the en-dash is the long
⏑⏑–, ⏑–⏑

I think these differ from the characters used for long-short in some other dictionaries (not sure which at
the moment).  I also saw note on a proposed 'metrical longum' to be distinguished from 'en-dash'.  
Sometime we should ferret out all the cases in all the dictionaries, and impose consistent usage across dictionaries.

**Comment by funderburkjim** [comment]
#### IAST conversion

The only variance from what we consider standard IAST was that the anusvara of the printed text uses
ṁ (m with dot above) whereas modern IAST uses ṃ (m with dot below).   The digitization was changed to use ṃ.

**Comment by funderburkjim** [comment]
#### meta line conversion

10 additional headwords uncovered   (they appear in square brackets in the print), and added with new
fractional L-numbers.

**Comment by funderburkjim** [comment]
### Devanagari extensions

#### Non-combining chandrabindu.   
Thomas coded these with the £ character, and this has been retained for
   now.  There are 948 lines with this £ character.  Here is a typical example in print:
![image](https://user-images.githubusercontent.com/6393033/35828497-a9e99442-0a8d-11e8-9c5c-e34f994730f2.png)

  Unicode has a code point DEVANAGARI SIGN SPACING CANDRABINDU  which shows as a (non-combining) candrabindu: ꣲ  and this is the current representation used in the displays. (example aMSa)

####  Accent numbers
There are about 50 lines in the digitization where the caret `^N` (N a digit) notation appears.
These correspond in the printed text to numbers place above Devanagari letters. The first example
appears under headword aMSu.
![image](https://user-images.githubusercontent.com/6393033/35829045-9f81aa9c-0a8f-11e8-9456-d0b1bfde47a6.png)
The current display function disp.php removes these ^n characters from `<s>X</s>` instances, so ^n does not appear in any way.

**Comment by funderburkjim** [comment]
Given Cologne's constraints regarding this dictionary, I'll make no further comments on the present conversion, which has now been installed.

**Comment by gasyoun** [comment]
10 additional is how much total? At http://www.dcpune.ac.in/pdf/Publications%20of%20SDP%202017.pdf do the numbers are the same. Will visit the makers of PD in a week. How many Devanagari qutes are there? How many per entry? Let me have some arguments for them that they are not even aware of. PD makers state 1500 sources (how many abbreviations we actually have? 1500 seems suspicios.   If I understood right, we have 2200 for PWG? Please correct me, @funderburkjim

**Comment by funderburkjim** [comment]
#### print corrections

One point the dictionary authors should find of interest is corrections identified as 'print changes'.
Take a look at the [print changes](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/dictionaries/PD/pd_printchange.txt).

#### 10 additional headwords
This is not a flaw in the print, but an improvement in our understanding of how to identify headwords.

Since you know how to access the dictionary,  suggest you show them the various display methods.
I wonder if they have similar capabilities 'in house'.     

Also, even if they are not comfortable allowing us to display the dictionary, they might find the Cologne
digitization useful.  We would be glad to share our work with them with no strings attached.

**Comment by gasyoun** [comment]
Jim, good to see you with electricity back. I showed a few interfaces at Pune and I have a few feedbacks. Last time Dr. Prasad spoke with Malcolm the Decan college vice-chancellor was against online files. Things are changing, but very slowly, I will write a report after. They want to have a payment gateway to access PD. That seems too hard and not worth it, still. My dialogue with them continues. Inside the library room where most work is accomplished there is only intranet with a scanned vetsion on the huge Scriptorium slips and the 1467 books used as basis as scanned TIFFs. There is no internet, so no cologne. There is a printed MW on each table a d that is the most widely used refertence work. That means they are slow, very slow. The dictionary will never be finished and the project remains very closed.
The IAST errors,  I guess are of no use to them, as they are ours only, right?

![dsc05607](https://user-images.githubusercontent.com/80761/37245237-d4928634-249d-11e8-9d8e-77d6cbc53e22.JPG)

They are aware of Cologne, but underestimate or do not understand it a lot. Outside the library, at home or on phone they use the offline versions. But it is not used in no way in the making and editing entries. And there is not and see s will not be no Unicode. Indian software is very strange and mostly reminds of a brick.
