### ISSUE TITLE
PGN meta/iast conversion

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#209]
This issue for comments related to the meta-line/iast conversion of pgn.txt, the Cologne digitization of the book `Personal and Geographical Names in the Gupta Inscriptions`.

**Comment by funderburkjim** [comment]
### IAST issues

The text  uses Latin alphabet with diacritics for most Sanskrit words.  Generally, the conventions of the
text agree with modern IAST, but with the difference:
* We use 'ṃ' for anusvara, instead of the author's ṁ.

**Comment by funderburkjim** [comment]
### Sections of the text.

The pgn.txt provides a digitized form of the entire text.  What we have identified as headword (485) entries comprises less than half of the entire text.  

We should consider a 'scanned' edition form of the text, which would provide an index into the
entirety of the text, since there is much material of interest outside the 'entry' sections.

According to some markup added to make the major sections identifiable, the sections appear as
follows (the numbers shown are line numbers within the text, and provide information on the length
of the sections.
```
35 matches for "^; " in buffer: pgn.txt
      3:; TITLE
     38:; FOREWORD
    140:; CONTENTS
    191:; PREFACE
    291:; ABBREVIATIONS
    520:; INSCRIPTION CODES
    722:; TRANSLITERATION
    743:; PART ONE PERSONAL NAMES
   1421:; ENTRIES (1)
   1942:; REFERENCES (1)
   2201:; ENTRIES (2)
   2956:; REFERENCES (2)
   3098:; ENTRIES (3)
   3792:; REFERENCES (3)
   3915:; ENTRIES (4)
   4669:; REFERENCES (4)
   4803:; ENTRIES (5)
   5386:; REFERENCES (5)
   5526:; ENTRIES (6)
   5625:; CONCLUSION
   6026:; REFERENCES (6)
   6068:; PART TWO
   6226:; ENTRIES (7)
   8318:; CONCLUSION
   8429:; REFERENCES (7)
   9377:; PART THREE
   9575:; REFERENCES
   9634:; ENTRIES (8)
  12322:; REFERENCES (8)
  13433:; ENTRIES (9)
  13775:; REFERENCES (9)
  13993:; APPENDICES
  14499:; BIBLIOGRAPHY
  15862:; PLATES
  15924:; INDEX
  17585:  END OF TEXT
```

**Comment by funderburkjim** [comment]
### Markup peculiarities
These comments apply to the entries only. The markup conventions of the other parts of the
text remain, for the most part, as in the original form of the digitization.

#### `<div n="X"/>`
This markup can have X as
* lb   typical line break.  The digitization followis the line breaks of the printed text
* P   a line break with indentation of the first line (585 instances)
* HI   First line of a paragraph, the whole of which is indented (12 instances)

Note that  this 'div' markup consists of empty xml tags.

#### `<sup>N</sup>`
Many references are annotated with a superscript number.

**Comment by funderburkjim** [comment]
#### Alphabetization absence
There is generally no alphabetization within the various sections of entries.

**Comment by funderburkjim** [comment]
The meta/iast conversion of pgn.txt has now been installed at Cologne.

**Comment by gasyoun** [comment]
Huray from Pune, congratulations.
