### ISSUE TITLE
PUI meta/iast conversion

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#210]
This issue for comments related to the meta-line/iast conversion of pui.txt, the Cologne digitization of the book `The Purana Index`.

**Comment by funderburkjim** [comment]
### IAST issues

The text  uses Latin alphabet with diacritics for most Sanskrit words.  The conventions of the
text agree with modern IAST, with one minor exception:
* We use `ḷ` instead of the text's `lṛ`  (occurs only twice.

#### One uncertain letter.

Our source for [modern IAST](https://en.wikipedia.org/wiki/International_Alphabet_of_Sanskrit_Transliteration) does not make provision for the consonant SLP1='L'  = Devanagari ळ.  There are a few instances of this letter in
pui, and it is represented with the same `ḷ` as the 9th vowel.

There is one entry,   alphabetically between words beginning with semivowels 'L' and 'V', which in the
text is written as `Ḷ`  (all the headwords show beginning with capital letters, so the fact that this is
capitalized is not important).

![image](https://user-images.githubusercontent.com/6393033/36346737-0b548c04-1412-11e8-8772-7269342e2e5d.png)

The author describes several vowels in a similar way (e.g. `Ṛkāra = 8th face of the fourteen-faced god`),  
The system seems to be 
* vowel N = Nth face of the fourteen-faced god.

Thus, I have inferred that the `tenth face of the fourteen-faced god` must be the 10th vowel, which is
ॡ and has IAST representation ḹ:

![image](https://user-images.githubusercontent.com/6393033/36346772-554855ba-1413-11e8-84f5-7583225e04ab.png)


Does this look like a correct interpretation to our Sanskrit scholars?  

Also, is there a source which describes the symbolism of 'the fourteen faced god' ?

**Comment by funderburkjim** [comment]
### Footnote reorg
There are many footnotes in this text (~9000). The original coding of these was like in KRM, and I changed
the coding in pui in a way similar to that which was done in KRM.
Here is an example of how the displays compare in the prior coding and in the current coding.

Prior coding:
![image](https://user-images.githubusercontent.com/6393033/36346789-24d4e69a-1414-11e8-8bdb-ddad907f0665.png)

Current coding:
![image](https://user-images.githubusercontent.com/6393033/36346793-42fa4340-1414-11e8-904d-0ee1e527ed35.png)

Print:
![image](https://user-images.githubusercontent.com/6393033/36346798-5fbbfff0-1414-11e8-9d9f-bf180f14e54c.png)

**Comment by funderburkjim** [comment]
### Sections of the text
The digitization has these sections:
```
entries for Volume I
entries for Volume II
Title pages for volume II
entries for Volume III
Title pages for volume III
```
Notably absent from the digitization are the Title pages for Volume I, and *35 pages of introduction*.
This introductory material looks like a good introduction to the Puranas and would be useful to many
readers, I think.  

#### Enhancement suggestion
Make the introductory material available in some form.
We have the images  as pages 661 ff. of the pui1-bookmark.pdf in the [PUI downloads](http://www.sanskrit-lexicon.uni-koeln.de/scans/PUIScan/2014/web/webtc/download.html).
We could make this available as
* a scan edition  (similar to other scan editions of dictionaries like PWG, MW, etc.)
* A digitized edition.   This would require someone to type in the 30+ pages.  This could be done
   by any careful typist, as the bulk of the material is English prose in a simple paragraph format.

**Comment by funderburkjim** [comment]
### Markup peculiarities
These comments apply to the entries only. The markup conventions of the other parts of the
text remain, for the most part, as in the original form of the digitization.

#### `<div n="X"/>`
This markup can have X as
* lb   typical line break.  The digitization followis the line breaks of the printed text
* P   a line break with indentation of the first line (585 instances)

Note that  this 'div' markup consists of empty xml tags.

#### `<sup>N</sup>`
Footnote references are annotated with a superscript number.

#### `<F>N) X</F>`
Footnote text X for footnote number N.

**Comment by funderburkjim** [comment]
The meta/iast conversion of pui.txt has now been installed at Cologne.

**Comment by drdhaval2785** [comment]
>Thus, I have inferred that the tenth face of the fourteen-faced god must
be the 10th vowel, which is ॡ and has IAST representation ḹ

It seems fine to me. If there are fourteen vowels, interpretation is fine.
The orthography also supports this.

But grammatically there is no dIrgha vowel ॡ.
