### ISSUE TITLE
SNP meta/iast conversion

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#212]
This issue for comments related to the meta-line/iast conversion of snp.txt, the Cologne digitization of `Meulenbeld's Sanskrit Names of Plants`.

**Comment by gasyoun** [comment]
The man said never trust Indian translators, use only German ones.

**Comment by funderburkjim** [comment]
### IAST issues

The text  uses Latin alphabet with diacritics for all Sanskrit words.  The conventions of the
text agree with modern IAST, so no particular issues arose in this part of the conversion.

**Comment by funderburkjim** [comment]
### Sections of the text.

The digitization contains excerpts from two publications.  Here are the sections of snp.txt.
The numbers at the start of each line represent the line number within the digitization
```
      3:; TITLE, Part 1
     39:; INTRODUCTION, Part 1
     92:; ENTRIES, part 1
   4219:; INTRODUCTION, Part 2
   4245:; Additional abbreviations of sources
   4337:; ENTRIES, part 2
   5745:; Additions and Corrections: Introduction
   5780:; ENTRIES, Additions and Corrections
```
Part 1 is from the book `THE MĀDHAVANIDĀNA AND ITS CHIEF COMMENTARY` by Meulenbeld.
Part 2 is a contribution by Meulenbeld to a book `Das Wissen von der Lebensspanne der Bäume: Śurapālas hṛkṣāyurveda ` by by Rahul Peter Das.

**Comment by funderburkjim** [comment]
### Markup particulars
These comments apply to the entries only. The markup conventions of the other parts of the
text remain, for the most part, as in the original form of the digitization.

#### `<div n="X"/>`
This markup can have X as
* lb   typical line break.  The digitization followis the line breaks of the printed text
* P   a line break with indentation of the first line (585 instances)

Note that  this 'div' markup consists of empty xml tags.

#### `<lang n="greek"></lang>`
One instance, of Greek text, not currently coded.

#### <bot>X</bot>
Markup has been added for the scientific names of plants appearing in  Part 1.  This markup was 
done in a project by some of Pawan Goyal's computer science students in a summer project in 2015.

There is no similar markup in the material of Part 2.

**Comment by funderburkjim** [comment]
The meta/iast conversion of snp.txt is now installed at Cologne.

**Comment by gasyoun** [comment]
Let us give @jsonreeder the Greek screenshot?

**Comment by jsonreeder** [comment]
Happy to help, just let me know what you need here.
