### ISSUE TITLE
BOR meta/iast conversion

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#213]
This issue for comments regarding meta/iast conversion of bor.txt, the Cologne digitization of `Borooah English-Sanskrit Dictionary`.

**Comment by funderburkjim** [comment]
### IAST issues

Most Sanskrit text within bor.txt appears in Devanagari. However, there is some usage of Latin alphabet
with diacritics to represent Sanskrit words.  This latter text has been converted to a first approximation to
modern IAST.  There still remain some cases where this conversion is incomplete, due to difficulty in
programmatic recognition of Sanskrit words which do not, in the printed text, have any diacritics.  For example 'Chandra' of the text would be 'Candra' in modern IAST.

**Comment by funderburkjim** [comment]
### Front matter not digitized

There are 30-40 pages of front matter, that can be seen [here](http://www.sanskrit-lexicon.uni-koeln.de/scans/csldoc/dictionaries/prefaces/borpref.html).  These pages are not part of bor.txt and have not been digitized, AFAIK.
The several pages of Abbreviations (both of literary sources and of general type) could be used to
add useful `<ab>` markup to bor.txt;  this has mostly not been done  (but see comment on `<ls>` tag
below).

**Comment by funderburkjim** [comment]
### Reconstruction of lines

Since this is one of the earlier Cologne digitizations of Sanskrit dictionaries, the original form of the 
digitization does not directly indicate line breaks.  That is, a line of the earlier digitization does not
represent a line of the printed text.

However,  the earlier digitization does seem to accurately identify the line breaks, using a vertical bar '|'.

In the converted form, this information has been used to reform the digitization so that each line of
the digitization represents a single line of the printed text.

There are many instances where sections of italicized text or of Devanagari text appear in multiple lines.
In the converted form, the markup used to represent these two types of text (`{%X%}` and `{#X#}`) have
been adjusted to be closed on each line.

There are also words which are split at a line break.   In some dictionaries, we have introduced a
markup involving the `<lbinfo n="N"/>` tag to unsplit such words.  However, this has not been done 
for bor.txt in this conversion.  Perhaps it could be done some other time.

**Comment by funderburkjim** [comment]
### An example

The first entry (for English headword 'A') illustrates most of the features of markup that will be discussed
in the next comment,.  Here is that entry, in several forms.


#### Scan of printed text
![image](https://user-images.githubusercontent.com/6393033/36618970-11a112e6-18bb-11e8-8160-4d284d93e635.png)

#### Current display
![image](https://user-images.githubusercontent.com/6393033/36618904-e7f90412-18ba-11e8-9bb2-f9e0e4987664.png)

#### Current markup from bor.txt
```
<L>1<pc>001<k1>a<k2>a
<div n="lb"/>{@A@}¦ {%or%} (before vowels) AN: <div n="I">I This article
<div n="lb"/>has no equiv. in Sanskrit and is expressed
<div n="lb"/>by the singular number alone: <div n="xe">{%there is a%}
<div n="lb"/>{%large silk-cotton tree on the banks of the Godavari%}</div>
<div n="lb"/><div n="xs">{#asti godAvarItIre viSAlaH SAlmalItaruH#}</div> <ls>H.</ls> i.; <div n="xe">{%there%}
<div n="lb"/>{%was a king named Cintamani%}</div> <div n="xs">{#aBUdrAjA cintAmaRi-#}
<div n="lb"/>{#rnAma#}</div> Va. </div><div n="I">II But {#kaScit#} ({#kAcit, kiYcit#})
<div n="lb"/>should be added when special attention
<div n="lb"/>is directed to the object: {%a%} (certain)
<div n="lb"/><div n="xe">{%Yaksha%}</div> <div n="xs">{#kaScid yakzaH,#}</div> Me. I 1.; {%A%} (certain)
<div n="lb"/><div n="xe">{%saint named Marichi%}</div> <div n="xs">{#kaScinmarIcirnABa BaharziH,#}</div> <ls>D.</ls>
<div n="lb"/>iii. </div><div n="I">III When it means a species of, {#viSezaH, #}
<div n="lb"/>{# BedaH,#} etc. should be added: {%Asoka is a tree%}
<div n="lb"/>{#aSoko vfkzaviSezaH.#} </div><div n="I">IV When used distribu-
<div n="lb"/>-tively, (a) expr. by avy. comp. with {#prati,#}
<div n="lb"/>{%or,%} by the repetition of the word in proper
<div n="lb"/>agreement with the verb: {%give%} ({%me%}) <div n="xe">{%500%}
<div n="lb"/>{%sovereign a day%}</div> <div n="xs">{#pratyahaM suvarRapaYcaSatAni dehi,#}</div> <ls>H.</ls>
<div n="lb"/>iii; (b) the simple gen. may be used in
<div n="lb"/>connection with num. adverbs: <div n="xe">{%dinner%}
<div n="lb"/>{%twice a day%}</div> <div n="xs">{#dvirahno Bojanam,#}</div> V. In O. E. some-
<div n="lb"/>-times=on, in, for: q. v.: <div n="xe">{%the world runs%}
<div n="lb"/>{%awheel%}</div> <div n="xs">{#*cakrErjagadDAvati.#}</div></div>
<LEND>
```

**Comment by funderburkjim** [comment]
### Markup particulars, 2

#### `<ls>X</ls>` Partial literary source markup

The original digitization also used the same bold markup `{@X@}` for a few hundred instances of
literary sources.   After checking 'X' with the abbreviations of works appearing in the [front matter](http://www.sanskrit-lexicon.uni-koeln.de/scans/csldoc/dictionaries/prefaces/borpref.html), such instances were converted to the markup `<ls>X</ls>` used in other dictionaries.

So for example `<ls>D.</ls>` marks the mentioned literary source 'Daśakumāra Carita` . There are about
500 such marked sources. This is small fraction of the estimated 13000+ literary source instances.
* The existing markup does not include the roman numerals following, which would be `<ls>D. iii</ls>`,
   where the `iii` appears on the next line in this case.
* Even in the 'A' example one notices several unmarked sources; for example 'Va' ('Vāsavadattā') is unmarked.

#### English-Sanskrit quotation examples
The original markup identified, in a particular way  (lines starting with `.{%`), about 13000 instances
of quotation examples in bor.txt.  For instance, in the 'A' example, the original digitization showed:
```
.{%there is a | large silk-cotton tree on the banks of the Godavari%} | {#asti godAvarItIre viSAlaH 
SAlmalItaruH#} {@H.@} i.; 
```
This markup has been preserved in the conversion, using the xml form
`<div n="xe">{%English%}</div> <div n="xs">{#Devanagari-slp1#}</div>` markup, such as
```
<div n="lb"/>by the singular number alone: <div n="xe">{%there is a%}
<div n="lb"/>{%large silk-cotton tree on the banks of the Godavari%}</div>
<div n="lb"/><div n="xs">{#asti godAvarItIre viSAlaH SAlmalItaruH#}</div> <ls>H.</ls> i.; <div n="xe">{%there%}
```
Note that since the conversion reconstructs the original lines, this div markup spans lines.

It is known that there are some errors in this markup. For instance, in the 'A' example:
```
<div n="lb"/>agreement with the verb: {%give%} ({%me%}) <div n="xe">{%500%}
<div n="lb"/>{%sovereign a day%}</div> <div n="xs">{#pratyahaM suvarRapaYcaSatAni dehi,#}</div> <ls>H.</ls>
```
The xe div should start before 'give me'.

Nonetheless, it was felt that the current markup was a good start at exposing this important part of
the Borooah dictionary.

**Comment by funderburkjim** [comment]
### The display

The display makes very limited use of the markup mentioned:
1) The line breaks of the text are maintained
2) The section identifiers are put in **BOLD**
3) The few 'ls' tags are indicated by slightly different font color.
4) The example markup  (english-sanskrit) is ignored.

It would be possible for the display to reveal much more of the logical structure of an entry.
Such as by using line breaks for subsections, and indentation for the examples.   Also, it would be
feasible to more fully mark the literary source and other abbreviations.
However, I feel that more work needs to be done to extend the accuracy and completeness of the
markup before exposing the markup more fully in the displays.

**Comment by funderburkjim** [comment]
The meta/iast conversion of bor.txt has now been installed at Cologne, and the displays adjusted
accordingly.

**Comment by gasyoun** [comment]
> Also, it would be
feasible to more fully mark the literary source and other abbreviations.

Sure, but this is a dictionary rarely used even in India, so let it be. In Deccan College, everybody has 1 volume of MW and that's it. Nothing more, nothing less - just the paper MW. They seem to never use Cologne, because there is only Intranet and no Internet inside the library, where work is going on the Historical dictionary.
