### ISSUE TITLE
MWE meta/iast conversion

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#214]
This issue for comments related to the meta-line/iast conversion of mwe.txt, the Cologne digitization of `Monier-Williams English-Sanskrit Dictionary`.

**Comment by funderburkjim** [comment]
### IAST issues

Most Sanskrit text within mwe.txt appears in Devanagari. However, there is some usage of Latin alphabet
with diacritics to represent Sanskrit words. This latter text has been converted to a first approximation to
modern IAST. There still remain some cases where this conversion is incomplete, due to difficulty in
programmatic recognition of Sanskrit words which do not, in the printed text, have any diacritics.

One feature which seems odd is the appearance of several Sanskrit words as English headwords, and the
use of diacritics in the spelling.   For example, the headword which we spell as 'sudra' is actually shown with diacritics:
![image](https://user-images.githubusercontent.com/6393033/36707372-0029cd04-1b3c-11e8-8800-bb1c61657536.png)

This word appears between 'sudorific' and 'suds',  Also note the use of the acute accent diacritic to represent the long vowel.  This use of acute accent as diacritic is by far the most common diacritic used.
In the conversion, we've used the macron diacritic which is consistent with current IAST.

![image](https://user-images.githubusercontent.com/6393033/36707566-d6e42290-1b3c-11e8-9fa9-72957773e381.png)

**Comment by funderburkjim** [comment]
### Sections of the book

The digitization includes the front matter, the main body of entries, and the appendix.
Images of the front matter are also available in the [MWE documentation](http://www.sanskrit-lexicon.uni-koeln.de/scans/csldoc/dictionaries/prefaces/mwepref.html).

```
      6:; TITLE
     37:; DEDICATION
     74:; ABBREVIATIONS
    122:; PREFACE
    566:; ENTRIES
 184096:; APPENDIX
```
Note that the Appendix is formatted in the same way as the main body of entries; thus the headwords therein are marked as headwords and their content is available in the displays.  For instance, the headword 'abase' occurs both in the main entries and in the appendix:

![image](https://user-images.githubusercontent.com/6393033/36707756-b65ebc96-1b3d-11e8-8761-8a620cf14085.png)

The abbreviations section could be used to add abbreviation markup `<ab>X</ab>`; this would be a useful enhancement.

**Comment by funderburkjim** [comment]
### Markup particulars

The only markup added is one for line breaks `<div n="lb"/>`.

**Comment by funderburkjim** [comment]
### Headword additions

14 additional headwords were added during the conversion;  these were previously not identifed as separate headwords, due to a small difference in their form.

#### Alternate headwords
There are several alternate headwords which could be identified without too much trouble.
For instance 'dramatical':
```
DRAMATIC, DRAMATICAL¦, {%a.%} {#nAwakIyaH -yA -yaM, nAwakavizayaH -yA -yaM#}
```

### Hyphenated headwords
The current spelling of 'key1' includes several (2340 out of ) headwords with a hyphen.   For instance
'able-bodied'.  Our coding is the same for Borooah ('able-bodied' is also the key1 spelling in bor).

This hyphen retention might be confusing in search -- not clear to me at the moment.

**Comment by funderburkjim** [comment]
The meta/iast conversion of mwe.txt is now installed at Cologne.

**Comment by gasyoun** [comment]
> seems odd is the appearance of several Sanskrit words as English headwords, and the
use of diacritics in the spelling

Agree, we would expect a Shudra with no diacritics at all.

> 14 additional headwords were added during the conversion

This is the most adorable and unexpected bonus of your hard work, Jim.
