### ISSUE TITLE
HxE record type in MW

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#225]
### The problem

There are numerous (~1000) 'etymology' sections at the end of headwords.  In some of these, the
section as previously coded, appears as if part of a sub-headword.  The headword 'hari' provides an example.

```
(H1) hari 2 [p= 1289] : mfn. ( prob. fr. a lost √ hṛ, "to be yellow or green" ; for 1. hari See above, col.2 ) 
fawn-coloured, reddish brown, brown, tawny, pale yellow, yellow, fallow, bay (esp. applied to horses), 
green, greenish RV.  &c. ,&c. [L=260897]
m. yellow or reddish brown or green (the colour) L.  [L=260898]
[MANY MORE LINES]
m. a partic. class of gods under manu tāmasa Pur. [L=260928]
--
(H1B) harī : f. N. of the mythical mother of the monkeysMBh.  ; R.  
[ cf. Lat. holus, helvus, fulvus ; Lith. żálias, żélti ; Slav. zelenŭ ; Germ. ge0lo, gelb ; 
Eng. yellow. ] [L=260929]
```
This form makes it look like the etymology section refers to the feminine form harī ;  but actually
the etymology section refers to the first headword, 'hari'.  This is the problem.

I've noticed this problem before, and recently Peter reminded me of it.

**Comment by funderburkjim** [comment]
### Summary of HxY record types

There are currently three sub-record types that the Cologne digitization of MW employs. These occur
only for substantives (nouns, adjectives, maybe indeclineables).
* HxA  These identify alternate senses of the main headword; same gender information
* HxB  Typically different gender information than the main headword.  
  * example 1 L=260898 in above.  The main headword (260897) was identified as an adjective (mfn.)
     And 'm.' was mentioned for 260898.  Since mfn != m, 260897 was classified as H1B.
  * example 2 L=260929. (H1B) harī : f.  Classified as H1B for similar reason, mfn. != f.
* HxC  headwords from some inflected form.
   * example. (H1C) : अग्रम् ind. in front, before, ahead of [L=1208].   This occurs under headword 'agra'.
      and is an indeclineable formed from accusative singular of 'agra'.

**Comment by funderburkjim** [comment]
### Solution: add an 'E' sub-record type

These etymology sections seem to be quite different from any of the other sections identified as
Hx, HxA, HxB, or HxC.   Since etymology starts with 'e', introducing a record type of 'HxE' seemed fortuitous.

### some untangling required.
Generally, these sections have a certain pattern: 
* They appear within square brackets starting with 'cf.', and
* they contain an `<etym>` tag.

Sometimes such sections appeared as separate HxA,B, or C records.  In such cases, the solution 
just required changing the 'A', 'B', or 'C' to an 'E'.

Often, the sections were at the end of an HxA,B, or C record.  The 'hari' example is like this
 `H1B) harī : f. N. of the mythical mother of the monkeysMBh.  ; R.  [cf ...]'
In such cases, the etymology part was removed, and inserted into a new record:
 Original digitization:
```
<L>260929<pc>1289,3<k1>harI<k2>ha/rI<e>1B
<s>ha/rI</s> ¦ <lex>f.</lex> <ab>N.</ab> of the mythical mother of the monkeys, <ls>MBh.</ls>; 
<ls>R.</ls>[<ab>cf.</ab> <ab>Lat.</ab> <etym>holus</etym>, <etym>helvus</etym>, 
<etym>fulvus</etym>; <ab>Lith.</ab> <etym>żálias</etym>, <etym>żélti</etym>; <ab>Slav.</ab> 
<etym>zelenŭ</etym>; <ab>Germ.</ab> <etym>gëlo</etym>, <etym>gelb</etym>; <ab>Eng.
</ab> <etym>yellow</etym>.]<info lex="f"/>
<LEND>
```
Result after splitting:
```
<L>260929<pc>1289,3<k1>harI<k2>ha/rI<e>1B
<s>ha/rI</s> ¦ <lex>f.</lex> <ab>N.</ab> of the mythical mother of the monkeys, <ls>MBh.</ls>; 
<ls>R.</ls><info lex="f"/>
<LEND>
<L>260929.1<pc>1289,3<k1>hari<k2>hari<e>1E
<s>hari</s> ¦ [<ab>cf.</ab> <ab>Lat.</ab> <etym>holus</etym>, <etym>helvus</etym>, 
<etym>fulvus</etym>; <ab>Lith.</ab> <etym>żálias</etym>, <etym>żélti</etym>; <ab>Slav.</ab> 
<etym>zelenŭ</etym>; <ab>Germ.</ab> <etym>gëlo</etym>, <etym>gelb</etym>; <ab>Eng.
</ab> <etym>yellow</etym>.]
<LEND>
```

**Comment by funderburkjim** [comment]
### conclusion:
There are 716 records with the 'HxE' markup.

There are 84 records where `<etym>` tag occurs outside of an 'etymology section' (i.e., not in an HxE
record).
  
[This gist](https://gist.github.com/funderburkjim/ebe2eabbc53cb46202fa3d7371beae05) contains
two files relevant to this work:
 
* etymnote.txt  identifies the 84 record set by headword and record number.
* etymrec.txt provides the full digitization text of all the 716 records with HxE markup.
   * The data appears twice, in the old/new format useful for corrections.
   * It is hoped that someone (@gasyoun ?) will examine these for corrections, notably for
      the diacritics in the various European languages represented.

**Comment by gasyoun** [comment]
> three sub-record types

So many things to learn. One can write a book on MW encoding alone.
