### ISSUE TITLE
Burnouf root convention

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#228]
Caujolle pointed out that Burnouf dictionary uses an initial '*' before a headword to indicate that the
entry is for a root.  There are 1989 instances according to the digitization. First example is
![image](https://user-images.githubusercontent.com/6393033/41438496-70fcfe76-6ff5-11e8-8c92-75e10ba1f76a.png)

This factoid of interest when we tackle a root-correspondence tabulation some time.
Also, Caujolle found it obscure.  This would be worth some kind of tooltip markup.

**Comment by gasyoun** [comment]
> '*' before a headword to indicate that the
entry is for a root.

This is for me.

> root-correspondence tabulation

Exactly, something like my PhD supplement once was https://yadi.sk/i/AFZFsMBHcSYsN

**Comment by funderburkjim** [comment]
### Additional Burnouf conventions

The page of abbreviations [[see](http://www.sanskrit-lexicon.uni-koeln.de/scans/csldoc/dictionaries/prefaces/burpref/burpref08.html)] provides, in addition to the root-marking convention, several other markup conventions that might be of interest from time to time.
@sanskritisampada provides this English translation of those comments.

```
- Asterisk place on top of a word indicated a root.
- The number marked immediately after a verb indicates the class.
- A word in parantheses () indicates a verb or a compound word.
- The brackets [] indicate an explanation.
- The horizontal bar _ separates the words in the same article
(i think this means sentence in the context).
- The vertical double bar || separates different meanings of the same word.

After a word is written in devanagarI, we have arranged those of its derivations and compounds which were found placed immediately after it acc to Alphabetical order. The other derivatives or compounds,which were away from immediate proximity to the main word, are arranged in their natural order. Thus, the alphabetical order is always observed.

Note: In the Sanskrit words printed in Italics, we never use capitals, even in case of proper nouns, as Indian writing doesn't permit capitalisation.
```
