### ISSUE TITLE
Include Transliteration scheme

### ISSUE THREAD

**Issue by Shalu411** [sanskrit-lexicon/COLOGNE#23]
Namaste
http://www.sanskrit-lexicon.uni-koeln.de/scans/SKDScan/2013/web/webtc2/index.php
Could it be possible to include a link to "Transliteration help" on every search-page of all Cologne Dictionaries? Please ..atleast for letters like ङ, ञ, ण, ऋ, which are not "obvious" for users..?

**Comment by drdhaval2785** [comment]
Help and Corrections are on all displays. Closing.
