### ISSUE TITLE
Display code unification

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#231]
This issue to document and solicit comments regarding work done towards unification of the Cologne code which generates the various displays (basic, list, advanced search, mobile1) for the various dictionaries.

A [websanlexicon](https://github.com/funderburkjim/websanlexicon) repository contains the code.

The readme.md in that repository states the basic idea:   Maintain the code in template form, then
install the template to each dictionary's code base.   
So one set of templates applies to all the dictionaries; when the templates are rendered to
the code for a particular dictionary X,  the resulting code contains any peculiarities for the given
dictionary   (such as dictionary name,  how `<div>s` are rendered, etc. etc.) on the basis of some
parameters governing the rendering.

I'll elaborate on this idea later.

Currently, all the 4 displays (basic, etc.) at Cologne have been generated  from the templates for these
8 dictionaries:   gra, bur, cae, stc, pwg, mw, skd, and ae.

Sometimes users will need to refresh caches  (e.g. by the Ctrl-F5 trick @gasyoun mentioned somewhere).

Over the next few weeks, I hope to finish the installation for the other dictionaries.

**Comment by gasyoun** [comment]
> Over the next few weeks, I hope to finish the installation for the other dictionaries.

So that's where you were lost, amazing work. I wish to contribute to the UI, I'll get there one day.

**Comment by drdhaval2785** [comment]
Wonderful. Pieces of puzzle falling in place. Saw the templates and code. Does not seem too much of work to customize for individual dictionaries.

**Comment by funderburkjim** [comment]
### v00 completion

All the 4 displays (basic, etc.) at Cologne have been generated from the templates for *all* 36 of the dictionaries.   This first subgoal of code unification now complete.

**Comment by funderburkjim** [comment]
### apidev next

The displays (such as http://sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/simple-search/v1.0/list-0.2s.html) currently use a separate sqlite database.  For example, when mw is the dictionary, the simple search display uses the mwhtml.sqlite database.  By contrast, when a basic display is used, the mw.sqlite database  (containing just the mw.xml data) is used.    

But now that we have one code base for generating html from xml for all dictionaries, we don't need the intermediate Xhtml.sqlite database --  we can just generate the html from xml at run time.

There is currently at cologne a 'shadow' apidev which functions just as described -- generating the html at run time from X.sqlite for dictionary X.   Based on work done with a small number of dictionaries a couple of weeks ago, my expectation is that completing the conversion of the apidev code to the new regime will be ready shortly.   One minor benefit is that the separate Xhtml.sqlite files will not be needed then; this will free up some space at Cologne.

**Comment by funderburkjim** [comment]
### Advanced Search

One side benefit of the display conversions is seen in the Advanced Search display.   Specifically, it is now possible to search for non-Devanagari text where there is a diacritic.  For example, suppose you use advanced search for Wilson dictionary, look up Sanskrit word 'guru', and notice the word 'Uṇādi' in the Etymology section, and want to see other examples of this word.  You can copy-paste 'Uṇādi' in a 'Text word' search and get many results.   By contrast, in the previous version, the presence of the extended ascii characters `ṇā` would have resulted in no matches.    Or suppose you are in MW and notice in the entry for deva the literary source reference 'Divyâv'  (Divyâvadāna) ;  you can paste 'Divyâv' in a 'Text word' search and get other entries with this reference.

**Comment by funderburkjim** [comment]
### Capitalization correction in advanced search

When searching for a 'text word'  (i.e., a word that is not a Sanskrit headword, and not a word appearing in Devanagari in the print),  the case of the letters in the word is ignore. This case-ignoring is done when generating the index of words that the advanced search query examines, and the technique used is to save only the lower-case form of the word in the index.  At query time, the user's query must also be lower-cased.   So for instance, if the user enters (e.g. by copy-pasting) the query `Śiva`,  this word
is converted to lower-case `śiva` and then the index is search for this lower-case form, and the matches
returned and displayed.

Until today, there was a bug in the query program, which had the effect of returning no matches (e.g. in MW) for `Śiva` while returning many matches for `śiva`.   

After a debug session (done with the MD dictionary), a solution to the bug was found, and a change to one of the program pieces (querymodel.php) was made.  This solved the problem for MD.   

But the nice thing is how easy it was to extend the solution to MW and all the other dictionaries.
The procedure was to make the change in the template for querymodel.php.  Then a script (redo_cologne_all.sh) was run which installs the latest revision of the displays for all the dictionaries  (script takes less than a minute to run).  

This is a good example of a benefit of code unification.

**Comment by gasyoun** [comment]
> This is a good example of a benefit of code unification.

After years of hard work, the fruits start coming in.

> separate Xhtml.sqlite files will not be needed then; this will free up some space at Cologne.

Less clutter as well. Next maybe we can have clickable URLs for each headword?

**Comment by funderburkjim** [comment]
### apidev
The other piece of the Cologne dictionary displays is governed by code in the 
scans/awork/apidev directory; this includes the simple-search:
http://sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/simple-search/v1.0/list-0.2s.html

This code has now been altered so it builds on the code of websanlexicon.  This apidev code is 
in the https://github.com/funderburkjim/apidev  repository.  

This code is also 'live' at the Cologne website.

### apidev extends websanlexicon
Previously, apidev gathered its data from an intermediate sqlite file, such as mwhtml.sqlite.  Essentially,
when there was some change to the data for a  given dictionary X, there would be two sqlite files
constructed:  
* X.sqlite  has data corresponding to X.xml, and
* Xhtml.sqlite has records of precomputed html (i.e., a record Xhtml.sqlite was the BasicDisplay html
   for the corresponding record of X.xml).

This was required to take into account differences among dictionaries in the xml->html transformation
of the basic display.

Now, since one program handles this transformation for each dictionary, there is no need for the 
Xhtml.sqlite file.  Programs such as simple search can instead construct the html on the fly from the
xml information of X.sqlite.

### Relation between apidev and websanlexicon
As currently written,  when there is a change in any of a few websanlexicon modules,
these modules need to be 
* copied to apidev
* In a few cases, altered slightly.

As the apidev system matures,  we will probably learn how to write a script that automatically
updates apidev from websanlexicon, but currently this is manual.  The few steps are described in
the api section at bottom of [readme_cologne.org](https://github.com/funderburkjim/websanlexicon/blob/master/readme_cologne.org)
