### ISSUE TITLE
MW Advanced view - new bug

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/Cologne#235]
# Setup
Windows
firefox
desktop version

# Steps to reproduce the problem
1. Write 'va', 'prefix', 'all'
2. Till 7th entry 'vaMSI' everything works fine.
3. When I click on 'vaMSafzi', it sh ows 'vaMSa'. When I click on 'vaMSakaWina', it shows 'vaMSA' etc.
Thereafter the order seems erraneous.

# Problem
1. Point mentioned above regarding disconnect between the clicked word and displayed word.
2. The alphabetic order seems to be haywire somewhere. varha, valAhaka, vakAra and vakAraBeda seem to be before 'vaMSa' which is not the correct alphabetic order.

@gasyoun may verify
and @funderburkjim may try to correct the algorithm. It seems to be related to the upgradation of certain words to headword status.

**Comment by funderburkjim** [comment]
Solution found.

files changed: 
* [query_gather.php](https://github.com/funderburkjim/websanlexicon/blob/master/v00/makotemplates/webtc2/query_gather.php)
* [query_multi.php](https://github.com/funderburkjim/websanlexicon/blob/master/v00/makotemplates/webtc2/query_multi.php)

The solution made changes in the websanlexicon directory, and in turn these changes have been
propagated into the display code for MW , as well as the other dictionaries.

This problem only arises in MW when the matching set of words for an Advanced Search
contained MW headwords with a particular property.   vaMSa is such a headword:
![image](https://user-images.githubusercontent.com/6393033/45249005-b42efa80-b2e6-11e8-95a6-e1310c1dfef6.png)

In the Cologne digitization,  the key1 value for two subwords of vaMSa are vaMSA and vaMSI:
```
<L>184174.1<pc>910,1<k1>vaMSA<k2>vaMSA/<e>1B     <<< Note the B in 1B
<s>vaMSA/</s> ¦ <ab>N.</ab> of an <s1 slp1="apsaras">Apsaras</s1> (daughter of <s1 slp1="prADA">Prādhā</s1>), <ls>MBh.</ls>
<LEND>
<L>184175<pc>910,1<k1>vaMSI<k2>vaMSI<h>a<e>1B
<s>vaMSI</s> <hom>a</hom> ¦ <lex>f.</lex> See <ab>s.v.</ab><info lex="f"/>
<LEND>
```

The intended logic of the display for vaMSa  shows these subrecords along with the rest of the
vaMSa subrecords.
Also, the logic of the display for vaMSA and vaMSI  similarly shows all the vaMSa records.
For vaMSA there are no other records in the dictionary other than the one subsidiary to vaMSa.
Thus, in the advanced search, the records displayed for vaMSA are the same as for vaMSa.
For vaMSI,  the records displayed are those of vaMSa, as well as another entry with
records having cologne ids 184318-22.
![image](https://user-images.githubusercontent.com/6393033/45249207-150c0200-b2ea-11e8-913f-5b57b1b651da.png)

The reason that there were repetitions for vaMSa, vaMSA, vaMSI in the Adv. Search display is that
the subsidiary records (L=184174.1 and 184175) were being treated as independent entries, rather
than as subrecords of vaMSa.

The program change in query_gather added an extra field (the major headword).  And the 
program change in query_multi  made use of this extra field.  Together, these two changes provide
a solution to the problem.

### another cosmetic improvement in output
Another change was made, which in effect inhibited unnecessary display of the printed page links:

BEFORE the change:
![image](https://user-images.githubusercontent.com/6393033/45249165-71225680-b2e9-11e8-8fec-01e4cc615ba8.png)

AFTER the change:
![image](https://user-images.githubusercontent.com/6393033/45249178-a8910300-b2e9-11e8-91f6-88300ff3193f.png)

**Comment by gasyoun** [comment]
A simple and working explanation, thanks.

**Comment by funderburkjim** [comment]
Looks like this can be closed.
