### ISSUE TITLE
MW Advanced Search, another Bug

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#236]
Here is a bug in Advanced search which Odile mentioned.

![image](https://user-images.githubusercontent.com/6393033/48093909-a90d2380-e1de-11e8-9eb9-8137c66d31bb.png)

**Comment by funderburkjim** [comment]
The problem is that the same word shows up multiple times.   The above display shows this duplication
in the left pane of the display.  But it also occurs in the right pane.

Part of the reason is that there are multiple HX entries for viz, in this case L=145348.1, L=200376, and L=ID=200387.

But the problem is a little more complicated.  For example, it occurs with 'agre' also.

**Comment by funderburkjim** [comment]
The problem is not restricted to MW.

For instance, in PWG with the same search (viz - HK),  there are two duplicates.

**Comment by gasyoun** [comment]
It's not new as well, years ago.

**Comment by funderburkjim** [comment]
### bug fixed
Here's the 'viS' example from above -- now the duplicates are gone.

![image](https://user-images.githubusercontent.com/6393033/48456102-c5cfcb00-e78b-11e8-8468-1a3d22bfe0de.png)

**Comment by funderburkjim** [comment]
Also made two other changes, per suggestions from Odile:

### remove the beige shading

BEFORE:

![image](https://user-images.githubusercontent.com/6393033/48456266-62926880-e78c-11e8-8c6e-11ce48e6930c.png)


AFTER:

![image](https://user-images.githubusercontent.com/6393033/48456329-a71e0400-e78c-11e8-860a-32f1aa51c891.png)

**Comment by funderburkjim** [comment]
### Added light gray shading to Basicdisplay, etc. for MW

This is similar to what has been present in the  apidev-based displays, such as simple search. But
now it is in Basic, etc.   The example shows a search for the feminine amAvAsyA.  This occurs as
one of the sub-sections of noun headword amAvAsya.  The  shading is a visual clue to  the subsections that *don't* pertain to the amAvAsyA, so the user will be less likely to think that 'neighborhood' is
the first meaning for amAvAsyA.

BEFORE:  no shading

![image](https://user-images.githubusercontent.com/6393033/48456637-bd788f80-e78d-11e8-9cc8-5ad10b62bb33.png)

AFTER: gray-out the parts not about amAvAsyA.

![image](https://user-images.githubusercontent.com/6393033/48456688-f6b0ff80-e78d-11e8-96f0-365f9d0bb4fd.png)

**Comment by funderburkjim** [comment]
### Bold 'Caus.' ,etc for MW

For many verbs in MW,  there are distinct subsections pertaining to the Causal, Desiderative or Intensive forms of the verb.  The displays already distinguished these sections by a line break.  But now there is the further distinction by displaying the abbreviation (Caus. , etc.) in Bold type.

Here's an example with root 'mad'.

BEFORE:

![image](https://user-images.githubusercontent.com/6393033/48457048-42b07400-e78f-11e8-9899-edbec66084a8.png)

AFTER:

![image](https://user-images.githubusercontent.com/6393033/48457086-5f4cac00-e78f-11e8-8a5c-a9b1f10ef559.png)

**Comment by funderburkjim** [comment]
### Changes applied to all dictionary displays

The changes in advanced search (no dups) and the removal of shading behind ID=xxx, etc. are evident in all dictionaries.  The other changes only affect MW -- this is primarily because the markup of the other dictionaries is less extensive than in MW.

**Comment by gasyoun** [comment]
Well done and important visual improvement.
