### ISSUE TITLE
Websanlexicon and apidev

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#238]
In the previous issue, it was noted that a bug in advanced search display, noticed for the MW dictionary, was fixed not only for the MW dictionary, but for the other dictionaries as well.

The reason that it was possible to quickly apply the fix to all the dictionaries has to do with the way the web display code is now generated.

The [websanlexicon](https://github.com/funderburkjim/websanlexicon) repository is the key.  I thought it might be useful for others to have an idea of what is in this repository and how it relates to the web displays for the individual dictionaries.

**Comment by funderburkjim** [comment]
### websanlexicon templates

The main part of websanlexicon contains the display code *in the form of templates*.

In fact, this [templates subdirectory](https://github.com/funderburkjim/websanlexicon/tree/master/v00/makotemplates) contains the code for the displays, but in a template form.   

To understand the template idea, just think of the basic display for two dictionaries, MW and PWG.

MW

![image](https://user-images.githubusercontent.com/6393033/48458256-8907d200-e793-11e8-96dd-f4f1618ef860.png)

PWG

![image](https://user-images.githubusercontent.com/6393033/48458485-86f24300-e794-11e8-9039-0f4bbb8f71dd.png)

**Comment by funderburkjim** [comment]
### indexcaller.php template

Here is the [indexcaller.php](https://github.com/funderburkjim/websanlexicon/blob/master/v00/makotemplates/webtc/indexcaller.php) template in websanlexicon.

The line pertaining to the dictionary name is, in the template file,
```
        <span id="title">${dictname}</span>
```

 `${dictname}` is a placeholder for the dictionary name.

The details of the syntax  (the `${XYZ}` form) is specific to the template engine being used; in the
case of websanlexicon, the template engine is a Python library called [mako](https://www.makotemplates.org/).

### code generation

[generate.py](https://github.com/funderburkjim/websanlexicon/blob/master/v00/generate.py) is used to generate the code files from the templates.

A sample invocation, for mw dictionary, is
```
python generate.py mw inventory.txt  makotemplates ../../MWScan/2014/web
```
When this program runs, it uses the dictionary code to get the values of various parameters, such as `dictname`.  

All these dictionary specific parameters are in module [dictparms.py](https://github.com/funderburkjim/websanlexicon/blob/master/v00/dictparms.py).

If you look at this dictparms file, you'll see the dictionary name associated with 'mw' and with 'pwg'.

### redo_cologne_all.sh
When the correction to advanced search was made,  it was made in one of the websanlexicon templates pertaining to advanced search, namely [querymodel.php](https://github.com/funderburkjim/websanlexicon/blob/master/v00/makotemplates/webtc2/querymodel.php).
After debugging this on local computer, the changes were pushed to the websanlexicon directory.
Then, on Cologne server, the changes were pulled from the Github websanlexicon directory to the Cologne repository.
Finally, to propagate these changes to *all the displays*, a single script, [redo_cologne_all.sh](https://github.com/funderburkjim/websanlexicon/blob/master/v00/redo_cologne_all.sh) was run to update the displays for all the dictionaries.

**Comment by funderburkjim** [comment]
### templates not the whole story
Currently, there are some parts of the displays that
a. vary from one dictionary to another
b. the variation is not captured by template variables (like dictname), but rather
    by code that depends on the dictionary code.

A good example of this is [basicadjust.php](https://github.com/funderburkjim/websanlexicon/blob/master/v00/makotemplates/webtc/basicadjust.php).  In this there are numerous 'if' statements that depend on the dictionary code, such as:
```
if (in_array($this->getParms->dict,array('pw','pwg'))) { 
  DO SOMETHING different for pw and pwg dictionaries
}
```

Over time, we will probably be able to reduce this variability by further reduction of differences among the xml forms of the dictionaries.

But at least, even in such code, the places of difference among the dictionaries is made obvious, and thus manageable.

**Comment by funderburkjim** [comment]
### apidev

There is another class of displays, such as [simple search](http://sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/simple-search/v1.0/list-0.2s.html).  These use code which assumes the dictionary is determined by the user.   

### built on top of websanlexicon
The displays are built on top of the websanlexicon code.  Thus, there is some degree of 
consistency between the displays of apidev and the Basic and other displays of the individual 
dictionaries.  
For instance, the 'bolding of Caus.' change that was made in the websanlexicon-based displays (Basic, etc.), also flow through to the apidev displays.

Essentially, the purpose of the apidev code is to provide an api on which to build other user interfaces to the dictionary displays.   

Much more could be said about apidev, but perhaps another day.

I hope this overview will give interested readers an idea of what is involved on the *other side*.

**Comment by gasyoun** [comment]
> The websanlexicon repository is the key.

Yes, of greatest importance.

> constructed from three main parts:

Crystal clear now.

> template engine is a Python library called mako.

Was not aware of.

> Much more could be said about apidev, but perhaps another day.

And must. I still do not even understand how to easily send a link to an entry to someone else.

>  experience in good CSS practices

A grain of salt, accepted. I even keep a tab in my Chrome open to get there in 2019.

**Comment by drdhaval2785** [comment]
csl-websanlexicon and csl-apidev are working fine.
