### ISSUE TITLE
Scharf's Derivations

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#239]
Peter has some preliminary work regarding derivations of words on Paninian principles.

This is above my pay grade, but thought it might be of interest to @drdhaval2785 or @SergeA.

The link is https://sanskritlibrary.org/derivation.html.

**Comment by gasyoun** [comment]
1994 design - but good to see for sure, thanks, did not notice before.
![linga](https://user-images.githubusercontent.com/80761/48761523-e3d08a80-ecb9-11e8-87d9-608116b5dd2c.PNG)

**Comment by drdhaval2785** [comment]
The underlying workhorse is his 'XML formalization of Ashtadhyayi'. Paper was published in 2015. Seems to have reached its culmination now.
