### ISSUE TITLE
Add "Previous" Button in advanced search

### ISSUE THREAD

**Issue by Shalu411** [sanskrit-lexicon/COLOGNE#24]
Namaste
This is regarding the Advanced search page (of any Cologne dictionary) -
When I search, I give option for 20 maximum and if more are there, then results appear as soon as I press "next" button. When results are two or three pages, its fine. I can go back with repeating to press "search" button. If there are more, then it is problem because you cannot go back to the previous 20-list and that's because of no "previous" button. Once you are at the end page, then no way going to first.
So - Can you add "previous" button too?
Thankyou

**Comment by drdhaval2785** [comment]
Now we have 1000 items per search. Issue of previous, next does not survive.
