### ISSUE TITLE
Cologne server https

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#240]
If you use the Chrome browser, you may have noticed this annoying aspect when using the Cologne sanskrit-lexicon site:

![image](https://user-images.githubusercontent.com/6393033/48731586-5fbfc980-ec0b-11e8-986b-398549faade1.png)

Another problem is that links to http://www.sanskrit-lexicon.uni-koeln.de/   from *some* https://
sites do not work.   
* This has something to do with the way the https site is set up.  For instance, the above link DOES 
   work, and it is coming from 'https://' site.  
* But, in general, it is a problem that https: protocol is not established at Cologne.

**Comment by fxru** [comment]
Let me know if you need local support for the SSL issue.

**Comment by gasyoun** [comment]
> annoying aspect when using the Cologne sanskrit-lexicon site:

Yeah, that's a rather new one.

> I asked Patrick

Please add more details - surname, email or whatever. For a case of emergency.

**Comment by funderburkjim** [comment]
surname is Holz.  You could get contact details from @fxru.

**Comment by funderburkjim** [comment]
@fxru 

Since Patrick approved the above as a strategy for preparing for https activation, I feel fairly confident that this will be adequate.   You might ask some other IT contact if anything else is needed.

I'm almost through making the 'http://' to '//' change everywhere on the site  (This work being done
in the docs/http/httpwork directory, if you want to look).  

When I've finished making all these changes,  I'll mention it here.   Then I'll notify Patrick that he can
go ahead with the activation.   My thought at the moment that I would request this be done 
Monday, November 26, 2018.   (on a Monday so IT support staff will be available in case of some
unforeseen problem).   

Do you want me to wait while you review this with 'local support' ?

**Comment by funderburkjim** [comment]
@fxru 

DId you see the [comment re gra](https://github.com/sanskrit-lexicon/GRA/issues/2#issuecomment-438099803) ?   I'm waiting for your confirm of changes before requesting space at Cologne for
the revised Documentation.

**Comment by funderburkjim** [comment]
### curl doesn't like protocol-relative

In the process of making changes from 'http://' to the protocol-relative form '//',
happened to encounter an instance of 'http://' used within a curl statement (such as in [dictionary_init.sh](https://github.com/sanskrit-lexicon/Cologne/blob/master/enhancements/code/dictionary_init.sh)).

Discovered, when running in a GitBash terminal on local Windows computer:
```
 curl -O "http://s3.amazonaws.com/sanskrit-lexicon/blobs/inmweb1.zip"    WORKS
 curl -O "https://s3.amazonaws.com/sanskrit-lexicon/blobs/inmweb1.zip"    WORKS
BUT
 curl -O "//s3.amazonaws.com/sanskrit-lexicon/blobs/inmweb1.zip"    DOES NOT WORKS

curl complains: fails with 'curl: (3) <url> malformed'

```

I doubt if this will have any impact on the Cologne conversion to https;
 but it does provide an instance where protocol-relative fails.

**Comment by funderburkjim** [comment]
### protocol relative work finished

All in all, approximately 11,000 files were found (among the Cologne sanskrit-lexicon files) which had
'http://'.  Almost all instances of 'http://' in these files were changed to the protocol-relative '//'.

There were a few exceptions, notably where the files were not in utf-8 encoding, where the change was
not made; but visual examination of the files makes me fairly certain that these files do not come up
as endpoints in any *current* displays.

So, preparation for https conversion seems complete.

**Comment by gasyoun** [comment]
> Holz. You could get contact details from @fxru.

Thanks.

> I doubt if this will have any impact on the Cologne conversion to https;
but it does provide an instance where protocol-relative fails.

Exactly.

> in Chrome that the connection is “not secure” for a simple dictionary page is more fear-mongering than actually helpful

So it does increase SSL sales :)

**Comment by funderburkjim** [comment]
### https activation Monday

Patrick is going  make the site available by either http or https on Monday, Nov 26, 2018.

**So keep your eyes open for any problems after Monday!**

After a few days, if all looks well,  Patrick plans to make the site pure https, but with a redirect
of http to https.

**Comment by funderburkjim** [comment]
### https conversion complete

Patrick notified me of this yesterday.
As far as I can see, everything is working properly.  O
http:// links still work, as they get rerouted to https.

**Comment by gasyoun** [comment]
> http:// links still work, as they get rerouted to https.

Works perfectly.

![ss](https://user-images.githubusercontent.com/80761/49671310-8047aa80-fa78-11e8-9acc-173e99fd001c.PNG)
