### ISSUE TITLE
Glob feature of Advanced Search

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#241]
A user suggested an enhancement to the Advanced Search displays.

The idea is to allow the '*' character to represent a sequence of characters.
So `up*ga`  should match any headword starting with 'up' and ending with 'ga'.

This use of '*'   reminds me of what is called 'globbing', which is used in Unix  usually for
generating lists of filenames --  such as `ls *.txt`  are all files ending in `.txt`.

It is also similar to '.*' in regular expressions.

I don't see how to implement this at the moment.   Perhaps someone will have a good idea.

The [querymodel.php](https://github.com/funderburkjim/websanlexicon/blob/master/v00/makotemplates/webtc2/querymodel.php) file, in particular the 'match_Sanskrit' function, would be the place to start.

The main objective would probably be construction of the `$search_regexp` string.  

It might be that a 'glob' search option (in addition to 'exact', 'prefix', etc.) should be added, so the glob feature would not commingle with the other search options.

**Comment by gasyoun** [comment]
Wildcard search, any idea @amordvinov ?

**Comment by drdhaval2785** [comment]
Acceidentally, this feature is there nowadays.

**Comment by funderburkjim** [comment]
Yes, it is in the code.   But it still has status as an 'alpha' stage of a potential enhancement.

Someday hope to revisit the 'glob' idea and its companion the 'keydoc' idea.
