### ISSUE TITLE
AP90 - Single hyphen, double hyphen

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/Cologne#255]
One user raised a query why there is only one hyphen before ISvarA and two before ISvarI?
Under headword ISvara.
![screenshot_20190217-073853_chrome](https://user-images.githubusercontent.com/5755132/52907420-50423200-3287-11e9-9674-8d437382a5de.jpg)

**Comment by gasyoun** [comment]
> one hyphen before ISvarA and two before ISvarI?

As I remember @funderburkjim he is not aware of why if any sense at all.

**Comment by drdhaval2785** [comment]
If there is no method to the madness, let us not spend time inventing one.
