### ISSUE TITLE
Alternative approaches to corrections for Cologne Sanskrit Lexicon

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#26]
While the 'Corrections' button and the associated Google correction form has some good features regarding the general problem of correcting the various digitizations available at the Cologne Sanskrit Lexicon, it also has some limitations.
The major limitation is that there is a bottleneck between the user who notices a correction that needs to be made, and the actual integration of the correction into the digitization.  
Wouldn't it be better if the digitizations were available in a form where a user could directly make corrections?
This thought leads quickly to the idea of a wiki form of the digitizations, since a wiki permits someone to change data via a browser interface.
There is a branch of wikipedia, called wikisource: https://wikisource.org/wiki/Main_Page ,
whose aim is to facilitate the creation of  digitizations and the validatation of them against scanned sources.  Click on the 'help' button on the wikisource page to get a lot of info on HOW TO.  
Other provocative links are http://en.wikisource.org/wiki/Sanskrit_Grammar
and https://sa.wikisource.org/ .
There is a substantial amount of infrastructure already developed at wikisource.
The purpose of opening this issue is to suggest that others think about this approach.
There are many potential obstacles to realizing such an approach. 
Do others think this approach should be pursued?

**Comment by gasyoun** [comment]
@funderburkjim Can we upload all, not just 5 pages to wiki now, or it's a big task?

**Comment by drdhaval2785** [comment]
This question has remained under discussion for quite some time. But the fact remains that we have not seen many real contributors for corrections. Having a correction submission interface which talks directly to Cologne data makes more sense as of now.

**Comment by funderburkjim** [comment]
## dokuwiki lost to spammers

One of the Cologne webmasters noticed that the dokuwiki had been heavily infested with spam.

I deleted it.

All the beautiful documentation therein is gone.

Sigh!

**Comment by funderburkjim** [comment]
## dokuwiki text restored 

One of the Cologne webmasters was able to restore from backup most of the dokuwiki text. 👍 
I've gathered it into a single file [dokuwiki.org](https://github.com/funderburkjim/testing/blob/master/dokuwiki/dokuwiki.org).

Certainly most of the material was thus recovered.   Thank you webmaster!

**Comment by gasyoun** [comment]
>  gathered it into a single file dokuwiki.org.

Good that not everything is gone. So Github remains the place #1 or sphynx for documentation?

**Comment by funderburkjim** [comment]
Do you think we should try Github wiki for this documentation, or maybe we should use the existing csl-doc repository ?

**Comment by gasyoun** [comment]
> Github wiki for this documentatio

Have never tried. Guess it should do the job.

**Comment by funderburkjim** [comment]
Any idea whether Github wiki less likely to be contaminated by spam?

**Comment by drdhaval2785** [comment]
Even if it gets spammed, it would be github's lookout and not ours I guess.

**Comment by drdhaval2785** [comment]
We have dumped the github wiki, dokuwiki and wikisource ways right now. 
Is my understanding correct, @funderburkjim ?

**Comment by funderburkjim** [comment]
Agree -- We don't use wikis at all for corrections currently.
