### ISSUE TITLE
hiatus

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#260]

**Comment by funderburkjim** [comment]
Youngsinn asks the following question:

```
I am having difficulty. When I type 'prauga' to get the meaning of it, MW displays the following:

(H1) [Cologne record ID=141343] [Printed book page 714,3]
प्रौग w.r. for प्रउग, MānGṛŚrS

Can you please help how to actually display the meanings of प्रउग in MW?
```

Youngsinn normally spells words with the HK transliteration.   The question points up a deficiency in HK.
Namely, 'au' in HK  is the long diphthong  (slp 'O', long form of 'o').

Similar problem would arise if using HK to represent hiatus 'ai'  (SLP 'E', long form of 'e').

AFAIK,  there is no generally accepted solution for HK to represent hiatus 'au'  or 'ai'.
However, SLP1 does not have any problem here.   Since SLP1 has separate representations for the long diphthongs O and E,  the spellings 'au' and 'ai' in SLP1 represent the hiatuses.

So, solution is to use SLP1 spelling when doing such a search.

Here is the 'prauga' example with input method SLP1:
![image](https://user-images.githubusercontent.com/6393033/57651705-ee4e4b80-759b-11e9-9e94-b00ec0490276.png)

**Comment by gasyoun** [comment]
> SLP1 spelling when doing such a search

Agree. SLP1 is the only way, HK can not solve this task.

> AFAIK, there is no generally accepted solution for HK to represent hiatus 'au' or 'ai'.

Yes, it is so.

**Comment by drdhaval2785** [comment]
It is encoding issue. SLP1 can handle this case, and HK can not.
Closing this.
