### ISSUE TITLE
Revise homepage

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#262]
Here are a couple of suggested minor revisions to Cologne home page.

1.  Jim Funderburk (jfunderb@uni-koeln.de) and Dr. Dhaval Patel (dpatel2@uni-koeln.de) maintain this web site.
2.  Change date last revised.
3.  Mention at the top a link to how to get Android versions of dictionaries.

This might be good second exercise for @drdhaval2785 .

**Comment by gasyoun** [comment]
Indeed it is. Jim, is there a biography anywhere? I would want to read it, if it is. And ask to write it, if there is none. I do now know nothing about you and not that I would want to leave it that way.

**Comment by funderburkjim** [comment]
Use sanskrit-lexicon version of homepage.

a) I suggest we name the sanskrit-lexicon repositories that are functionally part of Cologne codebase with the prefix 'csl' .   
b) In particular, we would rename 'sanlexhome'  repository to (for instance) 'cslhomepage'.
c) In 'scans/awork/homepage' directory at Cologne, the git repository 'origin' should be changed to
    'cslhomepage' [There is some git command to do this]
d) The  [homepage wiki documentation](https://www.sanskrit-lexicon.uni-koeln.de/doc/dokuwiki/doku.php?id=slfiles:docs:scans:awork:homepage) should be revised  to use 'cslhomepage' instead of 'sanlexhome'.  And the TODO can be

**Comment by gasyoun** [comment]
> 'cslhomepage'

'csl-homepage' for this samasa?

**Comment by funderburkjim** [comment]
> what non-CSL remains?

websanlexicon and apidev for sure.

Also, when we reorg the individual dictionaries, we *may* want to have csl-mw, csl-pwg, etc.  These dictionary repositories haven't been decided yet, but they were also what I was thinking of.

**Comment by funderburkjim** [comment]
### spelling of csl repositories

 @gasyoun  wrote above 'csl-homepage' : i.e. to spell the name of the repository in sanskrit-lexicon with the prefix 'csl-'  (note '-').    Are there any technical problems for having a '-' in a repository name ?
If not, I agree that prefix 'csl-' is more readable than 'csl' (no '-').
@drdhaval2785   Any opinion on this detail?

**Comment by drdhaval2785** [comment]
Our organization 'sanskrit-lexicon' itself has a hyphen in it.
I have used a private repo with two hyphens in its name
'sanskrit-lexica-ocr'.
There is not a single problem I faced from windows, ubuntu, archlinux, git
or github.

I am not sure about afs file system on Cologne server though. If that is
not behaving oddly with hyphens, we are good to go.

**Comment by drdhaval2785** [comment]
>    Jim Funderburk (jfunderb@uni-koeln.de) and Dr. Dhaval Patel (dpatel2@uni-koeln.de) maintain this web site.
    Change date last revised.
    Mention at the top a link to how to get Android versions of dictionaries.

All steps done.

Encountered a small glitch. Jim's data on server had MW link bolded in January 2019, but the sanlexhome git repository did not have that change.

If I had pulled up without making the change congruent, I would be ending up with the dreaded git errors. But fortunately I tried `git diff` on server and saw the changes. So I made changes to the repository to be congruent with the data on server. So it works now.

Also 

> c) In 'scans/awork/homepage' directory at Cologne, the git repository 'origin' should be changed to 'cslhomepage' [There is some git command to do this]

Currently it is set to listen to `https://github.com/sanskrit-lexicon/sanlexhome` by `git remote set-url origin git@github.com:sanskrit-lexicon/sanlexhome.git` command.
In my experience, whenever there is mere renaming of the repository on github, the git does understand the new name automatically. Let us see.

**Comment by funderburkjim** [comment]
> 'csl-' prefix

1. Cologne should have no problems with a '-' in file name :  for example, there is a '-' in 'sanskrit-lexicon' which is part of the AFS filesystem path to the website
/afs/.../sanskrit-lexicon/http/...
2. @drdhaval2785  Suggest go ahead and change:
   * name of Github sanskrit-lexicon homepage repository to 'csl-homepage'
   * Also, at Cologne, in homepage directory,
      ```git remote set-url origin git@github.com:sanskrit-lexicon/csl-homepage.git```
3. Similarly change 
   * name 'Github sanskrit-lexicon csldoc repository to 'csl-doc'
   * Also, at Cologne , in csldev/csldoc directory,
      ```git remote set-url origin git@github.com:sanskrit-lexicon/csl-doc.git```

When these are done, go ahead and  make corresponding changes within dokuwiki, so dokuwiki will be consistent with code.

**Comment by gasyoun** [comment]
> All steps done.

That's one small step for [a] man, one giant leap for mankind.

**Comment by drdhaval2785** [comment]
>Mention at the top a link to how to get Android versions of dictionaries.
@drdhaval278 left?

No. This too is done.

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/Cologne/issues/262#issuecomment-508563560

Changes suggested via this issue is installed on Cologne server and also dokuwiki updated accordingly to point to new names.

**Comment by funderburkjim** [comment]
Have also installed changes in local repositories.  Good!
