### ISSUE TITLE
dictionary update wiki documentation

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#263]
The dictionary update process is a big topic.

I've begun the wiki documention of this process with [readme_update.txt for MW](https://www.sanskrit-lexicon.uni-koeln.de/doc/dokuwiki/doku.php?id=slfiles:docs:scans:mwscan:2014:pywork:readme_update.txt). 

Next documentation step will describe how  User Correction Form provides 'manualByLine' update records.

**Comment by gasyoun** [comment]
> The dictionary update

I would add a line of how you collect and verify the corrections proposed.

Read the algo. The `TODO:` questions are for @drdhaval2785 ?

**Comment by funderburkjim** [comment]
> TODO: questions are for @drdhaval2785 ?

For all of us.   These are intended as reminders of open questions.

**Comment by funderburkjim** [comment]
> add a line of how you collect and verify the corrections proposed

I'll keep this in mind when documenting how Correction Form corrections are handled.

There has been much discussion regarding 'verification of proposed corrections'.   Maybe @gasyoun could add a page to the Dokuwiki summarizing the principles.

**Comment by drdhaval2785** [comment]
@funderburkjim, Let me know when you feel that I can try a small correction on Cologne server.
I will try with the docuwiki steps and let you know if I fumbled at some place.

**Comment by funderburkjim** [comment]
> small correction on Cologne server.

Documentation is written with an extended example of the oldest pending MW correction from the user correction form submissions.  See [correction_response](https://www.sanskrit-lexicon.uni-koeln.de/doc/dokuwiki/doku.php?id=slfiles:docs:php:correction_response) in the dokuwiki.

I have only modified manualByLine03.txt for MW.

Here's an exercise:
* Add the next oldest pending MW correction in correctionform (L=234107) to manualByLine03.txt
* Mark  as corrected in cfr.tsv, and save to server.
* Also, install these two corrections (mine and yours) as documented in the dokuwiki readme_update.txt.
   * Note: you will need the '.aws' directory from my login to do the aws backup step.
* Note: Documentation does not yet mention syncing CORRECTIONS to local copy, and I haven't done so.  I don't think this matters in the exercise.

When this exercise done,  @drdhaval2785 and @funderburkjim can decide how to work jointly on the rest of the 80 or so pending corrections -- we'll have to be careful not to step on each other's toes.

**Comment by gasyoun** [comment]
@funderburkjim this reminds me of another long wanting upgrade. https://www.sanskrit-lexicon.uni-koeln.de/php/correction_form.php?dict=MW is outdated. To submit it is pain. Hope you'll add the JS code that was developed and replicate it to other templates one day, after the minimum is there.

**Comment by drdhaval2785** [comment]
> L=234107

Correction installed at Cologne.

> AWS update

Pending.

> When this exercise done, @drdhaval2785 and @funderburkjim can decide how to work jointly on the rest of the 80 or so pending corrections -- we'll have to be careful not to step on each other's toes.

I suggest that I will handle all MW errors. (This will give me enough exposure and practice to gain confidence)
Rest dictionaries be handled by @funderburkjim .

**Comment by funderburkjim** [comment]
Ctrl-enter method:   I *think* it is available in the [simple search display](https://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/simple-search/v1.0/list-0.2s.html).

But not available for the B-L-A-M displays.

> correction_form.php ... is outdated.

I disagree.  I prefer this method.   Only @gasyoun and @SergeA have complained about correction_form.    The Ctrl-Enter method could be added to the B-L-M displays probably; but I think it would be problematic for the A (Advanced Search display).

One thing I dislike about the Ctrl-Enter method is that it is not discoverable.
This is my opinion.

**Comment by funderburkjim** [comment]
> Rest dictionaries be handled by @funderburkjim 

Agreed.   We'll still have to avoid simultaneous modification of csl.tsv.  If I work 5-8PM EST (US), will that be out of the times you might be working?  ( about 2:30-5:30 AM Gujarat time).

**Comment by drdhaval2785** [comment]
Yes. 2.30 to 5.30 AM Gujarat time I will definitely not be working.

**Comment by gasyoun** [comment]
> Ctrl-enter method: I think it is available in the simple search display.

Yes, right.

> But not available for the B-L-A-M displays.

In future, if simple display is made as it should be I do not see no need for B-L-A-M displays. 

> I disagree. I prefer this method. 

Jim - it takes minutes to do all that copy-paste monkey work! I have complained, because I know where to do it. People do not submit, because like @SergeA they are lazy. So am I. 

> One thing I dislike about the Ctrl-Enter method is that it is not discoverable.

Time to change it. I guess an icon in header can be added to give a hint.

**Comment by funderburkjim** [comment]
> if simple display is made as it should be I do not see no need for B-L-A-M displays  

Advanced search is different -- not just one word at a time like B,L,M.   I also use almost exclusively
the simple search display  (although, with the 'slp1' input method, not the 'simple' method).  


> icon in header

@gasyoun  Give a specific solution, and we'll give it a try in simple search

**Comment by gasyoun** [comment]
> Advanced search is different -- not just one word at a time like B,L,M.

Still it's a UI issue that can be handled in one place. No need for 4 or even 5.

>  I also use almost exclusively the simple search display

Let's have it as default in the future. It contains best of all worlds and if A is included, all of it.  There will be UI suggestions coming up from Mariya.

> (although, with the 'slp1' input method, not the 'simple' method)

Guess you're the only slp1 in-putter around.

>specific solution, and we'll give it a try in simple search

I googled and can't find a calm enough icon (red or yellow all the way will attract too much attention), it must be grey (looking at https://thenounproject.com/amante_de_icono/collection/error-collections/?i=1496976). 
`Corrections` is the text now. Make it verb? Or `Typo found?! Ctrl + Enter`
