### ISSUE TITLE
lowercase dictionary code in Correction form

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#265]
The following record appears in correctionform.txt, but not in MW_correctionform.txt.

It has to do with the small case in the suggested correction.

```
Case 24352: 02/10/2019 dict=mw, L= 262351, hw=hastipa, user=ejf
old = <ab n="elephants">el*</ab>-keeper
new = <ab n="elephant">el*</ab>-keeper
comment = markup
status = PENDING
```

**Comment by funderburkjim** [comment]
I see that there is no hastipa in mw_correctionform.txt,  and this seems to be an error.  But, what does 'small case in suggested correction'  mean, and what how does it relate to the error?

**Comment by drdhaval2785** [comment]
In cfr.tsv, the dictcode is 'mw' and not 'MW'.
Therefore it did not make it to mw_correctionform.txt.

Whatever corrections had 'MW' have made their way to mw_correctionform.txt.

**Comment by funderburkjim** [comment]
OK. Got it.

After we get caught up with corrections, we should address this detail.  Let's postpone for now.

**Comment by gasyoun** [comment]
> Let's postpone for now.

Let's at least make a new issue for it.

**Comment by drdhaval2785** [comment]
@funderburkjim any memories whether this was handled or not.

**Comment by funderburkjim** [comment]
I think either 'mw' or 'MW' will be handled properly by cfr_adj.py now.

`Case 24352`  is present currently in mw_correctionform.txt.

Problem looks solved to me.
