### ISSUE TITLE
correction process reengineering thoughts

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#266]
# Current scenario

1. cfr.tsv - Once a user submits correction from Correction Form, it gets populated to cfr.tsv
2. correctionform.txt - Generated from cfr.tsv for easy visualization.
3. {DICTCODE}/{DICTYEAR}/orig/{DICTCODE}XXX.txt - e.g. md/2014/orig/md4.txt - Used to check the base digitization
4. {DICTCODE}/{DICTYEAR}/pywork/manualByLineXXX.txt - e.g. md/2014/pywork/manualByLine03.txt - Created from correctionform.txt and md4.txt manually.
5. {DICTCODE}/{DICTYEAR}/pywork/manualByLine.py - This takes two inputs i.e. md4.txt and manualByLine03.txt and generates md.txt (treated as base version).
6. {DICTCODE}/{DICTYEAR}/orig/{DICTCODE}.txt - e.g. md/2014/orig/md.txt - Currently in use.

# Proposed scenario

1. cfr.tsv - No change suggested.
2. correctionform.txt - No change suggested.
3. md4.txt - No change suggested.
4. manualByLine03.txt - Remove this.
5. manualByLine.py - Remove this.
6. Whatever changes are to be made, make them directly in the body of md.txt. (We keep it in a git repository and track the changes to it by various commits.)

# Any data loss?

1. manualByLine03.txt keeps track of changes between md4.txt and md.txt. This can easily be achieved by doing a `diff md.txt md4.txt`.
2. It also has some information in term of comments like what is the change, who suggested this change, when was this change made etc, which may be lost in `diff md.txt md4.txt`.
3. For this purpose, we can keep the orig/md.txt and orig/mdXXX.txt (md1.txt, md2.txt, md3.txt, md4.txt etc) in a git repository, and note the necessary information in a preformatted commit message. This will ensure that the information in point 2 is not lost.
4. Whenever there is major version change, like meta-IAST conversion recently, keep doing as it is being done currently. bump the corrected data to md5.txt and then copy it to md.txt and then continue making changes to md.txt as usual.

# Additional functionality

1. With help of `git diff <commit1> <commit2> <filename>` we can see difference of the file between two commits e.g. changes made in the file from 1 June 2019 to 30 September 2019.
2. It becomes easier to share the differences to non technical people (in HTML) highlighting the difference after the incorporation of their correction.

# Reduced correction turnover timing

1. As the process is as simple as editing a single file i.e. md.txt, the corrections can be made directly to it and pushed to github. Whenever there is `redo_hw.sh` or `redo_xml.sh` at the Cologne server, we can `git pull` this file to ensure that the latest file is put to use for regeneration.
2. As there is no need to upload manualByLineXXX.txt, and no need to regenerate md.txt by manualByLine.py, the time consumed will come down.

# Thoughts for cfr.tsv

1. As this file gets larger with time, it is difficult to upload it / download it / edit it on server with time.
2. I think this should be done on local file.
3. We can think of some hack which will do the following - `git pull` on the Cologne server whenever the file cfr.tsv is modified on CORRECTIONS repository on github.

I have only one glitch in my mind - What if some user submits correction while we edit and commit the file to github?

**Comment by gasyoun** [comment]
Agree, comments travel to commit message, time consumed is of greatest importance.

> submits correction while we edit and commit the file to github?

Guess it will come up in 20 years for the first time. We have one commit per month, no?

**Comment by funderburkjim** [comment]
>  What if some user submits correction while we edit ...

This problem also currently exists:  A user could submit a new proposed correction while we are locally editing cfr.tsv.  When we save our local copy back to server, we would zap the user's correction.

There actually are date-stamped cfr files  (e.g. cfr-20190701.tsv) which contain a copy of the user's corrections.  These theoretically could be used to validate that no user corrections have been lost by our actions.

**Comment by funderburkjim** [comment]
I think of the manualByLine files as security blanket -- so there may be some kicking and screaming here if these go away!  But it may be time for this, nonetheless.

I'd like to think of this in the slightly larger context that was mentioned in our Sunday discussions, namely that we should separate the work for a dictionary into (a) archived portion and (b) currently active portion.   The current portion would be in repository form, and archived portion would not need to be in repository form.

We'll need to think carefully what should be in each dictionary's current repository.

For instance, 'md4.txt' (a.k.a. the previous digitization version) would not be needed in the repository for current 'md' dictionary.    If we needed a big change to a dictionary, then we might want to add the
current form of md.txt to the archive (as md5.txt).

**Comment by drdhaval2785** [comment]
Dear Jim,
I love your security blankets and do not intend to remove it.
I have seen git malfunctions over the years. So I also want to have some security blankets.

But both can be easily achieved.

1. Generate `diff ../orig/md.txt ../orig/md4.txt > manulaByLine03.txt` by a cronjob let us say once every day.


What I am suggesting is that instead of generating md.txt with help of md4.txt file and manualByLinep3.txt file -> we generate diff file (manualByLine03.txt) from md.txt and md4.txt.

**Comment by gasyoun** [comment]
> cronjob let us say once every day.

Makes sense.

> I love your security blankets and do not intend to remove it.

It's one of the strong sides of Jim - do, but do so, that you have 2 backups.

**Comment by drdhaval2785** [comment]
trial-md is the repository where I am experimenting with this thought process.

1. Created md5.txt from current md.txt from Cologne. 
2. Made a change to md.txt and tracked via git. See https://github.com/sanskrit-lexicon/trial-md/commit/bdf6a593b22b7ec1362214ddceba0be7f1de5a3c#diff-025f253325b46929cd34f2a7c3c55e7c.
3. Created pywork/manualByLine04.txt by `diff orig/md.txt orig/md5.txt > pywork/manualByLine04.txt.

@funderburkjim may like to draw attention to any lacuna or issue which might crop up.
Also this is a good repository to check what should belong to production and what should belong to archive purpose.

**Comment by gasyoun** [comment]
Looks nice.

![dawn](https://user-images.githubusercontent.com/80761/60871705-efb69000-a23b-11e9-9bf2-40986910ca63.PNG)

**Comment by drdhaval2785** [comment]
Commit message seems fine?
Lnum:Headword:old->new

Or do we need to capture anything else too @funderburkjim or @gasyoun?

**Comment by funderburkjim** [comment]
Maybe mention print changes when the correction warrants.  (Also update CORRECTIONS/dictionaries/XXX/xxx_printchange.txt  when print changes occur.).

For simple spelling corrections like above,  is 'down->dawn' needed in commit message, since the diff shows it?

**Comment by gasyoun** [comment]
> Maybe mention print changes when the correction warrants. (Also update CORRECTIONS/dictionaries/XXX/xxx_printchange.txt when print changes occur.).

That would be great.

> For simple spelling corrections like above, is 'down->dawn' needed in commit message, since the diff shows it?

Why not?

**Comment by drdhaval2785** [comment]
changes in csl-orig working fine. Closing.
