### ISSUE TITLE
Create a bare-bones repository - thoughts

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/Cologne#267]
This is during the correction of errors in VCP.
```
$ sh redo_xml.sh  
BEGIN redo_xml.sh
construct vcp.xml...
Unexpected <H>: <div n="H">svaravarRaviBAgAdi .
Unexpected <H>: <div n="H">sUryyAdigrahARAM janmanUmyAdisUcakavivaraRapatram .
Unexpected <H>: <div n="H">vEdaBede grahAdInAM mantraBedA hemAdryAdyuktAH pratIkato darSyante
Unexpected <H>: <div n="H">Ya
Unexpected <H>: <div n="H">Ra
Unexpected <H>: <div n="H">yoginIdaSAcakram .
Unexpected <H>: <div n="H">viMSottarIyadaSAcakram .
Unexpected <H>: <div n="H">viMSottarIyAntardaSAcakram .
Unexpected <H>: <div n="H">pUrvamanuktatvAt yoginyAmantardaSAcakramatra pradarSyate
Unexpected <H>: <div n="H">pariSizwam
Unexpected <H>: <div n="H">1334 pf0 pitfpakzaSabdapariSizwam
Unexpected <H>: <div n="H">4336 pfzWaKyapittalaSabdapariSizwam .
Unexpected <H>: <div n="H">4427 pf0 prakftiSabdasya pariSizwam
Unexpected <H>: <div n="H">4499 pfzWasTaprasADanaSabdasya pariSizwam
Unexpected <H>: <div n="H">4504 pfzWasTaprAkftaSabdasya pariSizwam
Unexpected <H>: <div n="H">4522 pfzWasTa prAtarSabdasya pariSizwaM
Unexpected <H>: <div n="H">Ba
Unexpected <H>: <div n="H">pariSizwam .
```

@funderburkjim may like to tell me what is the significance of this message?

**Comment by funderburkjim** [comment]
For VCP,  make_xml.py does some conversion of tags from their form in vcp.txt to an xml form in vcp.xml.
This is done in routine dig_to_xml_specific.   One of these tags is `<H>`.   Thomas used this `<H>` tag to indicate a 'centered headline' in the text, and there are two forms.  One form is used for letter breaks. For example `<H>a` , `<H>A`, etc.   Notice that in vcp.txt, the letter breaks occur *outside* the scope of the `<L>...<LEND>` of dictionary entries; and make_xml.py ignores these in its construction of vcp.xml.

But there are also a small (18) number of `<H>` tags that were *not* letter breaks. For example `<H>svaravarRaviBAgAdi` occurs in headword **Ozmya**, at top of page 1597:

![image](https://user-images.githubusercontent.com/6393033/61094049-46c68b80-a41b-11e9-85dd-e9cfa13af646.png)

In the vcp.xml   this becomes `<div n="H"><s>svaravarRaviBAgAdi .</s> </div>`.   
In disp.php , when displaying vcp, this is rendered as a simple line break:
`<br/> <span><s>svaravarRaviBAgAdi .</s> </span>`.

So, the main reason for the warning message is that these `<H>` cases were NOT viewed as letter breaks.

**Comment by funderburkjim** [comment]
### Ya, Ra, and Ba bugs

In this review,  I notice that these three cases actually ARE letter breaks -- don't know why they were not treated as letter breaks.  They currently occur
at the end of the last entry in the previous letter.   For instance, 'Ya' occurs within entry for headword
'Jyu'.

manualByLine transactions need to be inserted for these three, so that they are headwords.

These will be 'ins' (insert) type transactions, rather than the usual 'new' type.
Here are manualByLine transactions that should make new entry for 'Ya' ... it is modeled after 'ka', Ka', etc.
```
; close prior headword 'Jyu'
288500 old <>iti vAcaspatye JakArAdiSabdArTasaNkalanam .
288500 ins <LEND>
; insert meta line for 'Ya'
; prior meta line is <L>21688<pc>3185,b<k1>Jyu<k2>Jyu
288502 old <H>Ya
288502 ins <L>21688.1<pc>3186,a<k1>Ya<k2>Ya
; I don't currently remember exactly why I put the  empty `<edit type="hw"/>` tag.  It seems to
; serve no purpose now.
288503 old <>“YakArovyaYjanavarRRaBedaH ardDamAtrAkAlenoccAryyaH tasyo-
288503 new Ya¦ <edit type="hw"/> “YakArovyaYjanavarRRaBedaH ardDamAtrAkAlenoccAryyaH tasyo-
; 288523 <LEND> needs no change.  It is now the end of this 'Ya' entry.
```

@drdhaval2785 should use this as a model for the Ra and Ba cases.   Then rerun updateByLine, etc.
Check display for these three words (and the words preceding and following).

### Notes ###
1.  These changes will change the line numbers, due to 'ins' transaction.
     * This is why we  use line numbers from *preceding* digitization (vcp5.txt) when making subsequent transactions in this manualByLine02.txt for vcp
    * If you check vcp.txt *after* these changes, you should see that
       line 288501 is now `<LEND>` whereas in vcp5.txt it is `[Page3186-a+ 28]`; 
       and `[Page3186-a+ 28]` is now 288501;  and similarly with other lines
       after the insert.
       * Having to pay close attention to line numbers makes the insertion (and deletion) of lines more
         difficult in the current system.   All this detail should go away if the Git-based changes to vcp.txt
         are instituted along the lines @drdhaval2785 suggested.
2. There is no 'pywork/readme_update.txt' for VCP.  Suggest one be made, based on, say, the readme_update.txt for PWG.

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/vcp-minimal/commit/b3261c7eab68e7c2732d0a4c1f78efed81ec2c74 corrected this on git based correction.

https://github.com/sanskrit-lexicon/vcp-minimal is the testing ground where the bare minimum is kept. I corrected the data in vcp.txt in local machine, pushed it to github, pulled to a different repository in local machine and reran redo_hw.sh and redo_xml.sh and everything worked wonderfully.

@funderburkjim may like to see if there is any need to remove any file from this bare bones repository.

**Comment by drdhaval2785** [comment]
@funderburkjim and @gasyoun,

On Cologne servers, installed the experimental version of VCP as VCPExp.
https://www.sanskrit-lexicon.uni-koeln.de/scans/VCPExp/vcp-minimal/web/webtc2/index.php will give the frontend to the experiment.
The installation there has been made by `git clone git@github.com:sanskrit-lexicon/vcp-minimal.git`, followed by `cd vcp-minimal/pywork/`, `sh redo_hw.sh` and `sh redo_xml.sh`.

The corrections for https://github.com/sanskrit-lexicon/Cologne/issues/267#issuecomment-510709011 have been made directly in orig/vcp.txt file and tracked via git.

So I am making changes to vcp.txt on my local machine, pushing it to vcp-minimal repository and then pulling it to the Cologne server and redoing everything for update.

**Comment by funderburkjim** [comment]
In trying https://www.sanskrit-lexicon.uni-koeln.de/scans/VCPExp/vcp-minimal/web/webtc/indexcaller.php  
(Basic display experimental),  much works as expected -- Good!

These are missing   (via Chrome development console, 404 errors):
* cologne_univ_seal_.gif   in web/images
* oldstandard.otf  (in web/fonts)

Please present list of commands for integrating vcp-minimal on Cologne server.   I'd like to try to
make another temporary minimal version on Cologne.

Please elaborate on the (big) .gitignore file -- how did you come up with it?

One tech question on .gitignore:  Many lines start with `!` : what does this mean?

The current (non-experimental) VCP has NOT been updated.  This leaves the Cologne system in an ambiguous state.   


Note 'webtc/download.html' links still point to absolute paths in VCPScan/2013/downloads/.

**Comment by funderburkjim** [comment]
## VCPScan/2020

In Cologne `scans` directory:  `cp -r VCPExp/vcp-minimal VCPScan/2020`

Changed Cologne homepage to point to  VCPScan/2020.

NOTES:
* Effectively, with regard to current displays BLAM, the minimal version is active.   The VCPScan/2013 is 'old'.  
* Displays in apidev still point to the VCPScan/2013.
* The S3 backups still point toe VCPScan/2013.
* The two problems (cologne_univ_seal_.gif, and oldstandard.otf) can be fixed 'manually' 
* The scanned images still are hard-coded to VCPScan/2013 files.
* The 'downloads' directory is still out of sync.

I'll work to fix some of these problems *in a proper way* ---  Goal is to see what is required to completely modernize minimal version of VCP.

**Comment by funderburkjim** [comment]
### csl-websanlexicon
csl-websanlexicon repository purpose is to modify the *code* part of the *web* directory of displays for all dictionaries.  It does this by means of templates. 

These steps initialize csl-websanlexicon on local xampp server and on Cologne server
* Change name of sanskrit-lexicon/websanlexicon to sanskrit-lexicon/csl-websanlexicon  
* In local machine,  
   * `cd /c/xampp/htdocs/cologne`
   * `git clone git@github.com:sanskrit-lexicon/csl-websanlexicon.git`
* In Cologne server:
  * cd /scans
  * `git clone git@github.com:sanskrit-lexicon/csl-websanlexicon.git`

### modify to use VCPScan/2020 in csl-websanlexicon
* On Cologne server, in csl-websanlexicon/v00/ directory,
  * in dictparms.py, change 'dictyear' parm for 'vcp' to 2020.
  * in redo_colonge_all.sh, change vcp line to 2020:
     `python generate.py vcp inventory.txt  makotemplates ../../VCPScan/2020/web`
  * In VCPScan/2020/web, `mkdir images`
  * In VCPScan/2020/web, `mkdir fonts`

  * Run `python generate.py vcp inventory.txt  makotemplates ../../VCPScan/2020/web`

This fixes the `cologne_univ_seal.gif` problem.

Currently, csl-websanlexicon does not load fonts into web.  Maybe it should.  But for now,
I'll just copy the fonts directory from VCPScan/2013/web/ to VCPScan/2020/web
```
# in VCPScan/2020/web,
cp  ../../2013/web/fonts/* fonts/
```

### sync csl-websanlexicon with github

**Comment by funderburkjim** [comment]
## update vcp-minimal repository

After websanlexicon update, there is now a problem with scanned images -- code expects them to be
in VCPScan/2020/web/pdfpages/ directory, but they are still in the 2013/web/pdfpages/ directory.

## TEMPORARY FIX
In web/webtc/dictinfo.php, insert
`$path = $cologne_scandir . "/{$this->dictupper}Scan/2013/web";` after
`$path = $cologne_scandir . "/{$this->dictupper}Scan/{$this->year}/web";`


## sync VCPScan/2020 with vcp-minimal Github

**Comment by funderburkjim** [comment]
## relation between vcp-minimal and websanlexicon

vcp-minimal contains both data (orig and pywork and web/sqlite) AND display code  (web directory).

websanlexicon is current preferred way to make changes to dictionary displays (web directory)

There is thus some overlap.

**Comment by drdhaval2785** [comment]
> cologne_univ_seal.gif in web/images, oldstandard.otf (in web/fonts)

Added the two images and fonts in minimal repository.

> Please present list of commands for integrating vcp-minimal on Cologne server. I'd like to try to make another temporary minimal version on Cologne.

Run the following command on Cologne server to set up minimal version.
```
git clone git@github.com:sanskrit-lexicon/vcp-minimal.git
cd vcp-minimal/pywork
sh redo_hw.sh
sh redo_xml.sh
```

Thereafter for minor changes e.g. change in vcp.txt for a correction made in github.
```
cd vcp-minimal/pywork
git pull origin master
sh redo_hw.sh
sh redo_xml.sh
```

> Please elaborate on the (big) .gitignore file

This is created by https://github.com/sanskrit-lexicon/vcp-minimal/blob/master/create_essential_list.py . 
This is an attempt to create a whitelisting (rather than usual blacklisting) method in .gitignore, based on https://jasonstitt.com/gitignore-whitelisting-patterns.
The ultimate goal is to allow only bare minimum items in git repository, and ignore everything else. So we will not have to keep two separate repositories like the present (full fledged 2013 repository) and minimal version.
When this .gitignore file is put into the 2013 repository, it will only allow the bare minimum to be tracked by git. Rest will not be tracked e.g. vcp.xml, vcp.sqlite, vcphw0.txt, vcphw.txt etc.

> how did you come up with it?
That .gitignore file is generated by `python3 create_essential_list.py vcp`. This command generates two files `.gitignore` for whitelisting and `essential.txt`.
`essential.txt` can be used like `zip vcp.zip -@ < essential.txt`.
This command will create vcp.zip with the bare minimum skeleton needed for creating a local version.

> One tech question on .gitignore: Many lines start with ! : what does this mean?

`!` means logical NOT. So something prefixed with `!` tells .gitignore NOT to ignore that file i.e. track that file. Our .gitignore file starts with `*` which tells it to ignore everything except allowed. So we are whitelisting instead of blacklisting files with gitignore.

**Comment by funderburkjim** [comment]
> whitelisting, etc.

Thanks for explanation

**Comment by funderburkjim** [comment]
> When this .gitignore file is put into the 2013 repository

I find this confusing; not sure whether it would be ultimately workable or not.
If this were done, then the Cologne VCPScan/2013/ *directory* would contain all the *old* stuff intermingled with the *new* stuff.

By contrast, if we introduce a new VCPScan/2020/ directory, then all the new stuff (with possible exception of scanned images) would be in VCPScan/2020/;  the 2013 directory would then be archival and separate from new work.

**Comment by drdhaval2785** [comment]
> if we introduce a new VCPScan/2020/ directory, then all the new stuff (with possible exception of scanned images) would be in VCPScan/2020/; the 2013 directory would then be archival and separate from new work. We would be free to change the new stuff in the best way, without concern for compatibility with some piece of old code.

I wholeheartedly support the idea. 
Minimum technical debt, and less baggage to carry in this approach.
But even then whitelisting will have to be maintained. Let us say we embark on some correction which is not just simple typo e.g. some major corrections like meta-IAST conversion. In such case we will surely create a lof of scripts and intermediate products in 2020 repo. Then the repo would keep on getting inflated unnecessarily.
So shifting to 2020 with whitelisting is the way to go if we want to remain minimal for all times to come. And anyone who wants to download all the unused code ov 2013 or still older code can download the same from AWS or some archival zip file.

**Comment by drdhaval2785** [comment]
> scanned images

I propose that they be kept at some other location as sibling to the XXXScan folders just like awork folder. So every version of the display (old, new) can draw from them and there is no need to have separate copies across versions.

`images/vcp/*.pdf or *.jpg` should be OK.

images folder can be a sibling of VCPScan and awork folder.

**Comment by gasyoun** [comment]
> csl-websanlexicon does not load fonts into web

Why not?

**Comment by funderburkjim** [comment]
## today's experience with VCP

In attempting to use vcp-minimal as the repository for VCPScan/2020/,
I found that the web directory was 'empty' and tried to 'fill it up'.  and also tried to add whitelisted web files.
However, when pushed to vcp-minimal,  the added web files are not there.

Not sure what the problem is.

So the Cologne 2020 repository works.  But essential files are not properly saved.
@drdhaval2785   There must be some problem with my changes to .gitignore.

**Comment by drdhaval2785** [comment]
As the web is served by csl-websanlexicon, the web portion of vcp-minimal was removed.
It needs tl be regenerated by csl-websanlexicon

**Comment by funderburkjim** [comment]
1)  I reran init_query.sh in webtc2.  Advanced Search now works.
2) I changed gitignore to push many needed items to vcp-minimal --- But they don't seem to have been pushed up.   There must be an error in my .gitignore.


We don't want to leave 2020 in a bad state.

vcp-minimal and VCPScan/2020  are getting very confused.

**Comment by funderburkjim** [comment]
I'm signing off for tonight.  Let's keep VCPScan/2020 functional (it's the only version with some corrections) -- even if it is not synced with sanskrit-lexicon/vcp-minimal.

**Comment by drdhaval2785** [comment]
Leave it to me. I will make it running well and in sync.

**Comment by drdhaval2785** [comment]
It seems that you were able to handle it yourself. So not touching anything, lest I break it.

**Comment by funderburkjim** [comment]
##  backing out of VCPScan/2020

It was my idea to make VCPScan/2020  the 'active' version of VCP  -- e.g., the one referenced by the home page and s3-backup.

However, I now think this switching to 2020 was premature.   More testing and adjustment are needed before making 2020 (based on vcp-minimal) the current version.  
Therefore, I am reverting the homepage to refer to the VCPScan/2013  and taking various other actions so that VCPScan/2013 will be the current version while VCPScan/2020 will remain a test version.
I'll detail exactly what is done in next comment.

**Comment by gasyoun** [comment]
> However, I now think this switching to 2020 was premature. More testing and adjustment are needed before making 2020 (based on vcp-minimal) the current version.

At least we saw that someone uses it. The Piwik stats are down, right? Still want to know who visits the site.

**Comment by funderburkjim** [comment]
## backing out of VCPScan/2020 -- step 1

### Remake homepage
in awork/homepage,
* change 2020 to 2013 for vcp in indexdirs_edit.xml
* change homepage 'as-of' date to Jul 22, 2019 in index_make2.py
* remake homepage:  `sh redo_index.sh`  
  * this remakes `index.html' in homepage directory, and copies it to root directory of website.
* sync awork/homepage repository with GitHub/sanskrit-lexicon/csl-homepage repository

### Change Cologne directory name
  The awork/homepage directory at Cologne should have its name changed to awork/csl-homepage
     for consistency of naming with Github repository.
  This has been done.

**Comment by funderburkjim** [comment]
## backing out of VCPScan/2020 -- step 2

Changes to csl-websanlexicon:
* in v00/redo_cologne_all.sh,  revert so the generation changes the 2013 version:
   `python generate.py vcp inventory.txt  makotemplates ../../VCPScan/2013/web`
  * run this to bring recent changes into 2013 version
* Add (on Cologne)  script `v00/redo_cologne_2020.sh` to apply web regeneration to the test 2020 version
   `python generate.py vcp inventory.txt  makotemplates ../../VCPScan/2020/web`
   * .gitignore already ignores this script, so it is not part of the repository that is tracked by git.

**Comment by funderburkjim** [comment]
## backing out of VCPScan/2020 -- step 3

VCPScan/2013/orig/vcp.txt and VCPScan/2020/orig/vcp.txt (aka vcp-minimal) are not quite the same -- the recent user corrections need all to be made for both.

### for vcp-minimal:
* `L=39589, hw=राम, रापब्दा -> राशब्दो` was made for 2013, but not for 2020
* `L= 10581, hw=एक, मूरिशः -> भूरिशः` was made for 2013, but not for 2020
* On local copy of vcp-minimal:
  * edit local copy of vcp-minimal/orig/vcp.txt and manually make changes
  * push to github
* On Cologne server, in VCPScan/2020
  * `git pull origin master`  to bring in the changes to vcp.txt
  * in VCPScan/2020/pywork:
    * sh redo_hw.sh
    * sh redo_xml.sh

### for VCPScan/2013
The 'Ya', 'Ra' and 'Ba' headword errors need to be corrected.
All work on Cologne server; 
* in VCPScan/2013/pywork, edit manualByLine02.txt and add  appropriate inserts/changes.
* Follow steps of `readme_update.txt`  
  * python updateByLine.py ../orig/vcp5.txt manualByLine02.txt ../orig/vcp.txt 
  * sh redo_hw.sh
  * sh redo_xml.sh
* Also do the additional steps --  
  * cd ../downloads
  * sh redo_all.sh
  * cd ../pywork
  * sh make_sync.sh
  * make s3 backup:
     * cd ../../../awork/virtualenv/aws/
     * python make_copy_environ.py vcp
     * source s3bk_vcp.sh
     * rm s3bk_vcp.sh

### Note on additional steps for 2013
Later, in 2020 we may want to have some similar steps -- These will need to be rethought first.  For
instance, we don't yet have a `downloads` directory in 2020, and we need to think what the 
downloads directory should contain.

**Comment by funderburkjim** [comment]
## Similarity between 2013 and 2020 versions currently.
The basic digitizations (VCPScan/2013/orig/vcp.txt and VCPScan/2020/orig/vcp.txt) are identical.
We should maintain this identity until we are confident that 2020 (vcp-minimal) is finalized.

### End of Backing out 
I think the steps described above now give us:
* A fully functional VCPScan/2013  system, same as before and the one that homepage links to
* A mostly functional VCPScan/2020 system, based on vcp-minimal.

### Note on scanned images
I made VCPScan/2020/web/pdfpages a symbolic link to VCPScan/2013/web/pdfpages:
```
# in VCPScan/2020/web/ directory
ln -s pdfpages ../../2013/web/pdfpages
```

I agree with @drdhaval2785 comment [above](https://github.com/sanskrit-lexicon/Cologne/issues/267#issuecomment-511166224).  Whitelisting is a good idea.   Exactly what the list of whitelisted files should be needs more thought. 

Since this issue with comments is now quite long, we should open a new issue devoted to perfecting the vcp-minimal repository.

**Comment by gasyoun** [comment]
> don't yet have a downloads directory in 2020, and we need to think what the
downloads directory should contain.

Let's open an issue for it. As it is nobody understands what to download.

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/Cologne/issues/278 for pywork files.
