### ISSUE TITLE
pywork - segregate same and separate files

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#268]
A cursory look with `diff` shows the following differences between the actually used files of `pywork` folder between VCP and MD dictionaries.

# Same files
```
pywork/hw.py
pywork/hw0.py
pywork/hw2.py
pywork/hwparse.py # Only `dictcode = 'vcp'` line is different. This can be handled easily.
pywork/parseheadline.py
pywork/updateByLine.py # Except the `try except` in md
```

# Different
```
pywork/headword.py
pywork/hw1.py
pywork/hw_page.py
pywork/make_xml.py
pywork/update.py # Not seen in vcp/pywork.
```

@funderburkjim may like to tell whether the classification is OK or not.

*Question 1*  - If the classification is OK, we can keep the SAME files at one place only. So that any update is directly applied to all the dictionaries at one go.
*Question 2* - Are the files in the DIFFERENT list so different that we may not have their unified version? There would be really different items at some place. Can we put them in some form of config file and make the scripts generic ?

If these two items are answered satisfactorily, we can move ahead to unified code base (as far as possible).

**Comment by drdhaval2785** [comment]
# pywork/headword.py

I checked up the code base in both VCP and MD. This is no longer needed.
Most probably this has to do with Meta-IAST conversion done earlier.
Now we have the metadata line already in XXX.txt file. So there is no need to identify patterns of headwords by `reHeadword` regex (which is the only item residing in headword.py).
Therefore this file is not needed in current display in my opinion.

**Comment by drdhaval2785** [comment]
# pywork/hw1.py

Not used in any of the pywork files in minimal version.

# pywork/hw_page.py

Not used in any of the pywork files of minimal version.

Therefore these two files are not needed in the minimal version.

**Comment by drdhaval2785** [comment]
# pywork/update.py

Not used in any of the pywork files of minimal version.

This can be done away with.

**Comment by drdhaval2785** [comment]
# pywork/updateByLine.py

Now we do not intend to update by Line numbers, but changes in XXX.txt directly in git. Therefore this file is also not needed in minimal version.

**Comment by funderburkjim** [comment]
### hw_page.py of archival interest only

For most dictionaries, I made a specialized pdf from the scanned images.   hw_page.py was, I think, used to determine the first word on each scanned image.   This first word was in turn used to embed a pdf *bookmark* for each page in the pdf.   As example, try downloading the md_bookmark.pdf at https://www.sanskrit-lexicon.uni-koeln.de/scans/MDScan/2014/web/webtc/download.html.

At the time (2013 or so) I thought this bookmarked pdf might be liked by many semi-technical users.  But I have never received any feedback, positive or negative; this makes me conclude that there is no reason to include these in current download material.

So hw_page.py is not be of current interest.

### pywork/update.py not of current utility
An early version of an update program; a precursor to updateByLine.py


### pywork/updateByLine.py   a general utility
This should be retained in some library location applicable to any dictionary.
Sometimes, if we are making a programmatic change to a digitization,  the most convenient way might
be to prepare by program a 'manualByLine' file, and then update the dictionary with updateByLine.py.

**Comment by funderburkjim** [comment]
### unixify.py  a general utility

If a shell program  (xyz.sh) is created on Windows computer and then transferred to Cologne's Unix system, then it may have the '\r\n' line-endings, which will likely cause problems when run under Unix.
Running `python unixify.py xxx.sh`  reads lines of xxx.sh, removes the line-endings, and writes out lines with Unix ('\n') line endings to xxx.sh  (it changes xxx.sh).

**Comment by funderburkjim** [comment]
### pywork/make_xml.py

Currently, there is considerable variation in the version of this program  for the dictionaries.  
A systematic comparison could likely suggest many ways to reduce this variability.  
Another way to reduce the variability would be to alter the digitization xxx.txt.  For instance,
many dictionaries still use some of Thomas's original markup. e.g. {#slp1-for-devanagari#} while a few
use `<s>slp1-for-devanagari</s>`.  Similarly, {@BOLD@} and {%italic%} could be changed in 
xxx.txt to the xml-forms.   

The other kind of variation has to do with `<div>` markup.  For some dictionaries such markup is
part of xxx.txt, while for some other dictionaries such markup is generated by make_xml.py.   It might
be better to have all such markup already in xxx.txt.

So, ideally,  xxx.xml would be only a very simple translation of `meta-line thru<LEND>` into a string of xml.  Then there might be need for only a very small number of variants of make_xml.py for the different dictionaries.

**Comment by funderburkjim** [comment]
### other resources for some dictionaries

Some dictionaries have markup whose displays require other sqlite files in addition to the xxx.sqlite for the digitization.   For example, xxxab.sqlite (for abbreviation tooltips),  xxxauth.sqlite for literary source tooltips.

The updating of such additional resources is done in subdirectories of pywork, such as 'pwgab' and 'pwgauth' for pwg dictionary.   These subdirectories should be 'whitelisted'. Also, perhaps, make_xml.sh should include the 'redo' steps for remaking the web/sqlite files used by displays.

Note: Currently, pwg literary source markup is created in a unique way as part of pwg.xml construction.

**Comment by drdhaval2785** [comment]
# unixify.py

What about `dos2unix` utility from ubuntu repositories by `apt install dos2unix`? 
Seems to do the same and many more stuffs for differences of DOS and unix.

**Comment by gasyoun** [comment]
> bookmarked pdf might be liked by many semi-technical users

Indeed I've heard people use them. There are people who still use printed book or PDF only, who do not rely on OCRed text. The only non-critical issue I see with them is the lacking of title and preface in the same file.

**Comment by drdhaval2785** [comment]
@funderburkjim 
Can you explain why hw.py is absent from BEN?
Its redo.sh is also different from others.

**Comment by drdhaval2785** [comment]
Similarly hw0.py and hw2.py for BEN are also different from all others.
Is this deliberate or this dictionary just got missed out?

**Comment by drdhaval2785** [comment]
#hw.py

MW has some specific requirements for 'e' tag, and that makes hw.py for MW different from all others.
Is it possible to unify them? Some coding logic which may make hw.py same for all dictionaries?

**Comment by drdhaval2785** [comment]
csl-pywork migration over. Closing.
