### ISSUE TITLE
scroll to top in displays - a websanlexicon example

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#270]
In the current basic display code, there is  a bug;  I don't think the bug appears in other displays.

Take STC basic display as example (this example from user O. Caujolle recently).

Using SLP1 for input, look up 'UrDva'.   

![image](https://user-images.githubusercontent.com/6393033/61253973-ebeda680-a730-11e9-8ed4-cb4eeacc6e11.png)

Next, scroll down in the entry:

![image](https://user-images.githubusercontent.com/6393033/61254025-20f9f900-a731-11e9-803d-ccd6967f84b9.png)

Finally, look up the headword 'deva':
![image](https://user-images.githubusercontent.com/6393033/61254097-61597700-a731-11e9-9178-5e4a33dc445a.png)

Note that 'deva' also is scrolled down .

This is the error.

**Comment by funderburkjim** [comment]
This scrolling error is present for basic display in all dictionaries.

Oh, no!  You mean we have to change some code in *all* dictionaries?

**websanlexicon** to the rescue.   We can change the code just in *one* place, the Cologne *csl-websanlexicon* repository, then apply a script to install this code into the web directory of *all* the Cologne dictionaries.

I'll describe the process in this issue.

**Comment by gasyoun** [comment]
> websanlexicon to the rescue. 

It's about time.

**Comment by funderburkjim** [comment]
### Experimenting in a particular dictionary

Our ultimate objective is to make change(s) to the templates in the csl-websanlexicon repository (at Cologne), and regenerate the code of the 'web' directories of the various dictionaries from the templates.

However, we need to discover what changes to make to the templates, and it is often more convenient to experiment with the code in the 'web' directory of one particular dictionary.   Once experimentation is successful for that particular dictionary,  we can then make corresponding changes in the templates of the csl-websanlexicon repository, and regenerate 'web' code for all dictionaries.

This is the approach taken in the example of this issue -- all the work done at Cologne.   In a later comment, I'll show how much of the work could be done on a local machine.

**Comment by funderburkjim** [comment]
### The experimental change for STC

The problem was stated to occur in the Basic Display for STC dictionary, so let's first find a solution for this context.   This is not like an algebra problem, where a solution can be found by logic.   Rather, a solution is found by trial and error based on previous experience .

We know that html is put into the div by jQuery in the getWord function of the main_webtc.js Javascript module:
```
  var url =  "../webtc/getword.php" +  
   "?key=" +escape(word) + 
   "&filter=" +escape(filter) +
   //"&noLit=" + escape(noLit) +
   "&accent=" + escape(accent) +
   "&transLit=" + escape(transLit);

    jQuery.ajax({
	url:url,
	type:"GET",
        success: function(data,textStatus,jqXHR) {
	    jQuery("#disp").html(data);
	},
	error:function(jqXHR, textStatus, errorThrown) {
	    alert("Error: " + textStatus);
	}
    });
```

And from previous experience, we suspect that the problem is that the DOM scroll attributes of the '#disp' html div element need to be reset.  The details of how to do this may be found, for example, in 
[this reference](https://www.w3schools.com/jsref/prop_element_scrolltop.asp).   This is accomplished by the following change to the *success* callback:
```
        success: function(data,textStatus,jqXHR) {
            var elmnt = document.getElementById("disp");
	    elmnt.scrollTop = 0;
            elmnt.scrollLeft = 0;
	    jQuery("#disp").html(data);
	},
```

### Implement change for STC 
make above change manually to *web/webtc/main_webtc.js* at Cologne for STC,  

### check that the change solves problem
* Bring up URL in browser: https://www.sanskrit-lexicon.uni-koeln.de/scans/STCScan/2013/web/webtc/indexcaller.php
* Be sure new version of JS is used by browser
   * In Chrome, Ctrl-F5 reloads everything
* Do the UrDva, deva experiment as above: The result is
![image](https://user-images.githubusercontent.com/6393033/61416711-a8c33d00-a8c2-11e9-87eb-054134fd4911.png)

Excellent -  *deva* listing now appears at the top, as we wanted.

**Comment by funderburkjim** [comment]
## Install change into csl-websanlexicon

In ssh session on Cologne server, change directory to *scans/csl-websanlexicon.

Sync to GitHub:  *git pull origin master*.

The templates are in subdirectory *v00/makotemplates*.   The folder structure here is similar to that
of the 'web' directory of the dictionaries.   In this case, we want to modify the *webtc/main_webtc.js* file as above, by inserting the lines at appropriate spot:
```
            var elmnt = document.getElementById("disp");
	    elmnt.scrollTop = 0;
            elmnt.scrollLeft = 0;
```

### Regenerate STC and check
This step is not logically required, but for me this checking is psychologically required.

* make current directory *csl-websanlexicon/v00*
* edit *redo_cologne_all.sh*, find the stc regeneration step for STC and copy to clipboard:
  `python generate.py stc inventory.txt  makotemplates ../../STCScan/2013/web`
* then execute this generation step

**Comment by funderburkjim** [comment]
### Unexpected Error from generate.py
I've never seen this error before.   
```
> python generate.py stc inventory.txt  makotemplates ../../STCScan/2013/web
('makedirs WARNING: target directory already exists:', '../../STCScan/2013/web')
Using dictwebversion=00.003
Traceback (most recent call last):
  File "generate.py", line 85, in <module>
    renderedtext = template.render(**dictparms)
  File "/usr/lib/python2.6/site-packages/mako/template.py", line 189, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python2.6/site-packages/mako/runtime.py", line 403, in _render
    _render_context(template, callable_, context, *args, **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python2.6/site-packages/mako/runtime.py", line 434, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python2.6/site-packages/mako/runtime.py", line 457, in _exec_template
    callable_(context, *args, **kwargs)
  File "makotemplates_mobile1_index_php", line 27, in render_body
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 36: ordinal not in range(128)
> python --version
Python 2.6.6
```

**Comment by funderburkjim** [comment]
### works for cae
`python generate.py cae inventory.txt  makotemplates ../../CAEScan/2014/web` 
works without error.   Reason - there are no extended ascii characters involved.


### stc works on local machine
Local machine has python 2.7.   Cologne machine has PYthon 2.6.6

### old_websanlexicon
I saved a version of websanlexicon (a copy is currently called old_websanlexicon)
In old_websanlexicon,  
`python generate.py stc inventory.txt makotemplates ../../STCScan/2013/web`  gives no error!

'git log' in old_websanlexicon shows last commit of Jan 15.

So, something done since then is causing the current problem with websanlexicon.

Not sure how to fix.

**Comment by drdhaval2785** [comment]
I checked up the codebase by git log.
There is no change in either the template or code from January to Till date.

But as mentioned by you somewhere, you updated mako library by putting executable in /usr/lib. 

Mako documentation shows that they supoort only 2.7.

https://www.makotemplates.org/
```
Supports Python 2.7 and Python 3.5 and above.
```

**Comment by drdhaval2785** [comment]
You may try to revert back to old version of mako. It will most probably clear the issue.

**Comment by drdhaval2785** [comment]
Or https://docs.makotemplates.org/en/latest/usage.html#using-unicode-and-encoding may help you in this regard for handling unicode better.
Trial and error will be the way to go.

@funderburkjim 
One specific question regarding python in Cologne server.
Is it mandatory to get stuck to python 2.6.6 and 3.4.10 on Cologne?
Can't the webmasters upgrade it to the latest versions i.e. 2.7.16 and 3.7.4?

**Comment by drdhaval2785** [comment]
@funderburkjim 
I tried to correct the code at csl-websanlexicon and pulled on cologne server at https://github.com/sanskrit-lexicon/csl-websanlexicon/commit/49f5a60c0e2707eff9065b9767f9782c39a517c1 commit.
Also committed your change of https://github.com/sanskrit-lexicon/Cologne/issues/270#issuecomment-512606863.

Reference in mako - https://docs.makotemplates.org/en/latest/usage.html#mako.template.Template.render_unicode

There are some issues with unicode in mako.
render_unicode() method renders unicode appropriately depending on the python version being used.

No errors now in the terminal of Cologne
```
$ python generate.py stc inventory.txt  makotemplates ../../STCScan/2013/web
('makedirs WARNING: target directory already exists:', '../../STCScan/2013/web')
Using dictwebversion=00.003
```

**Comment by drdhaval2785** [comment]
Closing this issue.

**Comment by funderburkjim** [comment]
@drdhaval2785    
```
-   template = Template(filename=filename1,input_encoding='utf-8')
-   renderedtext = template.render(**dictparms)
+   template = Template(filename=filename1,input_encoding='utf-8',)
+   renderedtext = template.render_unicode(**dictparms)
```
As I understand it, you made the following change in v00/generate.py and this solved the problem.
Please confirm.

My understanding also is that we don't know exactly why this change is required now when it was not required earlier.

**Comment by funderburkjim** [comment]
## update web displays of other dictionaries.

First, make the change in mw, and manually examine basic display:
`python generate.py mw inventory.txt  makotemplates ../../MWScan/2014/web`

MW display looks ok.  So regenerate the web directory code for all dictionaries:

`sh redo_cologne_all.sh`

This takes about a minute

**Comment by funderburkjim** [comment]
##  GitHub version of csl-websanlexicon up to date

Currently, the Cologne version is slightly ahead.
```
# in csl-websanlexicon directory at Cologne:
git push origin master
```

**Comment by funderburkjim** [comment]
## update web downloads

The 'sh redo_cologne_all.sh' script above updates the code of the 'web' directories for all dictionaries.  

However, this does not update the web downloads   (e.g. the mwweb1.zip link  on the mw download page *https://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/webtc/download.html* does not yet reflect the change.)

We update these Xweb1.zip download files as follows:
```
# in awork/virtualenv/aws
# remake a script the runs downloads/redo_web.sh in the downloads directory for each dictionary
# (we remake since vcp now uses 2020)
python make_redo_web_all.py redo_web_all.sh
# Run the script, piping output to a log file.  This takes about 3 minutes to execute
date;sh redo_web_all.sh > redo_web_all_log.txt;date
```

**Comment by funderburkjim** [comment]
## aws backup for all the web downloads
```
# in awork/virtualenv/aws
date; sh s3bk_web_all.sh > temp_log_s3bk_web_all.txt; date
```
