### ISSUE TITLE
BHS dtd issue

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/Cologne#275]
while doing redo_xml.sh for BHS, I got the following error in my local machine. Something to do with the DTD being out of date or some specific error while generating the XML file?
```
bhs.dtd:28: parser error : ATTLIST: no name for Attribute
<!ATTLIST div (lb) CDATA #REQUIRED> 
              ^
bhs.dtd:28: parser error : Content error in the external subset
<!ATTLIST div (lb) CDATA #REQUIRED> 
              ^
```

**Comment by funderburkjim** [comment]
We want to have `<div n="lb">...` recognized as the only valid form for `<div>` elements:  i.e. there must be an 'n' attribute and the value of that 'n' attribute *must* be 'lb'  (line-break).

Here's what that (next-to-last) line in bhs.dtd should be:
```
<!ATTLIST div n (lb) #REQUIRED> 
```

I've made this change on the server and :
a) remade downloads for bhs
b) regenerated s3 backup for bhs
