### ISSUE TITLE
Working git based workflow - AFS filesystem issues

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#276]
https://github.com/sanskrit-lexicon/csl-pywork/ readme describes how to set up a git based cologne website locally as well as on any linux based distribution.

Seems to work OK for me. I tried replicating the things on different locations in my ubuntu distro. Works well.

But when trying on Cologne, it says 'Disk quota exceeded'.
This has to do with AFS file system which @funderburkjim mentioned.
We will need to have some quota of 20 GB or so if we want to test every dictionary and track it via git. Over time git repositories will also get inflated with diff logs.

On my local machine, it occupies 3.1 GB as of now.

**Comment by gasyoun** [comment]
> We will need to have some quota of 20 GB or so if we want to test every dictionary and track it via git. Over time git repositories will also get inflated with diff logs.

So we have run out of space. Hope the experiment does not end here.

**Comment by drdhaval2785** [comment]
I am sure the experiment will not end here.
I guess the AFS file system has directory wise quota. So the webmaster will have to allocate more resources to this folder. Whether we can do it ourselves or we have to ask the webmaster - only @funderburkjim can tell.

**Comment by drdhaval2785** [comment]
Now AFS is gone. NFS is in place. Closing.
