### ISSUE TITLE
whitelist for pywork

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#278]
placeholder for listing 
(1) what goes in the csl-pywork repository.
(2) What is handled by copying uniformly to all dictionaries `C`,  what is handled by templating `T` and what is handled by copying to unique dictionaries `U`

Explanation regarding C and U.

e.g. hw0.py can be copied to all dictionaries without any change so it is classified as 'C'.
'make_xml.py' is so different that it needs to be copied to unique dictionaries e.g. ACC/pywork/make_xml.py can not be copied to VCP/pywork/make_xml.py, thus it is classified as 'U'.

**Comment by drdhaval2785** [comment]
Look at https://github.com/sanskrit-lexicon/csl-pywork/tree/master/v00.
If there are any changes suggested, edit the following list.

# Template files - T

hwparse.py:T
hw.py:T
redo_hw.sh:T
redo_xml.sh:T

# Copy files - C

hw0.py:C
hw2.py:C
parseheadline.py:C
updateByLine.py:C

# Unique files - U

make_xml.py
XXX.dtd

**Comment by gasyoun** [comment]
> XXX.dtd

The (final) goal is to have 1 DTD for all. So only `make_xml.py` should remain unique.

**Comment by drdhaval2785** [comment]
Till we have one DTD, we will have to live with different DTDs.

**Comment by funderburkjim** [comment]
@drdhaval2785 

What I've been doing is now starting to overlap with csl-pywork.
But, I'm not sure how to use what you've set up here.

Can you provide example of how to use this repository to create, for example, a pywork for
BENScan/2020/  ?

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/csl-pywork/blob/master/readme.md is the step by step approach to reconstruct dictionaries based on csl-websanlexicon, csl-pywork and csl-orig.

**Comment by funderburkjim** [comment]
@gasyoun   Again, I didn't receive Dhavals message here.

**Comment by funderburkjim** [comment]
@gasyoun -- scratch above question.  My mistake.  I've gotten messages.

**Comment by drdhaval2785** [comment]
csl-pywork migration is made peacefully. Individual issues may be tracked in that repository. Closing.
