### ISSUE TITLE
csl-orig commit message

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#280]
@funderburkjim and @gasyoun may like to have a look at the two commits (based on real corrections submitted by users)

1. short one - 'mw:141468' - https://github.com/sanskrit-lexicon/csl-orig/commit/1ec80a7171e78e98799b547597ffc9c25da6543e
2. long one - 'pwg:43345:Śaṃkavācāryā:Śaṃkarācāryā' - https://github.com/sanskrit-lexicon/csl-orig/commit/291c892d1c1647c7f9692db5c5e8afdd70277828

What should we adopt?

The first one is more convenient to write.
When looking at the `git log` via command line or looking at the history in some git GUI client, the second item has some advantage. 

`git log` in local machine
```
commit 1ec80a7171e78e98799b547597ffc9c25da6543e
Author: drdhaval2785 <drdhaval2785@gmail.com>
Date:   Wed Jul 24 23:21:39 2019 +0530

    mw:141468

commit 291c892d1c1647c7f9692db5c5e8afdd70277828
Author: drdhaval2785 <drdhaval2785@gmail.com>
Date:   Wed Jul 24 23:10:25 2019 +0530

    pwg:43345:Śaṃkavācāryā:Śaṃkarācāryā

```

**Comment by gasyoun** [comment]
> The first one is more convenient to write.

It is important. There are around 60 edits per month?

**Comment by funderburkjim** [comment]
I don't have a strong opinion either way at the moment regarding which is better.

But I do have a question:    What is the anticipated functionality of the csl-orig repository?  [I'm behind on reading @drdhaval2785  many recent GitHub comments - so you may have already answered this elsewhere])

Also, have you proposed a change in the role of the CORRECTIONS repository?

**Comment by drdhaval2785** [comment]
Anticipated functionality of csl-orig is to hold the XXX.txt files of each dictionary. 
This is the repository where the corrections would be made in git. 

hw.py etc will feed on this XXX.txt to generate its output.

There is no change suggested in CORRECTION repository. It currently works via cfr.tsv and manual editing thereof on server. We can leave it as it is.

One reason why I am sugfesting to have dictcode and Lnum is that we may think of updating cfr.tsv programmatically once the correction is made e.g.if there is a correction sughested in MW lnum 12345, and we pass commit message 'mw:12345' in csl-orig ((i.e. we made necessary changes in MW 12345), script can add detail to cfr.tsv on that line mentioning `:Corrected on MM/DD/YYYY`.

That way majority of work can be automated. This feature is not yet implemented. But mentioning it here, for reference.

**Comment by drdhaval2785** [comment]
For catching up, I will request you to have a look at readme of https://github.com/sanskrit-lexicon/csl-pywork first. It will give fair idea about organization of csl-orig and csl-pywork (newly suggested). Their idea is very similar to your csl-websanlexicon i.e. copy / template.
csl-websanlexicon is used as it is. Just wrote a bash script redo_cologne_2020.sh to generate templates for 2020 versions.

**Comment by gasyoun** [comment]
> That way majority of work can be automated. 

Dream come true.

**Comment by drdhaval2785** [comment]
Now the commit messages have been working without any user complaint i.e. @funderburkjim and @drdhaval2785 :)

**Comment by funderburkjim** [comment]
Absolutely -- Have grown to love git and Github.
