### ISSUE TITLE
PGN S link broken

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/COLOGNE#281]
Link to https://www.sanskrit-lexicon.uni-koeln.de/scans/PGNScan/2014/web/webscan/index.php from homepage broken.

**Comment by drdhaval2785** [comment]
https://www.sanskrit-lexicon.uni-koeln.de/scans/PGNScan/2014/webscan/index.php
Link from current homepage is working fine. Tested. Found OK. Closing.

**Comment by funderburkjim** [comment]
The home page should link to 2020 for most things.

But, to avoid duplication of the large set of images,  current 2020 displays refer to the
2014 location.
