### ISSUE TITLE
BEN meta conversion

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#285]
As @drdhaval2785 noted in preparatory work on csl-pywork (see [analysis.md](https://github.com/sanskrit-lexicon/csl-pywork/blob/master/v00/analysis.md)),   Benfey doesn't have hwparse.py.  Further investigation shows that somehow the meta-line conversion of the dictionaries missed BEN.

Need to do this before continuing work on csl-pywork.

**Comment by funderburkjim** [comment]
## meta conversion complete

The next few comments report on points of interest noticed during the conversion.

**Comment by funderburkjim** [comment]
## apidev problem with `<pic>`

If you look up 'vatsa' in the basic, list, etc. displays,  you'll see an image:
![image](https://user-images.githubusercontent.com/6393033/64926927-aea9a180-d7d1-11e9-9e48-dec7730d1308.png)

However, using displays based on apidev, such as simple search, this image is not properly shown:
![image](https://user-images.githubusercontent.com/6393033/64926938-ddc01300-d7d1-11e9-95df-81edfafe84ff.png)

The actual location of the image is web/images/vatsa.png, and the code to generate an html `<img>` element is in basicdisplay.  This code locates the image at a relative url: `../../web/images/vatsa.png`.  This relative url works when the basicdisplay code is in the ben/web/webtc directory, but is the wrong url when basicdisplay is used in apidev.

An issue has been opened for this bug in csl-apidev.

**Comment by funderburkjim** [comment]
## Greek text

Greek text appears in 1276 lines of the digitization ben.txt.
It appears as `<lang n="greek"></lang>` in the digitization.
As the 'vatsa' display above illustrates,  this missing Greek text is displayed as `(greek)`.

**Comment by funderburkjim** [comment]
## downloads

I followed the model of CAE for downloads.   
Here is the basic pattern for the 3 downloads available via the downloads page in this model:
* xml directory to contain: xxx.dtd, xxx.xml, xxxheader.xml, xxx-meta2.txt
* txt directory to contain: xxx.txt, xxxheader.xml xxx-meta2.txt
* web directory a copy of ../web directory (without pdfpages subdirectory)

Currently an unknown subset of dictionaries follows this model.

We should apply this model (or possibly some better variant model) to all the dictionaries.
This might require a change to csl-websanlexicon  webtc/downloads.html,  as well as changes to
the downloads directory for each dictionary.

**Comment by funderburkjim** [comment]
## update of csl-orig
The csl-orig repository was initialized for benfey before this meta-line conversion.
Have replaced the ben.txt of csl-orig with this meta-line version.
> 1 file changed, 148306 insertions(+), 94201 deletions(-)

**Comment by gasyoun** [comment]
> We should apply this model (or possibly some better variant model) to all the dictionaries.

Would love to change it. Because it's not obvious what I need, if I do not know much ahead.

**Comment by drdhaval2785** [comment]
@funderburkjim I guess now BEN is at par with rest of the dictionaries and this issue is closable.

**Comment by funderburkjim** [comment]
Yes. Agree.
