### ISSUE TITLE
Three new repositories

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#288]
Three repositories have been added:
* [csl-kale](list-0.2s_xampp.html)
* [csl-westergaard](https://github.com/sanskrit-lexicon/csl-westergaard)
* [csl-whitroot](https://github.com/sanskrit-lexicon/csl-whitroot)

Each of these is a  self-contained php application for a *scanned edition*.

**Comment by funderburkjim** [comment]
## home page links

The sanskrit-lexicon home page provides links to these:

![image](https://user-images.githubusercontent.com/6393033/68536965-c9a81600-0329-11ea-90d2-53d4307933c5.png)


## links from MW display

Links to the Westergaard and Whitney roots displays occur as needed for roots in the MW dictionary displays.

![image](https://user-images.githubusercontent.com/6393033/68536978-45a25e00-032a-11ea-8e32-d85b3c692482.png)

**Comment by funderburkjim** [comment]
## non-Cologne installations

The repositories are treated as optional 'modules' for a local installation.

They may be installed simply by cloning within the 'cologne' directory of the local installation:
```
git clone https://github.com/sanskrit-lexicon/csl-kale.git
git clone https://github.com/sanskrit-lexicon/csl-westergaard.git
git clone https://github.com/sanskrit-lexicon/csl-whitroot.git
```

When the local homepage is re-installed,  a homepage link is presented for those modules that
are installed locally; if the module is not present locally, the local homepage does not show the link.

When displaying MW locally,  if the local csl-whit or csl-westergaard installations are detected, then the MW links to westergaard or whitney go to the local copies.   If the local installations are not detected, then the links go to Cologne.

**Comment by gasyoun** [comment]
> if the module is not present locally, the local homepage does not show the link

Everything is taken care of, as usual.
