### ISSUE TITLE
Logo = Home link

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/Cologne#29]
I propose to make every logo clickable. If we click on http://www.sanskrit-lexicon.uni-koeln.de/scans/PWGScan/2013/web/webtc/indexcaller.php left upper logo, we should get to the homepage. One could leave it in "Corrections Downloads      Home Help" as well, but it's hard to notice and not a very well practice indeed.

**Comment by gasyoun** [comment]
> http://www.sanskrit-lexicon.uni-koeln.de/monier1/webtc/indexcaller.php

Not fixed.

**Comment by funderburkjim** [comment]
This is an old display.

What about changing  this link to a redirect to http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/index.php ?

Or, alternately, adding a 'deprecated' message ?

**Comment by gasyoun** [comment]
> This is an old display.

I know. But even my friends still used it. Kill it or develop it :+1: 

> What about changing this link to a redirect to http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/index.php ?

I would redirect it.

**Comment by drdhaval2785** [comment]
Logo leads to home links now at least for current versions of dictionaries.
