### ISSUE TITLE
simple search simple url

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#294]
There is now a way to get the simple-search program with a simpler url.

The basic url at Cologne is: https://www.sanskrit-lexicon.uni-koeln.de/simple/
 
A complete form is:
 https://www.sanskrit-lexicon.uni-koeln.de/simple/mw/danda/iast/no

The complete form has values for the 4 parameters (the 'input' is set to 'simple').
dictionary code, citation (headword), output , accent
This would be the reference form.

The parameters need to be in the given order.  You should get meaningful results by leaving
off output and accent  (the prior settings, stored in cookies, will be used).

This is also implemented in local installations. Basic url is
`http://localhost/cologne/simple/`.   The parameter interpretation is the same.

**Comment by funderburkjim** [comment]
## .htaccess

At Cologne, the .htaccess file is in the root directory, and 
the rewrite rule is
```
RewriteRule simple/(.*$) scans/awork/apidev/simple-search/v1.0/list-0.2s_rw.php
```

In local installations, the .htaccess file is assumed to be in the *cologne* directory, and
the rewrite rule is
```
RewriteRule simple/(.*$) csl-apidev/simple-search/v1.0/list-0.2s_xampp_rw.php
```

**Comment by funderburkjim** [comment]
## the BASE html element

This is a technical note.  In the html of the implementing program list-0.2s_rw.php at Cologne,
you see:
```
<!DOCTYPE html>
<html>
<head>
<META charset="UTF-8">
<title>list-0.2s Cologne</title>
<!-- ref=https://www.w3.org/TR/html4/struct/links.html#edef-BASE -->
<BASE href="https://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/simple-search/v1.0/list-0.2s_rw.php">
...
<script type="text/javascript" src="../../sample/dictnames.js"></script>
...
</head>
...
</html>
```
That BASE element is required in order for the relative address elsewhere in the html to be
correctly interpreted.

An example of such a relative address is `../../sample/dictnames.js` .
Without the base specification, the relative address is interpreted as if relative to some the 
address that shows in the browser address. For example, with this url (and no base element)
`https://www.sanskrit-lexicon.uni-koeln.de/simple/mw/danda/iast/no`.
then ../../

For example, a test shows that the Chrome browser looks for dictcodes.js at

`https://www.sanskrit-lexicon.uni-koeln.de/simple/mw/sample/dictnames.js`

which is nonsense, and provides a javascript error.

Anyway, the base element takes care of this.
A similar base element is required in the local installation also.

**Comment by gasyoun** [comment]
> The basic url at Cologne is: https://www.sanskrit-lexicon.uni-koeln.de/simple/

It opened GRA by default. Because I had used it as last dictionary at Cologne?

**Comment by funderburkjim** [comment]
> because I had used it as last dictionary at Cologne?

Yes.

> Can it be shorter by using 's' instead of 'simple'  or by omitting 'simple' ?

Technically yes.  Don't think a good idea.

> Can it be shorter by omitting 'www' ?

No.
  https://sanskrit-lexicon.uni-koeln.de/simple/mw/manda ?  gives a server 'Privacy error'.  

> 'all' mode

https://www.sanskrit-lexicon.uni-koeln.de/simple/all/manda 

With 'www' and 'simple',  this url would make sense:   'all' means `in all dictionaries`.

However, It requires some change to the underlying application --- both in how to compute
and also how to display.  Likely hard.

Will submit an issue as enhancement suggestion.

**Comment by gasyoun** [comment]
> Technically yes. Don't think a good idea.

Lenght of URL is SOOOO important. No need to have the senseless word simple in URL. simple is by default.

> gives a server 'Privacy error'.

@drdhaval2785 can you ask the webmaster by email, please? Or should I?

> Likely hard.

Understood.

**Comment by funderburkjim** [comment]
> Length of URL is SOOOO important

Why?  Please provide reference discussions if available.

There seem to be two factors:
* length of url
* memorability of url

There is not much difference in length between 's' and 'simple'  - 5 letters.
's' is too short to mean anything, hard to remember.
'simple' is clearly related to one of the displays; `simple` :) to remember.

Have you considered using bit.ly or goo.gl ?

**Comment by gasyoun** [comment]
> bit.ly

Has become paid.

> goo.gl 
Discontinued by March 30, 2019

> There seem to be two factors:
Three. Long URLs tend to brake. When you make a Facebook post or copypaste to Skype - it's hard to deal with long URLs, they take more than a line.  In the world of SEO 5 letters is a lot. Even for a single letter you have to fight hard.

**Comment by funderburkjim** [comment]
Am leaving this as 'simple', and closing this.

It seems Marcis and I have different opinions currently. I like 'simple', he prefers  something shorter,
maybe 's'.

We can raise a similar issue later if it still seems important.  

BTW, @drdhaval2785   are you going to investigate the 'www' question with webmaster?

**Comment by gasyoun** [comment]
> I like 'simple', he prefers something shorter, maybe 's'.

`s` can stand for Sanskrit is well...
