### ISSUE TITLE
STC abbreviations

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#298]
In the stc dictionary (Stchoupak Dictionnaire Sanscrit-Français),  markup has been added, in the stc.txt digitization, for abbreviations.

This list of abbreviations so marked is from the [Front matter](https://www.sanskrit-lexicon.uni-koeln.de/scans/csldev/csldoc/build/dictionaries/prefaces/stcpref/stcpref04.html).  

Odile Caujolle provided digitization of this list.

See https://github.com/sanskrit-lexicon/csl-orig/tree/master/v02/stc/abbrev for the programming.

**Comment by funderburkjim** [comment]
## no change needed in dtd
When stc.txt is converted to stc.xml, the abbreviation markup `<ab>X</ab>` will be new xml elements.  These must validate against stc.dtd.  However,  since stc.dtd is made from one.dtd,
and since one.dtd already has the `<ab>` markup, there is in fact no change required for 
the validation of stc.xml to stc.dtd.

## display of abbreviations
For the abbreviation tooltips to appear in the displays of stc,  some additional steps are required.
* csl-pywork/v02
  * add distinctfiles/stc/pywork/stcab  --- directory which has steps to make stcab.sqlite, used by
     displays to get tooltip for abbreviations.
  * modify inventory.txt so the stcab files will be copied to stc/pywork/ during regeneration of stc.
  * modify makotemplates/pywork/redo_postxml.sh  so  the redo_postxml.sh for stc will 
    make use of stcab.
* csl-websanlexicon : Actually no changes required here.  The basicadjust.php script already
   knows to look for abbreviation tooltips in stcab.sqlite, and the basicdisplay.php script already
   knows how to generate tooltips if they are present.

That's it!

**Comment by funderburkjim** [comment]
@drdhaval2785   Maybe now is a good time for you to revisit the acc abbreviations you worked on
several years ago: They never were added to the production acc.txt. 

The steps outlined above for stc should apply to acc with very few differences.  

One difference is regarding attributes of the `<ab>` element -- As I recall, you included some
information in certain 'ab' attributes and attribute values,  which might make the acc attributes more
complex than those of stc, bur.   This complexity might be unavoidable, or it might be possible to
adjust the acc abbreviations to fit them into the simpler stc model. 

Let's discuss further if you are interested.

**Comment by gasyoun** [comment]
> In the stc dictionary (Stchoupak Dictionnaire Sanscrit-Français), markup has been added

Makes me want to test it.

> They never were added to the production acc.txt.

Yes, of great interest. Martin is scanning https://www.worldcat.org/title/new-catalogus-catalogorum-an-alphabetical-register-of-sanskrit-and-allied-works-and-authors/oclc/10393298 so if both combined one day, it would be something to research for years after.

**Comment by drdhaval2785** [comment]
I will try to make changes to acc.txt based on STC experience. But it seems that I will have to reinvent the wheel mostly. Because the text was converted to IAST in the meantime. Therefore the old script based on AS may not work well.

**Comment by gasyoun** [comment]
> I will try to make changes to acc.txt based on STC experience.

Of great interest.

**Comment by drdhaval2785** [comment]
#316 tracks the ACC work. So safe to close this now. Referring to the issue, so that that issue would also have link to documentation.
