### ISSUE TITLE
question re sūtrakrīḍā

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#301]
A user (Stephan Claassen) asks the following question:

> I am investigating the Sanskrit word sūtrakrīḍā, which is usually
listed as one of the 64 Kalas. It could be the earliest reference to
string figure making, of which I am a researcher.
In Boehtlingk's large dictionary it is translated as:
sūtrakrīḍā f. Fadenspiel unter den 64 Künsten Verz. D. Oxf. H. 217,a,8.
Problem: the Verz. D. Oxf. H. 217,a,8. is not in his list of
abbreviations (at least, I was not able to trace it).
Do you know what this reference could be? Undoubtedly it is
"Verzeichnis der Oxforter Handschriften, but what publication does he
mean?

Can anyone provide some help ?

**Comment by gasyoun** [comment]
> but what publication does he mean

Not aware of it. Always thought there is no such book.

**Comment by Andhrabharati** [comment]
@funderburkjim 

Now that the **Verz. d. Oxf. H.** pages got linked in PWG etc., you might like to post a message to this user and close this issue.

**Comment by funderburkjim** [comment]
Amazingly, I found Mr. Claasen's email and replied accordingly with the link.
https://sanskrit-lexicon-scans.github.io/Oxf_Cat_Aufrecht/index.html?217

<img width="917" alt="image" src="https://github.com/user-attachments/assets/24621034-7b15-4e29-b572-e8e73cbffa43">
