### ISSUE TITLE
Spondias_mangifera, Pentoptera_tomentosa

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/Cologne#31]
In http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/disp2/index.php the word pItana has Spondias_mangifera , Pentoptera_tomentosa and Pinus_Deodora with "_" - flora names in italics. Should it remain so - without italics (book has italics) and with additional "_"?

**Comment by drdhaval2785** [comment]
Corrected in new version.
