### ISSUE TITLE
Revive 'semi-numeric' Edition of Stchoupak

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#310]
This is the 'SD' link For STC dictionary on homepage: [SD]

This program uses a Perl cgi script.  I disabled the parts that would fail on the new server.
So input and output require HK transliteration.

I revived this because it is still an interesting idea for displaying a dictionary.

It depends on a database which associates with each headword, the page and page-position.
Thus, the scanned image is highlighted for the word.

Of course, this could be written in something besides Perl.  It also uses the mysql database available on the
Cologne server; and this database could be changed to sqlite.

But probably there is no real interest in doing this modernizing now,

**Comment by funderburkjim** [comment]
The Home page link (Under STC) is [SD](https://www.sanskrit-lexicon.uni-koeln.de/scans/STCScan/web/index_fr.php)

**Comment by gasyoun** [comment]
> But probably there is no real interest in doing this modernizing now

Exactly. If the French do not care, why should we?

**Comment by funderburkjim** [comment]
I think this idea of having dictionary headwords link to portions of scanned images is
interesting.   So it is worth keeping as an exemplar.

**Comment by gasyoun** [comment]
> headwords link to portions of scanned images is interesting

I mean of course it's great because it saves time. But that's something UI related. And we still have thousands of typos to fix first.
