### ISSUE TITLE
Revive a deprecated PWG display

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#313]
The link on home page is [Boehtlingk & Roth Sanskrit-German Dictionary, 2011](https://www.sanskrit-lexicon.uni-koeln.de/scans/PWGScan/disp2/index.php),

The changes are similar to the changes for STC (#310) and WIL (#311);
namely, Perl code is modified:
* no transcoding  (everything is HK)
* no other adjustments.

This also uses a 2011 version of the digitization of PWG.

**Comment by gasyoun** [comment]
> This also uses a 2011 version of the digitization of PWG.

Why not kill it?

**Comment by funderburkjim** [comment]
*  Some historical interest  (What things used to look like)
*  Relatively easy to keep.
