### ISSUE TITLE
Available displays

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/COLOGNE#32]
I have a suggestion. I love standards. I'm a Virgo, maybe that's the reason, but anyway. Usually Basic display comes first.
http://www.sanskrit-lexicon.uni-koeln.de/scans/PEScan/2013/web/index.php
Available displays
Basic display
List display
Advanced Search
Mobile-friendly display
downloads

In http://www.sanskrit-lexicon.uni-koeln.de/scans/PGNScan/2014/web/index.php above it is "Scan display" - let's move it to the bottom of the list. Otherwise not very convenient, I'm used clicking on the first link.
Available displays
Scan display
Basic display
List display
Advanced Search
Mobile-friendly display
downloads

And why is downloads the only one without initial capital letter?

**Comment by drdhaval2785** [comment]
Not much traction.
