### ISSUE TITLE
LIbrary

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/COLOGNE#323]
In mw.txt at https://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2020/web/webtc/download.html the line `<!-- Copyright Universitat Koln and The Sanskrit LIbrary 2012; for details see MWHeader.xml -->` contains `LIbrary` instead of `Library`.

**Comment by funderburkjim** [comment]
Change installed.
