### ISSUE TITLE
API endpoint for  servepdf

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#328]
Here is the current usage of the csl-apidev version of servepdf:

* dict   Cologne dictionary code.  Not case sensitive
* either
  * page   (only the numeric page number is used.  However, the program accepts,
     but ignores, column numbers depending on Dictionary).  The page does not
     have to be zero-filled.  For some dictionaries, a volume number is required.
  * key  A headword, default spelling assumed SLP1
     * optional 'input' (HK, SLP1, etc)  in which case the key is spelled accordingly

Examples:
* https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=AP90&page=700-a
* https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=AP90&page=0500
* https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=PW&key=aGga&input=HK
* https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=PWG&page=2-0767

## return
servepdf currently returns a string of HTML.

When key is used, there is returned the html for the FIRST matching entry.

If the page is 'invalid' for the dictionary,  the FIRST page in the dictionary is returned.

For API purposes, perhaps  some JSON object should be returned.
@drdhaval2785  -- please specify required JSON return, and I'll make a slightly 
different endpoint that returns JSON.
Perhaps there should be a 'status' code in the return (e.g. 200 or 404) indicating
success or failure.

**Comment by drdhaval2785** [comment]
I think the JSON should return all the matches instead of the current FIRST match. 
I understand that for a human, it is not advised to open 4/5 pages having a match.
But APIs are for machines. so, we should return all the matches.
For this purpose, I have taken up the example of ACC and headword 'kiraRAvalI'
When we do this search, there are following matches

```
lnum:pc
4246:1-107
4247:1-107
4248:1-107
30447:1-779
32198:2-021
39653:2-194
42642:3-023
```

In JSON we should output all the matches in an array of ['headword', 'lnum', 'pdflink']

I will try to write the JSON in the next comment.

**Comment by drdhaval2785** [comment]
# Expected JSON
``json
{
"pdflinks": [
    {"hw": "kiraRAvalI", "lnum": "4246", "pdf": "www.sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2014/web/pdfpages/pg1_107.pdf"},
    {"hw": "kiraRAvalI", "lnum": "4247", "pdf": "www.sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2014/web/pdfpages/pg1_107.pdf"},
    {"hw": "kiraRAvalI", "lnum": "4248", "pdf": "www.sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2014/web/pdfpages/pg1_107.pdf"},
    {"hw": "kiraRAvalI", "lnum": "30447", "pdf": "www.sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2014/web/pdfpages/pg1_779.pdf"},
    {"hw": "kiraRAvalI", "lnum": "32198", "pdf": "www.sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2014/web/pdfpages/pg2_021.pdf"},
    {"hw": "kiraRAvalI", "lnum": "39653", "pdf": "www.sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2014/web/pdfpages/pg2_194.pdf"},
    {"hw": "kiraRAvalI", "lnum": "42642", "pdf": "www.sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2014/web/pdfpages/pg3_023.pdf"}
]
}
```

**Comment by drdhaval2785** [comment]
> Perhaps there should be a 'status' code in the return (e.g. 200 or 404) indicating
success or failure.

We do not need to return the status code. It will be handled by flask module. It gives 200 for good response and 500 for internal server error.

**Comment by drdhaval2785** [comment]
@funderburkjim 
A side question : Why `2014` in the pdf links? Not `2020`?

**Comment by drdhaval2785** [comment]
# Alternate JSON

```json
{
"pdflinks": [
	"www.sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2014/web/pdfpages/pg1_107.pdf",
	"www.sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2014/web/pdfpages/pg1_779.pdf",
	"www.sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2014/web/pdfpages/pg2_021.pdf",
	"www.sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2014/web/pdfpages/pg2_194.pdf",
	"www.sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2014/web/pdfpages/pg3_023.pdf"
]
}
```
I would love to have the first option mentioned under https://github.com/sanskrit-lexicon/COLOGNE/issues/328#issuecomment-751314476 over this.
If finding hw for given lnum / lnum for given hw is done by the script servepdf.php, I would love to have all of them in the output.
If that is not done, and is too much of hassle, it would be OK if we give this minimalist alternate version as output.

**Comment by drdhaval2785** [comment]
# If word / lnum / page number is not found

Return
```json
{"pdflinks": []}
```

No need to return the first page of the dictionary in this case.

**Comment by drdhaval2785** [comment]
@funderburkjim 

I would request your attention urgently in this issue. If you can create JSON API as asked for in https://github.com/sanskrit-lexicon/COLOGNE/issues/328#issuecomment-751314476, I would be able to complete development of this endpoint.

**Comment by gasyoun** [comment]
> drdhaval2785 added this to the January 2021 milestone 4 hours ago

Love the new way or organizing work.

**Comment by funderburkjim** [comment]
## Preliminary results

The results below are from a localhost version.
They show a 'pretty-printed' html form.
@drdhaval2785  please comment, and I'll adjust accordingly and, when ready, upload to Cologne server.

The calling sequence will be
.../csl-apidev/api0/servepdf.php?<PARAMETERS>
These were created with an additional '&pretty' parameter,  which generates html with
an ad-hoc pretty-printing of the JSON.
Without '&pretty',  just the JSON is returned.

## the acc kiraRAvalI example
<details><summary>http://localhost/cologne/csl-apidev/api0/servepdf.php?dict=acc&key=aSva&pretty</summary>
<pre>

status = 200
errorinfo =
request:
   'dict' : 'acc'
   'page' : ''
   'key' : 'kiraRAvalI'
   'keyslp1' : 'kiraRAvalI'
   'input' : 'slp1'
links: (7)
Link # 1:
   'page' : '1-107'
   'key1' : 'kiraRAvalI'
   'lnum' : '4246'
   'pageurl' : '//www.sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2014/web/pdfpages/pg1_107.pdf'
   'prevpage' : '1-106'
   'nextpage' : '1-108'
Link # 2:
   'page' : '1-107'
   'key1' : 'kiraRAvalI'
   'lnum' : '4247'
   'pageurl' : '//www.sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2014/web/pdfpages/pg1_107.pdf'
   'prevpage' : '1-106'
   'nextpage' : '1-108'
Link # 3:
   'page' : '1-107'
   'key1' : 'kiraRAvalI'
   'lnum' : '4248'
   'pageurl' : '//www.sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2014/web/pdfpages/pg1_107.pdf'
   'prevpage' : '1-106'
   'nextpage' : '1-108'
Link # 4:
   'page' : '1-779'
   'key1' : 'kiraRAvalI'
   'lnum' : '30437'
   'pageurl' : '//www.sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2014/web/pdfpages/pg1_779.pdf'
   'prevpage' : '1-778'
   'nextpage' : '1-780'
Link # 5:
   'page' : '2-021'
   'key1' : 'kiraRAvalI'
   'lnum' : '32198'
   'pageurl' : '//www.sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2014/web/pdfpages/pg2_021.pdf'
   'prevpage' : '2-020'
   'nextpage' : '2-022'
Link # 6:
   'page' : '2-194'
   'key1' : 'kiraRAvalI'
   'lnum' : '39653'
   'pageurl' : '//www.sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2014/web/pdfpages/pg2_194.pdf'
   'prevpage' : '2-193'
   'nextpage' : '2-195'
Link # 7:
   'page' : '3-023'
   'key1' : 'kiraRAvalI'
   'lnum' : '42642'
   'pageurl' : '//www.sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2014/web/pdfpages/pg3_023.pdf'
   'prevpage' : '3-022'
   'nextpage' : '3-024'</pre>
</details>

## a particular page
<details><summary>http://localhost/cologne/csl-apidev/api0/servepdf.php?dict=acc&page=1-107&pretty</summary>
<pre>

status = 200
errorinfo =
request:
   'dict' : 'acc'
   'page' : '1-107'
   'key' : ''
   'keyslp1' : ''
   'input' : 'slp1'
links: (1)
Link # 1:
   'page' : '1-107'
   'key1' : ''
   'lnum' : ''
   'pageurl' : '//www.sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2014/web/pdfpages/pg1_107.pdf'
   'prevpage' : '1-106'
   'nextpage' : '1-108'</pre>
</details>

## invalid dictionary code
<details><summary>http://localhost/cologne/csl-apidev/api0/servepdf.php?dict=acd&page=1-107&pretty</summary>
<pre>
status = 404
errorinfo = servepdf ERROR: Unknown dictionary code: acd
request:
   'dict' : 'acd'
   'page' : '1-107'
   'key' : ''
   'keyslp1' : ''
   'input' : 'slp1'
links: (0)</pre>
</details>

## invalid page
<details><summary>http://localhost/cologne/csl-apidev/api0/servepdf.php?dict=mw&page=12345&pretty</summary>
<pre>
status = 404
errorinfo = servepdf ERROR: No pages found
request:
   'dict' : 'mw'
   'page' : '12345'
   'key' : ''
   'keyslp1' : ''
   'input' : 'slp1'
links: (0)</pre>
</details>

## invalid slp1 key
<details><summary>http://localhost/cologne/csl-apidev/api0/servepdf.php?dict=mw&key=azva&pretty</summary>
<pre>
status = 404
errorinfo = servepdf ERROR: No pages found
request:
   'dict' : 'mw'
   'page' : ''
   'key' : 'azva'
   'keyslp1' : 'azva'
   'input' : 'slp1'
links: (0)</pre>
</details>

## valid hk key
<details><summary>http://localhost/cologne/csl-apidev/api0/servepdf.php?dict=mw&key=azva&input=hk&pretty</summary>
<pre>

status = 200
errorinfo =
request:
   'dict' : 'mw'
   'page' : ''
   'key' : 'azva'
   'keyslp1' : 'aSva'
   'input' : 'hk'
links: (11)
Link # 1:
   'page' : '114'
   'key1' : 'aSva'
   'lnum' : '19869'
   'pageurl' : '//www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/MWScanpdf/mw0114-azokataru.pdf'
   'prevpage' : '0113'
   'nextpage' : '0115'
Link # 2:
   'page' : '114'
   'key1' : 'aSva'
   'lnum' : '19869.1'
   'pageurl' : '//www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/MWScanpdf/mw0114-azokataru.pdf'
   'prevpage' : '0113'
   'nextpage' : '0115'
Link # 3:
   'page' : '114'
   'key1' : 'aSva'
   'lnum' : '19869.2'
   'pageurl' : '//www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/MWScanpdf/mw0114-azokataru.pdf'
   'prevpage' : '0113'
   'nextpage' : '0115'
Link # 4:
   'page' : '114'
   'key1' : 'aSva'
   'lnum' : '19869.3'
   'pageurl' : '//www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/MWScanpdf/mw0114-azokataru.pdf'
   'prevpage' : '0113'
   'nextpage' : '0115'
Link # 5:
   'page' : '114'
   'key1' : 'aSva'
   'lnum' : '19869.4'
   'pageurl' : '//www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/MWScanpdf/mw0114-azokataru.pdf'
   'prevpage' : '0113'
   'nextpage' : '0115'
Link # 6:
   'page' : '114'
   'key1' : 'aSva'
   'lnum' : '19869.5'
   'pageurl' : '//www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/MWScanpdf/mw0114-azokataru.pdf'
   'prevpage' : '0113'
   'nextpage' : '0115'
Link # 7:
   'page' : '114'
   'key1' : 'aSva'
   'lnum' : '19869.6'
   'pageurl' : '//www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/MWScanpdf/mw0114-azokataru.pdf'
   'prevpage' : '0113'
   'nextpage' : '0115'
Link # 8:
   'page' : '114'
   'key1' : 'aSva'
   'lnum' : '19869.7'
   'pageurl' : '//www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/MWScanpdf/mw0114-azokataru.pdf'
   'prevpage' : '0113'
   'nextpage' : '0115'
Link # 9:
   'page' : '114'
   'key1' : 'aSvA'
   'lnum' : '19869.8'
   'pageurl' : '//www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/MWScanpdf/mw0114-azokataru.pdf'
   'prevpage' : '0113'
   'nextpage' : '0115'
Link # 10:
   'page' : '114'
   'key1' : 'aSva'
   'lnum' : '19869.805'
   'pageurl' : '//www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/MWScanpdf/mw0114-azokataru.pdf'
   'prevpage' : '0113'
   'nextpage' : '0115'
Link # 11:
   'page' : '115'
   'key1' : 'aSva'
   'lnum' : '20089'
   'pageurl' : '//www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/MWScanpdf/mw0115-azvakarNaka.pdf'
   'prevpage' : '0114'
   'nextpage' : '0116'</pre>
</details>

**Comment by drdhaval2785** [comment]
Pretty printed JSON would be better to check.
I am not sure whether `Link # 1` is a list or dict in this HTML version.

Otherwise the data seems sufficient.

**Comment by gasyoun** [comment]
> Otherwise the data seems sufficient.

So let's upload to Cologne and play with it.

**Comment by funderburkjim** [comment]
Version now uploaded to Cologne.
Sample url:

https://sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/api0/servepdf.php?dict=mw&key=deva

Without '&pretty', JSON is returned --- good for api usage.

Use '&pretty'  if you put the url into a browser address.

Note the 'getsuggest' api endpoint is now also in api0:

https://sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/api0/getsuggest.php?dict=mw&term=de

getsuggest does not know of 'pretty' at least for now.

**Comment by gasyoun** [comment]
> Sample url: https://sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/api0/servepdf.php?dict=mw&key=deva

Thanks, Jim! @drdhaval2785 is it the one?

```
{"request":{"dict":"mw","page":"","key":"deva","keyslp1":"deva","input":"slp1"},"errorinfo":"","status":200,"links":[{"page":"492","key1":"deva","lnum":"95518","pageurl":"\/\/www.sanskrit-lexicon.uni-koeln.de\/scans\/MWScan\/MWScanpdf\/mw0492-dRSTAriSTa.pdf","prevpage":"0491","nextpage":"0493"},{"page":"492","key1":"deva","lnum":"95519","pageurl":"\/\/www.sanskrit-lexicon.uni-koeln.de\/scans\/MWScan\/MWScanpdf\/mw0492-dRSTAriSTa.pdf","prevpage":"0491","nextpage":"0493"},{"page":"492","key1":"deva","lnum":"95520","pageurl":"\/\/www.sanskrit-lexicon.uni-koeln.de\/scans\/MWScan\/MWScanpdf\/mw0492-dRSTAriSTa.pdf","prevpage":"0491","nextpage":"0493"},{"page":"492","key1":"deva","lnum":"95521","pageurl":"\/\/www.sanskrit-lexicon.uni-koeln.de\/scans\/MWScan\/MWScanpdf\/mw0492-dRSTAriSTa.pdf","prevpage":"0491","nextpage":"0493"}
```

Even I can read https://sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/api0/servepdf.php?dict=mw&key=deva&pretty

**Comment by drdhaval2785** [comment]
https://kosha.sanskritworld.in/#!/default/get_pkt (For headword based search)
https://kosha.sanskritworld.in/#!/default/get_pkp (For page based search)

API is up and running.
Thanks @funderburkjim . 
I have got what I wanted in this issue.
This issue is now closeable.
