### ISSUE TITLE
Ways to Enter Devanagari and/or IAST

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#33]
In the Apte dictionary test on wikisource, Sanskrit is represented in the pages using the Kyoto-Harvard Transliteration.  However, in the accompanying scanned images, the Sanskrit is represented in Devanagari.  So there is a gap between what the user types (KH) and what the scan shows (Devanagari). Also, although editor Shalu has mastered the HK transliteration method, she has mentioned the preference for entering Devanagari directly,   No doubt other potential contributors would have the same preference. This observation is by way of preface to the following question.

**How do computer users proficient in Devanagari enter Devanagari into computer files?**

A bit of web research provides several possibilities, but  no definite answer.  Similarly, the List display of the Cologne dictionaries makes provides several ways to enter Devanagari in the context of that program  
It would be useful to know if there is a predominant way Devanagari is entered; for then software could be developed which would take this into account.

Incidentally, a similar question regards the typical way users enter IAST.

**Comment by gasyoun** [comment]
@funderburkjim @drdhaval2785 
How about Input convention : plain roman with no diacritics
http://www.ragalalit.net/misc/sanskrit_search.html `visnu`
gives a link to http://sanskrit.inria.fr/cgi-bin/SKT/sktsearch?lex=SH&q=visnu that links to http://sanskrit.inria.fr/DICO/61.html#vi.s.nu - a reincarnation of Monier Williams.

If we search `visnu` at http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/webtc/indexcaller.php
we get
not found: visnu
dbg: key = visnu
 विस्नु
still only HK, SLP1 and ITRANS is there - no devanagari or IAST input possible. That's even worse.
Do you think we do not need the `plain roman with no diacritics` part? I guess @drdhaval2785 is well-versed enough and we can at least ask if I'm not the only one to feel the need to make the search more friendly.

**Comment by funderburkjim** [comment]
@gasyoun   Re making the search more friendly.   
My reluctance to address such questions is not based on a
low opinion of the ideas.  Rather, it is something for which I do not see a quick fix.  And there are other things I would rather work on.  

All the data and code for these dictionaries IS available via downloads at Cologne,  so anyone can 
reconstruct a local environment almost identical to the one that I use at Cologne. [and if there are 
tools or data at Cologne that I have inadvertently omitted from download availability, I'll work to fill the gap.]

What is needed for the user interface enhancement ideas to materialize is, I think, someone who 
a. has programming skills, and
b. has strong motivation to create these enhancements.

So far, Dhaval and I seem to be the only participants in this sanskrit-lexicon project who have the 
programming skills.   I have just stated that I don't currently have the motivation to focus on these UI enhancement issues.  I can't speak for Dhaval.

**Comment by gasyoun** [comment]
As per `something for which I do not see a quick fix. And there are other things I would rather work on.` agree and understand. What's your take @drdhaval2785 ?

**Comment by drdhaval2785** [comment]
The ways to enter Devanagari varies from person to person. Some use
Inscript keyboard like Shalu. While some use IMEs like me. People who type
in Devanagari know which method is suitable for them. So in my opinion all
that is necessary is to install Devanagari to SLP1 converter in the
background before the word gets processed.

Just to help the user who is not proficient in typing in Devanagari a
couple of links i.e. the inscript one and on IME one would suffice in the
help file.

**Comment by gasyoun** [comment]
You want people to locally convert Devanagari to SLP1 and copypaste it? You do not understand why https://github.com/sanskrit-lexicon/Cologne/issues/33#issuecomment-95493233 should be there? People do not know what they search, before they find it sometimes.

**Comment by Shalu411** [comment]
There is a strong need for choice.. if it does not hurt.
Sometimes when we search for a word, we might not know the way the word is entered in the dictionary. Only solution is to do some guess work, with different combinations. 
One issue is- each dictionary having different standards. 
But usually there is a lot of confusion between --
श/ ष/ स.. 
and अल्पप्राणs and महाप्राणs.. eg. क/ ख;   द/ ध etc.
Then, व/ ब; 
र/ ल; 
Oh, so many.
List Display might help when we are using Devanagari, but sometimes no.
Also, there are lot of sandhi-combinations as well in words. So we must have some choice in word-entering from user's point of view.
So I want different ways of entry first. 
second - if nothing found, to use fuzzy to look for similarly sounding possible word solutions.
I had not noted the instances where I needed such options, but will provide examples once I get back on any such instance.
Do I make myself clear?

**Comment by drdhaval2785** [comment]
Marcis i dont want people to convert devanagari to SLP1. They can enter it
in devanagari. The backend code will convert it to SLP1 or any other format
by which Jim fires query in his database.

**Comment by funderburkjim** [comment]
As an experiment, try this [development](http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/webtcdev/indexcaller.php) version of Basic Display for MW.
Two Additional input methods are available - Devanagari and IAST.
My *very* limited test suggests this may work properly.

**Comment by gasyoun** [comment]
@funderburkjim thanks, works well.
LEGO: `ā ī ū ṛ ṝ ḷ ḻ ṅ ñ ṭ ḍ ṇ ś ṣ ḥ ṁ ṃ
Ā Ī Ū Ṛ Ṝ Ḻ Ṅ Ñ Ṭ Ḍ Ṇ Ś Ṣ Ḥ Ṁ` for testing.
If I search for `nīla` or `NĪLA` - should be no difference. Sometimes roots are written in capital only letters and there should be no difference in IAST.
Orthographic variations to be added:
`ṁ = ṃ
ś = ç
ṅ = ṉ
ḷ = ḻ
ō = o
ē = e
āi = ai
āu = au`

**Comment by drdhaval2785** [comment]
Devanagari works well.
IAST corrections suggested by @gasyoun are important.

**Comment by funderburkjim** [comment]
ṁ = ṃ   Already was implementd.  Did you find otherwise?

The other orthographic variations also added.   

As to capitalization, would you provide me with a small table of the unicode code points
for capital letters with diacritics?
example
 ā \u0101
 Ā \u????

 Include the Orthographic variants.

**Comment by gasyoun** [comment]
`Did you find otherwise?` - no, it's perfect.
Table will be provided, sure.

**Comment by gasyoun** [comment]
@funderburkjim I would take the table from http://shashir.autodidactus.org/shashir_umich/sanskrit_transcription.html and put it into the Help section for input (`devnag` can be left out or added as a possible input method, for the LaTeX folks around who still use it it might be the best way, some say Linux is still alive):

Congress of Orientalists 	Devanāgarī 	Kyoto-Harvard 	ITRANS 	devnag
k, kh, g, gh, ṅ 	क्, ख्, ग्, घ्, ङ् 	k, kh, g, gh, G 	k, kh, g, gh, ~N 	k, kh, g, gh, "n
c, ch, j, jh, ñ 	च्, छ्, ज्, झ्, ञ् 	c, ch, j, jh, J 	ch, Ch, j, Jh, ~n 	c, ch, j, jh, ~n
ṭ, ṭh, ḍ, ḍh, ṇ 	ट्, ठ्, ड्, ढ्, ण् 	T, Th, D, Dh, N 	T, Th, D, Dh, N 	.t, .th, .d, .dh, .n
t, th, d, dh, n 	त्, थ्, द्, ध्, न् 	t, th, d, dh, n 	t, th, d, dh, n 	t, td, d, dh, n
p, ph, b, bh, m 	प्, फ्, ब्, भ्, म् 	p, ph, b, bh, m 	p, ph, b, bh, m 	p, ph, b, bh, m
y, r, l, v 	य्, र्, ल्, व् 	y, r, l, v 	y, r, l, v/w 	y, r, l, v
ś, ṣ, s, h 	श्, ष्, स्, ह् 	z, S, s, h 	sh, Sh, s, h 	"s, .s, s
ṁ/ṃ, ḥ 	ं, ः 	M, H 	M, H 	.m, .h 

The table you are asking for is under `Characters for Romanization of Devanagari` http://kevincarmody.com/software/devanagari.html

Uppercase
IAST
Character 	Lowercase
IAST
Character 	Uppercase
IAST
Code 	Lowercase
IAST
Code
Ā	ā	x0100	x0101
Ī	ī	x012A	x012B
Ū	ū	x016A	x016B
Ṛ	ṛ	x1E5A	x1E5B
Ṝ	ṝ	x1E5C	x1E5D
Ḷ	ḷ	x1E36	x1E37
Ṃ	ṃ	x1E42	x1E43
Ṁ	ṁ	x1E40	x1E41
Ḥ	ḥ	x1E24	x1E25
Ṅ	ṅ	x1E44	x1E45
Ñ	ñ	x00D1	x00F1
Ṭ	ṭ	x1E6C	x1E6D
Ḍ	ḍ	x1E0C	x1E0D
Ṇ	ṇ	x1E46	x1E47
Ś	ś	x015A	x015B
Ṣ	ṣ	x1E62	x1E63
Ḻ	ḻ	x1E3A	x1E3B

**Comment by gasyoun** [comment]
As most are implemented in #156 , time to say goodbye.

**Comment by funderburkjim** [comment]
@gasyoun  Glad you revisited some of these old issues, and closed where appropriate.
