### ISSUE TITLE
API endpoint for getsuggest

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#332]
Per https://github.com/sanskrit-lexicon/COLOGNE/issues/328#issuecomment-756379213
https://sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/api0/getsuggest.php?dict=mw&term=de is the current API for getsuggest.

@funderburkjim, why there is a limit of 10 entries only? Can I do something with the API endpoint to get ALL results?

**Comment by funderburkjim** [comment]
getsuggest was initially developed to provide data for the 'autosuggest' feature when one is searching for
a particular word in a particular dictionary.  Easy example: https://www.sanskrit-lexicon.uni-koeln.de/simple/

then change 'input' to 'slp1' (or something other than 'simple').  Once the user now types 2 letters or more
in the 'citation' input,  getsuggest is called and the results are shown in a dropdown.

So, in that application, 10 was a reasonable number.

The main concern I have with extending the functionality to return ALL matches with getsuggest is similar to the concern in advanced search prefix (or other) matches.  In Adv. Search, we found it necessary to
restrict the return size due to payload size.  There a provision was made for 'pagination' by means of the
'next' button.

Will wait for your further comments before undertaking to modify api0/getsuggest.php .

**Comment by gasyoun** [comment]
> return ALL matches with getsuggest is similar to the concern in advanced search prefix (or other) matches

That is easily understood.

> found it necessary to restrict the return size due to payload size

As of now API is for testing only. Let us test and see what actually hands the server?

**Comment by drdhaval2785** [comment]
@fundetburkjim,

We can restructure this a bit. I am not sure where these suggestions are coming from. But I guess they are coming from sqlite file by some sqlite query.

Can we get the word suggestions from sanhw1.txt or hwnorm1c.txt only? 
This would reduce load on the servers and remove the artificial restrictions we had to put on the query. 

Pagination in API world is not that welcome. The frontend would have to check for existence of pagination every time.

**Comment by gasyoun** [comment]
> reduce load on the servers and remove the artificial restrictions we had to put on the query

Sure, the `artificial restrictions` might not be the only way.

> Pagination in API world is not that welcome

Never seen it any API.

**Comment by funderburkjim** [comment]
Current getsuggest examines the 'xxx.sqlite' file for dictionary xxx.

Currently, there is no sanhw1.sqlite, although there could be.

There is an 'hwnorm1c.sqlite' 

It seems that in the getsuggest API, you are wanting to go beyond the scope of the original
use case of csl-apidev/getsuggest.php.   I'll work to modify api0/getsuggest.php in the directions
you are indicating.

**Comment by funderburkjim** [comment]
## Today's revision:

Example url: https://sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/api0/getsuggest.php?dict=mw&term=gav&pretty

* Currently return list max is 200,000.
* The 'pretty' parameter works as with servepdf
* The returned data is also structured similarly to that of servepdf.
* The 'input' parameter can be used to indicate that 'term' is in the spelling of 'input'.  
   * If 'input' is absent, SLP1 is assumed.
   * The list of matches is spelled according to the value of 'input'
* Some errors are detected, and a status code is part of the returned data. 
   * status code = 200 means no errors detected  (but you still could have 0 matches)
   * status code = 404 means some error detected, always no matches in this case.
* The 'suggested list of matches'  is derived from xxx.sqlite for dictionary code xxx.  If Y is the search term,
   then the SQLITE Like parameter is 'Y%' -- this means 'any headword *beginning with Y*.
   * SQLITE LIKE wildcards also may be used in Y:
      `_` :  (underscore) is a wildcard for any single character
      `%`: is wildcard for any 0 or more characters.
*  The 'select distinct' feature of SQLITE is used, which makes the search fast.
    * If you generate a search *in the browser* with many thousands of results, the slowest part is
      generation of html.

Happy experimenting!

**Comment by funderburkjim** [comment]
We probably could use sanhw1 to generate exactly the same output as described above for a given
dictionary xxx.   

I',m not sure this would be an improvement.

 if we decide to try it,  suggest we make the
api method and the php endpoint have different names. 

Please advise if you want me to write code using these two sources of headwords, and if so, what the
benefits would be.

**Comment by drdhaval2785** [comment]
I am not sure yet, but going sanhw1.txt way would let us search for similar words ACROSS DICTIONARIES. Whereas doing the same via xxx.sqlite way would require parsing 37 sqlite files. 

I agree with the suggestion to have separate names for this API endpoint.

**Comment by gasyoun** [comment]
> SQLITE LIKE wildcards also may be used in Y

Pure magic, was not aware of the syntax.

**Comment by drdhaval2785** [comment]
> https://sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/api0/getsuggest.php?dict=mw&term=gav&input=slp1

This is now live at https://kosha.sanskritworld.in/#!/default/get_ckt
I tested Jim's statement that majority of the time is spent on creating HTML.
I tested with a rather large output item like 'ka' in MW. It gave 3763 matches in 838 milliseconds.
This is a reasonable speed for a not so heavily used service.

Wild cards also work as expected. 
I was just wondering if it is possible to change these wild cards from SQL syntax to regex syntax of `?` and `*` ?
More people know regex than do SQL.

**Comment by drdhaval2785** [comment]
Returns 12983 results for 'k' search in MW in 1594 ms.
Quite good.

**Comment by gasyoun** [comment]
> I tested Jim's statement that majority of the time is spent on creating HTML.

**Comment by drdhaval2785** [comment]
> Is it so?

As API returns all results in below 2 seconds, delay if any may be caused by browser rendering of HTML.

**Comment by drdhaval2785** [comment]
Working well. Closing the issue.

**Comment by funderburkjim** [comment]
> possible to change these wild cards from SQL syntax to regex syntax of ? and * ?


The real regex syntax for a single character is '.'  and for 0 or more of any character is '.*' --

There is also a [glob wildcard syntax](https://facelessuser.github.io/wcmatch/glob/).

We could alter what we use as wildcards, but will have to restrict to something that directly maps onto SQLITE 
wildcards '_' and '%'.

**Comment by funderburkjim** [comment]
re sanhw1 or hwnorm1c searches,  bring up in separate issue when needed.
