### ISSUE TITLE
Headword to entry API

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#335]
https://api.sanskrit-lexicon.uni-koeln.de/entries/hws/{headword}{/dictcode}

This is on priority item @funderburkjim .

# Expected output
```
{
	[
		"key1": "",
		"key2": "",
		"lnum": "",
		"pc": "",
		"txt": "",
		"xml": "",
		"html": "",
	],

	[
		"key1": "",
		"key2": "",
		"lnum": "",
		"pc": "",
		"txt": "",
		"xml": "",
		"html": "",
	],


}
```

**Comment by drdhaval2785** [comment]
txt, xml and html shoud return respective data.

For now, any kind of data would do. Whatever is low hanging fruit. But by January end, we need to have all the three items.

**Comment by funderburkjim** [comment]
Why is *January end,* important?

**Comment by drdhaval2785** [comment]
Yes. Above all in priority. And I mean it.

**Comment by gasyoun** [comment]
> Why is January end, important?

because it's a low hanging fruit :)

**Comment by funderburkjim** [comment]
## first implementation

https://sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/api0/hws0.php   with parameters:
* required:
  * dict : dictionary code 
  * key : headword  (spelled according to 'input' parameter)   
* optional:
  * input:  slp1 (default), itrans, hk, iast
  * output: slp1 (default) itrans, hk, iast   
  * accent : no (default), yes

Also, a 'pretty' parameter should be used when used in a browser.
Without pretty,  JSON is returned.

Example: https://sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/api0/hws0.php?dict=mw&key=deva&pretty

Let me know if there are any adjustments you want to make at this time.

**Comment by gasyoun** [comment]
> Let me know if there are any adjustments you want to make at this time.

Dhaval's turn. Looks like magic:

![rrewrwrwerew](https://user-images.githubusercontent.com/80761/105233799-634c9380-5b7b-11eb-8d0a-6b7d5df89156.JPG)

**Comment by drdhaval2785** [comment]
Looks like magic to me too.
Time to close.
