### ISSUE TITLE
Metaline format for synonymic dictionaries / thesaura

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#338]
https://github.com/sanskrit-lexicon/COLOGNE/issues/336#issuecomment-763730902 

File has to have a metaline. But synonymic dictionaries / thesaura pause a difficult problem with the present format.

# Sample entry
```
#ब्रह्मन्,स्रष्टृ,परमेष्ठिन्,धातृ,पद्मभू,सुरज्येष्ठ,वेधस्,विधि,विरिञ्च,हिरण्यगर्भ,शतानन्द,शम्भु,स्वयम्भू,द्रुहिण,चतुर्वक्त्र,प्रजापति,पितामह,जगत्कर्तृ,विरञ्चि,कमलासन
ब्रह्मा स्रष्टा परमेष्ठी धाता पद्मभूः सुरज्येष्ठः ।
वेधा विधिर्विरिञ्चो हिरण्यगर्भः शतानन्दः ॥ ६ ॥
शम्भुः स्वयम्भूर्द्रुहिणश्चतुर्वक्त्रः प्रजापतिः ।
पितामहो जगत्कर्ता विरञ्चिः कमलासनः ॥ ७ ॥
```
Here, these two verses enumerate words denoting ब्रह्मा. 

Typical metaline in dictionaries is like
```
<L>1<key1>ब्रह्मन्<key2>ब्रह्मन्<pc>6
ब्रह्मा स्रष्टा परमेष्ठी धाता पद्मभूः सुरज्येष्ठः ।
वेधा विधिर्विरिञ्चो हिरण्यगर्भः शतानन्दः ॥ ६ ॥
शम्भुः स्वयम्भूर्द्रुहिणश्चतुर्वक्त्रः प्रजापतिः ।
पितामहो जगत्कर्ता विरञ्चिः कमलासनः ॥ ७ ॥
<LEND>
``` 
Order of metaline may vary. I have written from my memory.

Now, the problem is that स्रष्टृ, परमेष्ठिन्, धातृ, पद्मभू etc. all are headwords. 
Copying the same entry for 20 times for these headwords does not make any sense. It may increase errors and also bloat the file greatly.

I will try to propose my solution. We can discuss and refine further.

**Comment by drdhaval2785** [comment]
# Proposal 1
```
<L>1<key1>ब्रह्मन्<key2>ब्रह्मन्<pc>6<s>स्रष्टृ,परमेष्ठिन्,धातृ,पद्मभू,सुरज्येष्ठ,वेधस्,विधि,विरिञ्च,हिरण्यगर्भ,शतानन्द,शम्भु,स्वयम्भू,द्रुहिण,चतुर्वक्त्र,प्रजापति,पितामह,जगत्कर्तृ,विरञ्चि,कमलासन 
ब्रह्मा स्रष्टा परमेष्ठी धाता पद्मभूः सुरज्येष्ठः ।
वेधा विधिर्विरिञ्चो हिरण्यगर्भः शतानन्दः ॥ ६ ॥
शम्भुः स्वयम्भूर्द्रुहिणश्चतुर्वक्त्रः प्रजापतिः ।
पितामहो जगत्कर्ता विरञ्चिः कमलासनः ॥ ७ ॥
```

Add a field `<s>` for synonyms, and write comma separated values there.

If we are OK with this proposal, we can move to next proposal of downstream production.

**Comment by drdhaval2785** [comment]
# Proposal 2a

1. Keep `s` data as it is inside the `h` tag of xml file.
2. While generating sqlite, store them as separate headwords pointing to the same entry.

This would reduce bloat of xml file too.

# Proposal 2b

1. Bring the synonyms as headwords in xml file itself.

I prefer Proposal 2a.

**Comment by drdhaval2785** [comment]
# Proposal 3

Can we have Lnum as `1.1.1.36.1` where lnum is in the format `kanda.varga.subvarga.verse.number` format?
This will capture the काण्ड, वर्ग, अध्याय, श्लोक, and the number of this headword in that श्लोक details.

**Comment by drdhaval2785** [comment]
@gasyoun and @funderburkjim , what is your take?

Once we are OK with the format, I will make the file compliant to that format.

**Comment by gasyoun** [comment]
> Copying the same entry for 20 times for these headwords does not make any sense. It may increase errors and also bloat the file greatly.

Agree.

> Proposal 2a

Can't see why we can't go for it.

**Comment by funderburkjim** [comment]
Many programs depend on the format of the meta-line, with just one 'key1'.  

The problem seems quite similar to the 'alternate headword' issue.   
Our current solution for alternate headwords is similar to 2b.
For dictionary xxx,

There is an xxx_hwextra.txt  file in csl-orig/v02/xxx.
Here is example from ap90_hwextra.txt:

`<L>185.01<pc>0009-b<k1>agatIka<k2>agatIka<type>alt<LP>185<k1P>agatika<ln1>2702<ln2>2709`

  This line provides an extra headword for `<L>185<pc>0009-b<k1>agatika<k2>agati(tI)ka`

Note that the hwextra line
* has it's own L value
* same pc as its parent
* it's own k1 and k2
* a 'type' of 'alt'
* LP = the L of parent
* k1P = the k1 of parent
* ln1 and ln2:   THESE ARE NOT USED, as far as I can tell.
  * vcp_hwextra  does not have ln1 and ln2.

The xxx_hwextra.txt file is used at ONLY 1 SPOT in the dictionary regeneration process:  by hw.py, which
creates xxxhw.txt from xxx.txt and xxx_hwextra.txt.
In the ap90 example the two lines of ap90hw.txt are:
```
<L>185<pc>0009-b<k1>agatika<k2>agati(tI)ka<ln1>2702<ln2>2709
<L>185.01<pc>0009-b<k1>agatIka<k2>agatIka<type>alt<LP>185<k1P>agatika<ln1>2702<ln2>2709
```

When make_xml.py constructs xxx.xml,   it uses xxxhw.txt and xxx.txt.

make_xml constructs an xml record for each line of xxxhw.txt.
It the 'type' parameter from the line of xxxhw.txt is present, it currently must have
one of two values:
* alt  for 'alternate'
* sub for 'subheadword'

And an extra phrase is inserted at  the beginning of the `<body>` tag, depending on 'type':
*  `  'alt':'<alt>%s is an alternate of %s.</alt>',`
*  `'sub':'<alt>%s is a sub-headword of %s.</alt>'`

This extra phrase shows up in the displays. For instance:

![image](https://user-images.githubusercontent.com/6393033/105234676-9a01ba00-5b39-11eb-8d3e-ed2d3b679bda.png)

This hwextra system works fairly well, but one drawback is that, in list displays, all the alternates appear in the left hand pane:
![image](https://user-images.githubusercontent.com/6393033/105235650-df25ec00-5b39-11eb-97d8-fdadcd56a8be.png)



## My suggestion
Construct the hwextra file

**Comment by funderburkjim** [comment]
> Lnum as 1.1.1.36.1   ?

No.  The Lnum is stored as a decimal number  (not a string) in the sqlite table.  In all current dictionaries,  the general principle
is to have the Lnumbers to be increasing within the xxx.txt digitization metalines.

But, the  Lnums don't necessarily need to be sequential integers.  For instance, if the maximum values of each component
of 1.1.1.36.1  is 99, you code code L = 0101013601.   I don't know if this would place sequential dictionary entries in
numerical order.    Probably it would be better to use a synthetic L number, 
and to have 1.1.1.36.1  in the text with some kind of markup (tag).

**Comment by funderburkjim** [comment]
In the metaline version of your sample entry,  suggest you include the first line of alternates.

We might want to invent another 'type' value for 'hwextra',  which would add no 'X is an alternate of Y' message to the xml.

**Comment by gasyoun** [comment]
> The problem seems quite similar to the 'alternate headword' issue.

Agree.

> Our current solution for alternate headwords is similar to 2b.

Means it would be easiest to go? `Construct the hwextra file` does not sounds too far away, nor too hard.

> This hwextra system works fairly well, but one drawback is that, in list displays, all the alternates appear in the left hand pane

So we would want some kind of coloring or symbol to show that it is not a real entry printed in the book, actually.

> have 1.1.1.36.1 in the text with some kind of markup (tag).

Makes sense.

> another 'type' value for 'hwextra', which would add no 'X is an alternate of Y' message to the xml.

Why not? Synonym based `hwextra`

**Comment by funderburkjim** [comment]
You might also consider adding `<s>X</s>` tags to each line.

To be consistent with other dictionaries,  the Devanagari needs to be transcoded to slp1 in xxx.txt.

You can look at https://github.com/sanskrit-lexicon/MWS/blob/master/mwtranscode/mw_transcode.py  to see how
python can be used for this transcoding.  You'll also need to copy at least transcoder/deva_slp1.xml  for transcoding from
Devanagari to slp1.

If the LINES in your dictionary should be preserved,  each body line of xxx.txt should have an indicator (such as `<lb/>`) at
beginning of each line.

**Comment by funderburkjim** [comment]
Maybe first line after metaline could be

`synonyms: <s>brahman, srazwf, ... </s>`

Use `<type>syn`  in hwextra

We can modify make_xml.py to add nothing to first line of type='syn'.

**Comment by drdhaval2785** [comment]
I saw the suggestions, and found out that the other solutions seem difficult to implement and maintain.

And I would anyhow be making corrections to the .txt file which I maintain at sanskrit-kosha repository, and generate Cologne compliant .txt file by a script.

Therefore, it is not difficult to generate a separate entry for each headword. 
I have added another meta data `<vn>` standing for verse number. It is an additional information, which can be ignored as of now. As and when we want to take this information to the frontend, we can transmit it to the XML / HTML / SQLITE as the need be.

```
<L>1<pc>0001<k1>svar<k2>svar<vn>1.1.1.3
svaH svargaH surasadma tridaSAvAsastrivizwapaM tridivam .<BR>dyOrgOramartyaBuvanaM nAkaH syAdUrDvalokaSca .. 3 ..
<LEND>
<L>2<pc>0001<k1>svarga<k2>svarga<vn>1.1.1.3
svaH svargaH surasadma tridaSAvAsastrivizwapaM tridivam .<BR>dyOrgOramartyaBuvanaM nAkaH syAdUrDvalokaSca .. 3 ..
<LEND>
<L>3<pc>0001<k1>surasadman<k2>surasadman<vn>1.1.1.3
svaH svargaH surasadma tridaSAvAsastrivizwapaM tridivam .<BR>dyOrgOramartyaBuvanaM nAkaH syAdUrDvalokaSca .. 3 ..
<LEND>
<L>4<pc>0001<k1>tridaSAvAsa<k2>tridaSAvAsa<vn>1.1.1.3
svaH svargaH surasadma tridaSAvAsastrivizwapaM tridivam .<BR>dyOrgOramartyaBuvanaM nAkaH syAdUrDvalokaSca .. 3 ..
<LEND>
<L>5<pc>0001<k1>trivizwapa<k2>trivizwapa<vn>1.1.1.3
svaH svargaH surasadma tridaSAvAsastrivizwapaM tridivam .<BR>dyOrgOramartyaBuvanaM nAkaH syAdUrDvalokaSca .. 3 ..
<LEND>
<L>6<pc>0001<k1>tridiva<k2>tridiva<vn>1.1.1.3
svaH svargaH surasadma tridaSAvAsastrivizwapaM tridivam .<BR>dyOrgOramartyaBuvanaM nAkaH syAdUrDvalokaSca .. 3 ..
<LEND>
<L>7<pc>0001<k1>dyo<k2>dyo<vn>1.1.1.3
svaH svargaH surasadma tridaSAvAsastrivizwapaM tridivam .<BR>dyOrgOramartyaBuvanaM nAkaH syAdUrDvalokaSca .. 3 ..
<LEND>
<L>8<pc>0001<k1>go<k2>go<vn>1.1.1.3
svaH svargaH surasadma tridaSAvAsastrivizwapaM tridivam .<BR>dyOrgOramartyaBuvanaM nAkaH syAdUrDvalokaSca .. 3 ..
<LEND>
<L>9<pc>0001<k1>amartyaBuvana<k2>amartyaBuvana<vn>1.1.1.3
svaH svargaH surasadma tridaSAvAsastrivizwapaM tridivam .<BR>dyOrgOramartyaBuvanaM nAkaH syAdUrDvalokaSca .. 3 ..
<LEND>
<L>10<pc>0001<k1>nAka<k2>nAka<vn>1.1.1.3
svaH svargaH surasadma tridaSAvAsastrivizwapaM tridivam .<BR>dyOrgOramartyaBuvanaM nAkaH syAdUrDvalokaSca .. 3 ..
<LEND>
<L>11<pc>0001<k1>UrDvaloka<k2>UrDvaloka<vn>1.1.1.3
svaH svargaH surasadma tridaSAvAsastrivizwapaM tridivam .<BR>dyOrgOramartyaBuvanaM nAkaH syAdUrDvalokaSca .. 3 ..
<LEND>
```

**Comment by drdhaval2785** [comment]
`<vn>` is in the format of `काण्ड.वर्ग.उपवर्ग.श्लोक` format. `kanda.varga.subvarga.verse` in English.

**Comment by funderburkjim** [comment]
Prefer that you use `<e>`  instead of `<vn>`   . 

`<e>` is used in some other  dictionaries for various dictionary-specific purposes.  For instance, in MW, `<e>1A`  is used
to represent `<H1A>` in the xml.    

If you insist on using the more meaningful `<vn>`,  we'll have to consider how code will use it, in make_xml.py,  
possibly in one.dtd, possibly in basicdisplay.php.


Are you not going to put line-breaks and `<s>` markup in xxx.txt ?

If not, perhaps make_xml.py will need to insert such markup.

**Comment by funderburkjim** [comment]
I think that the synonym line should be present in the entries for each synonym:

ब्रह्मन्,स्रष्टृ,परमेष्ठिन्,धातृ,पद्मभू,सुरज्येष्ठ,वेधस्,विधि,विरिञ्च,हिरण्यगर्भ,शतानन्द,शम्भु,स्वयम्भू,द्रुहिण,चतुर्वक्त्र,प्रजापति,पितामह,जगत्कर्तृ,विरञ्चि,कमलासन

In other words, each of the synonym entries are identical  (except for the 'meta' line).

Maybe you are already doing that -- I wasn't sure.

Did you decide you didn't want to add the word 'synonym: ' to the synonym line? e.g.
`synonym: <s>brahman, srazwf, ...</s>`

**Comment by drdhaval2785** [comment]
> Prefer that you use <e> instead of <vn>

I do not have any preference. `e` is fine for me.

> put line-breaks

They are already there.

> `<s>` markup in xxx.tx

These dictionaries are going to be all in Sanskrit, like SKD / VCP.
Therefore, there is no need to supply `<s>` markup. It would be superfluous.
So, make_xml may treat them at par with SKD / VCP for adding `<s>` markup to the whole text.
I have done such change in make_xml.py template for ARMH.

> I think that the synonym line should be present in the entries for each synonym

I also completely agree.
But you need to provide me some way in which the data can be handled in xxx.txt in `many -> one` fashion, and not the usual `one -> many` fashion.

I mean in the present case (hw1, hw2, hw3, hw4 ......) all refer to verse1.

Whereas in regular dictionary,
hw1 refers to (meaning1, meaning2, meaning3, meaning4, ....)

#339 explains the structure of synonimic dictionaries in further detail.
Kindly give it a thought and give some coherent xxx.txt format for synonymic / homonymic / mixed dictionaries.
I will then generate the dictionaries in that format, once the format is agreed to.

# Current way around

I have currently generated duplicated entries like the following to make it compliant with other Cologne dictionaries.
hw1
verse1
hw2
verse1
hw3
verse1
..
..
..

This is not at all a good way of doing this.

**Comment by gasyoun** [comment]
> This is not at all a good way of doing this.

There is only one man in the whole world who can answer the question.

**Comment by Andhrabharati** [comment]
Will see what that "single man" says.

This issue has been long back tackled at Andhrabharati site (over 10 years ago).

**Comment by funderburkjim** [comment]
That single man does not have a solution ready at hand for the thesaurus type of dictionary.

The only existing software that comes to mind as a potential solution goes under the name 'keydoc',
and is visible at
https://sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/sample/dalglob1.php

The ideas here are that:
* a document is a collection of meta-line headwords  (this is hwnorm2/keydoc_glob1.sqlite)
* The document may be 'reached' via
   * the metaline headwords keys  (nothing new here)
   * or by OTHER keys -- which may be specified in various ways [Yes, this is a bit vague.
      Think of an extension of 'alternate headwords'

For example: try [this dalglob1](https://sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/sample/dalglob1.php?key=antarayati&input=slp1&output=iast)

Notice that the MW document is 'antaraya'.  So, even though 'antarayati' is not a headword in
the MW dictionary,  we found an MW document that is (alleged) to be a reasonable search result
in MW for 'antarayati'.

From this example,  one can theorize that it would be possible to:
1) construct the armh dictionary using just one entry per synonym.
2) Add the synonyms to the armh part of  keydoc.   

There IS provision to have individual dictionary displays make use of their porition of keydoc db.
But it currently is not part of the dictionary build process.

So, that's my current 2 cents worth as to how a 'thesauras' dictionary might be handled.
Currently speculative, but probably could be put into production.

**Comment by funderburkjim** [comment]
Dhaval made a suggestion somewhere of extending the metaline to have a
comma-delimited list as the 'k1' value.

This also is an interesting idea,  and seems at first glance to be a more direct
addressing of the thesauras dictionary type.

It would be nice to try it in some temporary variants of
csl-pywork and csl-websanlexicon and csl-orig.
 At the moment, I am not sure what code would need 
enhancement, or even if such an apparently simple enhancement could readily co-exist with
current code.

**Comment by drdhaval2785** [comment]
> comma-delimited list as the 'k1' value.

I think comma delimited list of k1, k2 and L would be needed. This would take care of issue of duplicating the entry.

> I am not sure what code would need
enhancement

I understand. But make_xml.py , hw.py would require changes for sure.

**Comment by gasyoun** [comment]
> I think comma delimited list of k1, k2 and L would be needed. 

Makes sense. Sounds reasonable.

**Comment by funderburkjim** [comment]
ok - will work on this.

**Comment by funderburkjim** [comment]
@drdhaval2785   Please provide a link to armh.txt AS YOU WISH IT TO BE 
 i.e., with comma-separated values for <k1>.

You may have been holding off on adding armh to csl-orig  until we settle on the metaline format.

That's ok,  I will work on a temporary (non-git) version of armh in csl-orig.

**Comment by drdhaval2785** [comment]
I have uploaded ARMH at https://github.com/sanskrit-lexicon/csl-orig/blob/master/v02/armh/armh.txt .

# Current digitization

```
<L>1<pc>0001<k1>svar<k2>svar<vn>1.1.1.3
svaH svargaH surasadma tridaSAvAsastrivizwapaM tridivam .
dyOrgOramartyaBuvanaM nAkaH syAdUrDvalokaSca .. 3 ..
<LEND>
<L>2<pc>0001<k1>svarga<k2>svarga<vn>1.1.1.3
svaH svargaH surasadma tridaSAvAsastrivizwapaM tridivam .
dyOrgOramartyaBuvanaM nAkaH syAdUrDvalokaSca .. 3 ..
<LEND>
<L>3<pc>0001<k1>surasadman<k2>surasadman<vn>1.1.1.3
svaH svargaH surasadma tridaSAvAsastrivizwapaM tridivam .
dyOrgOramartyaBuvanaM nAkaH syAdUrDvalokaSca .. 3 ..
<LEND>
<L>4<pc>0001<k1>tridaSAvAsa<k2>tridaSAvAsa<vn>1.1.1.3
svaH svargaH surasadma tridaSAvAsastrivizwapaM tridivam .
dyOrgOramartyaBuvanaM nAkaH syAdUrDvalokaSca .. 3 ..
<LEND>
<L>5<pc>0001<k1>trivizwapa<k2>trivizwapa<vn>1.1.1.3
svaH svargaH surasadma tridaSAvAsastrivizwapaM tridivam .
dyOrgOramartyaBuvanaM nAkaH syAdUrDvalokaSca .. 3 ..
<LEND>
<L>6<pc>0001<k1>tridiva<k2>tridiva<vn>1.1.1.3
svaH svargaH surasadma tridaSAvAsastrivizwapaM tridivam .
dyOrgOramartyaBuvanaM nAkaH syAdUrDvalokaSca .. 3 ..
<LEND>
<L>7<pc>0001<k1>dyo<k2>dyo<vn>1.1.1.3
svaH svargaH surasadma tridaSAvAsastrivizwapaM tridivam .
dyOrgOramartyaBuvanaM nAkaH syAdUrDvalokaSca .. 3 ..
<LEND>
<L>8<pc>0001<k1>go<k2>go<vn>1.1.1.3
svaH svargaH surasadma tridaSAvAsastrivizwapaM tridivam .
dyOrgOramartyaBuvanaM nAkaH syAdUrDvalokaSca .. 3 ..
<LEND>
<L>9<pc>0001<k1>amartyaBuvana<k2>amartyaBuvana<vn>1.1.1.3
svaH svargaH surasadma tridaSAvAsastrivizwapaM tridivam .
dyOrgOramartyaBuvanaM nAkaH syAdUrDvalokaSca .. 3 ..
<LEND>
<L>10<pc>0001<k1>nAka<k2>nAka<vn>1.1.1.3
svaH svargaH surasadma tridaSAvAsastrivizwapaM tridivam .
dyOrgOramartyaBuvanaM nAkaH syAdUrDvalokaSca .. 3 ..
<LEND>
<L>11<pc>0001<k1>UrDvaloka<k2>UrDvaloka<vn>1.1.1.3
svaH svargaH surasadma tridaSAvAsastrivizwapaM tridivam .
dyOrgOramartyaBuvanaM nAkaH syAdUrDvalokaSca .. 3 ..
<LEND>
```

# Proposed digitization per https://github.com/sanskrit-lexicon/COLOGNE/issues/338#issuecomment-770320976

```
<L>1,2,3,4,5,6,7,8,9,10,11<pc>0001<k1>svar,svarga,surasadman,tridaSAvAsa,trivizwapa,tridiva,dyo,go,amartyaBuvana,nAka,UrDvaloka<k2>svar,svarga,surasadman,tridaSAvAsa,trivizwapa,tridiva,dyo,go,amartyaBuvana,nAka,UrDvaloka<vn>1.1.1.3
svaH svargaH surasadma tridaSAvAsastrivizwapaM tridivam .
dyOrgOramartyaBuvanaM nAkaH syAdUrDvalokaSca .. 3 ..
<LEND>
```

This is what I have in mind, @funderburkjim .

**Comment by funderburkjim** [comment]
The armh displays look satisfactory to me.  Agree?

They are based on your armh.txt.  In other words, you adapted your initial digitization source to
the current metaline format.

I did something similar in the early stages of all the dictionaries.  That is,  each dictionary is 'peculiar' in some way, regarding the identification of headwords and entries.  And it has thus far (including armh) been possible to get a reasonable digitization xxx.txt that conforms to the current metaline format.

What program or script did you develop to convert [abhidhanaratnamala.txt](https://github.com/sanskrit-kosha/kosha/blob/master/abhidhanaratnamala_halayudha/orig/abhidhanaratnamala.txt)
into [armh.txt](https://raw.githubusercontent.com/sanskrit-lexicon/csl-orig/master/v02/armh/armh.txt) ?

Perhaps this script can be generalized (perhaps via mako?) for converting other koshas to the
metaline format.

I realize that in this comment I am backing off from my earlier offer to investigate revising the
metaline format.  At the moment I don't see a sufficient reason for such a revision.
@drdhaval2785 Look forward to your further response.

**Comment by funderburkjim** [comment]
Another thought -

Perhaps we could consider the proposed format
`<L>1,2,3,4,5,6,7,8,9,10,11<pc>0001<k1>svar,svar ...`

as a 'premetaline' format.   We could store armh_premeta.txt in csl-orig.
We could also develop a (probably simple) premeta_meta.py converter in csl-orig that would
construct xxx.txt (metaline format) from xxx_premeta.txt.

Currently, xxx_premeta.txt would have no use other than as a precursor to xxx.txt.

But there might be future uses for xxx_premeta.txt (although no future uses come readily to mind).

Alternatively, we could consider armh_premeta.txt to be an end point in  the kosha directories,
and do the conversion to armh.txt via premeta_meta.py there; and not store xxx_premeta.txt in 
csl-orig.

**Comment by drdhaval2785** [comment]
> The armh displays look satisfactory to me. Agree?

Completely agree.

> What program or script did you develop to convert abhidhanaratnamala.txt
into armh.txt ?

https://github.com/sanskrit-kosha/kosha/blob/master/scripts/parse_data.py
This program generates JSON, MD, XML, HTML, BABYLON and COLOGNE filed from abhidhanaratnamala.txt file. Babylon file can be further converted to STARDICT files by stardict-editor program. 

> Perhaps this script can be generalized (perhaps via mako?) for converting other koshas to the
metaline format.

The script is generic enough. All I have to do is to change the dictcode.

>I realize that in this comment I am backing off from my earlier offer to investigate revising the
metaline format. At the moment I don't see a sufficient reason for such a revision. @drdhaval2785 Look forward to your further response.

I completely agree. As the process of generating metaline compliant file for Cologne is via a script, and the resultant files will not be more than 10 MB for even long koshas, I do not see any requirement to investigate revision of metaline format. I will generate files in metaline format. We can drop this issue now.

**Comment by drdhaval2785** [comment]
premeta seems non viable for me.
I already have some format (in which all my dictionaries will be annotated) from which I can create cologne metaline compliant files. So I do not intend to create another precursor.

**Comment by funderburkjim** [comment]
One file we haven't mentioned is the xxx_meta2.txt file of csl-orig.

The purpose of this meta2 file is to describe some of the technical aspects of the digitization xxx.txt.
The reasons for the file are:
1. To document 'peculiar' points of the xxx.txt file for us, since these details often have impact on
    * how xxx.xml is constructed
    * how the displays (basicadjust, basicdisplay php files) interpret some xml features in generating html
2. To document aspects that other possible developers might need to take into account when
     developing other applications based on xxx.txt.

For armh and your other kosha dictionaries,  information like you gave above for how xxx.txt
derives from your 'some format'  would appropriate as part of xxx-meta2.txt.
