### ISSUE TITLE
Sanskrit Devanagari Web Fonts

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/COLOGNE#34]
Jim, what I would love to see would be Sanskrit 2003 (http://www.omkarananda-ashram.org/Sanskrit/itranslator2003.htm) or Siddhanta (http://www.svayambhava.org/) fonts as web fonts similar to http://experimenting.in/css3/webfonts/hindifontsdemo/devanagarifonts.htm
where @font-face {src: url("Osho.ttf");font-family: "Osho";} is all we need. CSS3 is popular enough these days, one can count on it. Mangal should go away, it's bad.
Otherwise पु॒रस्ता॒द्वै नाभ्यै᳠ प्रा॒ण उ॒परि᳠ष्टादपा॒नः  TS. 3, 4, 1, 4. gives me "boxes" or "bricks" and it's hard to read. It's aesthetically unpleasing. Actually I applied Sanskrit 2003 to प्रा॒णाद्वा॒युर᳠जायत  90, 13.  but it did not help much. What stands behind the र᳠?

**Comment by drdhaval2785** [comment]
Siddhanta font installed.
