### ISSUE TITLE
paridhā vs. pard in Simple

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/COLOGNE#345]
@funderburkjim not sure if a feature or a bug, but the results differ a lot.

**Case #1**
input_simple:
paridhā
1 result: paridhā

**Case #2**
input_simple Devanagari
paridhā
3 results: pard parda pārda

![pard](https://user-images.githubusercontent.com/80761/114285386-627f1b80-9a5f-11eb-8100-1cf9315e1fb8.png)

https://sanskrit-lexicon.uni-koeln.de/simple/

**Comment by funderburkjim** [comment]
When you choose 'devanagari' for 'input_simple',  the citation is expected to be in Devanagari!

![image](https://user-images.githubusercontent.com/6393033/114289554-e4167f80-9a46-11eb-83b9-5c83659de933.png)

**Comment by gasyoun** [comment]
> 'devanagari' for 'input_simple'

When there are 2 inputs, I get mixed.
