### ISSUE TITLE
Devanagari conjuct list for comparing fonts

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#354]
Reference - https://github.com/sanskrit-lexicon/PWG/issues/5

A discussion was initiated there regarding checking rendering of conjuncts in Siddhanta and Adhishila fonts.
A working list of conjuncts from MW was also used there to derive a display there.

For a fuller list of conjuncts for font testing, I have scraped the alphabets and conjuncts from vcp.txt and put them in this file. The entries are in `conjunct:frequency` format.

While the last entries may be errors, the entries occurring more than 5 times are most probably proper Sanskrit conjuncts.

We may check the fonts further using this dataset.

[conjunct_frequency.txt](https://github.com/sanskrit-lexicon/COLOGNE/files/6972909/conjunct_frequency.txt)

Tech note -
Regex used is `conjuncts = re.split(r'[^kKgGNcCjJYwWqQRtTdDnpPbBmyrlvSzsh]', data)`

**Comment by drdhaval2785** [comment]
program
```python
import re
import codecs
from collections import Counter

fin = codecs.open('/var/www/html/cologne/csl-orig/v02/vcp/vcp.txt', 'r', 'utf-8')
data = fin.read()
conjuncts = re.split(r'[^kKgGNcCjJYwWqQRtTdDnpPbBmyrlvSzsh]', data)

conj_counter = Counter(conjuncts)
desc = conj_counter.most_common()
for (a, b) in desc:
	print(a + 'a:'  + str(b))
```

**Comment by gasyoun** [comment]
Simple, yet lovely. I've made such for Rigveda before and Ulrich Stiehl even 10 years before I did. Remains interesting, thanks, Dhaval.

**Comment by drdhaval2785** [comment]
Served its purpose.
