### ISSUE TITLE
AP90 and AE edition discussion

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#359]
@Andhrabharati mentioned elsewhere, which is irrelevant to that issue. Being tracked here, and deleted from that issue.

The bottom one Apte Practical Sanskrit-English Dictionary 1st ed. (that is used here) is of 1890, and it should come much above in the list chronologically. It is wrongly dated as 1920.
[Its (re-composed) reprints were in 1912 and 1924, none in 1920.]

And the Apte Student's English-Sanskrit Dictionary that is hosted dates 1920 (3rd ed.), not 1884 (1st ed.).
[Its 2nd ed. came out in 1893, with minor corrections.]

**Comment by funderburkjim** [comment]
Re ap90 --- Agree it should be 1890, according to the [title page](https://sanskrit-lexicon.uni-koeln.de/scans/csldev/csldoc/build/dictionaries/prefaces/ap90pref.html)

![image](https://user-images.githubusercontent.com/6393033/133012854-ff34a416-f665-4792-90a8-9b69d530517a.png)

**Comment by funderburkjim** [comment]
Re AE.

According to [ae front matter](https://sanskrit-lexicon.uni-koeln.de/scans/csldev/csldoc/build/dictionaries/prefaces/aepref.html),
this is 3rd edition.

Don't see publication year in above reference.

However, in the individual page scans, we see 1920 (and confirm 3rd edition):
[page 1](https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=ae&page=1)

![image](https://user-images.githubusercontent.com/6393033/133013592-f2756481-2947-4b05-bf85-4174ce443450.png)

So 1920 is right date for AE.

Will change home page accordingly.

Thank you for pointing out the error.

**Comment by funderburkjim** [comment]
Am finding a problem with updating home page; revision to dates will proceed when this bug resolves.

**Comment by Andhrabharati** [comment]
> 
> 
> Am finding a problem with updating home page; revision to dates will proceed when this bug resolves.

Just noticed that this csl-homepage folder is a fork from funderberkjim's repo; could this be the reason?

![image](https://user-images.githubusercontent.com/75209130/133232028-a023ed9d-0c12-43e6-998c-fd15f6c9a821.png)

**Comment by drdhaval2785** [comment]
Correction is made.
The issue which Jim referred to was related to updation of version.
It has been resolved.
The necessary changes as per suggestion of edition years has been made.
Closing.
