### ISSUE TITLE
Headword spelling in Sabda-kalpadruma

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#36]
The corrections submitted for SKD are now processed, and it won't take so long to process further corrections.
Two details arose in considering these corrections, and this 'sanskrit-lexicon/Cologne/Issues' list seems a reasonable place to mention these details.
1. A question was raised  whether an ending visarga should be part of the headword.
    For example ghaTotkaca. The text clearly has a visarga. In the 'definition' part of the displays, this visarga is still present. However, the spelling  used for looking up the word does NOT have the visarga.
    This was done intentionally, so nominal headwords would be spelled using the 'stem' rather than the first-singular form. This is the headword convention in MW.
    Similarly, neuter nominals appear with the ending 'm' or 'M', but this letter is not used in the lookup key.
2. When examining the patnI correction with the List display, I noticed that the second word
     after patnI had the key spelled as 'pattra'.  The text shows 'pa(tra)ttraM'.  The 'pattra' spelling
     bothered me, because it is not in alphabetical order.  So, I changed the spelling of the key to 'patra',
     which does place this word in alphabetical order.

**Comment by drdhaval2785** [comment]
hwnorm1 is where this should be handled. From my experience it is too difficult to do this change generically. Better to normalize in a shadow file like hwnorm1c.
