### ISSUE TITLE
large files at github test

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#365]
In https://github.com/funderburkjim/boesp-prep/issues/10,  @thomasincambodia had a problem pushing;  it was suspected
that this was due to accidentally putting a large pdf into the repository.

A test confirms that there are indeed limitations to the size of file that Github will accept.

In the test, a temporary repository was made at Github.
The repository was cloned to local computer.

Then a large pdf (125.8MB, 128896162 bytes) was put in the repository.
git add, and git commit worked fine.

But git push failed:
```
$ git push
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 16 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 121.70 MiB | 966.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
remote: error: Trace: 83e8ea79de23baec9c518a4d315dd573d674408018cc5f3819c790d19f05bdb0
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File boesp-1.pdf is 122.92 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To https://github.com/funderburkjim/temp_large_file.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/funderburkjim/temp_large_file.git'

```

And, the message is not lying.   

The pdf was not transferred to git as proved by
* it does not show up when viewing the temporary repository at github
* When the github respository is again cloned (into a temporary local directory), the
   size of the cloned repository is only 73K.

So -- looks like the 100MB individual file size is a hard limit at Github with 'normal' repositories.

**Comment by funderburkjim** [comment]
## removing the big file does not work
In the local repository with the large pdf,  I moved the large file out of the repository ,
then did git add, git commit.

git push still failed:
```
git push
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 16 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 121.70 MiB | 968.00 KiB/s, done.
Total 4 (delta 0), reused 0 (delta 0), pack-reused 0
remote: error: Trace: dd2a0e4872510db7ff9ba8742cb9bd550cbb508e119af3a4cd5f8386a63bcae3
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File boesp-1.pdf is 122.92 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To https://github.com/funderburkjim/temp_large_file.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/funderburkjim/temp_large_file.git'
```

**Comment by funderburkjim** [comment]
## a solution
In the local installation, rename the failing repository.

Then again clone the github repository.

Add to the newly cloned  local repository any needed files from the renamed repository  (except the big file, of course).

Then proceed as normal.

This works, because the failed pushes don't actually mess up the github repository.

**Comment by drdhaval2785** [comment]
My takeaway is as follows-
0-50 MB - No issue
50-100 MB - Warning, but file gets uploaded
>100 MB - Error. File does not get uploaded.

**Comment by funderburkjim** [comment]
> My takeaway ...

Concur.

**Comment by gasyoun** [comment]
@funderburkjim closable?

**Comment by funderburkjim** [comment]
probably closeable.  Closing.
