### ISSUE TITLE
Change MASCULINE ORDINAL INDICATOR to DEGREE SIGN)

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#369]
This change was recently made in SCH dictionary, and the suggestion was made for similar change in other dictionares [Refer:](https://github.com/sanskrit-lexicon/PWK/issues/74#issuecomment-925974669).]

## background
According to https://en.wikipedia.org/wiki/Ordinal_indicator, 
>In written languages, an ordinal indicator is a character, or group of characters, following a numeral denoting that it is an ordinal number, rather than a cardinal number. In correct typography, the ordinal indicators ª and º should be distinguishable from other characters.[1]
In English orthography, this corresponds to the suffixes -st, -nd, -rd, -th in written ordinals (represented either on the line 1st, 2nd, 3rd, 4th or as superscript, 1st, 2nd, 3rd, 4th).
Also commonly encountered are the superscript or superior (and often underlined) masculine ordinal indicator, º, and feminine ordinal indicator, ª, originally from Romance, but via the cultural influence of Italian by the 18th century, widely used in the wider cultural sphere of Western Europe,[citation needed] as in 1º primo and 1ª prima.

In the Sanskrit dictionaries, it is believed that this is NOT the purpose for using MASCULINE ORDINAL INDICATOR but rather that
its purpose is  the same as that of the DEGREE SIGN, i.e., *generally* to indicate missing (implied) characters.  Thus both characters are believed to be similar in purpose to the Devanagari LAGHAVA character: https://en.wikipedia.org/wiki/Laghava
> The laghava ( ॰ ; from the Sanskrit: लाघव चिह्न, romanized: lāghava cihna, lit. 'brevity sign') is the Devanagari abbreviation sign, comparable to the full stop or ellipsis as used in the Latin alphabet. It is encoded in Unicode at U+0970 ॰ DEVANAGARI ABBREVIATION SIGN (HTML &#2416;).[1]
It is used as abbreviation sign in Hindi and other Devanagari-script-based languages. For example, "Dr." is written as "डॉ॰", "M.Sc." as "एम॰एससी॰", etc.
See also
。: CJK full stop
° : degree symbol

This abbreviation can be both of a Sanskrit word or of an English word.  
I haven't found a reference describing this 'abbreviation' function of the DEGREE SIGN in English or German.  Could it be that the
authors of Sanskrit dictionaries adopted the use of the DEGREE SIGN because of its similarity to LAGHAVA in Devanagari?

Anyway,  it seems reasonable to replace MASCULINE ORDINAL INDICATOR with DEGREE SIGN in the dictionaries.

There may be a few specific instances where the MOI purpose is specifically intended and could be used;  but global changes
to DEGREE SIGN are probably safe.

## pre-change usage
From [easummary.tsv (at commit a634ae..)](https://github.com/sanskrit-lexicon/COLOGNE/blob/a634ae92bb51dc334caac73d9b505fb6003b4b4e/eascii/easummary.tsv) we see that
the two characters  usually do not both occur in a given dictionary (except for the 4 cases mw72 -- vei).  

```
º	\u00ba	45578	MASCULINE ORDINAL INDICATOR
acc 46
ap90 4050, ben 506, gst 205, ieg 45
inm 19532, krm 1, mci 65, yat 2
mw72 21109, pwg 4 , shs 3, vei 10  [Also degree sign, see below]

°	\u00b0	253319	DEGREE SIGN
ae 246, bhs 22189, bop 86, bur 12, cae 9849
ccs 6679, gra 1, md 4825, mw 55432, mw72 1
pw 21456, pwg 83347, sch 24446, shs 1, stc 24742
vei 2, wil 5
```

**Comment by funderburkjim** [comment]
## Samples 
Before making the changes,  let's review some sample usages of MOI 
* acc `See Garbhādhānādiº.`,  `{#nAciketopAKyAna#}¦ (vulgarly called Nāśiketoº`
* ap90 `{#KaMqaSas#} ... {#ºkf#}`
* ben `<P>º denotes abbreviations, which may be easily supplied from the context.` (front matter)
* gst  `{#sapurohitaH#} (Mss. {#ºtam#})`
  * Also used as DEGREE:  `({%Kālasaṅkalita%} p. 353); its place is 60º or 62º N.`
* ieg `{%Bhaṃº%}¦ (PJS), abbreviation of {%Bhaṇḍārin%}`
* inm `{@Kausalya@}<sup>2</sup>¦ (C. Kauśº)`
* krm (entry DfY) `<F>4. <s>‘ºavahArADArAvAyAnAmupasaMKyAnam’`
* mci `gāndhāraº ºstriyaḥ` 
* yat `{#anu-svAra#}¦ {#(raH)#} 1. {%m.%} The nasal (º).`     <<< An attempt to indicate the Devanagari anusvAra 
   `{#nara-rUpin#}¦ {#(pIº piRI-pi)#} {%a. Idem.%}`
* mw72 `A-tathocita (ºthā-ucº)`  
  1 From the [abbreviation front matter](https://sanskrit-lexicon.uni-koeln.de/scans/csldev/csldoc/build/dictionaries/prefaces/mw72pref/mw72pref24.html) : º that the rest of a word is to be supplied, e. g. ºri- inº after karīndra is for kari-indra.
  2 This usage (exposing compounds constructed with simple-vowel-sandhi) was handled (less completely) in mw99 by the circumflex;  e.g. tathôcita, karîndra.
* pwg `der 10te Bogen von 50º in einem Kreise`  (as DEGREE)
  `streiche das Zeichenº. `  (a correction under anyaTAvftti)  The reference uses degree sign {#°cetas#}
* shs `motion from the sun amounts to 6º`  (DEGREE)
  `{#goDUma#}¦ m. ({#-maH#}) Wheat: see the next. E. {#guD-vAº uma .#}`
* vei `location in 60º north ` (DEGREE)
  `{@Saindhava,@}¦  ... ({%ºkhilya%});`

**Comment by funderburkjim** [comment]
Barring any objections from others,  I'll make the above changes from MOI to DEGREE tomorrow.

**Comment by drdhaval2785** [comment]
No objection from my side.

**Comment by funderburkjim** [comment]
Changes now installed.
* [easicii/eachanges-degree](https://github.com/sanskrit-lexicon/COLOGNE/tree/master/eascii/eachanges-degree) Relevant code 
* [eascii/eachanges-degree/changes](https://github.com/sanskrit-lexicon/COLOGNE/tree/master/eascii/eachanges-degree/changes) has change transactions.

Note MASCULINE ORDINAL INDICATOR now absent in all dictionaries (see [easummary.tsv](https://github.com/sanskrit-lexicon/COLOGNE/blob/master/eascii/easummary.tsv)).

**Comment by gasyoun** [comment]
> Devanagari LAGHAVA character

Never knew it's name. Well done, as usual, Jim.
