### ISSUE TITLE
video tutorial for installing offline mwe

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#37]
This is not an issue, but an announcement (Is there a better place for such announcements in the Github world?).

Here is a link for a video going through the process of installing an offline version of the Monier-Williams English-Sanskrit Dictionary from the Cologne Sanskrit-Lexicon web site. It also describes how to install Server2go on Windows OS.  A similar procedure can be used to install offline versions of all\* the dictionaries at Cologne Sanskrit-Lexicon.

https://www.youtube.com/watch?v=yXkoHOZqKx0
- For Monier-Williams Sanskrit-English Dictionary, a download appropriate for this procedure is not yet available.  However, download#9 (Windows.exe) is even easier to install, but not quite as complete; it has a video also, https://www.youtube.com/watch?v=DH9XBb9e-ls.

**Comment by drdhaval2785** [comment]
Nowadays, releases is the key word. 
Github releases can help us announce things with proper changelog.

**Comment by funderburkjim** [comment]
From my experience with a non-tech-savvy Sanskritist, the procedures in these videos probably assume a certain level of general computer geekiness.   

### Is the video documentation good enough ?
For such users, there should be good documention of how to do the task, and these videos was my stab at such documentation.   

@gasyoun  should probably review them,  and maybe he would think how to do it better.

### Where to put a link to the video documentation?

Whenever we decide that the documentation is 'good',  a link to the documentation should be somewhere, probably on Cologne site.   Where should the link be?  Cologne?  Github.io site Dhaval started long ago?

**Comment by drdhaval2785** [comment]
Link on Cologne. Dictionary display page. And cologne home page if the procedure is generic.

**Comment by gasyoun** [comment]
> certain level of general computer geekiness.

High level. I do not see a real need for additional visualisation. Desktop users can use an offline tool like https://www.dropbox.com/s/chinnk41sd78fes/sandic.ru.zip?dl=0, Android users - the newly converted dictionaries. Who (other than a developer, who is already savvy enough) would want to redo the steps?
