### ISSUE TITLE
Proposed new home page

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#39]
All the digitizations from Thomas have now been installed.
   There is a  proposed new sanskrit-lexicon home page at url
     http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/index2.html

```
Please take a look, and let me know of stylistic or other improvements.
```

**Comment by gasyoun** [comment]
@drdhaval2785 @zaaf2 does not make much sense?

**Comment by drdhaval2785** [comment]
Now we are thinking about separating data from display. So closing this three year old announcement.
