### ISSUE TITLE
error loading dictionaries

### ISSUE THREAD

**Issue by JuliaNikolaeva** [sanskrit-lexicon/COLOGNE#393]
на этапе sh generate_dict.sh md  ../../md так получается
![Снимок](https://user-images.githubusercontent.com/32849539/157204881-3949d180-8505-48aa-aa14-08a02d6c0f66.PNG)

**Comment by drdhaval2785** [comment]
It seems that you have to instal python.

If you have python installed, and still the error comes, you can try to add the location to python executable in PATH vairable

**Comment by funderburkjim** [comment]
When you install python in Windows, use https://www.python.org/downloads/

I recall having a problem when installing from the microsoft store.

If you still have an installation error, here is another thing to try:
You may need to have python available as 'python3'  as well as 'python'.
in my '~/,bashrc' configuration file (used by Git Bash), there are two lines:
```
alias python='winpty python.exe'
alias python3='winpty python.exe'
```
Try adding these to your .bashrc file, restart gitbash terminal, and try 
`sh generate_dict.sh md ../../md` install again.

Let me know if you find this necessary for installation to succeed, So I can add a comment
to the readme.txt instructions.

**Comment by JuliaNikolaeva** [comment]
Python was installed from here https://www.python.org/downloads/

I can't find my file .bashrc. Could you tell us in more detail how to make these changes.

```
alias python='winpty python.exe'
alias python3='winpty python.exe'
```

**Comment by funderburkjim** [comment]
For debugging, you can add an 'echo' line to your .bashrc file.
such as `echo "hello from .bashrc"`.
Close your git bash terminal, then open it up again.
You should see that echo message -- if so, that proves gitbash is using that .bashrc.

Now, when you change directories to csl-pywork/v02 and do
`sh generate_dict.sh md ../../md`  , do you still get an error?
If so, please copy paste all the output from your gitbash terminal into a comment here.

**Comment by JuliaNikolaeva** [comment]
Yes, the error message is still there
![Снимок](https://user-images.githubusercontent.com/32849539/157722469-fed38003-46c4-4ad8-915d-34ade2f82fbe.PNG)

**Comment by funderburkjim** [comment]
@JuliaNikolaeva   
It seems that GitBash cannot find your python.
To confirm this,
In the git bash terminal, enter the command 'python --version'
What is result?

Similarly,  enter command 'python3 --version'  What is the result.

Separately, open the Windows 'cmd' terminal and try the same commands. What is result?

Also, what is your version of Windows OS?

**Comment by JuliaNikolaeva** [comment]
> In the git bash terminal, enter the command 'python --version'
> What is result?
> Similarly, enter command 'python3 --version' What is the result.
![1](https://user-images.githubusercontent.com/32849539/157727034-754f6089-16ee-42a5-98f0-94582d8538a0.PNG)

> Separately, open the Windows 'cmd' terminal and try the same commands. What is result?
![2](https://user-images.githubusercontent.com/32849539/157727088-6bab4320-17f9-417e-bf6b-75b395e06bbb.PNG)

> Also, what is your version of Windows OS?
Windows 10 Pro

**Comment by funderburkjim** [comment]
Most mysterious.
Maybe there is some problem in accessing python within a script.
Try this:
Make a script somewhere  'temp_pyversion.sh':
```
echo "is python found?"
python --version
echo "is python3 found?"
python3 --version
```
Then run the script in Git bash terminal: `sh temp_pyversion.sh`>
What is output?

**Comment by funderburkjim** [comment]
@JuliaNikolaeva   Ignore that `>` in previous comment (2nd line from bottom)

**Comment by JuliaNikolaeva** [comment]
![3](https://user-images.githubusercontent.com/32849539/157729436-c9afe939-98a8-41ef-8006-0d3d0d24e248.PNG)

**Comment by funderburkjim** [comment]
OK. So 'python' is found in the script but not 'python3'. 

open new gitbash terminal and try 'which python' ; then do an ls on the directory.
Do you find python3.exe in that directory?

Here's my result:
```
$ which python3
/c/Users/jimfu/AppData/Local/Programs/Python/Python39/python3

jimfu@DESKTOP-6PTUC6R MINGW64 /e/pdfwork/rgorr
$ ls /c/Users/jimfu/AppData/Local/Programs/Python/Python39/
DLLs/        NEWS.txt  libs/         python39.dll*      vcruntime140_1.dll*
Doc/         Scripts/  python.exe*   pythonw.exe*
LICENSE.txt  Tools/    python3.dll*  tcl/
Lib/         include/  python3.exe*  vcruntime140.dll*
```

```

**Comment by JuliaNikolaeva** [comment]
![image](https://user-images.githubusercontent.com/32849539/157733593-e3b5a647-f390-483d-b908-ee399f62b407.png)

**Comment by funderburkjim** [comment]
Weird that the 'ls' shows nothing.  What do you get with 'which python' (instead of 'which python3') ?

**Comment by JuliaNikolaeva** [comment]
![image](https://user-images.githubusercontent.com/32849539/157735655-c897adde-3eef-4ada-8a0f-a658da3e2214.png)

**Comment by funderburkjim** [comment]
So 'python' is in a different spot from 'python3'.
I think /d/Users/julia/Appdata/Local/Microsift/WindowsApps/python3  may be a remnant from
your first installation of python, and that it may be getting in the way.
Can you uninstall it?
Also, I don't understand why the 'ls' doesn't show any files.  try 'ls -all ...'

I'm going to try a full installation on another computer.

**Comment by funderburkjim** [comment]
I'll do the work on the other computer in a few hours.

**Comment by funderburkjim** [comment]
@JuliaNikolaeva   Whew! Have got most everything working on new computer.  Had to make several adjustments due to a newer version of php in xampp.
Please look again at: https://github.com/sanskrit-lexicon/COLOGNE/tree/master/localinstall/xampp/readme.txt.

It has been revised.
The Python problem will be resolved by two things:
* Uninstall the old Windows Store version.  If you can't tell which is which, just uninstall all python, then reinstall from python web site -- I give exact details of how I installed in the readme.
* You have to copy python.exe to python3.exe  to get 'python3' to work.  Details in the readme.

Please also note there are additional things to install:
* the 'mako' python library
* sqlite  -  readme hopefully has all the details.

Also, once you've done above, also pull new versions of csl-apidev, csl-websanlexicon, csl-pywork.
(cd to the directory and do git pull).  These will get the php corrections.

Then, you are ready (with fingers crossed!) to try again to install md.

I look forward to see how things turn out now.  Thanks for your patience.

**Comment by gasyoun** [comment]
> copy python.exe to python3.exe

Sounds fishy to me.

**Comment by funderburkjim** [comment]
> copy python.exe to python3.exe

I got this solution from a [stackoverflow comment](https://stackoverflow.com/questions/39910730/python3-is-not-recognized-as-an-internal-or-external-command-operable-program), and it worked under Windows.

**Comment by funderburkjim** [comment]
@gasyoun and @JuliaNikolaeva 

The instructions I've been leading you through will result in the installation of a 'development' version of the dictionaries.
Significantly, you are installing all the Python code used to regenerate (and perhaps change) any of the dictionarie in
the local install.

There is another approach which does not require python at all, but, at the same time, only gives you the displays,
but not the development environment.  The following instructions describe how to get the 'BLAM' displays.
https://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2020/web/webtc/download.html

**Comment by gasyoun** [comment]
> There is another approach which does not require python at all, but, at the same time, only gives you the displays,
but not the development environment. The following instructions describe how to get the 'BLAM' displays.
https://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2020/web/webtc/download.html

It would be hard to make a single button, to download all at once, all dictionaries, right?

> The instructions I've been leading you through will result in the installation of a 'development' version of the dictionaries.

Thanks, hope @JuliaNikolaeva will test the path and make a video of the steps.

**Comment by funderburkjim** [comment]
## Towards a one-button solution for displays
Assumptions: xampp installed and gitbash available
Step 1. Make a directory subdirectory of xampp/htdocs - call it what you wish
    (just make it different from 'cologne', if you also want to have
    the full development version.
    I'll use the directory 'colognedisp' in this comment
Step 2. make xampp/htdocs/colognedisp/downloadCologne_one.sh from the following:
```
# downloadCologne_one.sh
dict=$1
dictlo=$(echo $dict | tr '[:upper:]' '[:lower:]' )
dictup=$(echo $dictlo | tr '[:lower:]' '[:upper:]')
href="https://www.sanskrit-lexicon.uni-koeln.de/scans/${dictup}Scan/2020/downloads/${dictlo}web1.zip"

mkdir $dictlo
cd $dictlo
curl $href -o temp.zip
unzip temp.zip
cd ../

```

Step 3: In Gitbash terminal, cd to the colognedisp directory
Step 4: Install one dictionary using the dictionary code. For example, start with the 
     Macdonell dictionary whose code is 'md'.  Run the script with this dictionary code as
     parameter
`sh downloadCologne_one.sh md`

Step 5: You should now have the basic, etc. displays.  
Be sure xampp (Apache) is started.
Then direct your browser to 'http://localhost/colognedisp/md/web/'. 

Let someone with xampp and gitbash give this a try.
If it works as expected, we can then ramp up to create a script that would 
do `sh downloadCologne_one.sh X` for all dictionary codes X.

**Comment by gasyoun** [comment]
> If it works as expected, we can then ramp up to create a script that would
do sh downloadCologne_one.sh X for all dictionary codes X.

Perfect plan. @JuliaNikolaeva will get there.

**Comment by JuliaNikolaeva** [comment]
I got this result
![image](https://user-images.githubusercontent.com/32849539/158235827-56344351-5781-43f7-808a-16454bd6729f.png)

**Comment by JuliaNikolaeva** [comment]
> ## Towards a one-button solution for displays
> Assumptions: xampp installed and gitbash available Step 1. Make a directory subdirectory of xampp/htdocs - call it what you wish (just make it different from 'cologne', if you also want to have the full development version. I'll use the directory 'colognedisp' in this comment Step 2. make xampp/htdocs/colognedisp/downloadCologne_one.sh from the following:
> 
> ```
> # downloadCologne_one.sh
> dict=$1
> dictlo=$(echo $dict | tr '[:upper:]' '[:lower:]' )
> dictup=$(echo $dictlo | tr '[:lower:]' '[:upper:]')
> href="https://www.sanskrit-lexicon.uni-koeln.de/scans/${dictup}Scan/2020/downloads/${dictlo}web1.zip"
> 
> mkdir $dictlo
> cd $dictlo
> curl $href -o temp.zip
> unzip temp.zip
> cd ../
> ```
> 
> Step 3: In Gitbash terminal, cd to the colognedisp directory Step 4: Install one dictionary using the dictionary code. For example, start with the Macdonell dictionary whose code is 'md'. Run the script with this dictionary code as parameter `sh downloadCologne_one.sh md`
> 
> Step 5: You should now have the basic, etc. displays. Be sure xampp (Apache) is started. Then direct your browser to 'http://localhost/colognedisp/md/web/'.
> 
> Let someone with xampp and gitbash give this a try. If it works as expected, we can then ramp up to create a script that would do `sh downloadCologne_one.sh X` for all dictionary codes X.

![image](https://user-images.githubusercontent.com/32849539/158237693-0a88890f-8196-4024-8b97-442ec1ef32ec.png)

**Comment by funderburkjim** [comment]
This looks good!
* Try the displays for md -- url: localhost/cologne/md/web ,  Do they work?
* The errors at 'zip: command not found' are not material.
   *  They are create the .zip files referred to in the 
      http://localhost/cologne/md/web/webtc/download.html
   * There is a way to get 'zip' to be understood by GitBash if we later want to do this

Next things to try for md:
*  Go to  url localhost/cologne -- you should get a 'home page'
* Try accessing the displays for 'md' (B L A M) - they should work
* Next try the link to 'simple search'
  * You'll need the '.htaccess' file to be in the cologne directory.
  * Choose dictionary 'md' -- You then should be able to look up words in md.

When all the above look ok, you could then (in csl-pywork/v02) 
* manually generate other dictionaries (`sh generate_dict.sh xxx ../../xxx` for other dictionary codes xxx OR
* `sh redo_xampp_all.sh` to generate all the dictionaries.

**Comment by JuliaNikolaeva** [comment]
> * Go to  url localhost/cologne -- you should get a 'home page'
> * Try accessing the displays for 'md' (B L A M) - they should work
> * Next try the link to 'simple search'
![image](https://user-images.githubusercontent.com/32849539/158243336-1f24cf72-2c99-4f82-967a-40948c118dbe.png)

>   * You'll need the '.htaccess' file to be in the cologne directory.
>   * Choose dictionary 'md' -- You then should be able to look up words in md.

I don't see the file  '.htaccess' 
![image](https://user-images.githubusercontent.com/32849539/158243668-7035d025-9e3b-414a-b82e-a27e011f0d26.png)

> 
> When all the above look ok, you could then (in csl-pywork/v02)
> 
> * manually generate other dictionaries (`sh generate_dict.sh xxx ../../xxx` for other dictionary codes xxx OR
> * `sh redo_xampp_all.sh` to generate all the dictionaries.
for example
![image](https://user-images.githubusercontent.com/32849539/158243853-dc5fcc8a-d47f-4be0-a66e-d67281baaf8b.png)

**Comment by funderburkjim** [comment]
> Regarding one-button solution

The script requires a parameter for the dictionary code:
`sh downloadCologne_one.sh md`

**Comment by JuliaNikolaeva** [comment]
Thank you so much for your help and patience! Everything is working well now

**Comment by funderburkjim** [comment]
@JuliaNikolaeva Glad to hear that!  Let me know if further issues arise.

Will let you close this issue, if you think there are no more questions for now.

**Comment by gasyoun** [comment]
@JuliaNikolaeva thanks for takin this ride with our miraculous @funderburkjim 
Can I ask you to document all the steps taken or even make a video for us, please?

**Comment by drdhaval2785** [comment]
From what I see on screen, you may also have missing “zip”  program. You can download zip for your operating system. Programs would work more smoothly I guess.

**Comment by funderburkjim** [comment]
## installation of zip
The 'zip' command is needed by Gitbash in 'sh generate_dict.sh md  ../../md' to generate the .zip files
in /c/xampp/htdocs/cologne/md/downloads/.   These files are not used by the displays, unless you
want to download them.  Thus, the absence of 'zip' is not critical.
However, you may want to have zip.

The readme file at https://github.com/sanskrit-lexicon/COLOGNE/tree/master/localinstall/xampp
now has instructions for installing 'zip'.

**Comment by funderburkjim** [comment]
## request for proof-reading

@JuliaNikolaeva and @drdhaval2785   Request that you carefully review the 'readme.txt' file mentioned above and make suggestions for improvements as needed.

**Comment by funderburkjim** [comment]
## Why python3 needed

> copy python.exe to python3.exe
   Sounds fishy to me.

One quirky feature is that both 'python' and 'python3' are used in various shell scripts that
are invoked by generate_dict.sh
Thus, local installations we also need both 'python' and 'python3'.

The scripts are supposed to work both on the Cologne Server as well as in local installations.

On the Cologne server,  In a script, 'python --version' yields 2.7.5 while
'python3 --version' yields 3.6.8.   Some of our python programs do make use of python version 3,
so we need to run them on Cologne server with 'python3'.

Thus, for the scripts to work on local server, we need
to have both 'python' and 'python3' .  The local install  instruction (`copy python.exe python3.exe`)
happens to be one way to get 'python3' on local Windows installation.

**Comment by JuliaNikolaeva** [comment]
> ## installation of zip
> The 'zip' command is needed by Gitbash in 'sh generate_dict.sh md ../../md' to generate the .zip files in /c/xampp/htdocs/cologne/md/downloads/. These files are not used by the displays, unless you want to download them. Thus, the absence of 'zip' is not critical. However, you may want to have zip.
> 
> The readme file at https://github.com/sanskrit-lexicon/COLOGNE/tree/master/localinstall/xampp now has instructions for installing 'zip'.

I installed 'zip'  as it is written in the readme file. Everything is working fine now. Thank you very much!

**Comment by funderburkjim** [comment]
@JuliaNikolaeva   Thanks for feedback that zip instructions worked for you.

**Comment by gasyoun** [comment]
> zip instructions worked for you.

Should we give a link to them from https://www.sanskrit-lexicon.uni-koeln.de/scans/csldev/csldoc/build/index.html ?
