### ISSUE TITLE
google fonts in cologne websites

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#396]
This note received from webmaster of https://www.sanskrit-lexicon.uni-koeln.de/.
(translated by Google, the note reads in part):

> 
subject: Use of Google Fonts in web projects
dates: 8/11/2022, 3:35 AM
There are currently increasing reports that specific websites are being searched for the unauthorized use of Google Fonts under the General Data Protection Regulation (GDPR) and are being warned accordingly. See e.g.:
https://www.golem.de/news/google-fonts-abmahnungen-an-webseitenoperator-mit-google-fonts-2208-167472.html
Google fonts are often used unknowingly, e.g. in numerous Wordpress templates. It is important that you check as soon as possible whether you are using Google Fonts or other third-party tools that transmit unsolicited personal data such as IP addresses to non-EU companies and rectify this problem if necessary.
To check, you can simply call up your website with a standard browser such as Chrome or Firefox. In Chrome, the key combination "Ctrl+Shift+i" opens the developer tools. Switch to the "Network" tab and reload the page once. Then you will get a list of all automatically loaded resources. In the attachment you will find an example in which, unfortunately, personal data is immediately sent to domains such as twitter.com and cookiebot.com without any possibility of intervention. If this is also the case with your project, please take remedial action to avoid a warning.

**Comment by funderburkjim** [comment]
I don't think we use google fonts anywhere, but am not sure.

Please mention in a comment if you know of any such usage, so we may make adjustments in light of the webmaster's request.

Thanks!

**Comment by gasyoun** [comment]
We do not use them as far as I know.

**Comment by drdhaval2785** [comment]
Time to close?
