### ISSUE TITLE
where is file dicts.txt?

### ISSUE THREAD

**Issue by koleslena** [sanskrit-lexicon/COLOGNE#413]
In [notes](https://github.com/sanskrit-lexicon/COLOGNE/blob/master/localinstall/mac/notes.txt) it is mentioned a file dicts.txt with all the dictionary codes. I cannot find this file.

**Comment by drdhaval2785** [comment]
acc ae ap90 ben bhs bop bor bur cae ccs gra gst ieg inm krm mci md mw mw72 mwe pe pgn pui pw pwg sch shs skd snp stc vcp vei wil yat lrv armh lan

**Comment by drdhaval2785** [comment]
You can use these codes.
