### ISSUE TITLE
Learnt to upload new dictionaries to CDSL

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#414]
A happy moment for me to tell you all that I could upload two small dictionaries on CDSL .
They are ACPH and ACSJ.
@funderburkjim 's documentation helped a lot.

**Comment by funderburkjim** [comment]
I'm glad to know my notes were intelligible!

**Comment by drdhaval2785** [comment]
Yes, they were.
