### ISSUE TITLE
SIMPLE search stopped working

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/COLOGNE#415]
@funderburkjim 0 no results found

it stopped working a week ago.

![sasdadsaaads](https://github.com/sanskrit-lexicon/COLOGNE/assets/80761/0a3b8460-043e-4fd5-88bc-904027f556a8)

**Comment by funderburkjim** [comment]
This now solved.
<img width="715" alt="image" src="https://github.com/sanskrit-lexicon/COLOGNE/assets/6393033/cc922863-88a8-4dc3-a235-6d8286fa80e4">

See https://github.com/sanskrit-lexicon/csl-apidev/issues/37 for further discussion.
