### ISSUE TITLE
Cologne web site documentation with sphinx

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#42]
http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/csldoc/cslv0/index.html

I'm trying the python sphinx documentation system (http://sphinx-doc.org/) as a way to generate site-wide documentation.  Python is used to create the documentation from a collection of restructured text files;  the resulting documentation is a collection of html, css, and javascript that seems to run anywhere.

The current form of the above link is very primitive - I essentially just have stubs which need to be filled in.  But, I thought this might be a way to develop a good documentation system for the site, and wanted your opinions.  

Also, if you see any major headings missing, please mention that.

Marcis, the 'How you can help' section might get at what you were wanting. Maybe you could provide some details and better wording there. 

Shalu, if you have some materials related to FAQ, maybe you could forward them to me as a way to fill out the FAQ section.

Thanks to everyone for taking a look.

**Comment by drdhaval2785** [comment]
csl-doc repository handles this well.
