### ISSUE TITLE
fri_01 

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#420]
We aim to get fri.txt into a form consistent with the cdsl conventions.

I noticed that in general the current fri_00.txt entries are in a 3-line form:
```
<L><K1>x</K1><K2>y</K2>
<K2>a</K2>
<p>LENG n = "RUSSIAN">b</LENG>
<p><LENG n = "ENGLISH">c</LENG>
<p><LENG n = "CZEСH">d</LENG>
<pc>page<p>
<LEND>

Note 1:  The 5 middle lines are actually in ONE line of fri_00.txt.  
Note 2:  When there are homonyms, (e.g. 'a', 'akza'), then there is one 
of these  middle sections for each homonym.
```

However, there are some exceptions to this general form:
For instance, there are 1789 lines in fri_00.txt that do not start with the '<' character.  e.g.
```
575@ambu@ambu n.@вода@water@31@voda
```

@artanat I suggest you rewrite these '@' lines in the general form.

Call the resulting version fri_01.txt.

As a point of organization, I suggest:
* create a '01' directory
* Create a readme.txt file in the 01 directory -- Use this for documenting.
* create a program to do the conversion. e.g. a python program 'fri_01.py`
  * `python fri_01.py fri_00.txt fri_01.txt`

Let's see how this goes.

Also, do you notice any other variation from the 'general' form?

**Comment by funderburkjim** [comment]
Oops!
I put this issue in the wrong place!

**Comment by funderburkjim** [comment]
Copied this issue at https://github.com/sanskrit-lexicon/Frish/issues/2

**Comment by drdhaval2785** [comment]
Copying is easier, but it is also possible to transfer an issue across repositories. https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository# is an easy step.

**Comment by artanat** [comment]
@funderburkjim Modified file, all lines start with the '<' character.

[fri_01.txt](https://github.com/user-attachments/files/25337263/fri_01.txt)
