### ISSUE TITLE
How I Search and Submit Corrigenda

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/Cologne#47]
Out from 40 mistakes in my Dec-2013 fuzzy file on Sep-2014 I could submit only 25 errors (most of these 25 took 1 hour to submit, but in general making a video and documenting the process took 5 hours https://docs.google.com/spreadsheet/ccc?key=0AoQI5iPSBGwMdEJycVQ2aHZyOC1FTnRRYlY1blY0ekE#gid=0). 7 where allready corrected (some I might have submitted, but not all). Could not locate a single word in Stchoupak Dictionnaire Sanscrit-Français.
http://www.youtube.com/watch?v=Hs8cXhuIvfE&feature=youtu.be
There are several modes, let me illustrate one.
1) I use fuzzy MS Excel plugin and compare MW vs other dictionaries to find errors, grammar and variant issues.
2) I use a selfmade macro to add red colour to the letters that should be of interest, letters that are different in similar words (SLP does not work here, because capital letters are not well recognized by the fuzzy algorythm, so I use IAST and devanagari, some can be found only in devanagari, but almost none can be found in SLP).
3) For every column of IAST I have additional column of HK. Because it's the default mode (I can not change the default and have to click and change it every time I visit the website, so a few times per day). So I copy paste the HK (I have to convert and keep HK for every word I work with for reference purposes) to http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/webtc/indexcaller.php
If I do not have a word in HK but only IAST, I can convert it in MS Word with my self made converter or in EmEditor, the default text editor I use to deal with nagari. I copypaste the word to a new document, launch my trans2hk.vbee macro, select, copy it, paste it to the website and here we go.
In my case prasannaveGkaTezvamAhAtmya
Now I have to do 3-5 copy pastes and switching tabs. And pray for https://github.com/sanskrit-lexicon/Cologne/issues/45 I'm thinking maybe we need a popup and not a full page tab. I forget what's written on the page and switch often. And as there about 30 different tabs in my Chrome, it gets tough.
4) http://www.sanskrit-lexicon.uni-koeln.de/php/correction_form_thankyou.php Should have link if I want to submit one more. Otherwise I have to do steps I would prefer not to do. "Corrections" is a bad link name. A verb should be included. "Submit an error".
The rest can be seen in the video above, after submitting all these errors I've been tired. An there a few more hundred candidates, similar to:
<code>maitrāyaṇīpariśiṣṭa  maitrāyaṇīyapariśiṣṭa
abhinilīyamānaka  abhinilīyayamānaka</code>

**Comment by drdhaval2785** [comment]
The system for correction submission has been fairly standardized.

**Comment by gasyoun** [comment]
@amordvinov has a solution based on https://github.com/neongreen/orphus.js/blob/master/orphus.js but a few questions to @funderburkjim as yo where, in what file should he implement it, so it would be added to all the dictionaries at once?

**Comment by funderburkjim** [comment]
We already now have a 'Corrections Form' button on the displays.

What functionality would use of orphus.js add?

**Comment by gasyoun** [comment]
> What functionality would use of orphus.js add?

Speed, see https://youtu.be/1gK1uD_10P8

**Comment by funderburkjim** [comment]
Video Helpful.  I understand the point you are making -- ease of use for user to submit correction. 

Worth further examination.  

What is the status of solution proposed by @amordvinov ?  

Once we get a good solution for one display of one dictionary, that solution can propagate to
other displays for other dictionaries by being integrated into [websanlexicon](https://github.com/funderburkjim/websanlexicon) project.

**Comment by gasyoun** [comment]
> What is the status of solution proposed by

Ready for implementation. How to?

> into websanlexicon project.

Perfect, that was one of his questions.

**Comment by SergeA** [comment]
> We already now have a 'Corrections Form' button on the displays.

It's very frustrating to use this form with manual filling of all these fields. I hate to do this permanent copy-pasting. I am a lazy man (as I believe all the people are), and I want to select a wrong word with mouse, then click an ERROR button or press some keys, and then only type the correction. The numbers, the headings, the selected wrong words should be auto-filled by script.

**Comment by funderburkjim** [comment]
Ready for implementation. 

Please don't use websanlexicon initially.  Download the development version of one of the 
dictionaries and implement within the 'basic' display for that dictionary.

What I would really prefer, before you get too involved with the Cologne displays, is a live example  of a (small) website with the solution implemented therein.
This should be doable within a GitHub gh-pages example, perhaps hooked up to some simple backend.

Agree?

**Comment by funderburkjim** [comment]
@gasyoun  @amordvinov 

Was my suggestion regarding a 'live example' a problem?  

Another thought as to how you could implement orphus in a test environment involving the Cologne dictionaries.

I recently wrote a refactorization of the basic display using vue.js. 
https://funderburkjim.github.io/sanlex-vue/basicv0.2b/index.html
  [Please note: because this uses an intermediate website at pythonanywhere,  usually the first
   time you search for a word, it fails-- because the pythonanywhere site takes a while to 'wake up'.
   Just search again and you'll get the result.]

You could clone the repository:
https://github.com/funderburkjim/sanlex-vue

and then modify the basicv0.2b  application to use orphus.

**Comment by funderburkjim** [comment]
### concern about 'back-end'

Any practical solution must also take into account the back-end processing of correction submissions.
That is something that I do.  The current Correction Form submission has the virtue of giving precise
information regarding where to find the record that needs correction, and what the correction should be.   The new system will need to
also have this virtue if it is to be practical, so please keep this requirement in mind as we think more
about improving the user ease of use in correction submission.

**Comment by gasyoun** [comment]
> is a live example of a (small) website with the solution implemented therein.

I do not know how to. Neither does @amordvinov 

> Xampp application with php backend

I told him about it, but seems he has not tested it.

> GitHub gh-pages example, perhaps hooked up to some simple backend

No idea how to.

> Then, Download the development version of one of the
dictionaries and implement within the 'basic' display for that dictionary -- if you have xampp, this is
easy to do -- I can get you details.

He wants a readme.

> because the pythonanywhere site takes a while to 'wake up'.

Oh.

> You could clone the repository:
https://github.com/funderburkjim/sanlex-vue

and then modify the basicv0.2b application to use orphus.

That's a plan.

> The new system will need to
also have this virtue

It will.

**Comment by funderburkjim** [comment]
> That's a plan.

Good!  Start with that.  

 I can provide readme for 'download the development version' later if that
is required; it works with xampp  (which provides server with php on local windows machine). If you 
already have access to a server with php on some machine (local or cloud), the dev version probably
will work there also.

**Comment by amordvinov** [comment]
Hello @funderburkjim @gasyoun

I realized the feature for the basicv0.2b application of the repository: https://github.com/funderburkjim/sanlex-vue. I created my own branch for the feature but I haven't enough rights to push this branch and create a PR into the branch gh-pages.  Could you help me and give the rights?

P.S. My first version uses the same server script to save result. I changed orphus script to send results to send params here: http://sanskrit-lexicon.uni-koeln.de/php/correction_form_response.php. You  can see this file http://sanskrit-lexicon.uni-koeln.de/php/correction_response/cfr-20181104.tsv. First strings are from my script. I'd tested it. 

P.P.S. Please, see the screenshot. The word selected by the user is placed between tags <!!!>. I can change them as you want. There are texts before and after the selection. I placed the selection into param **entry_L**. The params **entry_old** and  **entry_new** are always empty now. I don't know if they are needed. This changed script can be easily used in other dictionaries.
![correction](https://user-images.githubusercontent.com/26087215/47960696-c2289f80-e039-11e8-8867-618c4a61a98f.jpg)


Thanks,
Aleksey

**Comment by gasyoun** [comment]
At https://github.com/funderburkjim/sanlex-vue I have not rights, so only Jim can. I can only at https://github.com/sanskrit-lexicon/ - but Jim's coding experiments are outside it. So not sure, maybe https://github.com/amordvinov/sanlex-vue will do for @funderburkjim to take the code and edit it.

>  entry_old and entry_new are always empty now.

As I understand sure they are - otherwise how do we know what to change with what?

**Comment by funderburkjim** [comment]
@amordvinov 

Looks like you are making progress!  Why don't you just clone the repository into one of your own,
then upload to your github  account and send me the address.  I'll then clone your repository and be able to examine

**Comment by gasyoun** [comment]
> I'll then clone your repository and be able to examine

Hope we can finalise it in two weeks from now.

**Comment by gasyoun** [comment]
> I'll start by cloning that.

So the show goes on?

**Comment by funderburkjim** [comment]
@amordvinov 

Have got your basicv0.2b working !  

I have several questions. 

First,  the format of what you are sending to the correctionurl is not quite right. 
Here is an example of what the previous correction-form dialog sends:

``` 
<tab> indicates a tab character
1              2                           3                              4                       5                        6                7
MW<tab>ID=147007<tab>brahmavAdin<tab>(finī., Var.<tab>(inī f., Var.<tab>Typo<tab>Caujolle
```
So there are 7 fields.
1. dict code -- you've got this
2. Cologne id -- you can leave this as a constant 'ID=' -- no good way to deduce this.
3. key -- you've got this, but not at right position
4. Error text.   You can leave this as the <!!!>xx<!!!> text 
5. the correction.  This would be from your 'Comment(optional)' field, I presume.
    I suggest you change the field label to 'Correction'  or maybe 'Correction/comment' -- this should
    *not* be marked as optional.
6 . Error type (You can just put in constant 'Typo')
7.  Email(optional).   I prefer  label to be 'Your email or name (optional):'

Also, it might be better to have, in your form, the email after the comment .

So first change request is to generate a 7-field tab-delimited output as above.

**Comment by gasyoun** [comment]
> 7-field tab-delimited output

Clear for me.

**Comment by amordvinov** [comment]
Hello @funderburkjim 

I fixed points 7, 5, 4. But we should disscuss of other fields. For the development I used the script http://sanskrit-lexicon.uni-koeln.de/php/correction_form_response.php as the backend part. This script can process only next external params: entry_L, entry_comment, entry_dict, entry_email, entry_old, entry_new, entry_hw. How should I fill every params? You mentioned "Cologne id", "key", "Error text", "Error type", "the correction". Please, describe the accordance of the params and fields you mentioned.

For now I used next params filling:
![2018-11-18_15-49-51](https://user-images.githubusercontent.com/26087215/48670507-7e5e8b80-eb4b-11e8-943d-f76c814eee8b.png)

![2018-11-18_15-51-39](https://user-images.githubusercontent.com/26087215/48670509-861e3000-eb4b-11e8-9bf0-b23c0cdf98c1.png)

Also I have a question: how wee should find "Cologne id"? Just parsing? 

Thanks,
Aleksey

**Comment by gasyoun** [comment]
> entry_L, entry_comment, entry_dict, entry_email, entry_old, entry_new, entry_hw. How should I fill every params? You mentioned "Cologne id", "key", "Error text", "Error type", "the correction".

Yeah, sounds confusing.

**Comment by funderburkjim** [comment]
### how much context to send:

I think you changed the amount of text in 'entry_old'   to include only the selected text:
`<!!!>reddish brown<!!!>`

And that in previous version you included some context around the selected text.

@gasyoun   Should there be some context around the selected text?  Maybe 10-20 characters on either side of the selection?   I'm thinking this would help me to identify the problem when I'm installing the correction.

**Comment by amordvinov** [comment]
@funderburkjim @gasyoun OK, I haven't any comments. Let it be so! =)

**Comment by funderburkjim** [comment]
@amordvinov   Notify us when these changes made in your repository and I'll update my copy of the orphus-feature branch.

T

**Comment by amordvinov** [comment]
Hello @funderburkjim @gasyoun 

I added the changes described above. Also I increased the number of characters before and after the selected text.

**Comment by gasyoun** [comment]
Guess it's done.

**Comment by funderburkjim** [comment]
@amordvinov 

Just tried it out, and corrections you made look right: 👍 
1. The entry_old, entry_new fields have right information
2.  There are extra characters in the entry_old field, which should be enough for context
   * The current version does not have the '<!!!>' surrounding the selected text.   This maybe
      should be restored.

I think maybe next step is for me to try to integrate this into the 'simple-search' program at
Cologne, since that's the one Marcis uses most.

@amordvinov  It would be a big help if you could now write some documentation.
Specifically:
1) in app.js,  Why did you put 'orphus.init' under 'axios.get' ? Where else could orphus.init be?
2) What is the relation between orphus.js and orphus.customized.js .  Most of your work is in
    orphus.customized.js.  Did you do anything in orphus.js to let it know about orphus.customized.js?
3) Where is the event-handler attached to 'Ctrl-Enter' keypress ?
4)  Where is the modal-dialog window opened and specified.  If I wanted to make the modal window
     to be movable, where would I do that?
5)  Briefly Identify the functionality of the functions of orphus.customized.js.   
6) What is the  order of execution of the functions  
7) when user clicks 'submit' or 'cancel', where are the handlers.

**Comment by funderburkjim** [comment]
@amordvinov 

Will you be able to do the documentation mentioned above?   If not, let me know and I'll get started on integrating your work into the simple-search program.

**Comment by amordvinov** [comment]
Hello @funderburkjim 

Yes, of course. I will add the documentation asap (tonight or tomorrow).

**Comment by gasyoun** [comment]
> I think maybe next step is for me to try to integrate this into the 'simple-search' program at
Cologne, since that's the one Marcis uses most.

Makes sense.

**Comment by amordvinov** [comment]
@funderburkjim 

> I think maybe next step is for me to try to integrate this into the 'simple-search' program at
> Cologne, since that's the one Marcis uses most.

Yeah, it's a good idea.

> 1. in app.js,  Why did you put 'orphus.init' under 'axios.get' ? Where else could orphus.init be?

The method orphus.init is responsible not only for initialization but for setting new values. Therefore,  it should be called when the word to search and dictionary are ready.

> 2. What is the relation between orphus.js and orphus.customized.js .  Most of your work is in
>    orphus.customized.js.  Did you do anything in orphus.js to let it know about orphus.customized.js?

The script *orphus.js* was developed by other developer.  The link to the project: https://github.com/neongreen/orphus.js. I customized it to satisfy our wishes.  So *orphus.js* is original script. I didn't change it.

> 3. Where is the event-handler attached to 'Ctrl-Enter' keypress ?
> 4. Where is the modal-dialog window opened and specified.  If I wanted to make the modal window
>    to be movable, where would I do that?
> 5. Briefly Identify the functionality of the functions of orphus.customized.js.
> 6. What is the  order of execution of the functions
> 7. when user clicks 'submit' or 'cancel', where are the handlers.

**Comment by gasyoun** [comment]
https://mistape.com has similar functionality and impressing UI, but for WP blogs. Jim, has Alexey answered enough questions to see it live, finally, please?

**Comment by funderburkjim** [comment]
### installed in simple-search

Just to be sure, the url is [this](https://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/simple-search/v1.0/list-0.2s.html).

There were several odd things that occurred, but let's see if the functionality is there before discussing the oddities.

@gasyoun   -- give it a test drive!

**Comment by gasyoun** [comment]
Hurray!

It was about time. Let me start commenting.

![typoe](https://user-images.githubusercontent.com/80761/49780419-827f6280-fd1f-11e8-94b2-3cd7780deb5f.PNG)

**Comment by funderburkjim** [comment]
### confirm of test correction
Just checked server, and found this test correction from @gasyoun 
```
12/11/2018 19:08:27	mw		agni	[L=890]       the number three, Sūryas.   [L=891]       the god of fire, the <!!!>fire<!!!> of the stomach, digestive faculty, gastric fluid  [L=892]       bile, L.	testing		gasyoun@ya.ru
```

**Comment by funderburkjim** [comment]
### General comment on UI changes

It would have been better to make these suggestions while amordinov was making other changes; the code in its current form is hard to change.

I like the idea of a having the 'correction/comment' field to be multiline.  I tried to implement this by changing this from `<input type="text"/"` to a `<textarea>..</textarea>`, but was not able to get everything to work:  The current code makes assumptions that the two user-supplied fields ('correction/comment' and 'email/name') are `<input>` elements.

I personally would prefer to leave the 'Cancel' button.

I am neutral regarding the other UI changes suggested above.

I'd like to see if @gasyoun  and/or @sergeA  make use of the form in its present state before investing time to change the UI.

If @amordvinov  wants to make changes now, I'll be glad to add them to the simple-search.

**Comment by funderburkjim** [comment]
### Are element ID's needed in orphus?
The 'id' attribute is used in orphus.minimized, at least in the two `<input>` elements.   Since the 'id' attribute is global  (i.e., in the whole of the web 'page' html), it would be better not to use this attribute.  
@amordvinov   Is it safe to remove these id attributes in orphus.minimized?

**Comment by gasyoun** [comment]
> checked server

Server or google docs?

> code in its current form is hard to change

Understood.

> but was not able to get everything to work: The current code makes assumptions that the two user-supplied fields ('correction/comment' and 'email/name') are <input> elements.

Oh, got it.

> Is it safe to remove

Guess we can only try.

**Comment by SergeA** [comment]
Better to separate "Correction" and "Comments" fields. 
Better to give a copy of the selected text in the "Correction" field for easy correction.
Better to make multilined comments.
Better to give some response after sending. E.g. "Thanx 4 da help. U R da best!!! :)) Press ESC to continue."
Better to place the cursor in the "correction" field after frame-opening.
Ctrl+Enter once again to send the correction.

> I would remove the Cancel button. 

I'd not.
But better to place this "Cancel" button in distance from "Send". E.g. "Cancel" in the left and "Send" in the right corner.

> Decrease the length of the email field, leave 1/4 of it

Doesn't matter.

> Make comment field multiline, 2-3 lines.

5 lines or even more.

> Make the background darker

Or just to change the color of the frame to make a visual difference.

**Comment by funderburkjim** [comment]
Just to be clear, I am expecting these UI changes to be made by @amordvinov  --  Do you agree? 

 I am viewing my task to be installing at Cologne.

Another UI change which I think could be useful is to have the form be draggable , so it can be moved out of the way of the underlying display.
