### ISSUE TITLE
Link to Exact Line, not Page

### ISSUE THREAD

**Issue by Shalu411** [sanskrit-lexicon/COLOGNE#5]
http://www.sanskrit-lexicon.uni-koeln.de/scans/PWGScan/2013/web/webtc2/index.php 

PWG Advance search>Sanskrit Word>Exact>"ziva">20output>12th entryभीम>

Now I would want to know where exactly here (in भीम) "ziva" occurs in that article. I have to scroll and manually find that word. 
It means- in each entry, where that word is found in the dictionary- those entries are given-- That's fine. But this word is not highlighted in those articles. Sometimes they are too long- and we cannot search with bare eyes for that little word.
If it could be highlighted, then would help much more.
Thankyou.

**Comment by drdhaval2785** [comment]
@funderburkjim 
Rather than looking for a server side approach, can we try browser side like javascript
http://www.the-art-of-web.com/javascript/search-highlight/ would be of some use?

**Comment by gasyoun** [comment]
@drdhaval2785 seems interesting, the more it has even a `Patch for accented characters`.

**Comment by funderburkjim** [comment]
These issues (5,8,9,10,11) will have to remain open.  
They are too complicated for me to consider now. :disappointed:

**Comment by drdhaval2785** [comment]
@funderburkjim, @Shalu411 and @gasyoun 
How do you like http://sanskrit-lexicon.github.io/cologne/highlighter/index.html ?

It highlights MW entry of Siva.

Uses http://www.the-art-of-web.com/javascript/search-highlight/ - hilitor-utf8.js to be precise.

Only lines added in the display HTML are
```
	<script type="text/javascript" src="hilitor-utf8.js"></script>
	<script type="text/javascript">

	  var myHilitor2;
	  document.addEventListener("DOMContentLoaded", function() {
		myHilitor2 = new Hilitor2("data");
		myHilitor2.setMatchType("left");
		myHilitor2.apply("Siva");
	  }, false);

	</script>
```

What I would want from @funderburkjim is 
Give me a string of keyword searched instead of "Siva" in `myHilitor2.apply("Siva");` line.
Preferrably it should be converted to the encoding in which the user wants his output e.g. SLP1, HK, IAST etc.

**Comment by drdhaval2785** [comment]
I guess this should be easily doable by PHP generating the page.

**Comment by gasyoun** [comment]
I guess it's a new issue. @Shalu411 was related to visual picture. Yours is textual only.

**Comment by funderburkjim** [comment]
I like the Siva example! 

From my reading of @Shalu411's suggestion, this addresses the issue she raised.

@drdhaval2785  - do you have this implemented locally  in mw/web/webtc2 ?

**Comment by drdhaval2785** [comment]
@funderburkjim No, I have not implemented in mw/web/webtc2.
This is just addition to a locally saved copy of the webpage.
Added a .js file and added https://github.com/sanskrit-lexicon/Cologne/issues/5#issuecomment-159498202 script to head of the html.

I could not understand the PHPs used for display of webpage. So didn't venture.

**Comment by drdhaval2785** [comment]
@funderburkjim 
Time to implement this functionality. Would be a great additionality to our repertoire.

**Comment by gasyoun** [comment]
> Time to implement this functionality. 

Or to add an OCR layer to the files and highlight the word found (but not strict correspodence, even partly would be enough.) But devanagari only files are too big for Oliver's OCR, will not manage them. 100+ pages is too big for Sanskrit OCR software.

**Comment by funderburkjim** [comment]
This again is a case where it would be better to use existing search engine technology than reinvent the
wheel.  I think this facility is called `highlighting`, and Google searches for 'Elasticsearch highlight'  will
bring up references.

I have set up an ECS instance of the Bitnami elastic search, with the intention of sometime trying to
fit one or two of our dictionaries into that search-engine framework.   It is also easy to install an elasticsearch instance on a local computer - I've done this and played around at a very preliminary level
using the book `ElasticSearch in Action` for learning.

Maybe it's time to get more serious with this approach, and see if my intuition pans out regarding utility of applying search-engine technology to our collection of dictionaries.

**Comment by gasyoun** [comment]
@artforlife ever dealt with highlighting?

**Comment by drdhaval2785** [comment]
Text highlight and PDF higight still elude us I guess. Right, @funderburkjim ?

**Comment by funderburkjim** [comment]
I must have missed this posting.

I like the  http://sanskrit-lexicon.github.io/cologne/highlighter/index.html 

Is it feasible to implement this in advance search display?

**Comment by drdhaval2785** [comment]
Yes, it seems feasible. 
It is just a .js file.

**Comment by funderburkjim** [comment]
OK -- I'll put it on nearterm list to investigate.

**Comment by drdhaval2785** [comment]
This is the relevant part of code.

```html
	<script type="text/javascript">

	  var myHilitor2;
	  document.addEventListener("DOMContentLoaded", function() {
		myHilitor2 = new Hilitor2("data");
		myHilitor2.setMatchType("left");
		myHilitor2.apply("Siva");
	  }, false);

	</script>
```

**Comment by drdhaval2785** [comment]
Instead of "Siva" which is hardcoded as of now, we would have to fill the searched word.

**Comment by gasyoun** [comment]
> nearterm list to investigate.

Thanks, it's one of the top 5 UI issues, agree with Dhaval.

**Comment by drdhaval2785** [comment]
#355 highlights all occurrence of searched word.

**Comment by gasyoun** [comment]
@artanat please share the code we use at https://samskrtam.ru/parallel-corpus/ for @funderburkjim

**Comment by funderburkjim** [comment]
@artanat 
Hi, Anatoly. Thanks for the JS.

Could you provide a stand-alone html demo?

**Comment by funderburkjim** [comment]
@artanat   I see that in Dhaval's comment above there is an example.
Maybe that's the demo I was looking for. Let me look at that first.

**Comment by funderburkjim** [comment]
@drdhaval2785   Your highlighter demo url http://sanskrit-lexicon.github.io/cologne/highlighter/index.html  works.  

But where is the code?  I don't find it at https://github.com/sanskrit-lexicon/COLOGNE/.

**Comment by funderburkjim** [comment]
## mdhl1: first use of highlighter
https://sanskrit-lexicon.uni-koeln.de/work/hilitdev/mdhl1/web/webtc2/index.php

This is an adaptation of the current normal display of md, using [hilitor-utf8.js](https://sanskrit-lexicon.uni-koeln.de/work/hilitdev/mdhl1/web/webtc2/hilitor-utf8.js) from Dhaval's demo.

It partially works - e.g.  for text word  'exact' or 'prefix', and if search term contains only normal alphabet (no diacritics, no devanagari).
Suffix, infix,substring don't work (no highlighting) 

'Sanskrit word' search works (with exact/prefix) if both input and output are slp1 or HK.

The way it works is (roughly):
* html is generated as per usual, and then inserted into the DOM at a particular div (id='data').
* A call is made to a function in  hilitor-utf8.js,
  The Dom at this div is itself searched and some css (yellow background) is inserted where matched.  The effect is to highlight the searched word.

## probable next step
  modify the js to get rid of some or all of the limitations mentioned above.

Request others to experiment and to provide feedback on what are the most important types of searches that would benefit from highlighting.  

I suspect that some of the limitations are unavoidable in this method. (e.g. searching for an slp1 input, but specifying a "Devanagari" output).

**Comment by artanat** [comment]
> @artanat I see that in Dhaval's comment above there is an example. Maybe that's the demo I was looking for. Let me look at that first.

https://samskrtam.ru/parallel-corpus/s/arjuna-617.html

**Comment by gasyoun** [comment]
![dffdsfdsfds](https://github.com/sanskrit-lexicon/COLOGNE/assets/80761/e0f503f2-89a4-43d6-8359-c2f052d442e7)

Looks promising, Jim! Anatoliy's code additionaly can go from one place to another.

**Comment by funderburkjim** [comment]
## demo based on @artanat 

This demo also local to md dictionary.

https://sanskrit-lexicon.uni-koeln.de/work/hilitdev/md_artanat/web/webtc2/index.php

More robust than mdhl1 above.

@artanat  What does the '=' button do?

----------------------------------------------------------
Request feedback.  There are some searches where hi-lighting fails, but I think these are acceptable imperfections.

What do others think?  
Should we accept this version for all cdsl dictionaries?

Note: this highlighting is only in Advanced Search.

--------------------------------------------------------------
Sample:

<img width="862" alt="image" src="https://github.com/sanskrit-lexicon/COLOGNE/assets/6393033/ea613ad5-dae1-4ef2-886c-b48e7104d2ae">

**Comment by funderburkjim** [comment]
@gasyoun @artanat 

Request you to provide feedback on the version https://sanskrit-lexicon.uni-koeln.de/work/hilitdev/md_artanat/web/webtc2/index.php mentioned above.

Is it ready for general deployment?

**Comment by gasyoun** [comment]
> Is it ready for general deployment?

Yes, it works. As expected.
![dsddsdsa](https://github.com/sanskrit-lexicon/COLOGNE/assets/80761/5421f668-bbab-45c0-9c07-0b1ec6d376f1)

**Comment by funderburkjim** [comment]
@gasyoun  Thanks for feedback.  @Shalu411 is also reviewing an skd-version.

**Comment by drdhaval2785** [comment]
Hurray. One of the oldest requests coming to a closure.
