### ISSUE TITLE
Unwanted Vertical Scrolling

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/COLOGNE#50]
Is the idea to have a box in a box a good enough practice these days? I have to scroll two windows just to see the results of just one box. I think that the header part is too vague. It can get more compact (2-3 lines can be saved with ease).

![aja](https://cloud.githubusercontent.com/assets/80761/4291427/689ed450-3dc4-11e4-97da-6b75443142d2.gif)

**Comment by drdhaval2785** [comment]
https://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2020/web/webtc2/index.php

Now it does not have vertical scroll, even on firefox in android.
