### ISSUE TITLE
Display of Metadata

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/Cologne#51]
Instead of khad [L=20919] [p= 2-0596]

I see

khad [L=20919] [p= 2-
0596]

So it takes hard to find where to click on the page number to open the scan. Volume and page number is visually broken, when there is actually no need for it to be so. In longer words in dances even more. Would not it be good to have by default:

khad 
[L=20919] 
[p= 2-0596]
P.S. Why is there a space after "p= " but not after "L=" - can we remove space, please? Would it be possible to search by 20919 (L number) one day? When I search in my .xml file it might return 120919 or 20919 - so the web would be quicker in several cases.

**Comment by gasyoun** [comment]
@funderburkjim never came to rescue.

**Comment by drdhaval2785** [comment]
Now it is being handles separately and AP even has implementation. Time to close this.
