### ISSUE TITLE
Gasuns Dhatu Concordance (based partly on Cologne Sources)

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/COLOGNE#52]
https://github.com/sanskrit-lexicon/PWG/issues/7 continued. I would love to see "work comparing verbs of MW with two other sources of verbs: Whitney Roots and Madhaviya Dhatu Vrtii." that has been already done. To proove I'm able to understand and give it some new life let me tell you my story in a nutshell. In 2004 I started entering Palsule's roots, so it's the basis of my concordance, then came EWA, VIA, Bucknell, Zlaiznyak & Lihusina. Huet & Panini I did not enter myself, nor did I took it from Cologne. Cologne I used for PWK.

![find_dhatu](https://cloud.githubusercontent.com/assets/80761/4427064/24344350-45bb-11e4-973f-6fbaf0f2ec33.gif)

Palsule 1955 https://yadi.sk/i/17Mio43qbeRNP
PWG 1855-1875 http://www.sanskrit-lexicon.uni-koeln.de/scans/PWGScan/2013/web/index.php
PWK 1879-1889 http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/indexcaller.php ideally integrated with SCH http://www.sanskrit-lexicon.uni-koeln.de/scans/SCHScan/2014/web/webtc/indexcaller.php
Whitney 1885 https://yadi.sk/i/gxGQLIGwbgScE
EWA 1986-2001 https://yadi.sk/i/Q2VZVgpnbgSXW
VIA I 1997 https://yadi.sk/d/WUf_n0XibgSTi

![werba](https://cloud.githubusercontent.com/assets/80761/4427112/c76df818-45bb-11e4-9af9-c198dbbf4211.gif)

I do not know if SCH contains roots additional to PWK, let me check it for 12427 º entries (aDarIkf 1662 - "ºnach unten bringen , demütigen"; karburIkf 9995 "sprenkeln , buntmachen" does not counts; kalmAzay 10166 "buntmachen"). So most of the lists (there are around 10 more additional smaller lists, none of them at Cologne and I guess never will be because they are not dictionaries at all) come from non-Cologne. But there is the PWK case - it is the single most interesting case and not only my dhatu concordance hardly relies on it, but even in a much bigger way my Reverse Dictionary of Sanskrit. So I took Palsule's list of dhatus and searched for them in PWK, Whitney, EWA, VIA. It took me about half a year to identify issues and more half year to find the guilty ones, including data entry, corrigenda, Excel macros.
In 2012-2014 I've done a lot of drafts based on the data, like reverse sorting Palsule, for example https://yadi.sk/i/YZjGa4qbbgdzn (Reverse-Palsule-Dhatu-Index.pdf) For example, I enlisted several parameters: ATI   ATE OTE DHATUP  onomatop.   Sautra  Wurzel  caus.   v.  l. v.l.    perf.   med.    mit     von     Vgl s.  s. u.
The higher the number (max. 11) the more chances we have a dhatu before us, but actualy even with 0 I have found 3052 candidates (without even -ay ones) in PWG.

![dhatu-gasuns-v13-25-12-13](https://cloud.githubusercontent.com/assets/80761/4427065/297d4a5a-45bb-11e4-8cb1-3a650c413800.gif)

As per https://yadi.sk/d/_YOAUZyObeRbj Gasuns-Dhātupāṭha-Concordance.pdf

![palsule-legend](https://cloud.githubusercontent.com/assets/80761/4427351/55bb0be0-45be-11e4-9298-a4e8efd7dec6.gif)

Out of 18457 cells 12898 are empty; 2173 without a translation (German or English); 3386 with a translation. I try to compare every list between all the other lists. But in this version Palsule is the default list. Palsule contains all Panini roots and all possible Indian editions of dhatupathas.

**Comment by drdhaval2785** [comment]
Verbs being tackled elsewhere. There is a concordance for 16 dicts. Am I right @funderburkjim ? Can you provide the link? I can not locate it.

**Comment by gasyoun** [comment]
> Verbs being tackled elsewhere

Did you mean https://sanskrit-lexicon.github.io/verbs/verbs01/verbs1_merge1_1vmw.html ?

**Comment by drdhaval2785** [comment]
Yes. The same link.
