### ISSUE TITLE
Encoding Issues: <br/> inside words, u7 & æ (VEI)

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/COLOGNE#53]
Is it so, that the different .xmls contain a mix (if compared to different parts of the same xml and compared with previous xmls)? Two examples that continue killing me:
1) con- <br/>sisting
descrip- [Page1-004+ 52] <br/>tion

2) When I see
Bu7hler's Encyclopædia
I want to cry.
So you want to say everybody can see (and encode) Encyclopædia, but can't have Bühler's?

Do not we want to mark br-s that should be removed, if we want a readable text, so our spell checkers do not shout and eyes do not weep? What is the code in display mode that takes care of them? Is there any known solution to keep the best of both worlds?

**Comment by gasyoun** [comment]
@funderburkjim what is the source of the mix? Time to say goodbay for some simpler `AS` cases?

**Comment by drdhaval2785** [comment]
Now no AS remains.
