### ISSUE TITLE
Remove index.php from Directory Links

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/COLOGNE#54]
There is no need to link to http://www.sanskrit-lexicon.uni-koeln.de/scans/BENScan/2014/web/index.php, http://www.sanskrit-lexicon.uni-koeln.de/scans/BENScan/2014/web/ is enough. The shorter the URL, the better. If https://github.com/sanskrit-lexicon/Cologne/issues/6 can't be done, do at least part of it, thanks.

**Comment by drdhaval2785** [comment]
I dont think anything remains to be done now. Right @gasyoun ?
