### ISSUE TITLE
Popular Names vs. Real Printed Book Names

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/COLOGNE#56]
https://github.com/sanskrit-lexicon/Cologne/issues/55 continued. When I click on "Bopp Glossarium Sanscritum" I get the popular name "Bopp Sanskrit Dictionary". It might be a good idea to have a popular name only above, but add bibliographical data below the "Downlods" link as well, please. And as now - there is no year of original data of publishing. "(2014 edition)" is a good way of telling how old is the digital file, but maybe make it "(2014 digital edition)"? There are so many reprints and Indian bookmakers rarely provide bibliography on the original book - we should not use the same practise. "MeulenBeld's Sanskrit Names of Plants" is even more puzzling.
We see <a href="https://www.worldcat.org/title/madhavanidana-and-its-chief-commentary-chapters-1-10-introduction-translation-and-notes/oclc/463543891&referer=brief_results">Gerrit Jan Meulenbeld</a> (no B in the middle, it's not MacDonell) under the "The Mādhavanidāna" name. Yes, people looking for Indian plant names will say thanks, but not having it on the page at least somewhere is a bad idea. I would even add it to the Help or any other section, so it's easy to access. But people, who will want to quote that passage, will think bad about you, if we do not add that data.

**Comment by gasyoun** [comment]
@drdhaval2785 ever had the same issue?

**Comment by drdhaval2785** [comment]
I never had such issue.
