### ISSUE TITLE
Funderburk's RegEx Library

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/COLOGNE#57]
In the preparation of all the dictionaries Jim must have <a href="http://linguistics.stackexchange.com/questions/9131/regex-cooking-book-for-nlp-tasks">library of RegEx</a> combinations that help him compile different editions, compare them in between. Is he ready to slowly share them? I hope so, because reinventing the wheel takes a lot of time.
https://github.com/sanskrit-lexicon/Cologne/issues/48
Note: for mw.xml, the key is identified as the contents of the key1 element <key1>xxx</key1>.
Here's a grep which searches for any character (.) repeated twice that occurs after <key1> but
before the '<' of </key1>:
<code>grep -E "<key1>[^<]_(.)\1\1" mw.xml</code>
"<key1>[^<]_(.)\1\1" does not show nothing in Notepad++. But does a variation http://regex101.com/r/iQ6bK9/1 Must be for Python.

My library has only a few pages, like for MW I use http://regex101.com/r/mD0sJ4/1
<code>([^\W\dA-Z && (I|i|X|x|L|V|.)])\1{2}</code> and <code>(\D|ā|ī|ū|ṛ|ṝ|ḷ|ṅ|ñ|ṭ|ḍ|ṇ|ś|ṣ|ḥ|ṁ|ṃ|Ā|Ī|Ū|Ṛ|Ṝ|Ḻ|Ṅ|Ñ|Ṭ|Ḍ|Ṇ|Ś|Ṣ|Ḥ|Ṁ)\1{2}</code>.
<code>(?<!<)/(?! ?>)</code> count udātta words, <a href="http://stackoverflow.com/questions/26196377/how-to-count-in-words-extracting-tags-like-s">without counting tags</a>, because both have a "/" in them.
`^\d[\d.a-z_*@,]+\s` - find all MBh numeration variants
`\d+[.,]\d{3}\.\d{3}[a-d]?[*@x]?\d*_?\d*`

**Comment by drdhaval2785** [comment]
Now every code is in github. Closing. Long journey
