### ISSUE TITLE
Link GitHub on Cologne web page 

### ISSUE THREAD

**Issue by Shalu411** [sanskrit-lexicon/Cologne#58]
Namaste
Such useful discussions going on on Git hub. Very helpful for anyone who wants to help or contribute to the web site. We see that correction forms are already stuffed with user-inputs. 
Now if git hub repository could be given on web page, then users who are familiar with using this place, would also contribute their part here as well.
Either on Home page or may be on each dictionary page, it will be better.
Please think seriously on this. More good and simple suggestions might come up.
Thankyou.

**Comment by gasyoun** [comment]
Please make a redirect from 2008 to new one, @funderburkjim , see https://www.facebook.com/nityanand.misra/posts/1823860394397698 again. It is still widely used without any need.
