### ISSUE TITLE
URL legth /scans/PWScan/disp2/index.php

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/Cologne#6]
URLs are too long. Would http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/disp2/index.php -> http://sanskrit-lexicon.uni-koeln.de/PWK/ be possible one day? When I look at /PWScan/ I can't even realize if it's PWG or PWK. So I do not know from the URL where I am, because no 3 letter abbreviations are met within it. What good is to know that /scans/ and /PWScan/? I can hardly imagine what are the benefits on the server end as well. But to quote the URLs is hard - they are way too long.

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/Cologne/issues/117 seems the way to go.
