### ISSUE TITLE
Even more lines of comments in code

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/COLOGNE#63]
@funderburkjim If only I could tell how glad I am to see, how thing have been changing in the field of Sanskrit lexicography lately. In 26.01.05 Thomas wrote to the webmaster of the sever on which for the first time I shared Thomas' .tiffs in .pdf format of PWK and PWG for free, what was classified by Thomas as "I do presume that Mr Gasuns has acted rashly and without  evil intentions." Just ten years ago the Sanskrit world was different, not much was shared. I spent months scanning different books myself. I got in trouble after sharing what Thomas has already shared with me. Just ten years ago.
  Just a year ago I could not even download full materials of PWK or PWG of Jim's work - we had to spend weeks scraping them with Anton from Ukraine. I was not aware about Apte and Poona dictionaries - the digital ones. Things have changed drastically. And after getting all this I do not keep silent? Jim, as the last time I wrote a line of PHP was in 2004 and I've never learned python, I ask you to comment even more lines in the code, if possible. You comment well and in a detailed way in the beginning. Just a line or few words after every few lines of code would make it even better, understandable and modifiable.
  It's good to see what a mathematician, doctor and student of literature can do together in just one year. It's been productive. Yes, Thomas "I sent him a DVD with the most important dictionaries, presuming that he would use them for reference to compile a new Sanskrit-Russion dictionary" - I'm still not there. But we are one step closer now. And I'll send one copy of the Reverse Dictionary of Sanskrit to Cambodia if I survive.

M.G.

**Comment by drdhaval2785** [comment]
I understand Jim's code and every literate person can understand his instructions. So closing this.
