### ISSUE TITLE
Eliminate Horizontal Scrolling

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/Cologne#7]
There is no need to have horizontal scrolling, but it is there in all screen sizes. Only part of the screen is used, rest is empty. Can't we just get rid of the scrolling inside a window at all and leave only browser lever scrolling?

![pwg2](https://f.cloud.github.com/assets/80761/1933187/37702c64-7ed7-11e3-98c2-24f7b8ac8eb8.png)
![pwg1](https://f.cloud.github.com/assets/80761/1933188/37738472-7ed7-11e3-9b30-4af051020ae7.png)

**Comment by drdhaval2785** [comment]
It seems that the change is universal now @funderburkjim ?
I don't see horizontal scrolls with either chrome or firefox

**Comment by gasyoun** [comment]
Neither do I see them.

**Comment by funderburkjim** [comment]
So maybe we've lucked out and can close the issue?  @gasyoun ?
