### ISSUE TITLE
Singhalese output request

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#70]
This issue was started by Naena, originally in #69 .

It is a request for enhancement to output options, to include 'Romanized Singhalese' as an option.

I am moving the discussion here, but many useful details are supplied by @naena in #69 .

**Comment by funderburkjim** [comment]
@naena Now that I understand better what you are after, I'll keep it in mind  as I work on new displays.  No promises as to when this might be done.

Incidentally, it sounds like you might be able to tinker with one of the web display downloads, if you are so
inclined. For instance item 5 for the [MW72 downloads](http://www.sanskrit-lexicon.uni-koeln.de/scans/MW72Scan/2014/web/webtc/download.html)  can be installed in a local php web server,
such as XAMPP, and should function just like the online version.   Then, you can modify the code on your
local server.  If you want to try this, I can try to point out where you might intervene to get Singhalese output,
once you get to that point.

**Comment by naena** [comment]
Thanks and sorry for the 4 day delay. (Busy with a report).
I have used XAMPP some years back. But just now let me try it on my web server, alright?

**Comment by gasyoun** [comment]
@naena right.

**Comment by naena** [comment]
Thank you. I just downloaded the files. 'will get back to it in a few days. Until then, cross-fingers.
Your kindness is mush, much appreciated.

**Comment by gasyoun** [comment]
His kindness is above what I've seen in indology folks around the world.
His erudition and programming skills - everything serves a practical purpose.

**Comment by gasyoun** [comment]
@naena no updates, closing the issue?
