### ISSUE TITLE
Repository for legacy Cologne Sanskrit and Tamil Dictionaries Display

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#71]
In the process of thinking about #69, I decided to make a repository for the legacy display
http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/tamil/index.html.

This repository is https://github.com/sanskrit-lexicon/Cologne-Sanskrit-Tamil.

You should be able to use it do make offline or other versions of the display.

**Comment by funderburkjim** [comment]
@naena -  I'm not sure it was you who requested that the legacy deprecated display not be abandoned, but it
was that comment in the Email to Thomas that prompted me to make this display public, and, I hope, accessible.

**Comment by gasyoun** [comment]
@funderburkjim I invited @naena to #Cologne so he can answer here.
