### ISSUE TITLE
Basic display, first steps

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#72]
An early version of a multi-dictionary basic display is [here](http://funderburkjim.github.io/displaysJun2015/basic-0.1.html).  

You could 'roll your own' using this as a guide.  For instance, a display with two dictionaries?
You can run this from anywhere  (e.g. from your local computer).
Comments solicited.
Also, please note things that look like bugs.

**Comment by gasyoun** [comment]
Jim, well done! If we want to look only in one dictionary, than the `dictionary` input field should be a dropdown menu.

**Comment by funderburkjim** [comment]
Good suggestion.   

I was thinking about putting all the code (server side apidev, and this and other) sample displays) in a
repository.   Then, it would have its own 'issue list', so enhancement suggestions like yours could be seen separately. There are also numerous interesting technical issues that probably need such a place so they can be mentioned and considered by others.

Does the separate repository idea sound good? Maybe call it 'Cologne-apidev' , under sanskrit-lexicon project?

**Comment by gasyoun** [comment]
If you think it deserves a place, let it be. I guess even more interesting than choosing between different dictionaries would be showing all entries of a headword from dictionaries on the same page. So 430k pages.

**Comment by funderburkjim** [comment]
Here are 
* revised sample [basic display]()
  * The revision is a 'compress2' display variant -  currently, I like this best, and think it should be the
     default.
* sample [list display](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/list-0.1.html)
  * note that for dict=mw,  the artificial homophones are present, as well as links at homophones to 'recenter'
     the list
  * This bakes in the 'compress2' option

**Comment by gasyoun** [comment]
Please fix the first link, it's broken.

**Comment by funderburkjim** [comment]
@gasyoun link fixed for first basic display.

**Comment by funderburkjim** [comment]
There is now a a [sample index](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/index.html) page for these displays.

The latest (basic-0.3)  has autosuggest feature for the dictionary and citation fields.
For the citation fields, autosuggest should work for the various choices of 'input' - I've tried it with slp1, hk,
Devanagari.  It needs more testing.  
@gasyoun You provided me with some enhancements for IAST-slp1 conversion -  do you recall where that information is?

**Comment by gasyoun** [comment]
Great. I tested http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/basic-0.3.html in IAST mode. Actually tonight I saw it in a dream! It's well made.

When I choose a word in the list of suggestions I have to press Enter afterwards. I wonder how to make it without Enter, like in Google. Not sure if http://sourceforge.net/projects/searchpuppy/files/ has the needed Javascript element.

One smaller question. I wonder what should `??` in mahab?? mean. I guess it wants to say there is no such word. I wonder what should we do to make it clearer.

@funderburkjim enhancements for IAST-slp1 conversion - could not trace.
ç = ś
ṁ = ṃ
Github search fails.

**Comment by Shalu411** [comment]
Namaste
Thank you for this.
http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/basic-0.3.html
I tested it too. Its wonderful dream come true. I have been waiting for this since long. Congrats for the work. :) 
@gasyoun 
Actually ?? appear when the word does not exist in the database . I typed देव, all options/suggestions were fine. Then I put a visarga to it- it gave ?? and ended up "Nदt found". 
@funderburkjim 
So you can conclude that non-existent words appear with a ?? 
just a guess of mine.

**Comment by funderburkjim** [comment]
re `with a ?? '   In this version of autosuggest,  the suggestions are drawn just from the 'key1' (headword) spellings as they appear in the particular dictionary chosen.

For instance, if the dictionary is MW, then 'devaH' does NOT appear as the initial part in the spelling of any
headword; in this case,  you see what you typed followed by ?? ---  that's just the way I thought of representing that situation to the user -- maybe there is a better way - I'm open to suggestions (accidental pun!).

 However,  if the dictionary is SKD,  then 'devaH'  has (one) suggestion - since the SKD headword is spelled with visarga.

So, the above describes this first version of the suggestion program.  I think there is utility in having a version like this.

But there would also be utility in having a version of the suggestion program that would not require the user to know the differences in spelling conventions among the dictionaries.   The only step we have in this direction is in the [hwnorm1](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/hwnorm/hwnorm1.php) display.  Try entering 'deva' and 'devaH' there, and you get the same list of dictionaries ; in other words, this
display knows that MW spells it 'deva' and SKD spells it 'devaH'.

**Comment by funderburkjim** [comment]
@gasyoun - I noticed the 'extra enter' aspect also. search puppy does not use jquery-ui  (just jquery) so probably not a help.  From the jquery autocomplete api, it may be that a 'submission' can be generated 
from the 'close' and/or 'change' events -- not sure.

**Comment by gasyoun** [comment]
Let me quote my colleague Sergey (http://renuvate.livejournal.com/) from https://groups.google.com/forum/#!topic/nagari/fvfci96y8T8
PWG, article स्वर्
http://www.sanskrit-lexicon.uni-koeln.de/scans/PWGScan/2013/web/webtc/indexcaller.php

`स्वर᳠न्ति॒ घोषं॒ वित᳠तम्  Ṛv. 5, 54, 12.`

Devanagari is ok in old UI.

http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/basic-0.3.html

`स्वर᳠न्ति॒ घोष॒ं वित᳠तम्  Ṛv. 5, 54, 12. `

Wrong sequence of devanagari characters in new UI.

**Comment by funderburkjim** [comment]
@gasyoun   This problem occurs when displaying PWG headword 'svar' 'WITH ACCENTS'.
It relates to situation of displaying accents in configurations like:
```
<vowel><accent><visarga or anusvara>
```
These were encountered in PWG and discussed in Corrections [issue #19](https://github.com/sanskrit-lexicon/CORRECTIONS/issues/19).

As part of this earlier work, the transcoder file 'slp1_deva.xml' was tweaked (but just for PWG).
Now, this tweak is in the transcoder file used in these new displays.

I think this problem is now corrected for these new displays.  

Thanks to Sergei!

**Comment by gasyoun** [comment]
@funderburkjim thanks, so now it's covered everywhere.

**Comment by funderburkjim** [comment]
A couple of changes to the autocomplete function make it a bit more refined along the lines suggested above. This is represented
in 'basic-0.3a'  (see the [index](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/) for link).  Similarly, list-0.2 provides the autocomplete for a list display.

I still want to get the capital IAST functioning for these, but haven't found @gasyoun 's work yet.

It also ought to be possible to do an 'accordion' or 'tab' display extending the functionality of hwnorm1;
and it ought to be possible to have a 'PW-SCH' dual display mimicing the deprecated
http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/disp2/index.php.

**Comment by gasyoun** [comment]
Better and better. I wonder if the autosuggest can be Siddhanta as well and not default Mangal.

**Comment by funderburkjim** [comment]
The 'svar' problem has been solved.   Here's what was involved.

Formerly, the suggestion list was being retrieved by 
* retrieve  first (in lnum order)100 records whose 'key1' starts with  what was typed (e.g., svar), 
* remove duplicates and present the first 10.

Thus, even though 'svar' is a headword in the MW dictionary, there are headwords that begin with
'svar' but are before 'svar'.  E.g. svarasa has L=258107, svarAj has L=258119, etc. but svar has
L=259078.   So, formerly, these other words were preceding svar in the suggestion box.

I noticed a similar problem with 'parama'.

Now, the logic goes as follows:
* retrieve  first (in lnum order)100 records whose 'key1' starts with  what was typed (e.g., svar),  [Same as above]
* retrieve any records exactly matching what was typed.  (e.g. svar)
* merge the two lists
* sort in Sanskrit alphabetical order
* return the first 10 records.

So, in particular, since 'svar' is a headword in MW  ( or parama),  then it will be first in the suggestion list.

The parameters of jquery-ui autocomplete were tweaked by setting 'autoFocus: true,', so the
first one in the list is selected by default.  Also, the 'enter' key functions so that if you type 
'svar<enter>' then the suggestion closes and you get back the data for that headword.  However,
if you type, for example, 'lab<enter>' you get back data for 'laba'  (since 'lab' is not a headword.

**Comment by funderburkjim** [comment]
Regarding using Siddhanta font in the autocomplete box when the user has chosen Devanagari as
the input method.

This is probably doable via an adjustment to some 
css related to jquery.  Any idea what jquery-ui css determines the font for the autocomplete?

**Comment by gasyoun** [comment]
What if we add to `font-family: Trebuchet MS,Tahoma,Verdana,Arial,sans-serif;` inside `jquery-ui.css` the line `font-family: Trebuchet MS,Tahoma,Verdana,Arial,sans-serif,Siddhanta;`. I would go for `.ui-widget`.

**Comment by funderburkjim** [comment]
In http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/basic-0.3a.html,
I tried the suggestions, with these details added to the css for the page (which will override the jquery-ui.css in the case of .ui-widget class:
Based upon an element inspection (n Chrome) on a suggestion with Devanagari input, I think
the siddhanta font is being used for Devanagari.  
Note I also changed the 'key' to use the given font-family.
Finally, I used 'bold' for font-weight, since the non-bold seemed a bit 'spindly' to my eye.
```
#key {
 font-family: Trebuchet MS,Tahoma,Verdana,Arial,sans-serif,siddhanta_deva;
 font-size: 14pt; 
 font-weight: bold;
}
@font-face { 
 /*src: url(../fonts/siddhanta.ttf);*/
 src: url(../fonts/siddhanta.ttf); /* relative to this css file */
 font-family: siddhanta_deva;
}
.ui-widget {
 font-family: Trebuchet MS,Tahoma,Verdana,Arial,sans-serif,siddhanta_deva;
 font-weight: bold;
}

```

If this adjustment seems preferable, I can add it to the list-0.2 version also.

**Comment by gasyoun** [comment]
Wonderful, Jim. Thanks, Jim.

![dur](https://cloud.githubusercontent.com/assets/80761/9023494/77ca0cbe-38a6-11e5-883e-f6a3959ea790.png)

Siddhanta works. But there is a lot of free space above (more than needed) and not enough - bellow. I would make the input box even bigger. Otherwise some parts of Devanagari can be hardly seen. 
Second, smaller point is that as in the `दुर्जनत्व` or any other case, the text inside the article is still Mangal. So maybe make .body Siddhanta? I guess no, but where else it should be added I do not get it as well.

**Comment by funderburkjim** [comment]
The following change to style seems to allow the 'u' in 'durjana' to be visible in the `<input>` element:
```
style="height:2.0em"
```

**Comment by gasyoun** [comment]
Maybe, but I still can't see the full word, so I guess at least the height should be increased.

**Comment by funderburkjim** [comment]
This is probably a caching problem -  empty the browser cached and reload.  The citation box itself should look larger, etc.

**Comment by funderburkjim** [comment]
The lower section now also uses siddhanta font.

**Comment by funderburkjim** [comment]
Here is screen shot with changes:
![image](https://cloud.githubusercontent.com/assets/6393033/9393882/cac46454-4752-11e5-9752-a04617684c26.png)

**Comment by gasyoun** [comment]
Caching was not the issue, because I always empty the cache. I see siddhanta in the lower section, great. I would propose you use Old Standard for the non-Devanagari part and Clarendon for headwords in non-Devanagari mode (for MW and MW72 at least, anyway more authentic than Times New Roman), otherwise very well looking.

![durjana](https://cloud.githubusercontent.com/assets/80761/9395898/e2415a5a-4799-11e5-9403-af9afa918ba3.PNG)

**Comment by funderburkjim** [comment]
Regarding the citation.  Is this a browser issue.  I am using Chrome, and it looks fine per my screenshot.  Yet, your screen shot shows a problem with the 'u' in durjana. Which browser are you using?

**Comment by funderburkjim** [comment]
I downloaded Firefox, and basic-0.3c looks fine there also:
![image](https://cloud.githubusercontent.com/assets/6393033/9398674/9dab51ce-4777-11e5-86e4-9d3189af1a5c.png)

**Comment by gasyoun** [comment]
I use Chrome on Win7.

**Comment by funderburkjim** [comment]
Another sample display (for MW) is discussed [here](https://github.com/sanskrit-lexicon/MWS/issues/26).

**Comment by gasyoun** [comment]
@funderburkjim I do not see a link to http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/basic-0.3b.html from nowhere on the real website. Can you add one, if so, please?

**Comment by funderburkjim** [comment]
The display does seem mature enough to make available to everyone.  

Add link in 'Miscellany'  or make a new section (perhaps 'Experimental') ?

**Comment by funderburkjim** [comment]
I would also add the list display: http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/list-0.2.html

**Comment by gasyoun** [comment]
> The display does seem mature enough to make available to everyone.

Indeed.

> Add link in 'Miscellany' or make a new section (perhaps 'Experimental') ?

I would make it big and bold. new section no one will notice. Maybe add in the header or in each line as the last (or first) link?

> I would also add the list display: http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/list-0.2.html

Yes, yes, yes.

![list](https://cloud.githubusercontent.com/assets/80761/20589455/a7406a22-b22d-11e6-88ef-726967c7d609.PNG)

I would use the Siddhanta font for the devanagari on the left, no?

**Comment by drdhaval2785** [comment]
I back Siddhanta font. Beautiful ligatures.

**Comment by funderburkjim** [comment]
I think I've changed [list-0.2](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/list-0.2.html) so it uses siddhanta font for devanagari.

The 'sn'    ligature in 'rAsnA'  seems harder to distinguish in Siddhanta; it looks close to 'rasrA'.
But if others prefer Siddhanta, I can leave it as Siddhanta.
'rAsnA' 
![image](https://cloud.githubusercontent.com/assets/6393033/20652371/dde299de-b4c5-11e6-96bf-e5763bc80402.png)

**Comment by funderburkjim** [comment]
@drdhaval2785   One of the advantages of these apidev displays is that the user can enter words in
Devanagari.  

When using the 'Sanskrit Devanagari Inscript Keyboard' under Windows,  how does one enter
 Devanagari for the slp1 spellings 'tF'  or 'kxp'   ?    (I can't find 'F'  or 'x' in Inscript keyboard).

**Comment by drdhaval2785** [comment]
In pramukhIME which I use,
ॠ is by RI
ऌ is by Li~

These two infrequent items are rather idiosyncratically decided by
developers.

**Comment by drdhaval2785** [comment]
Siddhanta looks beautiful.

**Comment by drdhaval2785** [comment]
I can see a small knob at the end of 'n' of rAsnA which is absent in 'r'.

**Comment by funderburkjim** [comment]
> pramukhIME  -   Thanks for the link.  I've downloaded and it seems to work fine, in particular for
the two cases where INSCRIPT seems lacking.

Maybe the INSCRIPT was mainly developed for Hindi, which must not use those infrequent items.

It ought to be possible to make such a keyboard for Devanagari, where one would use the SLP1 codes.
But this is too hard a problem to tackle.

**Comment by funderburkjim** [comment]
> small knob.  
Right, I saw that too, and the key word was *small*.  I'll leave Siddhanta in those apidev displays.

**Comment by funderburkjim** [comment]
Should this issue be closed?

**Comment by funderburkjim** [comment]
Do I need to add a 'corrections' link to these before installing on home page?

If so, where should a corrections button be placed?

**Comment by gasyoun** [comment]
> I can see a small knob at the end of 'n' of rAsnA which is absent in 'r'.

Indeed.

> Do I need to add a 'corrections' link to these before installing on home page?

Do not think so, but will not hurt.

> If so, where should a corrections button be placed?

As usual, top right.

**Comment by funderburkjim** [comment]
I've added a link to the list-0.2.html display to the sanskrit-lexicon home page.  

It is quite dull, aesthetically speaking.

**Comment by funderburkjim** [comment]
One interesting feature of this display is that it works even if the html file is downloaded to a local computer.  The reason is that all the content is governed by calls to various api scripts at Cologne.

It would be possible for someone with html/js knowledge to develop other displays.

For instance, one user long ago was interested in having a display where a local word list is in the left pane - this would be useful for Sanskrit classes.  Where the teacher would set up for each lesson the special vocabulary for that lesson.  

Another possibility would be displays that automatically referenced multiple dictionaries (e.g., PW and PWG, VCP and SKD, WIL YAT and SHS, etc.).

If someone has interest in developing such special purpose displays, I can develop documentation of the existing API calls.

We could even develop a repository of such api-based displays, and let interested users contribute.

**Comment by gasyoun** [comment]
> It is quite a modest addition, aesthetically speaking.

Well done, Jim.

> For instance, one user long ago was interested in having a display where a local word list is in the left pane - this would be useful for Sanskrit classes. Where the teacher would set up for each lesson the special vocabulary for that lesson.

So a .txt file for batch upload to be shown on the left - let him himself code one, because how do we know if the word in the orthography interested matches the one in dictionary he wants the most?

> Another possibility would be displays that automatically referenced multiple dictionaries (e.g., PW and PWG, VCP and SKD, WIL YAT and SHS, etc.).

All at once. Where is the source code for editing?

>  I can develop documentation of the existing API calls.

Just today I tried to convert to of my newest Sanskrit students for coding. 1 of them seems strong enough to tackle API, so I would say - le'ts give it a go.

> let interested users contribute

And hear the sound of silence in return :sake:

**Comment by drdhaval2785** [comment]
@gasyoun 

What is left, what is done?

**Comment by drdhaval2785** [comment]
APIs worked out. Frontend at #355 seem worth emulating. Closing this issue.
