### ISSUE TITLE
Problem with scanned image display under Linux

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#73]
Long-time user Lino Bercelli recently reported the following problem:
'I have some problems with scanned pages, by clicking on the link, i can get only a void page with merely the navigation-buttons in a corner. That with the most  new versions (in effect only wilson is working well) The oldest and deprecated versions seem ok. The same problem i have with all the new dictionaries (i.e. apte, mci, etc.) both on the web, and with the downloaded versions. Is it only a my problem? I'm using firefox under linux mint 17.
Thanks in advance, e cordialissimi saluti, lino '

At this point I have no idea of what might be going on.

**Comment by gasyoun** [comment]
Screenshot welcome.

**Comment by funderburkjim** [comment]
Lino responded to me that he solved the problem, which involved 'bad settings in the PDF-viewer'.
