### ISSUE TITLE
Improve Dictionary titles in the Cologne displays

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/Cologne#74]
A user (Frank Ziesing) made the following comment:
```
although the display of the dictionary has evolved fantastically, there is one thing I'd like to mention:

While in some Dictionaries the headline is complete, i.e. Monier William Dictionay (list display 
http://www.sanskrit-lexicon.uni-koeln.de/monier/webtc5/index.php) reads:
(Cologne Logo) Monier Williams Sanskrit-English Dictionary (Brown University Logo)

the headline of the many others is incomplete or unreadable, i.e.:
(list display) Böhtlingk Sanskrit-Wörterbuch in kürzerer Fassung
reads

(Cologne Logo)_Sanskrit-Wörterbuch in kürzerer

That's kind of strange. Wouldn't it be possible to have the complete title

(Cologne Logo) Böhtlingk Sanskrit-Wörterbuch in kürzerer Fassung

in a smaller font (and without the _ in front of the title)?

The problematic dictionaries are:

Same problem with Yates Sanskrit-English Dictionary, Edgerton Buddhist Hybrid Sanskrit Dictionary, 
Borooah English-Sanskrit Dictionary, Apte Student's English-Sanskrit Dictionary, Cappeller Sanskrit 
Wörterbuch, Schmidt Nachträge zum Sanskrit-Wörterbuch, Grassman Wörterbuch zum Rig Veda,    
  Böhtlingk and Roth Grosses Petersburger Wörterbuch, Bopp Glossarium Sanscritum, The Vedic 
Index of Names and Subjects, The Purana Index (just "The" missing), Aufrecht's Catalogus 
Catalogorum, Meulenbeld's Sanskrit Names of Plants, Personal and Geographical Names in the 
Gupta Inscriptions.
```

**Comment by funderburkjim** [comment]
This seems like a good suggestion.  I'll make corrections to the Titles, I think most (perhaps all) of the detailed proposed titles are good.  If anyone has refinements, now would be a good time to mention.

I'll do this tedious work a bit at a time, and use this issue to log the progress.

**Comment by gasyoun** [comment]
That's similar to what I wrote about the bibliographical data, which I've compiled in 1 file. If I want to quote - I can't find the data on the web, I have to download and extract it from an .XML file - does not makes much sense, because how do I know where to look after?

**Comment by funderburkjim** [comment]
First, regarding PW.  

For the list display, I've kept the old version accessible at url [index_prev](http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc1/index_prev.php), 

The current url [index](http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc1/index.php)  contains the changes suggested.

*  Frank mentions that 'Fassung' is missing in his display.  I'm unsure of the reason for this, since
 'Fassung' shows in `index_prev'.  It's possible that his browser is using a cached version which 
didn't display 'Fassung', or there may be some other reason.

* That spurious `_`  (underscore) character in the display is quite puzzling to me, and may indicate
  some error (or obscure feature) of the way browsers render html.  Both Chrome and IE show the 
  same odd rendering, so maybe there is some   This can be observed in a very small extract 
  html file:
```
<html>
<head>
 <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=utf-8">
 <title> Test of PW link</title>
</head>
<body>
<div id="dictid">
 <a href="http://www.sanskrit-lexicon.uni-koeln.de/">
 <img id="unilogo" src="http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/images/cologne_univ_seal.gif"
  width="60" height="60" title="Cologne Sanskrit-Lexicon">
 </a>
 <span>Sanskrit-Wörterbuch in kürzerer Fassung</span>
</div>
</body>
</html>
```

* Adding some positioning style information to the span makes the underscore go away:
```
 <span style="position:absolute; left:75px">Sanskrit-Wörterbuch in kürzerer Fassung</span>
```

The need for this is curious.  I hope some html expert can explain what is going on here.

**Comment by funderburkjim** [comment]
@gasyoun   If you open an issue related to your comment, I'll try to address it.

**Comment by gasyoun** [comment]
@funderburkjim underscore after logo is because the `space` after the logo is a clickable link. I would make `title="Cologne Sanskrit-Lexicon"></a>` a single line.

**Comment by funderburkjim** [comment]
@gasyoun / @Shalu411   -  Yep, The titles question was there.  Looks like I dropped the ball.  Am getting to it now. 
@gasyoun   Your solution to the under works just fine. Thanks for the tip!

**Comment by funderburkjim** [comment]
@gasyoun  Regarding that `<a>`, one other change was needed,  an addition of a style attribute to change the background-color to agree with the background color on which the link and image reside.
Otherwise,when the mouse hovers over the logo image, a rectangle shows up in another color.  
You can see this behavior in any of the displays not yet changed.

**Comment by funderburkjim** [comment]
One other change is to remove the `(2014 edition)` text when it occurs.  This phrase seems ambiguous and not useful.

**Comment by funderburkjim** [comment]
I've made the changes to all the PW displays.  @gasyoun  Would you look at each, and see if I've missed anything?   When all look ok, I'll make similar changes to the titles for the other (35- ugh!) dictionaries.

**Comment by gasyoun** [comment]
@funderburkjim `Böhtlingk Sanskrit-Wörterbuch in kürzerer Fassung` is not enough. You can't quote it in a scientific paper this way. Add data from https://github.com/sanskrit-lexicon/Cologne/blob/master/Cologne%20Digital%20Sanskrit%20Dictionaries%20Harvard%20Bibliography.txt and it will change everything. It will be reusable in scientific quotations.
In http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc2/index.php the title should be unbolded or the Advanced text. Similar with http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/download.html - make Download italic in the heading of different style, otherwise it looks as one, but should not be mixed with the title. http://www.sanskrit-lexicon.uni-koeln.de/pwindex.html Kleines Petersburger Woerterbuch (Boehtlingk) Sanskrit-German Dictionary should remain different?

**Comment by funderburkjim** [comment]
@gasyoun The bibliography document you prepared is good.  

I presume you have provided editions consistent with those used in Cologne digitisations (Question). 

The 'worldcat' links are interesting, although I don't know how to think of worldcat.

Perhaps the bibliography document on Github (or a copy of it on Cologne web site) should be
referenced on the Sanskrit-lexicon [home page](sanskrit-lexicon.uni-koeln.de), so that users
will know to use the information in that document when they need to provide a reference in a
scientific paper.

Regarding the titles (as they appear on the 3rd line of each entry in the bibliography documents).
The main problem I see in using these as titles on the displays is the string length.  For instance,
`Böhtlingk Sanskrit-Wörterbuch in kürzerer Fassung` is 50 characters, and this is probably close
to the maximum that will 'fit' in the title positions of each display.

**Comment by gasyoun** [comment]
As per `editions consistent with those used in Cologne digitisations` - we can presume only, but never can't be sure. Because title pages and preface pages are often missing or do not contain full data, as Indian editions.
worldcat is the default place for English based book bibliographical data.
Just referencing would not do. Copypasting it somehwere is a better idea, at least the relevant chunks.
50 characters is not the maximum, 75 is, so no worry.

**Comment by funderburkjim** [comment]
There is a working html document, [Cologne Titles01](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/misc/webtitles/titles/titlestudy1.html).

This coordinates various title candidates for the dictionaries.

This data may help in two decisions:

*  What title should appear on the individual displays (basic, list, downloads, etc) ?
*  How should the Bibliographic title be used?

**Comment by gasyoun** [comment]
1) Theodor Goldstücker,A Dictionary, Sanskrit and English - not having a space after a comma is bad style. I would make it Theodor Goldstücker / A Dictionary, Sanskrit and English or Theodor Goldstücker|A Dictionary, Sanskrit and English, but not with a comma, because commas happen in names of dictionaries as well.
2) None,Mehendale's Mahabharata Cultural Index - oh this None :) Why not name of main editor Mehendale?

**Comment by funderburkjim** [comment]
[template_dict_pp.txt](https://gist.github.com/funderburkjim/6e40c86ff83791519def) has title data for proposed rationalization of titles in the displays.  

This [newtitles](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/misc/webtitles/newdir/index_all.html) web page has links, for each dictionary (except STC) to:

* index.php The 'list of available displays' for the dictionary
* webtc/indexcaller.php  The 'basic' display page for the dictionary.
* webtc1/index.php  (NOT DONE) The 'list' display
* webtc2/index.php  (NOT DONE) The 'advanced search' display
* mobile1/index.php (NOT DONE) The 'mobile friendly' display
* webtc/download.html (NOT DONE) The 'downloads' page for the dictionary

Notes:

1. These are not yet 'installed'.  Once the details are ironed out regarding the title formatting,
    I propose to install these as replacements for the current pages (the ones linked to on the
    Sanskrit-Lexicon [home page](http://www.sanskrit-lexicon.uni-koeln.de/)).
2. I propose to use the same title on each of these displays.  This is the 'tit2' field shown in the
    template_dict_pp.txt file.
3. The 'tit1' field (currently, same as dictionary code) is used in the 'browser tab title' for a display.
4. The 'tit2' field is used for the title that appears next to the Cologne Logo.
     Usually, this is the same as the title that appears on the home page. But, I added the
      publication date to distinguish the two versions of Monier-Williams (MW, MW72) and of
      Apte (AP, AP90).
5. Note the enhancements to the 'index.php' file.  In addition to links to the displays and downloads,
    there is a 'related material' section, with four items:
   * Link to the 'front matter' section of the documentation.  This usually has scanned images of the
     title and preface pages of the scanned edition upon which the digitizations are based
   * License of Digital Edition  -  this is an XML document, that provides both the License and also
      title and edition information.  This is based on a TEI model developed by Peter; the content
      was developed jointly by Scharf, Malten and Funderburk.
   * WorldCat Reference.  This was developed by Gasuns. (Not currently available for PD and AP)
   * Bibliographic Entry:  This was developed by Gasuns. (Not currently available for PD and AP)
     Note: The bibliographic entry for Sabda-Sagara (SHS) may need revision.

7. STC is missing, because some of the current linked displays are in French, developed by
    Odile Coujolle. I intend to fill these in manually, at some later date.
7.  The two display forms thus far done are generated by a program which uses templates, which
    are 'filled in' using data from 'template_dict' mentioned above.
8. The webtc display is constructed from three templates, which take into account the variations in
    the basic display  (e.g., dictionaries which have English headwords, like MWE), and dictionaries
    which have Devanagari accents (like PWG)).

I hope that those of you who are interested in this will carefully review the details.  I'd like to get
the title details (especially 'tit2') resolved soon, so that I can complete the generating the
(NOT DONE) display pages,  and then install all the pages.

**Comment by gasyoun** [comment]
If (2014 edition) data remains somewhere, it might help. Now I can only see the last revision of a dictionary in the download section. But more than that - the major editions are important to know and distuingish. Many hundreds of people still use MW 2008 edition, because are unaware of any other.
Links the front matters are great and I was missing them. What's wrong with SHS entry and why you think we should ignore PD, AP entries? Under copyright does not means we can't quote them.
@Shalu411 how do you like the proposed titles?

**Comment by funderburkjim** [comment]
@gasyoun   

1. Regarding the '2014 edition' question.  I could treat MW as a special case, and have
   '2014 digital edition' there, to distinguish it from 2008 editions.  However, the absence of an
   edition could be thought of as meaning  'the latest digital edition', sort of like with browsers.  Because
   this latest edition is not static, since it reflects continuing improvements.
   Probably, this question is only relevant to MW and, perhaps, a small number of others.
   I'm still inclined to leave it off, but you might be able to convince me otherwise if you feel strongly
   about it.

2. Regarding SHS -   the words 'Sabda Sagara' don't appear in the 'bibliographic entry' -- that's mainly why it looked wrong to me.

3. Regarding PD, AP -  If you can fill in the 'worldcat' and 'bibliographic entry' for these, I agree it
 is appropriate to include them.   I don't want to ignore them, I just don't know how to fill in the worldcat and biblio. entry for them.

Thanks for looking at the examples. :+1:

**Comment by gasyoun** [comment]
1. I see tens of people using 2008 edition. And not aware of any other. I think there is nothing in 2008 edition, that is missing in 2014, or am I wrong?
2. Oh, must be my mistake.
3. I'll do that myself.

**Comment by funderburkjim** [comment]
Re 'anything missing in 2008 MW'?   The display is based on the same underlying data.
  I think the 2008 display fails or doesn't display properly on a few records, such as those where Arabic utf-8 data has been inserted.

**Comment by gasyoun** [comment]
That's not crucial. If there are no advanced things, I would redirect it to 2014 fully.

**Comment by funderburkjim** [comment]
The 2008 displays are clearly marked as deprecated.  That seems enough for now; I'm reluctant to make the old displays completely inaccessible; though I'm not exactly sure why I have this reluctance.

**Comment by funderburkjim** [comment]
There are now Sample pages for all the displays. These can be viewed [here](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/misc/webtitles/newdir/index_all.html).  

I'm about ready to install these.

@gasyoun Now would be good time for you to give me the revisions for SHS, PD, AP that were
mentioned above.

**Comment by gasyoun** [comment]
clearly marked as deprecated for Jim, might be, but not for the rest of the world. I see a lot of people still using it and being unaware there is an update.

**Comment by funderburkjim** [comment]
Clearly marked not only for Jim, but for the rest of the world, too.  Look at the links:
* [2008, basic](http://www.sanskrit-lexicon.uni-koeln.de/monier/indexcaller.php)
* [2008, advanced](http://www.sanskrit-lexicon.uni-koeln.de/mwquery/index.html)
![image](https://cloud.githubusercontent.com/assets/6393033/9692542/a8cad9de-5317-11e5-826c-e598c7b942e1.png)
Surely, this display is 'clearly marked' as deprecated!

**Comment by drdhaval2785** [comment]
Can we do something like this?
All links to previous versions of a dictionary are redirected to the latest
version.
the latest version has links to the older ones, which are not redirected..

**Comment by gasyoun** [comment]
Linking to homepage is bad practise. Link should go to the dictionary.
The word deprecated might be a bit above plain English. Maybe OLD in bold?
I would go Dhaval's way, what do you think, Jim?

**Comment by funderburkjim** [comment]
Regarding deprecated editions -  There is certainly more than one way to skin a cat.

I think the current way is adequate, and am not inclined to change it much now.

I think the home page should be the one 'source of truth'  for all editions; links to the deprecated editions are there, and clearly marked. I think the link from
deprecated pages should remain targeted at the Home Page, since I want people to navigate 
through the home page.  

I can add the word 'OLD" in the 'deprecation notice' of the deprecated displays. 
These modest changes are all I'll make to the deprecated editions, for now at least.

**Comment by gasyoun** [comment]
This is a potential point of confusion - I fully agree. Let's go for OLD.

**Comment by funderburkjim** [comment]
I've installed the new titles for 4 dictionaries:  ACC, MW, PWG, MWE

Will wait a week or so to see if any problems encountered.  If all looks ok, will then install the rest of
the display pages with the new titles.

**Comment by gasyoun** [comment]
So be it.

**Comment by funderburkjim** [comment]
@gasyoun  Just a reminder --- If you can provide corrections to the bibliographic/worldcat data for PD, AP, and SHS , now would be the best time to do so,.

**Comment by gasyoun** [comment]
@funderburkjim not forgot, just not sure it's perfect.

10) http://www.sanskrit-lexicon.uni-koeln.de/scans/SHSScan/2014/web/
BHAṬṬACARYA, J. V. (1900). Shabda-Sagara, or a comprehensive Sanskrit-English lexicon: chiefly based on Professor Horace Hayman Wilson's Sanskrit-English Dictionary and compiled from various recent authorities for the use of schools and colleges. Calcutta, Calcutta Press.

https://www.worldcat.org/title/shabda-sagara-or-a-comprehensive-sanskrit-english-lexicon-chiefly-based-on-professor-horace-hayman-wilsons-sanskrit-english-dictionary-and-compiled-from-various-recent-authorities-for-the-use-of-schools-and-colleges-by-pandit-kulapati-jibananda-vidyasagara-1st-edition/oclc/457574734



Ghatage, A. M., Joshi, S. D., Ranade, H. G., Bhatta, V. P., Gandhe, V. S. (1976–<2009>). An Encyclopaedic Dictionary of Sanskrit on Historical Principles. – Poona: Deccan College Post Graduate and Research Institute.

https://www.worldcat.org/title/encyclopaedic-dictionary-of-sanskrit-on-historical-principles/oclc/3932453&referer=brief_results



V. S. Apte’s The practical Sanskrit-English dictionary (1957-<1979>) / ed. in chief P. K. Gode and C. G. Karve; K. V. Abhyankar. – Poona: Prasad Prakashan.

https://www.worldcat.org/title/prin-vs-aptes-the-practical-sanskrit-english-dictionary/oclc/716419540&referer=brief_results

**Comment by funderburkjim** [comment]
@gasyoun   Thank you.  This material is now incorporated into the [revised title pages](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/misc/webtitles/newdir/index_all.html), 
which will be installed next week

**Comment by gasyoun** [comment]
So be it.

**Comment by funderburkjim** [comment]
New displays have been installed for all dictionaries.  
Note to self:  awork/misc/webtitles/

**Comment by gasyoun** [comment]
Enough is enough.
