### ISSUE TITLE
"Cologne Scan" PDF Title

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/COLOGNE#77]
It might be confusing if I open different scan pages like http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/webtc/servepdf.php?page=1041 or http://www.sanskrit-lexicon.uni-koeln.de/scans/SKDScan/2013/web/webtc/servepdf.php?page=4-554 but they have an identical title.

![cologne-scan](https://cloud.githubusercontent.com/assets/80761/10293623/3f170c1e-6bbe-11e5-87da-6210c7fbdd28.PNG)

Would adding the abbreviation before it would be a good idea or no need, @funderburkjim, @zaaf2 ? I open many bookmarks at once when in errata mode. The other issue is I thinkg how informative is `AP Basic` or `PWG Basic`.

**Comment by funderburkjim** [comment]
I'm glad you are using the new displays.  

Before I comment on your question, let me ask a clarification question.

Are you saying that 'MW Basic' etc. are good titles, but 'Cologne Scan' are bad (non-informative) titles?

**Comment by gasyoun** [comment]
Are you saying that 'MW Basic' etc. are good titles, but 'Cologne Scan' are bad (non-informative) titles? - yes, I do. Not good, but better. I'm thinking maybe add different favicons as well? I could make them. Different colors or letters on them, instead of the default blue one.

**Comment by drdhaval2785** [comment]
Favicons is a good idea.

**Comment by gasyoun** [comment]
38 colors would not make sense. Letters or stripes in addition?

**Comment by funderburkjim** [comment]
re favicons:  @gasyoun   Go for it!   

re better tab-titles for scan:  I'll look into what's involved.

**Comment by gasyoun** [comment]
To go for it we need to invent some strategy. I proposed a few above - need your comments.

**Comment by funderburkjim** [comment]
I thought you were suggesting a general favicon relevant to the Sanskrit-Lexicon (instead of the blue square).
However, your previous comment suggests my impression must be mistaken. 

I don't know what 'Add a number for each, 01, 02, 03 ... 37, 38'  intends, so cannot comment.  

Maybe you can draw a sketch to illustrate how you are imagining favicons might be used.

**Comment by gasyoun** [comment]
general favicon relevant to the Sanskrit-Lexicon - right, and be it a unique ID attached to each dictionary, like MW is 37 or Apte 09. Because it would fit and look similar to the google calendar sample above.

**Comment by funderburkjim** [comment]
I think it would be better to use 'MW' rather than '37', 

For instance, I find the titles 'AP Basic'  for the display to be good (short, accurate, not too cryptic).

For the scanned images, what about 'AP Scan'  or perhaps 'AP Scan 831'  (for page 831) ?

**Comment by gasyoun** [comment]
MW might fit, SKD - never. So new issues arrive.
AP Scan 831 makes more sense than AP Scan, but maybe AP Scan 1955?

**Comment by gasyoun** [comment]
@drdhaval2785 what do you think?

**Comment by gasyoun** [comment]
@drdhaval2785 do you think at all about it?

**Comment by drdhaval2785** [comment]
I do not think about it at all.

**Comment by drdhaval2785** [comment]
Closable?

**Comment by funderburkjim** [comment]
Recent work  (based on Marcis suggestion somewhere)  has resulted in more descriptive browser tab titles.

Let's close this particular issue.
