### ISSUE TITLE
Null characters contained in the file

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/Cologne#78]
http://www.sanskrit-lexicon.uni-koeln.de/scans/PWGScan/2013/web/webtc/download.html
@funderburkjim pwg.txt opened without any issues
pwg_orig_utf8_slp1.txt opens only with error popup and get broken afterwards, as the encoding is not treated as the one declared on Windows. Never had such an issue with Cologne file before. Everything fine with XML files as well. Low priority.

![00h](https://cloud.githubusercontent.com/assets/80761/10590885/e90b85f8-76bb-11e5-8e4d-8d9ccdd579b3.PNG)

**Comment by funderburkjim** [comment]
I just downloaded pwgtxt.zip, and opened pwg_orig_utf8_slp1.txt in Notepad++ without problem.

Also, opened in Emacs, and (after reopening in UTF-8 encoding), it looked fine.

So, I'm not sure what to make of your error.
What Editor are you opening in?

**Comment by gasyoun** [comment]
EmEditor in Windows. Position I'm unaware of.

**Comment by funderburkjim** [comment]
Downloaded EmEditor Trial version, and confirm your observation.

The 'search/jump' option (after continuing with utf-8 encoded loading). provided 
that there are TWO 'BAD LINES' line # 1060, and line # 1126.

In the processing of pwg,  these two lines are part of the pwg_header.txt file, and thus do
not play a further role in  construction of pwg.txt.

However, they should be removed, so that the 'pwg_orig_utf8.txt' and 'pwg_orig_utf8_slp1.txt' files open properly.   

I'll mark this issue to be done.

Thanks for mentioning it.

**Comment by funderburkjim** [comment]
Did you purchase the standard version of EmEditor, or the Professional version?  

Do you find EmEditor superior to Notepad++ ?

**Comment by gasyoun** [comment]
EmEditor has lots of converters for Devanagari needs I use on daily basis. That is the only reason. I've got Pro, but no need for you, I guess. It's just http://www.svayambhava.org/ Siddhanta's font author used it and I took the practice from him. Because of the JS converter library.

**Comment by gasyoun** [comment]
@funderburkjim, done?

**Comment by funderburkjim** [comment]
Nope, haven't done this yet.

**Comment by funderburkjim** [comment]
The two garbagey lines in pwg_orig_utf8_slp1.txt, pwg_orig_utf8.txt, and pwgheader.txt have now been replaced with blank lines.

This should solve the problem.  You can download pwgtxt.zip from http://www.sanskrit-lexicon.uni-koeln.de/scans/PWGScan/2013/web/webtc/download.html  to get these files.
You might try opening in EmEditor again and confirming.

Then you can close issue if all is well.

**Comment by gasyoun** [comment]
`%***This_File_is_E:\SANSKRIT\BOEHTLIN\PWG.ALL,_Last_update_24.06.09` opened well, thanks.
