### ISSUE TITLE
Smartphone compatibility

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/Cologne#79]
@funderburkjim,

We have not yet spent time on mobile friendliness of the dictionaries discussion.

When i tried to open [this link]()

**Comment by drdhaval2785** [comment]
http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=MW&key=avipraRaSa

I see the error that plugin is not supported.

**Comment by drdhaval2785** [comment]
The issue is there in samsung internet explorer as well as chrome

**Comment by gasyoun** [comment]
No PDF plugin?

**Comment by funderburkjim** [comment]
I myself do not have a smartphone.   The 'mobile-friendly' editions linked to from Cologne sanskrit-lexicon home page are essentially the same as the basic display,  but with the addition that they were
adapted to use the [jquery mobile](https://jquerymobile.com/) framework.

**Comment by gasyoun** [comment]
Neither do I have one. The jQuery mobile framework does not seem to be actually mobile. So be it.

**Comment by funderburkjim** [comment]
Are there other issues besides the PDF viewing?

**Comment by funderburkjim** [comment]
Here is a note from Gerard, (5/14/2014)  that is also relevant to mobile editions.
```
This is to announce the release of the Golden Heritage dictionary.
I gives under a standard format my dictionary with grammatical hyperlinks, for all platforms.
I include a version of MW (evolved from Jim's) under the same format, also with declension links. 
All comments welcome, as usual.
```

I haven't followed up on this, since I don't use mobile phone.  

For someone knowledgeable about mobile app development, attending to the development of such for the dictionaries sounds like a good, substantive project.

**Comment by drdhaval2785** [comment]
After the stardict-dictionary-updater app which delivers cologne dictionaries as stardict dictionaries, necessity for creating a stand alone app is over. Stardict is really fast and compact.

**Comment by gasyoun** [comment]
> Stardict is really fast and compact.

That should be enough. Is there a need for M display? Or M is M, app is app and no need it it, as we have Stardict?

**Comment by drdhaval2785** [comment]
Mobile display should be there for people who prefer online viewing and feeling.

Stardict for people who prefer offline access.

App would be superfluous, if we give properly formatted text data in stardict.
