### ISSUE TITLE
Make L numbers unchangeable

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/Cologne#80]
From a flying discussion somewhere, I am given to understand that L numbers are generated automatically by some program.
We are treating it as an anchor for our references to that entry in future. See https://github.com/sanskrit-lexicon/CORRECTIONS/issues/168.

But this means that we have to fix the L numbers as it existed in one point of time.
Let us say 31 Nov 2015.

Whatever entry addition / deletions are done, maybe we should have a separate series for such addenda.
e.g. In case alternate headwords get headword status - Let us number them 200001, 200002 etc..

So that they don't impinge and alter our earlier L numbers.

@funderburkjim may like to explain possibility or otherwise of it.
@gasyoun what do you feel about the requirement ?

**Comment by gasyoun** [comment]
@drdhaval2785  I fully agree and support. If alternate headwords come out - give them 200001, 200002 etc. If new headwords form addenda come - let it be even 300001, 300002 etc. Do not see why it should be an issue.

**Comment by funderburkjim** [comment]
There are two questions, relating to L-numbers (the folllowing comments don't pertain to the 1899 version of MW, the one whose dictionary code is 'MW').

**Question 1**:  How are the L-numbers currently constructed?   Answer. By the make_xml.py program.
  This program assigns an L-number to a record of x.xml.  The number assigned is the sequence
  number of the line in the xhw2.txt file (which associates headwords with ranges of lines in x.txt).

  So, theoretically, the L-number can change. How?  Only if there is an insertion of an existing headword or a deletion of an existing headword.  Currently, this only occurs almost never.

**Question 2**.  When alternate headwords are implemented for a dictionary, how can these
alternate headwords be assigned L-numbers without clobbering the existing L-numbers?  
* One way to do this would be to assign L-numbers 'at the end', by starting the numbering at
  some large number , such as two-hundred-thousand and 1.
* Another way would be to assign decimal numbers between two existing L-numbers.
  For instance, if X is a headword with L=1234, and if we discover alternate spellings of this
  as Y and Z, then we could assign Y an L-number of 1234.1 and Z an L-number of 1234.2.
  Or, if there 10 or more alternates, we could assign them L-numbers of 1234.01, 1234.02, etc.
  Currently, a limitation of the definition of the x.sqlite definition allows only 2 decimal places.

The case of MW provides some experience.
In the first phase of integrating the supplement of MW into the body of the digitization, the first method was used.
Then, in the second phase of integrating the supplement, the second method was used; so, the
supplement words appear 'where they belong' in the body.
 
In the case of separating out the 'alternate headwords' in MW, the second method was used;
and furthermore, when an alternate headword was separated out, it was done by copying the
'base' headword into a new MW record, which was essentially identical to the base record, but with a new key1 and key2, and of course a new L-number squeezed in.  Also, there is generally information in each alternate indicating the other variants.

**Comment by gasyoun** [comment]
If both are alive at MW that means both are acceptable. 2nd has several advantages.

**Comment by funderburkjim** [comment]
Clarification re MW:  In the current MW, only the second method is present.   The first method existed in prior versions of MW, but does not form part of current MW.

**Comment by gasyoun** [comment]
Understood, thanks. For MW the next thing would be to add the f. stems as ghost-words - to make search universal. That would many thousands of additions (I can say that based on my https://github.com/sanskrit-lexicon/CORRECTIONS/issues/170 work).

**Comment by drdhaval2785** [comment]
I feel that after we started to use 1256.1 etc for Lnums, lnums have now become static. Time to close this @funderburkjim? Or am I missing something?
