### ISSUE TITLE
samaasa splitting

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#82]
As a bye product of [samasa splitting](https://github.com/drdhaval2785/samasasplitter) exercise -

I have culled out entries which are potential compound words from sanhw2.txt - 
https://github.com/drdhaval2785/samasasplitter/blob/master/compoundstudy/compoundhw.txt

Logic -
1. The word can be made up by joining two or more headwords of 'MD' dictionary (chosen because of its not too extensive coverage)
2. The components are all having length > 3 (To weed out false positives because of verbs / suffix etc entries).

Stats -
86402/434833 headwords qualify these tests, and are mostly compound words.

Future -
1. To display compound splits as an add - on in dictionary display.
2. If found fit, adding this info in dictionary XML files also as an additional `<compound></compound>` tag.

What are your takes @gasyoun and @funderburkjim ?

**Comment by gasyoun** [comment]
@drdhaval2785 we should use MW compound split data as base. It already has the `-` where they belong.

**Comment by drdhaval2785** [comment]
Don't reinvent the wheel of upasargas.
I have noted all from upasargArthacandrikA at https://docs.google.com/document/d/1s1kLCCz-jvLZdj5jwZ7hNMA3dBSP1GUFKjVSBL4gv9Y/edit#heading=h.mcp9jnahrxt7.

I will explore MW key2 when Jim provides sank1.txt and sank2.txt

**Comment by funderburkjim** [comment]
@drdhaval2785   I did some work on MW several years ago that pertains to samAsa structure of nominal headwords.  The approach taken was slightly different than I suspect your approach to be.

I would like to revisit this work and  bring it to a useable state.  

Once this is done, it would be excellent to compare the two approaches.   

Will keep you apprised.

**Comment by gasyoun** [comment]
@funderburkjim great to hear. Eagerly waiting.

**Comment by drdhaval2785** [comment]
@gasyoun and @funderburkjim 
Can I have the splits in MW as a txt file or something like that ?

**Comment by gasyoun** [comment]
@drdhaval2785 you've got it now yourself, did not you? Please let me know if help still wanted.

**Comment by gasyoun** [comment]
https://www.academia.edu/29519124/Using_Recurrent_Neural_Networks_for_joint_compound_splitting_and_Sandhi_resolution_in_Sanskrit is the most advanced solution I'm aware of. We need Oliver's code open. Maybe ask @funderburkjim to drop him an email? I've asked 3-5 times, you and Usha as well. Vishvas has, but we need to flood him.

**Comment by drdhaval2785** [comment]
I have got the splits I wanted. 
Closing this.
