### ISSUE TITLE
Transliteration Scheme .pdf

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/COLOGNE#85]
I think that http://www.sanskrit-lexicon.uni-koeln.de/scans/SHSScan/2014/web/webtc/help.html is bad. I would introduce an update. https://github.com/sanskrit-lexicon/Cologne/blob/master/Devanagari-Scheme.pdf how do you like it, @funderburkjim ? 

Devanagari
अ आ इ ई उ ऊ ॠ ऋ ऌ ॡ
ए ऐ ओ औ ं ः
क ख ग घ ङ
च छ ज झ ञ
ट ठ ड ढ ण
त थ द ध न
प फ ब भ म
य र ल व श ष स ह

IAST
a ā i ī u ū ṝ ṛ ḷ ḹ
e ai o au ṃ ḥ
k kh g gh ṅ
c ch j jh ñ
ṭ ṭh ḍ ḍh ṇ
t th d dh n
p ph b bh m
y r l v ś ṣ s h

HK
a A i I u U R RR lR lRR
e ai o au M H
k kh g gh G
c ch j jh J
T Th D Dh N
t th d dh n
p ph b bh m
y r l v z S s h

SLP1
a A i I u U f F x X
e E o O M H
k K g G N
c C j J Y
w W q Q R
t T d D n
p P b B m
y r l v S z s h

ITRANS
a aa i ii u uu Ri RI Li LI
e ai o au M H
k kh g gh ~N
ch Ch j jh ~n
T Th D Dh N
t th d dh n
p ph b bh m
y r l v sh Sh s h

**Comment by gasyoun** [comment]
@funderburkjim how about it?

**Comment by funderburkjim** [comment]
Your display is clearer in some ways.

I am a bit confused as to why there are two copies of the Devanagari.

There might be an improvement in the line spacing,  so that the Devanagari lines up perfectly with
the others.   Then, the reason for two copies of Devanagari might be obvious.  
What about also duplicating the red 'Devanagari title' also?

**Comment by gasyoun** [comment]
> I am a bit confused as to why there are two copies of the Devanagari.

Two different fonts. Can kill 2nd. People do not recognize different fonts, here at least they can check.

> What about also duplicating the red 'Devanagari title' ?

Does not makes sense to me.

> There might be an improvement in the line spacing, so that the Devanagari lines up perfectly with
the others. 

What exactly do you mean? I hardly get, but agree, I guess.

**Comment by funderburkjim** [comment]
> What exactly do you mean?

![image](https://cloud.githubusercontent.com/assets/6393033/20611634/617fd78a-b27c-11e6-97ac-1d80b4d59405.png)

By adjusting the css line-height for the Devanagari, you could get the Devanagari lines to be perfectly
lined up with the IAST lines.   The Devanagari line-height should be about 90%, as a guess.

**Comment by gasyoun** [comment]
> Devanagari lines to be perfectly
lined up with the IAST lines. The Devanagari line-height should be about 90%, as a guess.

Oh, now I got it. For that we need to have a table, that's the only way.

**Comment by drdhaval2785** [comment]
@gasyoun 

Anything you want done still?

**Comment by drdhaval2785** [comment]
I see no issues in the help page transliteration details as of now. Closing.
