### ISSUE TITLE
Two HTML Title Issues

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/COLOGNE#86]
As of http://www.sanskrit-lexicon.uni-koeln.de/
- title='Vaman Shivram Apte,The Student's English-Sanskrit Dictionary,501 pages' -> title='Vaman Shivram Apte,The Student's English-Sanskrit Dictionary,501 pages' because of the Student`'`s code got corrupted
- title='Monier-Williams, Monier,Ernst Leumann,Carl Cappeller,The digital Monier-Williams Sanskrit-English dictionary: XML edition.,1333 pages' what need of `: XML edition.`?

**Comment by funderburkjim** [comment]
@gasyoun 
 
For some reason, I'm not finding the precise places where the two titles appear that need attention.
