### ISSUE TITLE
Add Ajax AutoComplete

### ISSUE THREAD

**Issue by Shalu411** [sanskrit-lexicon/Cologne#9]
Namaste
Encoding is indeed a big issue;  
While typing for a word to search, we hit on different spellings. (not knowing the exact encoding.. sometimes difficult for beginners) So why not give "suggestions" while typing for the word in search box? The words which are near to the searched word- could be given; at least if not for each letter.. may be for whole word. Eg. "ziva" could be Shiva, Siva, shiva, Shiv, ziv, Siv etc. Though in Devanagari one can be saved from these issues, it is needed in other encoding.
Thankyou.

**Comment by drdhaval2785** [comment]
http://jqueryui.com/autocomplete/ is what I have used for my [tiGanta machine](http://www.lanover.com/lan/sanskrit/SanskritVerb/tiGanta.html) to suggest verbs.
The bad part about this approach is that this is fine for smaller number of words e.g. <10000, but trying it for a wordlist of >400000 definitely kills the browser for sure.
So, in my opinion the jquery or any browser side application is too difficult for this activity.
Some smartly designed AJAX application may be able to help us out.

**Comment by gasyoun** [comment]
AJAX is JS so it's browser side. Let me do a research once free.

**Comment by drdhaval2785** [comment]
One of the most important ones @funderburkjim and @gasyoun.
