### ISSUE TITLE
Advanced search: what to save in cookies?

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/COLOGNE#92]
A user recently commented (relative to the MW advanced search):

>  I use ITRANS and after you suggested, am using "Headword Only" too. So whenever I pull up the URL, I have to make these choices because they are not defaults. Wish they there is a way to keep my defaults for all the drop downs this GUI offers.

Currently, only a few of the options (I think input and output coding selection) are remembered in cookies.

It should be possible to save other optoins in cookies (for instance, the Headword Only choice)

Should all the options be saved (e.g. matching type?).  

Should any of the options be unsaved?

**Comment by drdhaval2785** [comment]
From my experience, there is nothing which can harm. Keep all stored in
cookie.

**Comment by gasyoun** [comment]
> Should all the options be saved (e.g. matching type?).

Let it be. If chosen in one dictionary I would have it in all others as well.

**Comment by drdhaval2785** [comment]
@funderburkjim 
Any update on what is stored in cookie and what is not.

**Comment by funderburkjim** [comment]
The cookie management is done in main.js of webtc2 for Advanced Search
* in the cookieUpdate function
* in the document.ready function, which attaches cookieUpdate actions to changes in certain html input elements
   * currently just #translit and #filter.
   * The getNext function lists all the html elements that are search parameters.
      This would identify other elements (besides #translit and #filter) that need to be tracked by a cookie.

The parameters currently tracked by cookie are the two checked below.
There are 5 parameters that are not currently tracked by cookie, those with an X in image.

![image](https://user-images.githubusercontent.com/6393033/102564510-98ac2000-40a9-11eb-9b0b-d48f88b21c02.png)

**Comment by drdhaval2785** [comment]
Default values look good in the rest of the fields. 
I have no complaints.
We can close this issue.

**Comment by funderburkjim** [comment]
OK -- will not extend cookie content at this time.
