### ISSUE TITLE
Rigveda Hyperlinking

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/COLOGNE#93]
Old question, new ideas. In MW72 we have

> Ṛig-veda VIII. 20, 9 

Which is equal to
> rv08.020.09

In my Concordance file of Rigveda.

> rv08.020.09
प्रति॑ वो वृषदञ्जयो॒ वृष्णे॒ शर्धा॑य॒ मारु॑ताय भरध्वम्। ह॒व्या वृष॑प्रयाव्णे॥
prati vo vṛṣadañjayo vṛṣṇe śardhāya mārutāya bharadhvam |
havyā vṛṣaprayāvṇe ||
О вы. украшенные каплями дождя!
Принесите бычьей стае марутовой
Жертвенные возлияния – (этой) мощно выезжающей!
Bringet, ihr Salbetriefende, eure Opfergaben der bullenhaften marutischen Heerschar dar, deren Anführer der Bulle Indra ist.
Bring, ye who sprinkle balmy drops. oblations to your vigorous Marut company, To those whose leader is the Bull.

Can we interlink them, @funderburkjim ?

https://www.dropbox.com/sh/ukqdjbhu6lohd4q/AABuwBb_oTfjP-ET0TfrPeoja?dl=0

**Comment by fxru** [comment]
Wonderful idea, Marcis! I think using the reference to Vedic (and other) texts and taking them as anchors for links to online editions of the texts is a great idea! I think it can be very useful from an indological/philological point of view.

At least in the pwg, the job seems to be non-trivial as many reference lack the RV, AV, SB etc. prefix.

p.s. Hi you all, I’m back from github-blocking China and will be active again.

**Comment by gasyoun** [comment]
> I think it can be very useful from an indological/philological point of view.

And in case of Rigvead easy as well, as there is only one edition.

> non-trivial as many reference lack the RV, AV, SB etc. prefix.

Let's hunt for the easy pray first.

> will be active again

It sure would be great, just you know it. We are watching you.

**Comment by funderburkjim** [comment]
This looks like a candidate for some experimenting.  

We would need to have a Rig-Veda edition for to which we can link to a particular verse.
```
http://rigveda.com/index.php?verse=rv08.020.09
```

That would solve half of the problem.

The other half would involve enhancement to a particular dictionary.  

For cases like PWG and PW and MW, there are at least `<ls>` tags already generated in the xml version.

There is no such markup present in mw72.  The regex
```
Ṛig-veda [IVX]+[.] *[0-9]+, *[0-9]+   comes up with 688 matches in mw72
```
So markup could be added.

In each dictionary, we would need to devise the appropriate parsing, to go *from* the conventions
of  the `<ls>` coding of Rig veda  in that dictionary *to* the standard form of our rigveda.com.

`easy pray` -> `easy prey`

The above is a broad outline of the technical steps required to get started.

The first step is to find our target, what I called rigveda.com, which lets us link to a particular verse,
and to find the api details of it.  If such a target doesn't already exist,  maybe we could adapt the edition
pointed to above by @gasyoun 's Dropbox link to serve our purpose.

**Comment by gasyoun** [comment]
> We would need to have a Rig-Veda edition for to which we can link to a particular verse.

We have one. I've made it. It's in my dropbox folder.

> PWG and PW and MW

Would be a first step. Let's start with a first step first.

> 688 matches in mw72

Is not bad at all.

> In each dictionary

Let's start with 3-4. Others can wait. For reference purposes not all of them are used. MW, AP, PWG - that is what counts.

> and to find the api details of it
Mine is just an HTML file with no API.

> If such a target doesn't already exist, maybe we could adapt the edition
pointed to above by @gasyoun 's Dropbox link to serve our purpose.

I would go for it hosting it on our server, because an outer source can change and all will be in vain, @funderburkjim 
@fxru can you invent a regex to find out how many textual references in PWG have no abbreviation before them? Or which was the last one before?

**Comment by gasyoun** [comment]
@funderburkjim even GRA has it. The question would be how could @artforlife do it for MW72 as well.

**Comment by funderburkjim** [comment]
> RV links in MW72

Very likely possible.

My first inclination would be to add `<ls>` markup to MW72.
Then in particular, there would be markup like `<ls>Ṛig-veda VIII. 20, 9</ls>`.

Then, the display logic for mw72  would be enhanced, probably within [basicadjust.php](https://github.com/sanskrit-lexicon/csl-websanlexicon/tree/master/v00/makotemplates/webtc/basicadjust.php).
The enhancement probably similar to that for grassman  (see ` Experiment 05-21-2018 for dict == gra`, currently at line 82 of basicadjust.php).

It would be possible to do also add the `<ls>` markup just for Rig Veda within basicadjust for MW72.
That is, we could skip the preliminary step of adding `<ls>` markup to the digitization for all literary source references.

**Comment by funderburkjim** [comment]
> Rigveda Hyperlinking in other dictionaries

Enhancements to basicadjust could also add Rigveda hyperlinking for other dictionaries.  Notably,
MW,  PW, and PWG  already have `<ls>` markup.  For PW and PWG the changes would likely be in
method `ls_callback_pwg`; for MW in `ls_callback_mw` method.   These methods currently add tooltips for the literary source; but probably they would be the place to also add a link.

## basicdisplay

basicadjust alters the xml structure;  but then also basicdisplay.php  has to be altered to create the html from this altered xml structure.

This and the prior comment give a very sketchy idea of what would be required;  handling all the details will require some delicacy in coding to change those two programs to add RV linking for dictionaries other than GRA.  But conceptually, my guess is the task is doable.

**Comment by drdhaval2785** [comment]
@gasyoun The RV and AV linking is being tracked elsewhere I guess. Can you provide the link here, so that we can close this issue

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/rvlinks/ is the repository dedicated to linking RV. Closing this issue.
Necessary issues may be raised in that repository.
Correct, @gasyoun?
