### ISSUE TITLE
Advanced display MW - target a bit off mark

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/Cologne#96]
http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/webtc2/index.php

1. I selected Advanced search for headwords starting with 'ka', 
2. I scrolled down to entry 695 कण्टकवत् and clicked, the right panel showed details of  
```
kaṭakīya
(H2) kaṭakīya [p= 243,3] [L=41994] 	mfn. belonging to a mat or string &c g. apūpā*di Pāṇ.  5-1, 4
```

This seems to be an erroneous linking.

The second issue is that despite selecting Devanagari Unicode as output, I still see output in IAST.

**Comment by gasyoun** [comment]
> still see output in IAST.

There is no spoon, Dhaval.

**Comment by drdhaval2785** [comment]
I dont know. I am able to load subsequent queries properly. May be a false alarm too.

**Comment by funderburkjim** [comment]
I'm not seeing the problem:  

![image](https://cloud.githubusercontent.com/assets/6393033/22959168/0a895138-f302-11e6-958b-6c56043c6bdd.png)

**Comment by drdhaval2785** [comment]
Maybe a false alarm. Maybe something to do with slow internet speed. Now I am also unable to reproduce it.
