### ISSUE TITLE
Integrate Cologne dictionaries with stardict-updater

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/COLOGNE#98]
It is a bit ambitious.
It would be great if we can convert all dictionaries (of course in descending order of importance) to babylon format. 
We will then be able to use them as stardict files.
I personally use it on mobile on colordict and am deeply in love with the ease.
https://github.com/sanskrit-coders/stardict-sanskrit/

Babylon format is simple enough format.

```
Line 1 - headwords separated by |
Line 2 - Dictionary entry
Line 3 - line break
```

Currently [stardict-dictionary-updater project](https://play.google.com/store/apps/details?id=sanskritcode.sanskritdictionaryupdater&hl=en) uses some of the dictionary data from Cologne (scraped maybe some years back). This means their users are not benefiting from corrections being made day in and day out at Cologne servers.

If we integrate seamlessly, both will benefit.
1. Dictionaries will have wider circulation (also on android / mobiles etc)
2. Dictionaries will be better updated.

@gasyoun and @funderburkjim 
What do you think about this?

Not much of work compared to the benifit.

**Comment by drdhaval2785** [comment]
We can make this babylon generation stuff a shell script which can regenerate babylon files based on current DICT.xml file from our 36 dictionaries.

**Comment by funderburkjim** [comment]
I like the idea. 

Are there some details regarding the format of the dictionary entry ?

Not sure what 'page break' means --- given that it pertains to headword entries, it probably does not
literally refer to 'page' breaks.

Coincidentally, I got this email from someone who is a Mac user:
```
I saw someone who had loaded the MW data into the resident Mac dictionary.  What file would I use to load into it?  What format?  There are a number of formats available online on the website.

If you have a set of instructions on how to do this, could you pass them onto me?
```

Would the conversion you are talking about apply ?

**Comment by drdhaval2785** [comment]
On 24 Feb 2017 05:57, "funderburkjim" <notifications@github.com> wrote:

I like the idea.

Are there some details regarding the format of the dictionary entry ?


Stardict format is what it is called. Vishvas has a convertor which
converts babylon files to stardicts with some Sanskrit specific
preprocessing like converting headwords to ITRANS transliteration too, so
that search via Devanagari and roman letters both are possible.

Not sure what 'page break' means --- given that it pertains to headword
entries, it probably does not
literally refer to 'page' breaks.


My error. Read line break.

Coincidentally, I got this email from someone who is a Mac user:

I saw someone who had loaded the MW data into the resident Mac
dictionary.  What file would I use to load into it?  What format?
There are a number of formats available online on the website.

If you have a set of instructions on how to do this, could you pass
them onto me?

Would the conversion you are talking about apply ?


Yes. All he needs to have is a stardict dictionary reader. Colordict or
goldendict. Currently I have nearly 44 dictionaries etc loaded on my mob.
It is damn fast. And best thing is it works without internet too.

This format is so versatile that it can be used in non dictionary kind
books too. E.g. Paninian grammar books can have sUtra|sUtranumber instead
of headwords and explanation instead of dictionary entry. Then I can type
1.3.1 and see all commentaries on that sUtra.

If you agree, I shall try create some generic script to generate babylon
files from .xml files of cologne. Mostly xpaths would vary. They can be
passed as arguments.

**Comment by funderburkjim** [comment]
> If you agree, I shall try create some generic script to generate babylon
files from .xml files of cologne

I definitely agree.  Maybe start with a 'small' dictionary, say McDonnell.   Don't worry too much about 
generic at first. You obviously know a lot more
about this than I do. Seeing the details of a specific example will help me get up to speed.

**Comment by funderburkjim** [comment]
SOme time ago, Gerard Huet mentioned that he done something along these lines.

Here is link to his [GoldenDict](http://sanskrit.inria.fr/goldendict.html) page.

**Comment by drdhaval2785** [comment]
Yes his dict is available in updater.

**Comment by funderburkjim** [comment]
Q: what is 'updater'?

**Comment by funderburkjim** [comment]
A search for 'python stardict' gives several resources.  Most appear to be for parsing a stardict file.

This one appears to deal with creating stardict file:

https://pypi.python.org/pypi/penelope/3.0.0.1

It might require an ubuntu-type setup to fully use.

**Comment by drdhaval2785** [comment]
https://play.google.com/store/apps/details?id=sanskritcode.sanskritdictionaryupdater&hl=en

Gave the link in first post.

It in a way updates stardict files in your local machine whenever you click on it.

**Comment by gasyoun** [comment]
> Not much of work compared to the benifit.

Agree. Do not see many possible issues.

> It is damn fast. 

Sure that's important. Is word order devanagarish?

> I shall try create some generic script to generate babylon
files from .xml files of cologne. Mostly xpaths would vary. They can be
passed as arguments.

Makes sense to me.

**Comment by funderburkjim** [comment]
I came across a project ca April 2008 where an `mdict` version of MW was created.  This was for the now obsolete windows mobile phone.   If anyone thinks it might be of interest as a model for current conversions, here is [mdict.zip](http://sanskrit-lexicon.uni-koeln.de/mwupdate/mdict.zip).  It is about 19mb.  The programs are written in Perl.

**Comment by funderburkjim** [comment]
Here is [readme.txt](https://github.com/sanskrit-lexicon/Cologne/files/800762/readme.txt) for mdict project.

**Comment by gasyoun** [comment]
As per the babylon format, @drdhaval2785 I found out that there are people who use a MW version from 2004, that is split like documented bellow. It is similar to Babylon in some way I guess?

```

------------------------------------
===> [dha]1[dha]1 aspirate of the preceding letter , 
------------------------------------
===> [dhakAra]3[dha--kAra] m. the letter or sound [dh] 
------------------------------------
===> [dha]1[dha]2 mf([A])n. (root 1. [dhA] 

---> cf.2. [dhA]) ifc. placing , putting 

---> holding , possessing , having 

---> bestowing , granting , causing &c. (cf. [a-doma-dha] , [garbha-dha]) 

---> m. N. of Brahmaa or Kubera cf. L 

---> (in music) the 6th note of the gamut 

---> virtue , merit cf. L 

---> n. wealth , property cf. L 

---> ([A]) , f. in 2. [tiro-dhA] 

---> [dur-dhA] (qq. vv.) 
------------------------------------
===> [dhak]1[dhak]1 nom. fr. [dagh] or [dah] (cf. [dakSiNa-dagh] and [uza-dah]) 
------------------------------------
===> [dhak]1[dhak]2 an exclamation of wrath cf. Uttarar. iv , 23 
```

**Comment by funderburkjim** [comment]
Is there an official documentation of the stardict format?

I have done several searches but have not found a definitive specification.

**Comment by drdhaval2785** [comment]
@funderburkjim and @gasyoun 
This is to inform that integration of MD (MacDonell) with stardict is now over.
I am able to see the dictionary working well on my android phone colordict app.

https://github.com/sanskrit-coders/stardict-sanskrit/tree/master/sa-head/macdonell has all the files, if you want to test them out separately in stardict / colordict for computers.

If you prefer to use auto-updater on android phone, follow these steps.
1. Install Stardict Dictionary Updater from play store. 
2. Install colordict from play store.
3. Open Stardict Dictionary Updater on phone.
4. Select only sanskrit-coders/stardict/sanskrit/master/sa-head. Deselect others.
5. Click PROCEED.
6. In next step, keep macdonell__2017-04-01_10-43-35.tar.gz select. Deselect others.
7. Click PROCEED.
8. See for the log. Usually it should say - Succeeded on ......
9. QUIT the application.
10. Open Colordict.
11. Click on Folder structure on the right upper corner.
12. Click on three vertical dots on right upper corner.
13. Click on Reindex.
14. It will reindex dictionary for you.
15. Once it is over, the dictionary is ready for you to use. Write the headword you want to see.

Let me know if there are any suggestions or display issues in the MacDonell dictionary.

**Comment by gasyoun** [comment]
> I am able to see the dictionary working well on my android phone colordict app.

Hurray, congratulations, Dhaval! Let me test it and make a video even, so others can follow as well.

**Comment by drdhaval2785** [comment]
@funderburkjim

NOTE

MD, BEN, AP90 and ACC are added in stardict updater. Please fillow above steps and check out the results. There are a lot of improvements possible. Post an issue for bug / feature.

**Comment by funderburkjim** [comment]
@drdhaval2785   I got 'Failed on macdonell__2017-04-01_10-43-35.tar'

Do I need to have an sd card  (I'm using a ZenPad android tablet)?

**Comment by drdhaval2785** [comment]
Check in

Internal storage/dictdata/macdonell

Do you have any files or not?

If there are files there, try to do reindexing. It sometimes get resolved
on reindexing.

**Comment by funderburkjim** [comment]
I see internal storage >root>sdcard>dictdata, but no files.  

Since the Instructions for updater mentioned SDCARD,  it must be that an SDCARD is needed.

I'll have to get one, and try again.

**Comment by drdhaval2785** [comment]
I dont have SD card and it functions.

**Comment by drdhaval2785** [comment]
BHS, BOP, BOR, BUR added now.

**Comment by drdhaval2785** [comment]
CAE, CCS, GRA, GST, IEG, INM, MD, MW72, MWE added.

KRM, MCI, MW were already there. 
Will need to examine the converted version v/s current cologne version.
Will handle them later on.

**Comment by drdhaval2785** [comment]
PD can't be converted / uploaded because of copyright issue.

**Comment by gasyoun** [comment]
> PD can't be converted

Can be converted, but not for public access.

**Comment by funderburkjim** [comment]
Similarly for 'AP' as for PD - not publicly available.

**Comment by funderburkjim** [comment]
I finally got an sdcard.  However,  still get 'Failed on macdonell...' 😢 

I was successful in getting the English wordnet dictionary in Colordict.

When I do the download step for MD,  it takes a while (WORKING), and then gives the message
"We're done. Get a stardict... Then reindex all your dictionaries'
Failed on Macdonell...

In the file system, root/sdcard/dictdata has a bunch of files, which all seem to be referring to English wordnet dictionary.

**Comment by drdhaval2785** [comment]
Try something other than MD. Try AP90.

**Comment by drdhaval2785** [comment]
I tried on my phone. Downloaded well.

**Comment by drdhaval2785** [comment]
Also update your stardict dictionary updater to the latest version.

**Comment by funderburkjim** [comment]
There may be some subtle difference in my particular device -  I have tried another (benfey) with same results.

Could I download the download files to my pc, and then somehow transfer them to the ZenPad --- is such a workaround possibe?  If so, what would be the url for the file(s)?

**Comment by funderburkjim** [comment]
How do I update the stardict dictionary updater --- I'm ignorant of how to do things in Android.

**Comment by drdhaval2785** [comment]
How do I update the stardict dictionary updater --- I'm ignorant of how to
do things in Android.


1. Go to play store
2. Search for stardict dictionary updater.
3. Click update.

**Comment by drdhaval2785** [comment]
Why I want you to update is that with latest version, error log is
generated for debugging.
See https://github.com/sanskrit-coders/stardict-dictionary-updater/issues/11
.

You can send crash report like this
https://m.youtube.com/watch?feature=youtu.be&v=whpoaqRbb-A.

This will help improve things for similar device holders.

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-coders/stardict-sanskrit?files=1

This is the place where data is stored.
Most data is in sa-head and en-head subdirectory.

The structure is visible in stardict updater interface also.

https://github.com/sanskrit-coders/stardict-sanskrit/tree/
master/sa-head/en-entries/macdonell is specific for MacDonell.

Download dict.dz, idx, ifo, sym files.

**Comment by funderburkjim** [comment]
Updated the updater. -  Got the one dated today.    

Now Benfey loads successfully. Hurray!

BTW.  Saw something that looks like an add on the Colordict page ('phone is in danger virsues found...blah blah..')  Is that normal with Colordict?  With all Android apps?

**Comment by drdhaval2785** [comment]
It is ad. Ignore bottom ads. That is the only drawback of colordict. In-app
ads.

**Comment by drdhaval2785** [comment]
The best way to overcome adds is to turn off internet. I do it often.

Goldendict free supports only 5 dicts.
Goldendict paid is paid.
So colordict remains a free option with unlimited dict support, with a
small hitch of adds.

**Comment by funderburkjim** [comment]
Got it -- may get the paid version --  

But this is just a detail.  Main thing is that the dictionaries are there.  

Way to go, Dhaval !!

One thing to keep in mind is that it would be possible to make an xml form that is optimized for stardict. Don't know whether this will be necessary, but we should be aware it is an option.

**Comment by drdhaval2785** [comment]
I am planning to convert all existing dictionaries to stardict version
first. Then we will examine every dictionary syatematically for the
drawbacks or features required to modify it to look better or more user
friendly. At that time we can decide whether to do it in XML step (your
side) or babylon step (my side) depending on feasibility.

The best scenario I envisage is to have a uniform DTD for all cologne
dictionaries, so that XMLs are all predictable. Then I will not have to
maintain separate patches for separate dictionaries. But that is currently
way far off. So I am happy having different patches for different
dictionaries.

Also the encoding should be uniform in dictionaries. XYZ tag will hold
information in SLP1 only. ABC tag will hold information in IAST only etc.

**Comment by funderburkjim** [comment]
I'm definitely in agreement with the standardization goals you mention.  This would help not only in your stardict constructions, but would also simplify the maintenance of the Cologne system.  

One DTD to rule them all ! (goofy reference to Lord of the rings 'One ring to rule them all') :)

**Comment by vvasuki** [comment]
> The best scenario I envisage is to have a uniform DTD for all cologne
dictionaries, so that XMLs are all predictable.

+1!

**Comment by gasyoun** [comment]
> But that is currently
way far off. So I am happy having different patches for different
dictionaries.

Exactly.

> I'm definitely in agreement with the standardization goals you mention

It's about 8-10 months away at best, and some unique dictionary features will get lost. But sure I'm for it. If we will have list of what has become what. Before and after.

**Comment by vvasuki** [comment]
> The best scenario I envisage is to have a uniform DTD for all cologne
dictionaries, so that XMLs are all predictable.

A few suggestions while doing this:

* A basic software engineering principle is that one should separate data (what's being communicated fundamentally) from presentation (how it should look). Following this will make life a lot easier downstream, since those components may have less regard for the original presentation.
  * Currently the xml-s mix them up, more or less replicating the newlines etc.. as they were in the book when published under the constraints of the time.
  * So, this **current xml** (declaring it to be mostly a faithful digitization of the presentation of how the text was published) could be retained as is for each dictionary, while the **standard structural xml** could be generated from it using dictionary-specific scripts.
    * At its toughest would entail stuff like understanding what the table structure in kRdanta-rUpa-mAlA represents. Usually it would be easier.

*  The **standard structural xml** which is being proposed need not be an xml, of course. I would suggest taking to JSON (the currently popular standard used in looots of webapps).

**Comment by drdhaval2785** [comment]
@funderburkjim and @gasyoun 
This comment https://github.com/sanskrit-coders/stardict-sanskrit/issues/18#issuecomment-294391095 summarizes present state of affairs of stardict conversion from Cologne dictionaries.

Stats
Total             - 36
Added           - 26
Copyrighted  - 02
Ready           - 06 (There are visually enhanced versions already in use in stardict format.)
Pending        - 02

**Comment by vvasuki** [comment]
Dream come true! Thanks, @drdhaval2785

**Comment by vvasuki** [comment]
> Ready - 06 (There are visually enhanced versions already in use in stardict format.)

@drdhaval2785 Could you list these, so that we can be sure?

**Comment by vvasuki** [comment]
> @drdhaval2785 Could you list these, so that we can be sure?

Never mind - just saw the table here: https://github.com/sanskrit-coders/stardict-sanskrit/issues/18

**Comment by drdhaval2785** [comment]
@gasyoun and @funderburkjim 

Just to give you an idea about the popularity of the dictionary downloads
They were uploaded on 17-Apr-2017 and till 23-Apr-2017, the download counts are as below
```
apte-1890__2017-04-02_23-18-23.tar.gz: 48 downloads
aufrecht-catalogus-catalogorum__2017-04-02_21-28-09.tar.gz: 23 downloads
benfey__2017-04-03_10-26-12.tar.gz: 35 downloads
Bohtlingk-and-Roth-Grosses-Petersburger-Worterbuch__2017-04-17_00-33-12__15MB.tar.gz: 22 downloads
Bohtlingk-Sanskrit-Worterbuch-in-kurzerer-Fassung__2017-04-17_07-13-34__7MB.tar.gz: 27 downloads
bopp__2017-04-04_08-43-21.tar.gz: 23 downloads
borooah__2017-04-03_23-51-58.tar.gz: 27 downloads
burnouf__2017-04-04_08-43-21.tar.gz: 22 downloads
capeller-sanskrit-english__2017-04-05_08-58-12.tar.gz: 26 downloads
capeller-sanskrit-german__2017-04-05_08-58-12.tar.gz: 23 downloads
edgerton-buddhist-hybrid__2017-04-04_08-43-21.tar.gz: 23 downloads
goldstucker__2017-04-05_08-58-12.tar.gz: 24 downloads
grassman-sanskrit-german__2017-04-05_08-58-12.tar.gz: 22 downloads
index-names-mahabharata__2017-04-05_18-52-42.tar.gz: 3 downloads
indian-epigraphical-glossary__2017-04-05_08-58-12.tar.gz: 39 downloads
kalpadruma-sa__2017-04-02_20-23-08.tar.gz: 3 downloads
macdonell__2017-04-05_08-58-12.tar.gz: 24 downloads
Meulenbeld-Sanskrit-Names-of-Plants__2017-04-17_08-29-39__0MB.tar.gz: 32 downloads
mw-1872__2017-04-05_08-58-12.tar.gz: 43 downloads
Personal-and-Geographical-Names-in-the-Gupta-Inscriptions__2017-04-16_22-21-43__0.tar.gz: 25 downloads
Schmidt-Nachtrage-zum-Sanskrit-Worterbuch__2017-04-17_07-16-11__1MB.tar.gz: 22 downloads
shabda-sAgara__2017-04-16_23-42-35__2.tar.gz: 47 downloads
Stchoupak-Sanscrit-French__2017-04-17_09-00-19__1MB.tar.gz: 24 downloads
vAchaspatyam-sa__2017-04-17_07-29-20__12MB.tar.gz: 22 downloads
Vedic-Index-of-Names-and-Subjects__2017-04-17_00-20-32__0.tar.gz: 26 downloads
wilson__2017-04-17_00-07-31__2.tar.gz: 25 downloads
yates__2017-04-17_00-12-54__1.tar.gz: 26 downloads
```

**Comment by gasyoun** [comment]
> Just to give you an idea about the popularity of the dictionary downloads

Thanks, there seem to be 30 more junkies around :100:

**Comment by vvasuki** [comment]
> They were uploaded on 17-Apr-2017 and till 23-Apr-2017, the download counts are as below

I am honestly surprised as well.  There aren't that many active "updater" installs, and I did not expect users to have run the updater app so soon (without any announcement from our end too) - 
![image](https://cloud.githubusercontent.com/assets/2664797/25316975/11ef46fa-2825-11e7-9984-95e6069e47e6.png)

It is unlikely that these dicts were installed independently of the updater app (remember - no announcement done). This of course, is totally separate from:
* "Delete the updater after dict installation" types, who would reinstall only if they are aware of fresh dicts.
* (post-install) dictionary usage stats - I personally now many hard core Indian stardict beneficiaries (and heard of many more I don't know) - I expect them to run into a few hundred (at least) to a few thousand (at most).

**Comment by drdhaval2785** [comment]
The stats show that roughly 20+ downloads were done of 'whole sa-head' type. Default selected dicts were all downloaded. 
Why on earth would anyone download bopp independently?

**Comment by drdhaval2785** [comment]
(without any announcement from our end too) -


I intend to defer announcement till licence issue is settled to the
satisfaction of @funderburkjim. See
https://github.com/sanskrit-lexicon/cologne-stardict/issues/1.

**Comment by vvasuki** [comment]
> I intend to defer announcement till licence issue is settled to the satisfaction of @funderburkjim. See sanskrit-lexicon/cologne-stardict#1.

No hurry at all. Take your time.

> Why on earth would anyone download bopp independently?

Because it is not clear from the filename that they're getting a latin dictionary! (which is what I alluded to in https://github.com/sanskrit-coders/stardict-sanskrit/issues/37 ) may be they think it is their baap's dict :-)

**Comment by gasyoun** [comment]
> baap's dict 

You made my day.

**Comment by gasyoun** [comment]
See the offline dictionary I use on Win 7:
https://sourceforge.net/projects/sandic/files/stats/timeline?dates=2012-03-01+to+2017-04-24

![5years-10k-downloads](https://cloud.githubusercontent.com/assets/80761/25362597/a4caea4a-295d-11e7-893f-1e157a8891f9.PNG)

**Comment by vvasuki** [comment]
That's quite some impact! I observe a mild downward trend. It's interesting to note so many non-Indian users (I suspect most of the US downloads are by Indians, though) - Russia, Korea and Ukraine are a surprise to me in particular.

![image](https://cloud.githubusercontent.com/assets/2664797/25368346/a2cfeace-2930-11e7-94e9-29de8905ca4b.png)

**Comment by funderburkjim** [comment]
@drdhaval2785 

Peter Scharf asked me: Does Stardict and the downloader work on Mac iphone?

Do we have any information on that?

**Comment by funderburkjim** [comment]
The actual dictionary files (from Cologne made by Dhaval) are the xx.babylon files [here](https://github.com/sanskrit-lexicon/cologne-stardict/tree/master/output).  Right?

So if one could get these files onto iphone, then the 'Dictionary Universal' app would display them.

Is there an ad hoc way to get such a file on an IOS device to test the compatibility of the DU app with
the files?

**Comment by funderburkjim** [comment]
Another application possibility is to use the stardict format files along with some stardict viewer as a
way to get standalone versions of the dictionaries for Win, MAC-OS, Linux.   While we have a way to
get such versions of the dictionaries on these OS, they way depends on first getting a local PHP server.
This step is too complicated for many people who would otherwise like to have a version of one or more
of the Cologne dictionaries available locally on their laptop or desktop computer.

**Comment by vvasuki** [comment]
> Another application possibility is to use the stardict format files along with some stardict viewer as a
way to get standalone versions of the dictionaries for Win, MAC-OS, Linux. While we have a way to
get such versions of the dictionaries on these OS, that way depends on first getting a local PHP server.

This is a fully solved problem. I refer to a hundred plus stardict dictionaries (in one shot) on my linux computer using the goldendict app. I hear that windows and mac computer users are similarly endowed. No need for further efforts here.

> The actual dictionary files (from Cologne made by Dhaval) are the xx.babylon files here. Right?
Yes.

> So if one could get these files onto iphone, then the 'Dictionary Universal' app would display them. Is there an ad hoc way to get such a file on an IOS device to test the compatibility of the DU app with
the files?

We know that the stardict files (basically tar.gz urls listed [here](https://github.com/sanskrit-coders/stardict-sanskrit/search?q=tar.gz&unscoped_q=tar.gz)) generated from those initial babylon files are already fully compatible with 'Dictionary Universal' app - nothing to test anew.. And, it is quite simple to get any dictionary one desires one at a time as explained in http://old.aupasana.com/software/stardict .

**Comment by gasyoun** [comment]
New OCR of MD dictionary https://raw.githubusercontent.com/novikovag/OCR/master/Macdonell%20A.A.%20Sanskrit-English%20Dictionary/html/data.txt.html - for comparison.

**Comment by drdhaval2785** [comment]
Stardicts were generated and is being regenreated on and off. Safe to close. Cronjob is misaing, but tracked separately.
